cloudflare/workerd

patches/sqlite/0001-row-counts-plain.patch
src/workerd/api/sql-test.js
src/workerd/util/sqlite-test.c++

SQLite may generate temporary tables while executing a SELECT statement. Rows written to these tables shouldn't count as they're not under control of the user.
This change is essentially
https://github.com/tursodatabase/libsql/commit/5d6c79e8fe493232111cf9ea85ff46765e7a23a9, which does this same thing in libsql; libsql is also where the original row-counting logic comes from.
The test was written by glen@cloudflare.com.

sqlite: don't count rows written to temporary (ephemeral) tables

---

src/workerd/tools/BUILD.bazel

Dependent repositories will not have the required rust crates for them by default, so disable them there.

[bazel] Mark param_extractor{_bin} as no-downstream

---

samples/pyodide/config.capnp
src/pyodide/python-entrypoint-helper.js

It looks like both are supported by JS Workers (both in EWC and in workerd). So this PR ensures the same is the case for Python Workers.
```
$ bazel run @workerd//src/workerd/server:workerd -- serve $PWD/deps/workerd/samples/pyodide/config.capnp --experimental
```
+ test upstream

Accept module names with and without a .py extension.

---

src/workerd/api/r2-rpc.c++

A potential negative value returned by atoi() may cause an excessive memory allocation. This PR adds a check that the returned value is nonnegative.

Check lower bound returned by atoi()

---

src/pyodide/BUILD.bazel
src/pyodide/pyodide_extra.capnp
src/workerd/api/BUILD.bazel
src/workerd/api/pyodide.c++
src/workerd/api/pyodide.h
src/workerd/api/pyodide/pyodide.h
src/workerd/io/BUILD.bazel
src/workerd/server/workerd-api.c++

So we don't have to search for it in the module list. It's not meant to be imported by the user anyways.

Move python-entrypoint.js into a top level Capnp constant

---

src/workerd/api/streams/common.h
src/workerd/api/streams/internal.c++
src/workerd/api/streams/internal.h
src/workerd/api/streams/readable.c++
src/workerd/api/streams/writable.c++

Fixes a memory leak in certain uses of streams.
This is a simpler version of #1598. I was able to directly fix the problem that the WeakRef refactor also solved.

Fix GC visitation in stream readers and writers

---

src/cloudflare/internal/d1-api.ts
src/cloudflare/internal/test/d1/BUILD.bazel
src/cloudflare/internal/test/d1/d1-api-test.js
src/cloudflare/internal/test/d1/d1-api-test.wd-test
src/cloudflare/internal/test/d1/d1-mock.js
types/defines/d1.d.ts

This PR does a couple of things:
* Massively improves the realism of the D1 test suite. I've also got d1-api.ts and d1-api-test.js being imported into D1's internal test suite to verify these are correct, but the new d1-mock now much more closely mirrors the real system.
* Adds a resultsFormat flag to better control what D1 returns behind the scenes, with a default to `ROWS_AND_COLUMNS`, which should be more efficient (see below).
* Fixes `.run()` to no longer return `.results` property, as per the docs.
* Makes `.raw()` effectively the default and derives `.all()`/`.first()` from that, rather than the other way around.
In particular, this change fixes a long-standing bug with D1 where joining tables with the same column names was losing data, e.g.
```js
await DB.exec(`
CREATE TABLE abc …
```

Adding resultsFormat to d1-api.ts to fix .raw() bug

---

.github/workflows/test.yml

This should mitigate the recent disk space exhaustion issues. Also simplifies how the benchmark tests are being excluded and enables this for the Linux based asan/debug configurations.

[CI] Use limited debug info on Linux-{asan,debug} CI runs

---

samples/pyodide-fastapi/config.capnp
samples/pyodide-langchain/config.capnp
samples/pyodide/config.capnp
src/pyodide/README.md
src/workerd/api/pyodide/pyodide.h
src/workerd/jsg/modules.h
src/workerd/server/server-test.c++
src/workerd/server/workerd-api.c++
src/workerd/util/autogate.c++
src/workerd/util/autogate.h

This is no longer required upstream.

Clean up builtin-wasm-modules autogate (used for Python)

---

src/workerd/api/basics-test.c++
src/workerd/api/basics.c++
src/workerd/api/basics.h

Make the connection between EventTarget and NativeHandler safer.
Simplify/Cleanup the implementation a bit

Cleanup EventTarget::NativeHandler

---

src/pyodide/python-entrypoint-helper.js

Before this PR we instantiate the Python interpreter from scratch on every request. This is slow and uses up a lot of memory. This switches to sharing an interpreter across requests. This makes per-request non-coldstart execution time and memory usage much lower.

Python: Share Python interpreter across requests

---

src/workerd/server/BUILD.bazel
src/workerd/server/workerd.c++
src/workerd/tests/BUILD.bazel
src/workerd/tests/test-fixture.c++
src/workerd/util/BUILD.bazel
src/workerd/util/entropy-test.c++
src/workerd/util/entropy.c++
src/workerd/util/entropy.h

Reduction of code duplication across workerd and internal code bases. We have several duplicated implementations of kj::EntropySource.

Consolidate entropy source impls into a single source

---

src/workerd/api/basics.c++
src/workerd/api/basics.h
src/workerd/api/global-scope.h
src/workerd/api/gpu/gpu-device.h
src/workerd/api/web-socket.h
src/workerd/jsg/BUILD.bazel
src/workerd/jsg/iterator.h
src/workerd/jsg/jsg.h
src/workerd/jsg/memory.c++
src/workerd/jsg/memory.h
src/workerd/jsg/setup.c++

Expands heap tracking memory tracking for handful of API types
~~Includes the context global in the heap tracking trace.~~ originally had some extra stuff in here for special-case handling of the context global in order for it to appear in the snapshot a certain way but it added way more complexity than it was worth. The non-special case handling is sufficient.
Refines a few bits and pieces in the memory tracker def

Implement heap snapsnot memory tracking for Event, EventTarget

---

src/workerd/io/worker.c++

The original code did not check if the allocation succeeded, leading to possible issues if malloc() returns null. 
This PR should fix that by simply replacing the malloc with a stack allocation.

Fix unchecked malloc

---

src/workerd/api/cache.h
src/workerd/api/cf-property.h
src/workerd/api/form-data.h
src/workerd/api/hyperdrive.h
src/workerd/api/kv.h
src/workerd/api/queue.h
src/workerd/jsg/memory.h

* cache
* cf-property
* form-data
* hyperdrive
* kv
* queue

Implement memory tracking for handful of classes

---

src/pyodide/python-entrypoint-helper.js
src/workerd/api/pyodide/pyodide.c++

Just to tighten up what we allow. Tested upstream.

Disallow file extension-less Python modules.

---

src/workerd/jsg/memory.c++

This fixes a warning from clang:
> INFO: From Compiling src/workerd/jsg/memory.c++:
> src/workerd/jsg/memory.c++:1:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
> #pragma once
>         ^
> 1 warning generated.

Remove `#pragma once` from memory.c++

---

build/wd_cc_library.bzl
src/workerd/util/BUILD.bazel

this is very incovenient. `bazel build` commands pass without doing anything, while everything is broken.
Reverts cloudflare/workerd#1512

Revert "[bazel] Do not compile wd_cc_library by default"

---

src/workerd/api/global-scope.c++
src/workerd/api/global-scope.h
src/workerd/io/limit-enforcer.h
src/workerd/io/worker-entrypoint.c++
src/workerd/server/server.c++
src/workerd/tests/test-fixture.c++

This PR adds a wall time timeout for alarm handlers. 
When the timeout for an alarm it hit, we cancel deferred alarm deletion and abort the currently running handler. 
The alarm timeouts are counted against limits, so they get deleted once the maximum retry limit is reached.

Limit alarm handler walltime to 15minutes

---

.github/workflows/fixup.yml
.github/workflows/npm-types.yml
.github/workflows/npm.yml
.github/workflows/release.yml
.github/workflows/test.yml

- Node 16 support for actions will be dropped in the future. This updates most packages where deprecation warnings for node or other features apply.
- Use `show-progress: false` as introduced in checkout@v4 to not print the current progress when fetching a repository during build steps. This makes logs slightly smaller and more readable.
There are still some actions after this that use node 16 – some have not been updated to node 20 yet, with actions/download-artifact and actions/upload-artifact we'd need to check carefully if the breaking changes of v5 affect us, and actions/upload-release-asset (using node 12!) is EOL and needs to be replaced. This is only intended as a first patch to get the ball rolling on this.
We could use `show-progress: false` every time we use checkout, but …

[CI] Update action versions, fix deprecation warnings and silence progress messages

---

.bazelrc
build/wd_test.bzl
src/workerd/api/BUILD.bazel
src/workerd/api/gpu/webgpu-buffer-test.js
src/workerd/api/gpu/webgpu-compute-test.js
src/workerd/api/gpu/webgpu-errors-test.js
src/workerd/api/gpu/webgpu-windowless-test.js
src/workerd/api/gpu/webgpu-write-test.js

The WebGPU tests were previously not included in the bazel build system. With this change we have 5 more tests that will run on CI and achieve better code coverage.

Automatically run webgpu tests if enable_experimental_webgpu is enabled

---

types/defines/pages.d.ts

Whilst I wasn't able to reproduce the error from #1327, it did surface that the incoming request doesn't have the correct `cf` type. Currently, it's implicitly typed with `CfProperties` which includes both incoming and outgoing types, whereas we know this is an incoming request, so only `IncomingRequestCfProperties` are valid. This PR fixes that.
Closes #1327

Use `IncomingRequestCfProperties` in Pages `EventContext`

---

src/workerd/api/basics.c++

No need to visit the native handler ref here.

Fixup gc tracing in EventTarget

---

src/workerd/api/actor.c++
src/workerd/api/actor.h
src/workerd/api/http.c++
src/workerd/api/http.h
src/workerd/api/worker-rpc.c++
src/workerd/api/worker-rpc.h
src/workerd/io/worker-interface.capnp

This is a series of small refactorings that prepares for the future where RPC params or return values can contain new RPC objects. For this to work, we need to disentangle the sending of one RPC call from the creation of RPC sessions, since one session may encompass many calls in both directions.

Refactor JSRPC to prepare for capability-based RPC

---

src/workerd/api/basics.c++
src/workerd/api/basics.h

Reverts cloudflare/workerd#1648
This change was not correct, see analysis here:
https://github.com/cloudflare/workerd/pull/1648#issuecomment-1936584437

Revert "Fixup gc tracing in EventTarget"

---

src/workerd/api/sockets.c++
src/workerd/api/sockets.h
src/workerd/util/autogate.c++
src/workerd/util/autogate.h

This has been rolled out via the autogate to RoW, so is safe to remove.

Removes old Socket::close implementation.

---

types/defines/d1.d.ts
types/test/types/d1.ts

Now https://github.com/cloudflare/workerd/pull/1586 is shipped, I wanted to update the type definitions for `.raw()` to include `{columnNames: true}` which retrun as a special case. I believe this is the best way to express it:
```ts
raw<T = unknown[]>(options: {columnNames: true}): Promise<[string[], ...T[]]>;
raw<T = unknown[]>(options?: {columnNames?: false}): Promise<T[]>;
```
This means if you pass anything other than `{columnNames: true}` you get the old type signature, i.e. just the rows. But it validates that the following syntax is correctly typed:
```ts
const [columns, ...rows] = await stmt
.bind(1)
.raw<[string, number, boolean]>({ columnNames: true });
expectType<string[]>(columns);
expectType<[string, number, boolean][]>(rows);
```
I also added an assertion that `.run()` …

D1: Adding `.raw({columnNames})` types and tests for `.run()`

---

WORKSPACE
src/workerd/api/http.c++
src/workerd/io/worker-interface.c++
src/workerd/util/abortable.h

This reverts commit 25172d0c0a8415c284cdae0933b11a70f9813d58, and includes a bugfix in a caller of `getPreferredExtensions()`.
Capnp PR: https://github.com/capnproto/capnproto/pull/1943

Revert "Revert "Add implementations for getPreferredExtensions""

---

src/workerd/api/trace.c++
src/workerd/util/uuid-test.c++
src/workerd/util/uuid.c++
src/workerd/util/uuid.h

`UUIDToString` has been moved to `UUID::toString()` and it's now possible to create a UUID from a string too.

Extend UUID API

---

WORKSPACE
patches/v8/0001-Allow-manually-setting-ValueDeserializer-format-vers.patch
patches/v8/0002-Allow-manually-setting-ValueSerializer-format-versio.patch
patches/v8/0003-Make-icudata-target-public.patch
patches/v8/0004-Add-ArrayBuffer-MaybeNew.patch
patches/v8/0005-Allow-Windows-builds-under-Bazel.patch
patches/v8/0006-Disable-bazel-whole-archive-build.patch
patches/v8/0007-Make-v8-Locker-automatically-call-isolate-Enter.patch
patches/v8/0008-Add-an-API-to-capture-and-restore-the-cage-base-poin.patch
patches/v8/0009-Speed-up-V8-bazel-build-by-always-using-target-cfg.patch
patches/v8/0010-Implement-Promise-Context-Tagging.patch
patches/v8/0011-Enable-V8-shared-linkage.patch
patches/v8/0012-Fix-V8-ICU-build.patch
patches/v8/0013-Randomize-the-initial-ExecutionContextId-used-by-the.patch
patches/v8/0014-Always-enable-continuation-preserved-data-in-the-bui.patch
patches/v8/0015-Attach-continuation-context-to-Promise-thenable-task.patch
src/workerd/api/tests/als-test.js
src/workerd/api/tests/als-test.wd-test

Patches v8 to allow async context to propgate to async thenables
@qard ... this probably doesn't tick all of the boxes v8 would need to land this (I skipped tests and there might be some additional debug asserts they'd want in a couple places) but this patch should cover the basics. Could I bother you to give it a once over? ... specifically this patch: `patches/v8/0015-Attach-continuation-context-to-Promise-thenable-task.patch`

Add v8 patch to preserve async context for custom thenables

---

src/workerd/io/BUILD.bazel

This allows us to clean up dependencies of some internal libs. It's especially nice to eliminate the dependency on the generated file `trimmed-supported-compatibility-date.txt`.

Cleanup: Split compatibility-date.capnp into its own capnp_library.

---

src/workerd/jsg/jsg.h
src/workerd/jsg/resource.h
src/workerd/jsg/setup.h
src/workerd/jsg/wrappable.h

This PR ensures that Object.prototype.toString() returns the correct values for built-in objects (i.e. ResourceTypes).

Add toStringTag value on JSG resource types

---

src/workerd/jsg/jsg.h
src/workerd/jsg/resource.h
src/workerd/jsg/wrappable.h

Reverts cloudflare/workerd#1607
Breaks downstream trace test

Revert "Add toStringTag value on JSG resource types"

---

src/workerd/io/worker.c++

It logs frequently in production. We're stuck supporting this. Sadness.

Remove log line about addEventListener in modules scripts.

---

src/pyodide/internal/python.js
src/pyodide/python-entrypoint-helper.js
src/workerd/api/BUILD.bazel
src/workerd/api/pyodide/pyodide.h
src/workerd/server/workerd-api.c++

Introduces a new `ArtifactBundler` API that is used by Python Workers to store and retrieve runtime artifacts.

Implements artifact store for Python.

---

src/cloudflare/internal/workers.d.ts
src/cloudflare/workers.ts
src/workerd/api/http.c++
src/workerd/api/tests/js-rpc-test.js
src/workerd/api/worker-rpc.c++
src/workerd/api/worker-rpc.h
src/workerd/io/worker-interface.capnp
src/workerd/jsg/jsg.h
src/workerd/jsg/resource.h
src/workerd/jsg/ser-test.c++
src/workerd/jsg/ser.c++
src/workerd/jsg/ser.h
src/workerd/jsg/setup.h

The first four commits (mainly the third commit) add a framework to allow JSG types to declare themselves serializable. @jasnell I know you were also working on something here so sorry if this overlaps. I did take some inspiration from your design doc. But, it occurred to me that instead of writing a tag and a version, we could combine these: whenever a type decides it needs a new serialization version, it allocates a whole new tag for it. This way we save some bytes on the wire.
The remaining commits, after some bug fixes and refactoring, introduce `RpcTarget` as a new type which classes can extend to mark themselves as being RPC objects -- without being a top-level entrypoint. Instances of these types can then be sent in RPC messages. The receiving side gets an `RpcStub` instead, which …

JSRPC: Support passing RPC stubs across other RPCs

---

src/workerd/api/tests/module-test.js
src/workerd/api/tests/module-test.wd-test
src/workerd/jsg/modules.c++
src/workerd/jsg/modules.h

there's probably more elegant additional cleanups that can be made in here but this fixes the immediate issue.

Fixup importing built-ins from module "subdirectories"

---

src/cloudflare/internal/d1-api.ts
src/cloudflare/internal/test/d1/d1-api-test.js

Sadly there's no way when pulling the results out to stop SQLite returning 0 or 1 (since to it, a "boolean" is just a number: https://www.sqlite.org/datatype3.html), but at least this lets you use `true` and `false` to mean 1 or 0 (the way SQLite will allow you to use `TRUE` and `FALSE`).
This fixes https://github.com/cloudflare/workers-sdk/issues/3070

D1: allow binding 'true' and 'false' by converting to 1 or 0

---

.github/workflows/release.yml

We recently moved `@cloudflare/kv-asset-handler` into the `workers-sdk` package. Miniflare's tests depend on this to verify Workers Sites work. Previously, when this was outside of `workers-sdk`, we installed built files from `npm`. Now that it's in `workers-sdk`, we're responsible for building it before using it. This change makes sure we build it before running Miniflare's tests.

Build `kv-asset-handler` before running Miniflare tests

---

.bazelrc
.github/workflows/test.yml

This resolves CI failures due to running out of disk space, at least for
the near term. Also drops a flag modifying features for windows_no_dbg,
disabling optimizations when building for the host configuration is not
necessary.
I picked common MSVC flags that are safe to use with debug info here. When I last measured this, the bazel output + cache takes up 60GB with this on a fully cached Windows-debug build whereas the build previously ran out of space upon reaching 70GB. Based on those numbers this is just a short-term fix unfortunately, a larger improvement would be possible by changing cache behavior (70GB is only reached when binaries are duplicated between disk cache and regular bazel output) or by patching bazel to make opting out of PDB generation possible.

[CI] Reduce Windows debug binary size

---

src/workerd/jsg/jsg.h
src/workerd/jsg/resource.h
src/workerd/jsg/wrappable.h

Reverts cloudflare/workerd#1714
It turns out that this change breaks some tests in miniflare -- I think we do in fact need to place it behind a compatibility flag. 
https://github.com/cloudflare/workers-sdk/blob/cab7e1c7f24ff0097e15d90030c805fe2785d173/packages/miniflare/src/workers/core/proxy.worker.ts#L81-L85

Revert "Revert "Revert "Add toStringTag value on JSG resource types"""

---

src/workerd/api/global-scope.c++

This PR changes prefix ordering for event timeout error messages, ensuring the brokenness reason comes before the `jsg.Error`.
We do this also in:
https://github.com/cloudflare/workerd/blob/9ea0e090d7f32e89239a6c687a25ef70376ea906/src/workerd/api/actor-state.c%2B%2B#L817-L836

Make broken prefix before jsg.Error for event timeouts.

---

src/workerd/jsg/setup.c++
src/workerd/jsg/setup.h

Using Attach/Detach to pass has been deprecated.

Pass CppHeap using CreateParams

---

src/workerd/api/queue.c++
src/workerd/api/queue.h

@a-robinson and I are trying to add some debug information to help identify the cause of an issue where queue events seem to hang for 15 minutes (the timeout duration).
This info should tell us:
* Is the user's queue() handler function actually finishing?
* Are there other waitUntil tasks that are causing the event to run for 15 minutes then timeout?

Add debug information for queue handler timeouts caused by lingering waituntils

---

src/workerd/api/queue.c++
src/workerd/api/queue.h

This patch updates the queues api so that a delay value can be specified when sending messages to a queue. The delay is sent as an header in the request and also as the message payload in case of a batch.

MQ-498: Add support for delivery delay in Queues

---

src/workerd/api/queue.c++
src/workerd/io/compatibility-date.capnp

Adds a new compat flag + date to switch to JSON as the default message format for Queues.

Add compatibility flag for queues JSON format by default

---

src/workerd/api/global-scope.c++
src/workerd/api/global-scope.h
src/workerd/io/worker-entrypoint.c++
src/workerd/io/worker-interface.c++
src/workerd/io/worker-interface.capnp
src/workerd/io/worker-interface.h
src/workerd/io/worker.c++
src/workerd/server/alarm-scheduler.c++
src/workerd/server/alarm-scheduler.h
src/workerd/server/server.c++

This PR adds a new `runAlarm` parameter to keep track of alarm invocation retries.

Distinguish initial alarm invocations from retries.

---

src/workerd/api/streams/common.h
src/workerd/api/streams/standard.c++
src/workerd/api/streams/standard.h
src/workerd/api/tests/streams-test.js

The cancel algorithm for TransformStreams was recently added to the spec. This implements it. See the new test for example use.
Refs: https://streams.spec.whatwg.org/#callbackdef-transformercancelcallback

Add TransformStream cancel algorithm

---

src/workerd/util/sqlite-test.c++

We accidentally a word.
No functional changes.

Fix comment in SQL test.

---

src/workerd/api/pyodide/pyodide.h
src/workerd/io/compatibility-date.capnp
src/workerd/server/tests/python/env-param/env.wd-test
src/workerd/server/tests/python/hello/hello.wd-test
src/workerd/server/tests/python/langchain/langchain.wd-test
src/workerd/server/tests/python/subdirectory/subdirectory.wd-test
src/workerd/server/workerd-api.c++

This is necessary in order to allow upload for non-cloudflare users. This is safe because EWC has custom logic for blocking the upload of bundles containing Python modules, so only certain users will be allowed to upload.

Adds python_workers compatibility flag

---

src/workerd/io/io-context.c++
src/workerd/io/io-context.h

- The total PUT size limit for a worker request continues to apply.
Note that this is effectively a NO-OP since the individual and total PUT limit are identical. Merging this first will still help us make the total PUT limit configurable – ongoing work is on the `felix/cache-put-limit` branch here and in the internal repository, but being familiar with it shouldn't be needed to review this PR.
Also updates an outdated comment, the put size limit has been 5GB for a while.

Remove cache individual PUT size limit

---

src/workerd/api/http.c++
src/workerd/api/http.h
src/workerd/api/tests/js-rpc-test.js
src/workerd/api/worker-rpc.c++
src/workerd/api/worker-rpc.h
src/workerd/io/worker-interface.capnp
src/workerd/jsg/jsg-test.c++
src/workerd/jsg/jsg.h
src/workerd/jsg/jsvalue.h
src/workerd/jsg/resource.h
src/workerd/jsg/setup.h

You can now access properties on an RPC object by just awaiting them:
let value = await stub.someProperty;
And you can access properties on a _promise_ returned by an RPC call, in order to make speculative calls on stubs that you expect to be returned:
await stub.someMethod().someOtherMethod();
Both of these are achieved via custom thenables rather than regular promises. This allows us to return a value that can be awaited, but which also has a wildcard property.

JSRPC: Promise Pipelining (and property access)

---

.bazelrc
WORKSPACE
build/wd_ts_project.bzl

This is largely for maintaining parity with the internal version following the rules_ts major update.

Roll rules_{js, ts, nodejs}, bump NodeJS version

---

src/workerd/api/http.c++
src/workerd/api/tests/js-rpc-test.js
src/workerd/io/io-context.h
src/workerd/io/worker.c++

I can't believe this was sitting under our nose this entire time!
Until now, when a native function returned a Promise that eventually rejected, the rejection Error would have an empty stack trace, making it very hard to figure out where the problem came from.
For years, we've known this is a big problem, but I thought it would be much harder to solve. Something like four years ago I was trying to figure out how to make async stack traces work, and I learned that native async stack traces require using the inspector API. But, we don't enable the inspector in production; only when debugging. So it seemed like we couldn't use this.
I'd learned this from a former V8 team member, but that person probably wasn't aware than in 2019 (after he had left) V8 added a new built-in async tracing …

Fix stack traces for native async functions that throw.

---

src/workerd/api/pyodide/pyodide.h

Just a small change to enable creating the artifact storage without an upload callback specified.

Use static universal memory snapshot

---

src/workerd/api/cache.c++
src/workerd/api/crypto.c++
src/workerd/api/gpu/gpu-buffer.c++
src/workerd/api/gpu/gpu-buffer.h
src/workerd/api/gpu/gpu-device.c++
src/workerd/api/gpu/gpu-device.h
src/workerd/api/gpu/gpu-shader-module.c++
src/workerd/api/gpu/gpu-shader-module.h
src/workerd/api/http.c++
src/workerd/api/pyodide/pyodide.h
src/workerd/api/sockets.c++
src/workerd/api/streams/internal.c++
src/workerd/api/streams/standard.c++
src/workerd/api/web-socket.c++
src/workerd/io/io-context.h
src/workerd/io/promise-wrapper.h

Previously, awaitIoImpl() would return a jsg::Promise. If awaitIo() had been called with a continuation callback, then this was appended to the promise chain by calling `.then()` on the JSG promise.
This required a lot of hackery. Many such callbacks capture KJ I/O types, so the callback had to be wrapped in an IoOwn. Similarly, the *parameter* to the callback could contain KJ I/O types, so had to be wrapped in IoOwn. Also lots of JavaScript allocation and V8 API back-and-forth is needed to schedule JSG promises like this. Finally, it could become a bit difficult to reason about whether the callback would actually outlive the KJ promise -- but many call sites require this.
Instead, we can pass the callback down and capture it via the KJ promise chain, so it never has to be "owned" by JSG …

Refactor: awaitIo() captures callback in KJ promise, not JSG.

---

src/workerd/api/basics.h

Fixes https://github.com/cloudflare/workerd/issues/1504
This overrides the `CustomEvent` types to better match other implementations.
This is my first time contributing to `workerd`, and really using JSG at all, so apologies if there's anything weird with this change. If there's a better way to do this, please just let me know.
Old output:
```typescript
export declare class CustomEvent extends Event {
constructor(type: string, init?: CustomEventCustomEventInit);
get detail(): any | undefined;
}
```
New output:
```typescript
export declare class CustomEvent<T = any> extends Event {
constructor(type: string, init?: CustomEventCustomEventInit);
get detail(): T;
}
```
TypeScript `lib.dom.d.ts` reference: https://github.com/microsoft/TypeScript/blob/1d6d962d3132a901f5fb48be4a389c45faf5a74e/src/ …

fix: CustomEvent generic type

---

WORKSPACE
patches/v8/0015-Add-ValueSerializer-SetTreatFunctionsAsHostObjects.patch
src/node/internal/internal_assert.ts
src/workerd/api/tests/js-rpc-test.js
src/workerd/api/worker-rpc.c++
src/workerd/api/worker-rpc.h
src/workerd/jsg/ser.c++
src/workerd/jsg/ser.h

It's simple: If you send someone a function, they get an RpcStub. The stub is callable. Calling it makes an RPC back to the isolate where the function was created, calling the original object there.
To reiterate, because this keeps confusing people: The function's code is NOT serialized. We are NOT magically moving code around. Closures strictly execute in the isolate where they were created.
I also went ahead and said that functions are allowed to have properties, but these work like properties on an RpcTarget. That is, they are not marshalled proactively when sending the function, but you can access them by accessing properties of the RpcStub representing the function.
There are also some other commits thrown in this PR because I did them at the same time:
* First two commits: Prevent …

JSRPC: Support "serializing" functions by turning them into stubs

---

src/workerd/api/tests/js-rpc-test.js
src/workerd/api/tests/js-rpc-test.wd-test
src/workerd/api/worker-rpc.c++
src/workerd/io/io-context.c++
src/workerd/io/worker-interface.capnp
src/workerd/server/server-test.c++
src/workerd/server/server.c++
src/workerd/server/server.h
src/workerd/server/workerd.c++
src/workerd/server/workerd.capnp

This PR makes it possible to configure incoming sockets and outgoing ExternalServers to allow negotiating a Cap'n Proto connection over HTTP. Miniflare will need this to allow RPC over service bindings to be tested, since miniflare currently implements service bindings by running each worker in a separate workerd instance.
Currently, this works by using an HTTP CONNECT request specifying a magic hostname (hostname chosen in the config). In theory it might be better to use `Upgrade`, but that would require extensions to KJ HTTP. It could also make sense to use a WebSocket endpoint, but that would have been more work. We can support those as alternatives in the future if there is demand.
I also went ahead and used this new code path to enhance js-rpc-test, so that it actually tests running …

JSRPC: Support capnp-over-http for external server bindings

---

src/workerd/api/streams/standard-test.c++
src/workerd/api/streams/standard.c++
src/workerd/api/tests/streams-test.js

The internal implementation of the JS-backed streams is rather overly complicated and has a few design flaws that make it difficult to debug and maintain. This, coupled with tests scattered across multiple repos with incomplete coverage. It's time to simplify the implementation and improve test coverage. This is the first of several clean up steps that will greatly simplify a number of cases. This commit focuses on one specific internal bit, follow on commits will touch other pieces. The plan is to do this as incrementally as possible spread over some time to ensure things don't break. The incomplete test coverage makes things a bit difficult so that will be a key focus.
Currently in a JS-backed `ReadableStream`, we have an underlying `ReadableStreamJsController` that has either a …

Greatly simplify JS-backed ReadableStreams AllReader

---

src/workerd/api/http.h
src/workerd/api/tests/js-rpc-flag.js
src/workerd/api/tests/js-rpc-test.js
src/workerd/api/tests/js-rpc-test.wd-test
src/workerd/io/compatibility-date.capnp

These were intended to be convenient wrappers around `fetch()` that perform the respective HTTP method. It was a bad idea (my fault). Luckily it was never documented and probably few people depend on it.
Note that a long time ago, KV namespace bindings were Fetchers rather than being the specific KvNamespace type. This had lots of problems, but sort of worked as long as your key names were URL-safe. It's possible very old scripts are in production that still depend on these old-style bindings, but they won't be broken since they obviously have ancient compat dates as well. (In fact... they predate compat dates...)

Remove Fetcher methods get(), put(), delete() with compat flag.

---

src/workerd/api/basics.h

This simplifies this type override as reported by @mrbbot in https://github.com/cloudflare/workerd/pull/1759#discussion_r1513493487.
It produces the same output:
```typescript
export class CustomEvent<T = any> extends Event {
constructor(type: string, init?: CustomEventCustomEventInit);
get detail(): T;
}
```

chore: simplify CustomEvent type override

---

src/workerd/jsg/exception.c++

We check for these cfjs errors in tunneledErrorType, but there hasn't been any code that generated such exceptions for quite a long time at this point, so it's safe to remove them now.
---
FWIW I think the jsg-internal prefix is unused (other than by a couple macros that are themselves unused), so we may want to rip that out as well.

cleanup: Remove remaining references to cfjs

---

samples/pyodide-fastapi/config.capnp
samples/pyodide-fastapi/worker.py
src/pyodide/internal/asgi.py

According to the suggestion I got here:
https://github.com/tiangolo/fastapi/discussions/11219#discussioncomment-8625938 this makes it possible to get access to `env` in fastapi as follows:
```py
from asgi import env
@app.get("/hello")
async def root(env=env):
return {"message": "Hello World", "secret": env.secret}
```

Simplify access to env parameter from fastapi

---

src/workerd/api/http.c++
src/workerd/api/http.h
src/workerd/api/queue-test.js
src/workerd/api/queue.c++
src/workerd/api/queue.h
src/workerd/io/worker-interface.capnp

This patch updates the queues api so that a delay value can be specified (from the consumer side) when retrying a batch or a message. Existing retry fields in capnp structs were maintained to prevent breaking changes. These fields are consolidated with the new ones on the broker side.

MQ-498: Add support for delayed retries in Queues

---

src/pyodide/BUILD.bazel
src/pyodide/internal/builtin_wrappers.js
src/pyodide/internal/python.js
src/pyodide/python-entrypoint-helper.js

This ensures that Pyodide instantiation and package loading happens inside of the enterStartupJs limitEnforcer. In workerd, we can't yet load packages outside of an IoContext because we make actual requests to load the packages. So in workerd, only run loadPyodide at top level and run setupPackages at first request. In the internal runtime, we can do the whole thing at top level.
As a side effect, we have to disable hash randomization because normally the hash comes from `crypto.getRandomValues` but this crashes at top level. Likewise, Python initializes the `random` module's random seed using `crypto.getRandomValues`. We replace `crypto.getRandomValues` with a function that tries to call `crypto.getRandomValues` but if it throws an Error saying `"Disallowed operation called within global …

Set up Pyodide in the top level scope

---

src/workerd/api/streams/standard.c++

Continuing on with necessary simplifications of the js-backed streams implementation. This carries on from the previous `AllReader` and `PumpToReader` change to further simplify

Simplify ValueReadable/ByteReadable

---

src/pyodide/internal/python.js

This fixes two bugs in the code:
* `length` is not defined for ArrayBuffer, so changed to `byteLength`.
* Emscripten expects a Uint8Array instead of an ArrayBuffer, so ensure that is what we have.

Fixes Python memory snapshot loading.

---

src/workerd/api/global-scope.c++
src/workerd/api/global-scope.h
src/workerd/api/tests/js-rpc-test.js
src/workerd/api/tests/js-rpc-test.wd-test
src/workerd/api/worker-rpc.c++
src/workerd/api/worker-rpc.h
src/workerd/io/io-context.c++
src/workerd/io/io-context.h
src/workerd/io/worker-entrypoint.c++
src/workerd/io/worker-interface.capnp
src/workerd/jsg/jsg.c++
src/workerd/jsg/jsg.h
src/workerd/jsg/resource.c++
src/workerd/jsg/resource.h
src/workerd/jsg/rtti-test.c++
src/workerd/jsg/rtti.capnp
src/workerd/jsg/rtti.h
src/workerd/jsg/setup.c++
src/workerd/jsg/setup.h

* RpcStubs and RpcPromises now have `Symbol.dispose`.
* Stubs passed in call parameters are automatically disposed upon return.
* If the result of a call is an object, a disposer will be added to it, which disposes all stubs therein. (If it's not an object, it can't possibly contain any stubs...)
* Stubs also have a `dup()` method which creates a separately-disposed copy of the stub, in case you want to keep a stub past when it would otherwise be automatically disposed.
* Of course, when the I/O context is destroyed, everything is implicitly disposed.
Note: The first few commits use a method named "dispose" but the last commit changes it to `Symbol.dispose`. Maybe I should have done that first, oh well.

JSRPC: Support resource management for RPC stubs

---

src/workerd/api/streams/internal.c++
src/workerd/io/io-context.c++
src/workerd/io/io-context.h

EW-8204
The unused stream warning emitted when a tee'd branch of an internal stream is left unconsumed is spammy and not very helpful. This change improves things by ensuring that only one instance of the warning per IoContext is emitted, aggregating all of the information about branches that are not read. The warning message is further augmented to include the JavaScript stack trace locations where each of the unconsumed branches were created.

Add WarningAggregator, improve unused stream warning

---

src/workerd/util/sqlite-test.c++
src/workerd/util/sqlite.c++

There are two commits here:
1. Return error when writing a read-only file in the in-memory VFS
2. Return error when truncating a read-only file in the in-memory VFS
The commit message for the write commit has a bunch of detail on why we want that particular fix.  I'm ambivalent on the truncate commit and could see the wisdom of dropping that commit (especially since I don't know how to test it at a high level), but it does seem weird to fix write, but not fix truncate.

Return errors for mutations on read-only files in the in-memory VFS (rather than crashing)

---

src/workerd/io/worker.c++

The lower timeout could plausibly be hit purely due to a busy CPU loop after issuing a storage operation. The new number matches the CPU limit per request. There's no need for this to be exactly the same number as that, but it seemed just as good a reason as I had for any other larger number.

Increase the timeout for storage operations before resetting an actor

---

src/workerd/api/worker-rpc.c++
src/workerd/io/worker-entrypoint.c++

The `IoContext` will be destroyed during the course of `event->run()`, at which point this `onAbort()` will reject with a "PromiseFulfiller destroyed without fulfilling promise" exception. I don't know why this doesn't happen in tests but it seems to happen a lot in prod?
Anyway, I moved the `onAbort()` handling into the JSRPC CustomEvent implementation, which is the place I needed it for my purposes. I suspect many CustomEvent implementations do not honor onAbort(), though, which will need to be fixed later.

Fix recently-introduced onAbort() in WorkerEntrypoint::customEvent().

---

src/workerd/io/limit-enforcer.h
src/workerd/io/worker.c++
src/workerd/io/worker.h
src/workerd/server/server.c++
src/workerd/server/workerd-api.c++
src/workerd/tests/test-fixture.c++

Currently it isn't very different but this gives us a bit of additional flexibility for configuring Python startup limits.

Add separate enterStartupPython limiter specifically for Python

---

src/workerd/io/observer.h

Allows RequestObservers to receive metrics on dynamic dispatch.j

Add dispatch metrics

---

types/src/generator/type.ts
types/test/generator/type.spec.ts

Hey! 👋 This PR ensures `kj::Array(Ptr)<const char>`s are treated as `string`s when generating TypeScript types. 
Previously we assumed both `char`s and `unsigned char`s were byte arrays. This isn't quite right, `kj::byte` is defined as `unsigned char` and `char` arrays represent `string`s in JSG. This PR updates the TypeScript generator to only treat `unsigned char` arrays as byte arrays.
This results in the following diff for the `experimental` entrypoint (all compatibility flags enabled) from `@cloudflare/workers-types@4.20240222.0` (the last correct types version) to the types with this change:
<details>
<summary>Diff</summary>
```diff
diff --git a/node_modules/@cloudflare/workers-types/experimental/index.d.ts b/bazel/definitions/experimental/index.d.ts
index 1ef970c..2c5f491 100755 …
```

fix: treat `kj::Array(Ptr)<const char>`s as TypeScript `string`s

---

src/workerd/io/compatibility-date.capnp
src/workerd/jsg/jsg.h
src/workerd/jsg/promise-test.c++
src/workerd/jsg/promise.h
src/workerd/jsg/type-wrapper.h
src/workerd/jsg/value.h
src/workerd/server/workerd-api.c++

Adds a new compat flag that enables support for accepting custom thenables in the jsg `PromiseWrapper`.
Note that this is on received values only (e.g. `tryUnwrap(...)`.

Support for custom thenables in PromiseWrapper with compat flag

---

src/workerd/api/sql-test.js
src/workerd/util/sqlite.c++

Fixes https://github.com/cloudflare/workerd/issues/1760

Make SQLite VTable module name comparison case-insensitive

---

src/workerd/jsg/url-test.c++
src/workerd/jsg/url.c++
src/workerd/jsg/url.h

Separates the `jsg::Url` modifications out from the module registry refactor PR to ever-so-slightly reduce the size of that PR... addresses review comments also.
Refs: https://github.com/cloudflare/workerd/pull/1553

Separate out some jsg::Url mods from the module registry refactor

---

src/pyodide/internal/python.js
src/pyodide/python-entrypoint-helper.js
src/workerd/api/pyodide/pyodide.c++
src/workerd/api/pyodide/pyodide.h
src/workerd/server/workerd-api.c++

This assumes that we disallow access to `pyodide-internal` from the Python code.
TODOs left:

Implements Jaeger tracing for Python.

---

src/workerd/io/io-context.c++
src/workerd/io/io-context.h
src/workerd/io/limit-enforcer.h
src/workerd/server/server.c++
src/workerd/tests/test-fixture.c++

Make cache API PUT limit configurable

---

WORKSPACE
patches/sqlite/0002-macOS-missing-PATH-fix.patch

The macOS CI build consistently failed with "couldn't find HOME environment variable to expand path" errors on several branches. While I was unable to reproduce the error or figure out why it started appearing, this can be fixed by patching out the command that leads to HOME being queried (it is only used to define an unused variable anyway).

[CI] Fix macOS build

---

WORKSPACE
patches/sqlite/0003-sqlite-complete-early-exit.patch
src/workerd/api/sql-test.js
src/workerd/api/sql-test.wd-test
src/workerd/api/sql.c++
src/workerd/api/sql.h
src/workerd/util/sqlite.c++
src/workerd/util/sqlite.h

This PR adds the required APIs to enable ingesting a ReadableStream of data from a Request and, in a single transaction, applying all the statements to the DB. For example:
```js
const reader = request.body.getReader()
const decoder = new TextDecoder()
await storage.transaction(async () => {
let buffer = ''
while (true) {
const { value, done } = await reader.read()
if (done) break
const chunk = decoder.decode(value, { stream: true })
// Append the new chunk to the existing buffer
buffer += chunk
// Ingest any complete statements and snip those chars off the buffer
buffer = sql.ingest(buffer)
}
})
```
This is made possible by a new API, `sql.ingest(string)` that immediately executes all valid SQL statements in the string, returning the substring of the input that is yet to be processed …

SQLite: add streaming input SQL endpoint `sql.ingest`

---

src/pyodide/internal/python.js
src/pyodide/python-entrypoint-helper.js
src/workerd/io/io-context.h

This PR:
* Moves upload outside the global scope
* Makes certain methods in IoContext  public so they can be used in EW.
Tested in EW.

Fixes memory snapshot upload for Python Workers.

---

src/workerd/api/streams/internal.c++

When tee'ing an internal stream that was already teed, we'll end up with an extraneous unused stream warning if we don't mark it read.
Fixes: https://github.com/cloudflare/workerd/issues/983

Mark a teed WarnIfUnusedStream as read

---

src/workerd/api/streams/common.h
src/workerd/api/streams/standard.c++
src/workerd/api/streams/standard.h
src/workerd/api/tests/streams-test.js

Previously landed but reverted while tracking down some other issue. Adds support for the new TransformStream cancel algorithm

Reland TransformStream cancel algorithm

---

src/workerd/api/streams/standard.c++
src/workerd/api/streams/standard.h
src/workerd/api/streams/writable.h
src/workerd/api/tests/streams-test.js
src/workerd/api/tests/streams-test.wd-test

Partially undoes a prior change that removed the weakref between the WritableStream JS implementation and it's underlying WritableStreamDefaultController.

Use a weakref between WritableStream and WritableStreamDefaultController

---

src/pyodide/internal/python.js
src/pyodide/python-entrypoint-helper.js
src/workerd/api/pyodide/pyodide.h

Adds more spans and metadata.
Tested in internal repo.

Improve Jaeger Python traces (more spans/snapshot tag).

---

src/workerd/api/BUILD.bazel
src/workerd/api/streams/internal-test.c++
src/workerd/api/streams/internal.c++
src/workerd/api/streams/internal.h

In some uses we end up enqueuing a write event to a `WritableStreamInternalController` while it is being piped to, leading to an assertion given that we expect the `Pipe` event to be the last event in the queue while it is being piped. To match the behavior seen when using the `WritableStreamDefaultWriter`, we should reject attempts to write, close, or flush while the pipe is still going.
Also improves the logging around the assertion that was being hit and fixes another apparent latent bug in the pipe source close check.

Prevent queuing writes while internal writable is being piped

---

src/workerd/api/http.c++
src/workerd/io/compatibility-date.capnp

It turns out that there exists code in the wild which explicitly detects binding types based on the presence of certain methods, and also code in the wild which appears to call RPCs by accident. It's unclear if anyone is actually broken, but out of an abundance of caution, we'd better put this behind a compat flag.

JSRPC: Guard wildcard method behind feature flag.

---

src/pyodide/BUILD.bazel
src/pyodide/internal/jaeger.js
src/pyodide/internal/metadata.js
src/pyodide/internal/process_script_imports.py
src/pyodide/internal/python.js
src/pyodide/internal/setupPackages.js
src/pyodide/python-entrypoint-helper.js
src/workerd/server/workerd-api.c++

This adds dedicated memory snapshots. It's pretty finicky how you load shared
libraries in a memory snapshot since their metadata needs to be allocated in the
same location whether starting from scratch or from the snapshot. The simplest
way to deal with it is to preload the libraries in a given order before the
runtime starts. This approach leaves us without a good way of figuring out which
ones are needed so we take a naive approach and preload all of them.
We then parse the user code into abstract syntax trees and look for import
nodes. We try to import all of these and catch and throw away if it fails.
Then we record which dynamic libraries have been dlopened and where the handles
are located. We put the handle data together with the heap snapshot.
This required pretty major surgery …

Dedicated Python memory snapshots

---

src/pyodide/internal/python.js
src/pyodide/python-entrypoint-helper.js
src/workerd/api/pyodide/pyodide.h

Some small changes to make it possible for validator to get the memory snapshot.

Implements changes needed for Python mem snapshot in validator.

---

src/pyodide/internal/metadata.js
src/pyodide/internal/python.js
src/workerd/api/pyodide/pyodide.c++
src/workerd/api/pyodide/pyodide.h

Implements functionality to grab the memory snapshot from the WorkerBundle (without disabling grabbing it from the ArtifactStorage, though WorkerBundle snapshot is prioritised).

Uses memory snapshot from WorkerBundle for Python.

---

WORKSPACE
src/pyodide/BUILD.bazel
src/pyodide/internal/setupPackages.js

In flame graphs this single call frame takes up a lot of loading time. It also is not necessary except for debugging purposes. This gets rid of it.

Python perf: Don't report undefined symbols

---

src/node/internal/mock.js
src/node/test.js
src/workerd/api/node/assert-test.js

Requires the `nodejs_compat` compatibility flag to be enabled.
Does not yet support mock timers.
Does not implement the full `node:test` module, just the mocks
Refs: https://nodejs.org/docs/latest/api/test.html#class-mocktracker
Implementation was adapted directly from Node.js implementation. Only changes necessary to make it work in workers were made. Majority of new lines are the tests (which were also adapted directly from Node.js' tests). The API and implementation here are intended to match Node.js'.
While this could likely be polyfilled fairly easily, building it into the runtime allows us to take advantage of it for our own tests, much like we've started to do with `node:assert`

Implement node:test MockTracker

---

src/workerd/api/cache.c++
src/workerd/io/io-context.c++
src/workerd/io/io-context.h
src/workerd/io/limit-enforcer.h
src/workerd/server/server.c++
src/workerd/tests/test-fixture.c++

After further discussions within the team, we will be lifting the limit entirely as limits defined in the Cache backend will be sufficient. This enables significant cleanup, including the limit functions defined in #1772 and the existing cache stream setup.
Also see the corresponding downstream PR.

Remove Cache API PUT limit

---

src/workerd/api/http.c++
src/workerd/api/http.h
src/workerd/api/queue-test.js
src/workerd/api/queue.c++
src/workerd/api/queue.h
src/workerd/io/worker-interface.capnp
src/workerd/server/server-test.c++

This patch updates the queue message capnp schema so that the number of attempts is included within each message, allowing queue consumers to implement backoff logic based on that. Note this is a breaking change and we are making sure that all clients are updated accordingly before this change gets released.

MQ-576: Add attempts to QueueMessage

---

src/node/internal/debuglog.ts
src/node/util.ts
src/workerd/api/node/util-nodejs-test.js

Handful of additional `node:util` APIs

Fill out more of the node:util implementation

---

src/workerd/io/observer.h

The metric indicates if a worker has actually dispatched to another, not that it has a dispatch binding.

Clearify dispatch metrics

---

.gitignore
build/wd_ts_type_test.bzl
package.json
pnpm-lock.yaml
src/cloudflare/.eslintrc.json
src/cloudflare/internal/d1-api.ts
src/cloudflare/internal/sockets.d.ts
src/cloudflare/internal/vectorize-api.ts
src/cloudflare/tsconfig.json
src/node/.eslintrc.json
src/node/tsconfig.json
src/workerd/api/actor.h
src/workerd/api/global-scope.h
src/workerd/api/http.h
types/.prettierrc
types/defines/disposable.d.ts
types/defines/rpc.d.ts
types/src/generator/structure.ts
types/src/generator/type.ts
types/src/index.ts
types/src/transforms/comments.ts
types/src/transforms/globals.ts
types/src/transforms/helpers.ts
types/src/transforms/iterators.ts
types/src/transforms/overrides/index.ts
types/test/index.spec.ts
types/test/print.spec.ts
types/test/types/rpc.ts
types/test/types/tsconfig.json

This PR adds TypeScript types for JSRPC. `Fetcher`s and `DurableObjectNamespace`s are now generic types accepting subclasses of `WorkerEntrypoint` and `DurableObject` respectively. Most of the interesting changes are in `types/defines/rpc.d.ts` with tests verifying the types in `types/test/types/rpc.ts`.
I wanted to use `using` in my TypeScript type tests, and the `Disposable` `interface` in the stub type. This necessitated an upgrade to TypeScript 5.2+. This update included a few breaking compiler API changes, meaning the types generator had to be updated a bit.

JSRPC: Add TypeScript types

---

src/node/internal/internal_inspect.ts
src/node/internal/workers.d.ts
src/node/tsconfig.json
src/workerd/api/tests/js-rpc-test.js
src/workerd/api/worker-rpc.h

Previously, code like this would fail:
```js
const counter = new Counter();
const stub = new RpcStub(counter);
console.log(await stub.increment()); // 1
console.log(await stub.increment()); // 2
console.log(stub);
console.log(await stub.increment()); // Fails with "Error: RPC stub used after being disposed."
```
The `util.inspect()` function has special handling for JSG resource types. In particular, it tries to call the `entries()` function if it's defined for `Map`-like formatting. Because `RpcStub`s and other JSRPC types define wildcard property handlers, `entries()` existed, but attempting to call it and iterate through the resulting value ended up triggering this line:
https://github.com/cloudflare/workerd/blob/bfcfe9a7b2518a93d6c6d176be2f45d27e7c0913/src/workerd/api/worker-rpc.c%2B%2 …

JSRPC: Ensure logging `RpcStub`s doesn't dispose them (skip getting `entries()` for RPC types)

---

src/pyodide/python-entrypoint-helper.js
src/workerd/api/pyodide/pyodide.h
src/workerd/server/workerd-api.c++

Right now we have a limiter around the full Python Worker startup (which includes the time it takes to start up Pyodide). This PR implements a simple limiter to have a separate limit for the Python user code specifically.

Implements limiter for startup of Python user code.

---

src/workerd/api/tests/js-rpc-test.js
src/workerd/api/trace.c++
src/workerd/api/trace.h
src/workerd/api/worker-rpc.c++
src/workerd/io/trace.c++
src/workerd/io/trace.h
src/workerd/io/worker-interface.capnp
src/workerd/util/own-util.h

eventInfo was being left null, causing wrangler tail not to report the event at all. Let's fill it in and specify the top-level method name.
Also added entrypoint name, which seems highly relevant to JSRPC.

JSRPC: Fill in trace (tail) events better.

---

src/workerd/api/hibernatable-web-socket.c++
src/workerd/api/hibernatable-web-socket.h
src/workerd/api/queue.c++
src/workerd/api/queue.h
src/workerd/api/streams/readable.c++
src/workerd/api/tests/js-rpc-test.js
src/workerd/api/trace.c++
src/workerd/api/trace.h
src/workerd/api/worker-rpc.c++
src/workerd/api/worker-rpc.h
src/workerd/io/worker-entrypoint.c++
src/workerd/io/worker-interface.h

This fixes two bugs @jasnell discovered (but he's OOO this week so can't review).

JSRPC: Fix waitUntil() and response streams

---

WORKSPACE
src/workerd/api/trace.c++
src/workerd/api/trace.h
src/workerd/io/io-context.c++
src/workerd/io/trace.c++
src/workerd/io/trace.h
src/workerd/io/worker-interface.capnp
src/workerd/io/worker.c++
src/workerd/io/worker.h
src/workerd/jsg/util.c++
src/workerd/jsg/util.h
src/workerd/jsg/value.h

A new property, `stack`, contains the stack trace.
To support this in the case of async exceptions (which have already been converted to KJ), exception tunneling now adds a serialized copy of the V8 error to the exception itself, as a "detail". For now, this is _only_ used by `logUncaughtException()`. In the future, though, when the exception propagates back into JavaScript, we could de-tunnel it by deserializing this detail, rather than based on the description string. However, there are several complexities that need to be solved first, so I have not tried to do that in this PR.
Depends on: https://github.com/capnproto/capnproto/pull/1978

Add exception stack traces to trace/tail events.

---

src/pyodide/internal/python.js

Invalidate caches if we have a baseline snapshot because the contents of site-packages may be different when we rerun.

Python baseline snapshot: Invalidate caches

---

src/pyodide/BUILD.bazel

Looks like #1868 also replaces a call to Module.reportUndefinedSymbols, which throws an error in local dev because this value is assigned in two other places like so:
```
Module.reportUndefinedSymbols = () => {}
...
Module["reportUndefinedSymbols"] = ...
```
Which are not matched by the rule. This PR simply refuses to replace `Module.reportUndefinedSymbols()` with `Module.reportUndefinedSymbolsNoOp()`.

Fix bug with reportUndefinedSymbols shim

---

WORKSPACE
patches/v8/0001-Allow-manually-setting-ValueDeserializer-format-vers.patch
patches/v8/0002-Allow-manually-setting-ValueSerializer-format-versio.patch
patches/v8/0003-Add-ArrayBuffer-MaybeNew.patch
patches/v8/0004-Allow-Windows-builds-under-Bazel.patch
patches/v8/0005-Disable-bazel-whole-archive-build.patch
patches/v8/0006-Make-v8-Locker-automatically-call-isolate-Enter.patch
patches/v8/0007-Add-an-API-to-capture-and-restore-the-cage-base-poin.patch
patches/v8/0008-Speed-up-V8-bazel-build-by-always-using-target-cfg.patch
patches/v8/0009-Implement-Promise-Context-Tagging.patch
patches/v8/0010-Enable-V8-shared-linkage.patch
patches/v8/0011-Randomize-the-initial-ExecutionContextId-used-by-the.patch
patches/v8/0012-Always-enable-continuation-preserved-data-in-the-bui.patch
patches/v8/0013-Attach-continuation-context-to-Promise-thenable-task.patch
patches/v8/0014-increase-visibility-of-virtual-method.patch
patches/v8/0015-Add-ValueSerializer-SetTreatFunctionsAsHostObjects.patch
patches/v8/0016-wasm-liftoff-arm64-Fix-LoadTaggedPointer.patch

This PR adds a v8 patch that has already existed in edgeworker for a while. It causes a failed DCHECK when a wasm module with large functions is run in arm64 platforms.

Cherry-pick arm64 loadtaggedpointer fix

---

RELEASE.md

Added explanation on why release actions are done on main, not on the release tag.

Update Release docs

---

types/defines/rpc.d.ts

Hey! 👋 This PR removes some references to `Symbol.dispose()` introduced in #1870. As this comment helpfully explains... 
https://github.com/cloudflare/workerd/blob/aa43411321843bfe19709d8e4a9a18d54a049f79/types/defines/disposable.d.ts#L1-L7
...using `Symbol.dispose` will fail type checking with TypeScript versions before 5.2. 🤦‍♂️ 
These uses of `Symbol.dispose` were meant to hint that these classes could be `Disposable`s and `workerd` would handle calling `Symbol.dispose` at an appropriate time. Users can still define `Symbol.dispose()` without these definitions. They were also meant to provide some basic type checking if users did define a `Symbol.dispose`, but since they're `void` return typed, anything could've been returned from them. Removing them shouldn't cause any problems.
Note …

fix: remove `Symbol.dispose` references for old TypeScript versions

---

src/pyodide/internal/metadata.js
src/pyodide/internal/python.js
src/pyodide/internal/reportError.js
src/pyodide/internal/setupPackages.js
src/pyodide/internal/util.js
src/pyodide/python-entrypoint-helper.js

Nonfunctional change. Rename reportError.js into util.js and move simpleRunPython there. Also run formatter.

Minor Python cleanup

---

src/pyodide/BUILD.bazel
src/pyodide/internal/python.js

See #1919 
Instead of keeping Modules.reportUndefinedSymbols, this PR actually defines Modules.reportUndefinedSymbolsNoOp and performs the substitution as before.

Different fix for reportUndefinedSymbolsNoOp bug

---

src/pyodide/internal/tar.js

Previously file names (which are actually file paths + names) could not exceed 100 bytes. This supports the `gnu` style of long names, which is the default behavior of `tar` on my debian system. We will probably need to support this eventually since some file names are already up to 97 bytes.

Support long names in tarfs

---

.github/workflows/release.yml

Hey! 👋 These alerts have been a little too noisy for us, and aren't really actionable/useful. Removing them until we can figure out a better process.

Remove chat alerts on Miniflare test failures

---

src/pyodide/internal/builtin_wrappers.js
src/pyodide/internal/python.js
src/pyodide/internal/snapshot.js
src/pyodide/internal/tar.js
src/pyodide/python-entrypoint-helper.js

Nonfunctional change. This splits python.js (~600 lines) into two files, with ~360 lines moved into `snapshot.js`. I think it's easier to understand this way.

Move Python snapshot logic to its own file

---

src/workerd/api/queue.c++
src/workerd/io/io-context.c++
src/workerd/io/io-context.h
src/workerd/io/worker-entrypoint.c++

WIP
- Ignore "aborted" requests and only log info on timeouts
- TODO: Add more contextual info (user account ID)
CC: @a-robinson

Update queues debug logging to ignore aborted requests

---

src/workerd/api/actor.h

Include `GetDurableObjectOptions` in `DurableObjectNamespace` override

---

.bazelrc
.github/workflows/release.yml
.github/workflows/test.yml
Dockerfile.release
build-releases.sh
build/wd_cc_benchmark.bzl

- Match macOS wd_benchmark link options with wd_binary options
- Correct spelling of WIN32_LEAN_AND_MEAN
- /await and /GF are ignored by clang-cl, no need to pass them in the
Windows build.

Add platform-specific release configuration

---

src/workerd/api/basics.c++
src/workerd/api/basics.h
src/workerd/api/http-test.js
src/workerd/api/tests/abortsignal-test.js

The spec defines `onabort` as a prototype property, implement it as such.
Technically speaking, this *could* be considered a breaking change :-/ ... I'm hoping we can get away with it without requiring a compat flag. It's a potentially breaking change because prior to this, the following operations would have different results:
* `'onabort' in AbortSignal.prototype`  ... previously, false, now true
* `delete signal.onabort` ... previously deletes the own property if set, now has no change
* `Object.keys(signal)` ... previously would include `onabort` if it was set, now always excludes it
One thing this PR doesn't do (that we can do later in a separate PR) is define the type mapping override for `onabort`.

Implement AbortSignal.protototype.onabort

---

src/workerd/api/streams/standard.h

Per the standard, these properties are really supposed to be prototype properties, not instance properties.
Technically this *could* be considered breaking... I think it's extremely unlikely to actually break anyone.

Convert the standard properties on streams objects to prototype

---

src/workerd/io/worker.c++
src/workerd/io/worker.h
src/workerd/server/server-test.c++
src/workerd/server/server.c++

This fixes a regression in miniflare around named entrypoints: If a script had a top-level export that was an object with no instance properties, miniflare would treat it as a named entrypoint (configuring a socket for it), but workerd would consider this config invalid because the export didn't appear to actually be able to handle events.
It would be hard to make miniflare be able to detect the types of exports, so instead we make workerd more lenient.

Allow referencing empty-object exports as entrypoints.

---

src/workerd/api/tests/url-test.js
src/workerd/api/url-standard.c++
src/workerd/api/url-standard.h

~~Should wait to land until after https://github.com/whatwg/url/pull/825 lands..~~ spec change landed!
Refs: https://github.com/whatwg/url/pull/825

Implement URL.parse

---

.bazelrc
.github/workflows/release.yml
.github/workflows/test.yml
Dockerfile.release
build-releases.sh
build/wd_cc_benchmark.bzl

Reverts #1900. The issue is fixed in #1964, but reverting is also an option given the time constraints.
============
This reverts commit 3eb728b05b0f03b8f675aee1e8d598fd55c4b11b. The change caused an unforeseen regression in macOS binary size as the Unix release configuration failed to actually apply the 'opt' configuration.

Revert "Add platform-specific release configuration"

---

types/defines/hyperdrive.d.ts

It is returned as a number in the implementation of the binding (both in prod and in local development), not a string. This was purely an error in the types.
Noticed in https://github.com/cloudflare/cloudflare-docs/pull/13763#discussion_r1552262281
---
Confirmed both by checking the return type in our source code (`uint16_t`) and by running `console.log(typeof(env.HYPERDRIVE.port));` within a worker at the edge and getting back `number`.

Fix the type of the Hyperdrive binding's port field

---

src/workerd/api/r2-api.capnp
src/workerd/api/r2-bucket.c++
src/workerd/api/r2-bucket.h

Adds an string option called storageClass for the R2 binding PutObject and CreateMultipartUpload methods. R2 will interpret this string to determine the storage class of the newly created object.
Adds a field to HeadResult, and by extension GetResult and ListResult, that R2 will use to return the storage class to the binding.
There is a corresponding internal PR for this change.

Add support for a storageClass option for R2 objects

---

src/workerd/api/tests/js-rpc-test.js
src/workerd/io/worker-interface.capnp
src/workerd/jsg/dom-exception.c++
src/workerd/jsg/dom-exception.h

Makes DOMException cloneable for use with jsrpc and `structuredClone()`

Make DOMException serializable/cloneable

---

src/workerd/jsg/observer.h

This separates out the new ResolveObserver interface from the new module registry PR in order to make it easier to review and further reduce the size of that other PR. This only adds the definition and does not introduce any code that uses it. That'll come with the module registry PR.
The idea is to improve observability of the module resolution process, including tracking the failure cases. For workerd, these observers are non-ops by default but can be set up by embedders to have actual backing implementations.
Refs: https://github.com/cloudflare/workerd/pull/1553

Add ResolveObserver to jsg/observer.h

---

.bazelrc
.github/workflows/test.yml
src/workerd/util/BUILD.bazel

- Pass -fdebug-info-for-profiling in the profile configuration. We may also want to add this in some other -g1-based configurations to have better backtraces, but that can be handled separately.
- -g1 is not needed at link time.
- As of bazel 7.1, `bazel info` does no longer produce excessive warnings – drop the warning filter.
- Report CI disk space usage in MB – this makes it easier to gauge the binary size impact of code changes.
- Drop superfluous perfetto-tracing => V8 dependency.

[build] Fix profile configuration, assorted build cleanup

---

src/workerd/api/streams/readable.c++

... to squash a compiler warning about a non-final class with a virtual destructor.

Mark NoDeferredProxyReadableStream as final

---

src/workerd/io/hibernation-manager.c++

I believe it should be ok to only do this for the autoresponse because I think the non-autoresponse path already calls synctime.

call syncTime for hibernatable websocket autoresponses

---

.bazelrc

Mark C++ inline methods as hidden, causing them to not be exported when creating shared libraries.
This significantly reduces binary sizes and possibly link times on Linux, where shared linkage is used for everything except the workerd binary (build folder size shrinks 7011MB => 6954 MB based on CI statistics). There is a smaller binary size improvement for macOS, where shared linkage is not enabled by default.
I want to also enable actual hidden visibility (i.e. `-fvisibility=hidden`) for V8, but that likely requires significant patching as it is only supported in the V8 GN build so far.
See https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html#index-fvisibility-inlines-hidden for background information.

[build] Add -fvisibility-inlines-hidden

---

src/workerd/jsg/BUILD.bazel
src/workerd/jsg/jsg.h

Also remove url.c++ from "jsg" library since it is part of "url". Glob before didn't make it obvious that url.c++ is included twice.

[nfc] replace glob with explicit file list

---

src/workerd/server/server.c++

Prior to this commit, if a Durable Object in Workerd (local dev/miniflare) hibernated (i.e. Worker::Actor was destroyed), but the stub wasn't dropped by the worker (i.e. PromisedWorkerInterface still alive), then we would incorrectly create an entirely new refcounted ActorContainerRef upon a new request coming in.
This is incorrect because the old ActorContainerRef is still owned, and by creating an entirely separate one, we break our request tracking.
Specifically, the ActorContainer only tracks a weak reference to an ActorContainerRef, and so if we have two separate ActorContainerRef's one of them will not be tracked.

Reuse ActorContainerRef if it exists

---

src/workerd/api/BUILD.bazel
src/workerd/api/pyodide/pyodide.h
src/workerd/api/sockets.c++
src/workerd/jsg/BUILD.bazel
src/workerd/jsg/memory-test.c++
src/workerd/jsg/modules.h
src/workerd/jsg/resource.h
src/workerd/jsg/url-test.c++
src/workerd/jsg/url.c++
src/workerd/tests/BUILD.bazel
src/workerd/tests/test-fixture.c++
src/workerd/tests/test-fixture.h

Spiritual successor to #2012. Also see the downstream PR.
- [build][nfc] Clean up JSG build file in accordance with IWYU
- [nfc] Drop support for old V8 version
This was only needed around the time of the switch from 12.0 to 12.1.

[nfc] Clean up JSG build

---

src/workerd/io/trace.c++
src/workerd/io/trace.h
src/workerd/io/worker-interface.capnp

Passes `scriptId` and `sourcemapsAvailable` through various usages of `Trace`.

Pass scriptId in Trace

---

src/workerd/io/actor-cache.c++
src/workerd/io/actor-cache.h

These commits were scattered before and after the larger read coalesce changes, and since that change is really big and complicated, I figured it would be easier to yank these quick refactors out into a separate PR so we can focus on the scary stuff elsewhere.

Quick ActorCache refactor

---

src/workerd/io/io-channels.h

Added new `startTime` field to be used for general accounting to `IoChannelFactory::SubrequestMetadata`.

Add Request Start Time to SubrequestMetadata

---

types/defines/rpc.d.ts

Fixes #1996
Previously, the RPC types used `unique symbol` to enforce nominal typing rather than structural typing for Durable Object and Service binding entrypoints. While this works, it's slightly _too_ strict. It meant that different versions of `DurableObject` and `WorkerEntrypoint` were not compatible (e.g. across workers-types entrypoints, and across ambient and exported types. This PR relaxes that constraint to use a well-known string instead, which will preserve nominal typing unless someone goes out of their way to add a specific property.
cc @Skye-31

Remove unique symbol from RPC types

---

src/workerd/io/io-context.c++
src/workerd/io/io-context.h
src/workerd/io/io-own.c++
src/workerd/io/io-own.h

Avoid allocating the new string on every dereference. The previous iteration was done pretty quickly just to get something we can test with. I imagine we'll keep it so let's make it more performant.

Improve new IoOwn logging

---

src/pyodide/BUILD.bazel
src/pyodide/internal/builtin_wrappers.js
src/pyodide/internal/python.js
src/pyodide/internal/snapshot.js
src/pyodide/internal/topLevelEntropy/entropy_import_context.py
src/pyodide/internal/topLevelEntropy/entropy_patches.py
src/pyodide/internal/topLevelEntropy/import_patch_manager.py
src/pyodide/internal/topLevelEntropy/lib.js
src/pyodide/internal/util.js
src/pyodide/python-entrypoint-helper.js
src/workerd/server/tests/python/BUILD.bazel
src/workerd/server/tests/python/random/random.wd-test
src/workerd/server/tests/python/random/worker.py

We don't have access to entropy outside of request scope, so `random()` will give poor results. Raise an error if it is called.

Python: Make top level random() raise

---

src/workerd/api/streams/readable.c++
src/workerd/api/streams/writable.c++
src/workerd/api/tests/streams-test.js

In some edge cases, if the Writer/Reader is the only thing remaining holding a strong reference to a WritableStream or ReadableStream, the calls to `close()`, `abort()`, `cancel()`, etc can cause the Writer/Reader to drop it's strong reference in mid operation, leading to issues. Let's defensively hold an additional strong reference while the operations are pending

Hold strong refs in certain streams Writer/Reader methods

---

src/workerd/io/actor-cache-test.c++
src/workerd/io/actor-cache.c++
src/workerd/io/actor-cache.h

This is some additional refactoring work that the read coalesce change relies on.
I specifically wanted to separate this so we can think about whether we want to retain the `FLUSHING` state or continue forward with `flushStarted`. It was too difficult to untangle that change when the smaller commits were all over the large single PR, but now that they're all [in front of us](https://github.com/cloudflare/workerd/pull/1914) we should be able to make changes with less effort.

Refactor: ActorCache flush transaction and CountedDeletes

---

src/workerd/io/actor-cache-test.c++
src/workerd/io/actor-cache.c++
src/workerd/io/actor-cache.h

Sorry @a-robinson, I forgot to change the target branch to `main` from `actor-cache-refactor` before merging [the actual PR](https://github.com/cloudflare/workerd/pull/1915) :upside_down_face:.

Refactor: ActorCache flush transaction and CountedDeletes (attempt 2)

---

src/workerd/api/streams/queue.c++
src/workerd/io/io-context.h
src/workerd/jsg/jsg.h
src/workerd/jsg/promise-test.c++
src/workerd/jsg/promise.h

Remove last few uses of the deprecated jsg/promise method variants that do not take a jsg::Lock as the first param.
Just some drive by general cleanup while investigating some other issues.

Cleanup deprecated jsg/promise methods

---

src/workerd/server/server.c++
src/workerd/tests/test-fixture.c++

Set default getAlarmLimit() value to 15 minutes to avoid hitting 'invalid alarm timeout value' warning in workerd.

Set default getAlarmLimit() value to 15 minutes

---

src/cloudflare/internal/ai-api.ts
src/cloudflare/internal/test/ai/ai-api-test.js
src/cloudflare/internal/test/ai/ai-api-test.py
src/cloudflare/internal/test/ai/ai-mock.js

This was a testing method added to debug the Ai binding, and is now being deprecated.
It no longer returns any data from the server

Deprecate getLogs method from Ai binding

---

src/workerd/util/sqlite.c++
src/workerd/util/sqlite.h

There are `sqlite3` API functions that may prepare and execute their own internal statements.  We need to call those functions with a regulator or we’ll summarily reject them.  Adding a method to do this seemed like a clean way of handling these cases.

Add SqliteDatabase::executeWithRegulator

---

src/workerd/api/streams/internal.c++
src/workerd/api/tests/streams-test.js
src/workerd/api/tests/streams-test.wd-test
src/workerd/io/compatibility-date.capnp

Per the spec, a BYOB read is supposed to return an empty ArrayBufferView when the stream is closed (done = true) in order to allow the code reading to retake ownership of the underlying buffer. This change makes the internal streams implementation return an empty Uint8Array in this case, matching the behavior of the JS-backed standard streams impl.
~~It's unlikely but this may be considered a breaking change if anyone has code that depends on the fact that `value` would be `undefined` if `done === true` when using the old streams implementation. We need to decide if this case needs a compat flag or not. I'd prefer not to have to introduce Yet Another One.~~ Updated to add the compat flag :-(

Have internal streams return empty Uint8Array on end of byob stream

---

src/workerd/api/tests/js-rpc-test.js
src/workerd/api/worker-rpc.c++

An oversight on my part. :(
Tested in internal PR.

JSRPC: Honor output gates.

---

src/workerd/util/sqlite.c++

There's certain kinds of schema changes that are really painful to do in SQLite; this makes things a little easier.
For example, let's say you want to change the "users.email" column's collation to be case-insensitive (COLLATE NOCASE). You can't do that with ALTER TABLE, so what you have to do instead is a three-step dance*:
1: rename users to users_old
2: create a new table users with the same schema as users_old, except
for the collation, and copy the data over
3: drop users_old
The problem comes in with foreign keys. If you've got a "favorites.user_id" column that's a foreign key to users.id, then doing the above dance will delete all your users' favorites (assuming ON DELETE CASCADE, otherwise it'll error out).
1: after the rename, all the foreign keys now reference users_old.id
2: no …

sqlite: allow PRAGMA legacy_alter_table

---

src/workerd/io/worker.c++

The capnproto pull request
https://github.com/capnproto/capnproto/pull/2014 adds another assignment operator for Maybes.  With a version of capnproto including that PR, we get compilation errors of the form:
```
external/workerd/src/workerd/io/worker.c++:2524:15: error: use of overloaded operator '=' is ambiguous (with operand types 'kj::Maybe<InspectorChannelImpl &>' and 'void')
channel = {};
~~~~~~~ ^ ~~
bazel-out/k8-dbg/bin/external/capnp-cpp/src/kj/_virtual_includes/kj/kj/common.h:1679:17: note: candidate function
inline Maybe& operator=(decltype(nullptr)) { ptr = nullptr; return *this; }
^
bazel-out/k8-dbg/bin/external/capnp-cpp/src/kj/_virtual_includes/kj/kj/common.h:1682:17: note: candidate function
inline Maybe& operator=(T* other) { ptr = other; return *this; }
^
```
The Maybes …

Reset kj::Maybes with `kj::none` instead of `{}`

---

src/workerd/api/basics.c++
src/workerd/api/events.c++
src/workerd/api/events.h
src/workerd/api/global-scope.c++
src/workerd/api/global-scope.h
src/workerd/api/rtti.c++
src/workerd/api/tests/reporterror-test.js
src/workerd/api/tests/reporterror-test.wd-test
src/workerd/api/web-socket.c++
src/workerd/api/web-socket.h
src/workerd/io/worker.c++
src/workerd/jsg/jsg.c++
src/workerd/jsg/jsg.h
src/workerd/jsg/setup.h
src/workerd/server/workerd-api.c++
src/workerd/tools/api-encoder.c++

Refs: https://developer.mozilla.org/en-US/docs/Web/API/reportError
/cc @irvinebroque

Implements the web platform standard reportError API

---

src/workerd/api/sql-test.js
src/workerd/api/sql.c++
src/workerd/api/sql.h
src/workerd/util/sqlite.c++
src/workerd/util/sqlite.h

D1 bills based on rows read and written, but sql.ingest() didn't return those. Now it does.
This required changing the return type of sql.ingest(), but it's an experimental API so that should be okay.
let sqlCode = "INSERT INTO tbl (col) VALUES (123); INSERT I";
let result = sql.ingest(sqlCode);
Old:
result == " INSERT I"
New:
result.remainder == " INSERT I"
result.meta.rowsRead == 0
result.meta.rowsWritten == 1
This "meta" attribute also gives us a convenient spot to stick additional information. For example, if we wanted to count how many SQL statements ingest() executed, we could easily add "result.meta.statementsExecuted" without breaking any existing users.
Implementation-wise, there might be an optimization opportunity around SqlStorage::IngestResult::getMeta(). Right now, it …

Return row counts for SQL ingestion (storage.sql.ingest()).

---

src/workerd/api/sockets.c++
src/workerd/api/streams/common.h
src/workerd/api/streams/internal.c++
src/workerd/api/streams/internal.h
src/workerd/api/streams/standard.c++
src/workerd/api/streams/writable.c++
src/workerd/api/streams/writable.h

removeSink is used to extract the WritableStreamSink that is owned by a WritableStream using the original implementation. It is currently used in only three places in the codebase, two of which are unnecessary. There are two pending changes refactoring those two places to avoid using `removeSink()` as currently defined. Replacing the version of `removeSink` that returns the `WritableStreamSink` with a `detach()` method that returns nothing covers the sockets use case where we call the method then immediately throw away the sink.
Opening this to broadcast the intent in case folks have reason to keep removeSink around.
Once this and the two other PRs land, we hopefully move towards removing removeSink entirely. Note that ultimately the goal is to entirely eliminate the need for (and remove …

Deprecate WritableStream::removeSink

---

src/workerd/jsg/modules.c++
src/workerd/jsg/modules.h

We need to determine two things:
1. Are worker bundles with multiple modules all that common and
2. Are worker bundles using module names that are known to be Node.js bare builtin specifiers.
The idea is for this logging to be temporary.

Add temporary module logging

---

src/workerd/api/http-test.js
src/workerd/api/http.c++
src/workerd/api/http.h

RM-18292
Updates the Request object to support specifying a cache mode per the standard. Only `undefined`, `'no-store'` and `'no-cache'` may be specified, and the fetch implementation specifically does not implement the semantics for either `'no-store'` or `'no-cache'` yet. This just lays the ground work for the additional changes.
The next step is to start adding the support for adding the appropriate header fields in the fetch implementation behind an autogate.

Update Request to support cache option

---

src/workerd/api/html-rewriter.c++
src/workerd/api/streams/transform.c++
src/workerd/api/streams/transform.h

The original code was allocating an `IdentityTransformStream` and `WritableStream` just to end up throwing both away immediately after. This simplifies things by making it possible to create a the identity pipeline that underlies `IdentityTransformStream` directly, simplifying things a bit by avoiding the unnecessary additional allocations and removing an unnecessary use of the `removeSink()` API.
Internal CI is green.

Avoid unnecessary allocations in HTMLRewriter

---

src/pyodide/internal/topLevelEntropy/entropy_import_context.py
src/pyodide/internal/topLevelEntropy/entropy_patches.py

Package installation uses tempfile which tries to create entropy. This patches it to use a deterministic sequence of file names.
@garrettgu10

Fix package installation in workerd with top level entropy restrictions

---

src/workerd/io/io-context.c++

The error now reports the total number of timeouts started instead of just the number of outstanding timeouts.

Added more data to help debug timeout id collisions

---

src/cloudflare/internal/ai-api.ts

This re-adds a removed property as backwards compatibility, removed in the last release

Fix ai binding logs property

---

WORKSPACE
docs/v8-updates.md
patches/v8/0001-Allow-manually-setting-ValueDeserializer-format-vers.patch
patches/v8/0002-Allow-manually-setting-ValueSerializer-format-versio.patch
patches/v8/0003-Add-ArrayBuffer-MaybeNew.patch
patches/v8/0004-Allow-Windows-builds-under-Bazel.patch
patches/v8/0005-Disable-bazel-whole-archive-build.patch
patches/v8/0006-Make-v8-Locker-automatically-call-isolate-Enter.patch
patches/v8/0007-Add-an-API-to-capture-and-restore-the-cage-base-poin.patch
patches/v8/0008-Speed-up-V8-bazel-build-by-always-using-target-cfg.patch
patches/v8/0009-Implement-Promise-Context-Tagging.patch
patches/v8/0010-Enable-V8-shared-linkage.patch
patches/v8/0011-Randomize-the-initial-ExecutionContextId-used-by-the.patch
patches/v8/0012-Always-enable-continuation-preserved-data-in-the-bui.patch
patches/v8/0013-increase-visibility-of-virtual-method.patch
patches/v8/0014-Add-ValueSerializer-SetTreatFunctionsAsHostObjects.patch
patches/v8/0015-Set-torque-generator-path-to-external-v8.-This-allow.patch
patches/v8/0016-Modify-where-to-look-for-fp16-dependency.-This-depen.patch
patches/v8/0017-Fixup-RunMicrotask-to-restore-async-context-on-termi.patch
patches/v8/0018-Expose-v8-Symbol-GetDispose.patch
patches/v8/0019-Rename-V8_COMPRESS_POINTERS_IN_ISOLATE_CAGE.patch
src/workerd/api/node/util-nodejs-test.js
src/workerd/jsg/jsg.c++
src/workerd/jsg/resource.c++
src/workerd/jsg/setup.c++
src/workerd/jsg/setup.h

Non-trivial changes:
* V8 appears to be in the process of supporting the explicit resource management spec. Since `Symbol.dispose` has been exposed to JS I've patched v8 to expose it via a native API so we can now use v8's `Symbol.dispose` for our JS RPC implementation.
* Node’s util.inspect changed behaviour due to the following V8 change: https://chromium-review.googlesource.com/c/v8/v8/+/5378709. I've patched the tests to reflect the new behaviour.

Jphillips/v8 12.5

---

src/workerd/api/http.c++
src/workerd/api/tests/blob2-test.js
src/workerd/api/tests/blob2-test.wd-test
src/workerd/io/compatibility-date.capnp
src/workerd/util/mimetype-test.c++
src/workerd/util/mimetype.c++
src/workerd/util/mimetype.h

Using a compatibility flag, selects the correct content type for a blob from the fetch-provided content-type header(s) as defined by the fetch spec: https://fetch.spec.whatwg.org/#concept-header-extract-mime-type
Sadly it's potentially breaking change so the compat flag is needed.
Fixes: https://github.com/cloudflare/workerd/issues/2099
Goal: Web standards compliance, bug fix

Fix content type determination for blob from fetch

---

src/workerd/api/http.c++

Previously an invalid content-length would result in an unhelpful "internal error" message to the user. This intercepts that error and replaces it with a more helpful message.
Longer term, it would be idea to align this more with the fetch spec but for now, improving the error message is a good first step.
Fixes: https://github.com/cloudflare/workerd/issues/2101

Improve user facing error message on invalid content-length

---

src/workerd/api/http-test.js
src/workerd/api/http.c++
src/workerd/api/http.h

This reverts commit https://github.com/cloudflare/workerd/commit/bb8c8cd75e6a85dc88a1905553eb1ce4e1e58576.
This is a temporary fix for https://github.com/cloudflare/workerd/issues/2116. We plan to re-add this feature behind a compatibility flag.

Revert "Update Request to support cache option (#2073)"

---

src/workerd/jsg/memory.c++
src/workerd/jsg/memory.h
src/workerd/jsg/modules-new-test.c++

An API change in v8-profiler.h causes the build to complain about ambiguous API usage. This fixes things up so it's not ambiguous.
Needed for the v8 12.6 update

Cleanup in preparation for a v8 12.6 change

---

src/workerd/api/http-standard-test.js
src/workerd/api/http-standard-test.wd-test
src/workerd/api/http.c++
src/workerd/io/compatibility-date.capnp

Adds a compat flag that makes it so that the fetch('...') method variant that takes a URL string, the `Request` object constructor, and redirects will use the standard URL parser.
This is not really how I would prefer to address this since, unfortunately, this introduces a double parsing and serialization of the URL in order to minimize changes to the existing implementation. It would be nicer (and very possible) to refactor things to avoid the double parsing at some point.
Fixes: https://github.com/cloudflare/workerd/issues/1957

Add fetch_standard_url compat flag

---

src/workerd/api/crypto.c++
src/workerd/api/crypto.h
src/workerd/api/tests/crypto-streams-test.js

This is one of a series of PRs intended to simplify and improve the implementation/safety/performance/design of various streams bits in the runtime. This one starts with refactoring `DigestStream`.
 
The original implementation of `DigestStream` used a `WritableStreamSink` and the old "internal" streams implementation. This is unnecessary and makes the implementation less efficient than it otherwise could be due to the operations having to bounce between the kj event loop and the JS isolate lock. There's just nothing in the implementation of `DigestStream` that requires the bound through the kj event loop and the original implementation was more an artifact of what was possible at the time it was written.
This PR converts `DigestStream` into a JS-backed stream where the operations occur …

Convert DigestStream into JS-backed stream

---

src/workerd/jsg/modules.c++
src/workerd/jsg/modules.h

This reverts commit c3c30aa32ce028e3ecd42e3fc6d11b7f1da93dc3.
The temporary logging showed us what we needed to know. Ok to remove it now.

Revert "Add temporary module logging (#2083)"

---

src/workerd/jsg/setup.c++
src/workerd/jsg/setup.h

V8 does not dispose of the v8::CppHeap we pass to it on isolate construction, so we now do that ourselves.

Fix CppGc leak.

---

src/cloudflare/internal/ai-api.ts
src/cloudflare/internal/test/ai/ai-api-test.js
src/cloudflare/internal/test/ai/ai-mock.js
types/defines/ai.d.ts

This adds support for defining gatewayId in the .run method

Add support for setting gatewayId in AI binding

---

src/workerd/api/tests/js-rpc-test.js
src/workerd/api/worker-rpc.c++
src/workerd/api/worker-rpc.h

`IoContext::WeakRef` is a KJ I/O object, so `kj::Own<IoContext::WeakRef>` is not safe to hold from a JSG object. Instead, it would need to be `kj::IoOwn<IoContext::WeakRef>`. But, at that point we don't even need the `WeakRef` anymore because dereferencing the `IoOwn` itself will do exactly the check that we were using the `WeakRef` to do.
Actually, all we really need here is an `IoPtr<T>` (the type of `T` is irrelevant) which we can attempt to dereference in order to effect the context check we want.

Fix JsRpcPromise::Resolved context checking.

---

src/workerd/io/worker.h
src/workerd/jsg/modules.c++
src/workerd/jsg/modules.h
src/workerd/jsg/setup.h
src/workerd/server/server.c++

Fixes: https://github.com/cloudflare/workerd/issues/2112

Provide the raw specifier for the module fallback service

---

src/workerd/io/BUILD.bazel
src/workerd/io/actor-cache-test.c++
src/workerd/io/actor-cache.c++
src/workerd/io/actor-sqlite.c++
src/workerd/server/server-test.c++
src/workerd/util/autogate.c++
src/workerd/util/autogate.h

These "Durable Object storage is no longer accessible" exceptions would occur during actor destruction, if no other explicit exception is provided.  It is unknown if these still occur, but it seems likely that they would occur due to a transient reason -- like the worker getting evicted -- rather than overload, so we'd like to treat them as retryable.

actor-cache: migrate DO default shutdown exception type from "overloaded" to "disconnected"

---

src/workerd/api/sockets.c++
src/workerd/api/sockets.h

Adds a `highWaterMark` to `SocketOptions` that is used to configure the high water mark for the socket `WritableStream`. When the size of the internal pending write queue reaches this value, the stream will signal backpressure to the user.

Add `highWaterMark` option to `Socket` for backpressure signaling

---

src/workerd/io/worker-interface.capnp
src/workerd/jsg/dom-exception-test.c++
src/workerd/jsg/dom-exception.c++
src/workerd/jsg/dom-exception.h
src/workerd/jsg/jsg.h
src/workerd/jsg/ser.c++
src/workerd/jsg/setup.h
src/workerd/jsg/util.c++
src/workerd/jsg/util.h

* Eliminate the extra object allocated for the stack using the new v8::Exception::CaptureStackTrace API.
* Avoid having to use the JS constructor to create instances by using the FunctionTemplate directly

Refactor DOMException

---

src/workerd/api/global-scope.h

Bug Fix: Expose TransformStreamDefaultController as global

---

src/workerd/jsg/ser.c++
src/workerd/jsg/setup.c++
src/workerd/jsg/wrappable.c++
src/workerd/jsg/wrappable.h

v8 is simplifying the way embedder apis connect to wrapper JS objects.
This attempts to keep the necessary changes as minimal as possible.
Note that with the move to `v8::Object::Wrap/Unwrap`, we ought to be able to eliminate the special handling of the context global wrapper and simplify things a bit further, but that's bit of a larger change. Will save that for a separate PR.

V8 Updates: Migrate to v8::Object::Wrap/Unwrap

---

src/workerd/api/web-socket.c++
src/workerd/api/web-socket.h

Breaks the strong ref cycle between the two WebSockets in a WebSocketPair.
Aso, while at it, add a missing visitForGc impl to WebSocket to make sure the stored error, if any, is traced.

Use weak refs between WebSockets in a WebSocketPair

---

.github/workflows/npm-types.yml
.github/workflows/npm.yml
.github/workflows/release.yml

This should fix the compatibility issues causing the npm-types build to fail by implicitly updating the LLVM version – note that ubuntu-latest still resolves to 22.04 at this time. Also updates the version CI jobs to use 24.04 since they build code without creating binaries to be published.

[CI] Use Ubuntu 24.04 for npm-types build

---

src/workerd/api/streams/internal.c++
src/workerd/api/streams/internal.h
src/workerd/api/streams/standard.c++
src/workerd/api/streams/standard.h

Fixes a bug in the internal WritableStream impl that would cause it to signal backpressure too often, also add a warning if a WritableStream excessively exceeds the configured highwatermark (if any). "Excessive" here is defined as a multiple of the high water mark.

Bug Fix: Fixup WritableStream backpressure signaling, add warning

---

.github/workflows/npm-types.yml

This should fix type generation, the Ubuntu 24.04 image appears to be lacking libc++ (?). Note that this is not a complete revert of the previous commit, version jobs continue to use 24.04 as they appear to work with 24.04 without issue. Mirroring the build configuration there too would add additional maintenance overhead.

[CI] Have npm-types build job mirror release build job

---

src/workerd/api/http-test.js
src/workerd/api/url.c++
src/workerd/api/url.h
src/workerd/jsg/resource.c++
src/workerd/jsg/resource.h
src/workerd/jsg/type-wrapper-test.c++

V8 has deprecated the SetAccessor method. Per the deprecation message, we're supposed to replace it with SetNativeDataProperty. Unfortunately, SetNativeDataProperty does not work with setters specified on the prototype. Doh! Per feedback from the v8 team, we should use SetAccessorProperty for this case instead.
Unfortunately, SetAccessorProperty is not a drop in replacement for the deprecated SetAccessor and requires more extensive changes than simply calling a different method.
Can't say that I'm entirely happy with this PR as is given the duplication is ends up introducing. We may want to revisit this whole bit to determine if there's a way of simplifying things.

V8 Updates: Replace deprecated SetAccessor with SetAccessorProperty

---

.devcontainer/Dockerfile
.github/workflows/npm-types.yml
.github/workflows/release.yml
.github/workflows/test.yml
Dockerfile.release

Be more intentional about what dependencies we use. This should make CI run a bit faster.
===========
Was inspired to do this while debugging an internal CI issue. We have long resolved our CI space constraints by not building everything twice and using shared linkage, but this should still speed up the build process slightly.

[CI] Reduce set of build dependencies

---

src/workerd/jsg/value.h

There are plenty memory leaks reported with clean shutdown.
I think the fundamental reason is this line: https://github.com/v8/v8/blob/main/src/objects/backing-store.cc#L180
and our array returning nullptr for begin()

avoid backing store allocation for 0-sized arrays

---

src/node/internal/process.ts
src/node/internal/util.d.ts
src/workerd/api/global-scope.c++
src/workerd/api/global-scope.h
src/workerd/api/node/node-compat-v2-test.js
src/workerd/api/node/node-compat-v2-test.wd-test
src/workerd/api/node/node.h
src/workerd/api/node/util.c++
src/workerd/api/node/util.h
src/workerd/io/compatibility-date.capnp
src/workerd/io/worker.c++
src/workerd/jsg/jsg.c++
src/workerd/jsg/jsg.h
src/workerd/jsg/modules.c++
src/workerd/jsg/modules.h
src/workerd/jsg/setup.h

The `nodejs_compat_v2` flag supersedes the 'nodejs_compat' flag. When enabled...
1. Node.js built-ins are available for import/require
2. Unlike the original `nodejs_compat` flag, Node.js imports do not require the 'node:' specifier prefix. Internally, the implementation will detect a Node.js raw specifier and convert it into the appropriate prefixed specifier, e.g. 'fs' becomes 'node:fs'
3. The `Buffer`, `process`, and `global` are exposed on the global
4. A user worker bundle can still provide its own implementations of all `node:` modules which will take precedence over the built-ins
5. The new `process.getBuiltinModule(...)` API is implemented. See https://github.com/nodejs/node/pull/52762
A worker can replace the implementation of `node:process` if they choose, which may mean that …

Node.js Compat: Implement the nodejs_compat_v2 compat flag

---

src/workerd/server/server.c++

This was supposed to have been done in the original PR but I accidentally forgot to merge the change in that PR

Rename fallback service "raw" param to "rawSpecifier"

---

src/workerd/api/streams/internal.c++
src/workerd/api/streams/internal.h

These changes improve the account for external memory usage in internal readable and writable streams. JS-backed streams will be handled in a separate PR.
When a `v8::BackingStore` is detached from the `v8::ArrayBuffer`, it is no longer accounted for in the external memory reporting for a given isolate. Here we implement manual adjustments for both pending read into buffers and enqueued data.

Account for external memory usage internal streams

---

types/defines/cf.d.ts

Adding colo id for bucket requests

Adding colo id for bucket requests

---

src/node/buffer.ts
src/workerd/api/node/node-compat-v2-test.js

https://nodejs.org/api/buffer.html#bufferatobdata
https://nodejs.org/api/buffer.html#bufferbtoadata
Fixes #2196

fix(node:buffer): add missing atob and btoa exports

---

src/workerd/api/r2-bucket.c++
src/workerd/api/r2-bucket.h

This is a bit of a random drive-by optimization. I noticed that the R2Bucket `Checksums` class was unnecessarily performing multiple heap allocations and copies when it could be implemented with stack allocation and a single copy. This does end up making instances of `Checksum` slightly larger but reduces the number of small heap allocations and copies.
In reality, the `Checksums` class really could have been a struct given how it is used but that would possibly be a breaking change :-/

Optimize r2-bucket Checksums

---

.bazelrc
.github/workflows/test.yml

Test plan:
```
bazel test /src/...
```
Observe that Python import tests are not run.
Furthermore, Python import tests should be run in:
1. Linux nondebug on workerd CI
2. Linux debug on Edgeworker CI

Disable slow tests by default

---

.bazelrc
.github/workflows/test.yml

Reverts cloudflare/workerd#2205
I think this breaks upstream CI, so it's not safe to merge just yet. Investigating now 😳

Revert "Disable slow tests by default"

---

src/workerd/api/streams/standard-test.c++
src/workerd/jsg/BUILD.bazel
src/workerd/jsg/jsg-test.h
src/workerd/jsg/modules-new-test.c++
src/workerd/jsg/util.c++
src/workerd/jsg/value.h
src/workerd/util/autogate.c++
src/workerd/util/autogate.h

Add .retryable and .overloaded properties to tunneled exception objects based on the `kj::Exception` type.  The intent is to provide hints to the worker about whether a failed Durable Object operation should be retried.
For "disconnected"-type exceptions, we set the `.retryable` property to true to indicate that the operation's failure is likely transient, and could be retried using best practices, like randomized exponential backoff.
For "overloaded"-type exceptions, we set the `.overloaded` property to true to indicate that retrying the operation in the short term will probably fail, and might contribute to further failures.
We otherwise leave the properties undefined.
Implementation is behind an `ACTOR_EXCEPTION_PROPERTIES` autogate.

Add .retryable and .overloaded properties to tunneled exception objects

---

.github/workflows/test.yml
src/workerd/server/tests/python/import_tests.bzl

- Generating the test files is likely much less expensive than building them, but still cuts down the number of superfluous build actions.
===========
This eliminates ~140 build targets out of ~8000 total depending on build platform. Keeping that number under control makes it easier to reason about bazel caching and build performance.

[CI] Don't generate python tests if they will not be built

---

src/workerd/api/tests/commonjs-module-test.js
src/workerd/api/tests/commonjs-module-test.wd-test
src/workerd/jsg/modules.c++
src/workerd/jsg/modules.h
src/workerd/server/workerd-api.c++
src/workerd/server/workerd.capnp

Adds the ability for a worker module definition to define a list of named exports. So if the CJS module exports something like...
```
exports.foo = 42;
```
Then the worker can import `foo` directly from the module:
```
import { foo } from 'cjs-module';
```
This just enables the exports in workerd, a separate internal PR will be required to enable it's use in production.
The runtime does very little lifting here. It will be up to whomever is constructing the worker module configuration to identify the exports that should be provided. The runtime will not try to automatically detect the exports. if an export is named but not actually defined by the CJS module, then it's value will be `undefined`. Only exports that are defined when the initial evaluation of the module completes will be …

Implement named export support for CJS modules

---

src/workerd/api/blob.c++
src/workerd/api/blob.h
src/workerd/api/form-data.c++
src/workerd/api/form-data.h
src/workerd/api/http.c++
src/workerd/api/r2-bucket.c++
src/workerd/api/tests/blob-test.js
src/workerd/io/limit-enforcer.h

Updates the `Blob` storage (`ownData`) to use a `jsg::BufferSource` rather than a raw `kj::Array<byte>` to allow the isolate to better track the external memory allocation.
While in here, also updates the `concat(...)` method to use the new safer `copyFrom(...)` API in kj replacing the less safe `memcpy` and manual pointer arithmetic.
We also avoid an extraneous copy when creating a File from a Blob

Improve Blob memory accounting

---

src/workerd/api/streams/queue-test.c++
src/workerd/api/streams/queue.c++
src/workerd/api/streams/queue.h
src/workerd/api/streams/standard.c++
src/workerd/jsg/buffersource.h

To better account for per-isolate external memory usage, use a jsg::BufferSource to store the backing store in various queues instead of jsg::BackingStore.

Account for external memory is JS-backed BYOB streams

---

src/workerd/api/hibernatable-web-socket.c++
src/workerd/api/hibernatable-web-socket.h
src/workerd/api/trace.h

Should resolve unused field warnings.
---
Apparently unused since the `waitUntilTasks` method parameters were added in d1275703d.  More work could be done to clean up the now-unused constructor parameters, but this at least resolves the build warnings.

Remove unused waitUntilTasks fields

---

src/workerd/api/streams/standard.c++
src/workerd/api/streams/writable.c++
src/workerd/api/tests/js-rpc-test.js

First pass at implementing support for JS-backed WritableStreams with JSRPC.
Provides an alternative adapter that will acquire the isolate lock on each write/close call, passing the operation off to the JS interface. This is obviously not as efficient as the original adapter used for `WritableStreamSink` but not yet sure if there's a better approach.

Implement support for JS-backed WritableStreams in JSRPC

---

src/pyodide/internal/loadPackage.js

Fix for "Python: Fetch error while loading external packages #2229"
`response.body.arrayBuffer()` to `response.arrayBuffer()`

Python: Fix fetching external packages loadBundle

---

src/workerd/api/sockets.c++

A regression was introduced in the socket API with the recent additional of the fetch standard url compat flag.
Fixes: https://github.com/cloudflare/workerd/issues/2232

Fixup regression in socket api

---

src/workerd/api/r2-bucket.c++

Improve error message for R2 etag parsing logic

---

src/workerd/api/r2-bucket.c++

Recently tried to make an optimization here but ran into some errors. Some of the hash sizes in some cases were not correct. Need to understand how common this is and determine if there's another problem somewhere.

Add logging if r2-bucket metadata hash sizes are not correct

---

src/workerd/api/sockets.c++

This was creating a new `Request` object just to serialize the default CfProperty field. This ended up being a bit wasteful, requiring additional wasted allocations and copies.

Simplify socket connect a bit

---

src/workerd/api/blob.c++
src/workerd/api/blob.h
src/workerd/api/http.c++
src/workerd/api/http.h
src/workerd/api/tests/blob2-test.js

Refs: https://fetch.spec.whatwg.org/#body-mixin
Refs: https://w3c.github.io/FileAPI/#dfn-Blob
The `bytes()` method was recently added to `Blob` and the `Body` mixin.

Implement new bytes() method for Blob and Body objects

---

.github/workflows/release.yml
.github/workflows/test.yml

The updated runner image uses an MSVC version that expects LLVM 17, but the image has LLVM 16 still, leaving it in a broken state. Manually install 17 as a workaround.

Work around actions/runner-images#10004

---

src/workerd/api/blob.c++
src/workerd/api/blob.h
src/workerd/io/BUILD.bazel
src/workerd/io/features.capnp
src/workerd/io/observer-test.c++
src/workerd/io/observer.c++
src/workerd/io/observer.h

Too often we end up adding temporary logging output to determine if a particular feature, API, etc is being used. This PR introduces a new "Feature Observer" that is essentially a process-wide set of counters that can be used to determine how much a particular feature is used. For workerd this is a non-op by default. Internally, the idea is to collect these metrics process-wide via a prometheus endpoint.
Features themselves are just simple identifiers defined in a capnp enum.  In code, we can call `FeatureObserver::maybeRecordUse(feature)` to increment the counter for a particular feature. This will make it easier for us to add in tracking to determine if and how much a particular feature is used.
There is an internal PR that builds on this. Discussion on how this is expected to be …

Add FeatureObserver to metrics

---

src/cloudflare/internal/vectorize.d.ts
types/defines/vectorize.d.ts

Add the new type definition for Vectorize v2 insert/upsert response. This would be used to enable v2 operations in wrangler by making the new type available in workers-sdk.

VS-197: Add new type for Vectorize v2 insert response

---

.github/workflows/release.yml

The issue is a re-edition of #2168, no longer defining the version directly
should stop this from reappearing.

[CI] Fix miniflare build

---

.github/workflows/release.yml
.github/workflows/test.yml

Follow-up to #2248. The upgraded image uses a higher LLVM version by default, causing the upgrade action to be rejected. We don't actually need to downgrade in that case, but this allows us to support both the old and the new image.

[CI] Make Windows build work with updated GitHub Actions image

---

src/workerd/api/sql-test.js
src/workerd/util/sqlite.c++

This module was inadvertently missed in the original allow list – it's a standard part of of FTS5. As per the docs:
> The fts5vocab module is a part of FTS5 - it is available whenever FTS5 is.
https://www.sqlite.org/fts5.html#the_fts5vocab_virtual_table_module

Allow fts5vocab module (#1540)

---

src/cloudflare/workers.ts
src/workerd/api/node/node.h
src/workerd/api/tests/compat-flags-test.js
src/workerd/api/tests/compat-flags-test.wd-test
src/workerd/jsg/jsvalue.c++
src/workerd/jsg/jsvalue.h

A simple built-in module and API for determining if a given compat flag is set.
```
import { compatFlags } from 'cloudflare:workers'
// Any of the enable/disable flag names can be passed here.
// Invalid values come out as `undefined`.
console.log(compatFlags['url_standard']);
console.log(compatFlags['url_original']);
```
Having an API for this is something we've discussed a few times.
Note that this only works with ESM syntax workers given that it requires the module registry.

Implements cloudflare:workers compatFlags API

---

.github/workflows/release.yml
.github/workflows/test.yml

The issue has been fixed in actions/runner-images#10014, which has been fully deployed since. Since this issue happened the last time LLVM was updated within MSVC, our build might be broken again without warning the next time too.

[CI] Remove Windows CI image workaround

---

src/workerd/api/tests/js-rpc-test.js
src/workerd/api/worker-rpc.c++

...so that they get the expected ".remote" property when tunneled to JS, like exceptions from Durable Object fetch() calls do.

Annotate exceptions arriving over JSRPC as "remote"

---

WORKSPACE

In particular this pulls in the change to allows using reserved IP addresses:
https://github.com/capnproto/capnproto/pull/2066

Update capnp dependency.

---

src/workerd/io/io-context.h
src/workerd/jsg/util.c++

In this case `js.tryCatch()` wouldn't actually catch the `JsExceptionThrown`. But we actually want to ignore this type of error too.

Fix addExceptionDetail() when execution is being terminated.

---

src/workerd/io/worker.c++

`messagePump()` is defined as:
```
return receiveLoop().exclusiveJoin(dispatchLoop()).exclusiveJoin(transmitLoop());
```
`receiveLoop()` is responsible for receiving the final close message, and `transmitLoop()` is responsible for replying to it. This creates a race where `receiveLoop()` might receive the close message and exit before `transmitLoop()` can reply.
We can fix this by having `receiveLoop()` pause after receiving a close message. `transmitLoop()` will reply to it and then return, at which point `receiveLoop()` will be canceled anyway.

Fix shutdown timing in inspector protocol.

---

src/workerd/api/encoding.c++
src/workerd/api/tests/encoding-test.js

The Encoding [spec](https://encoding.spec.whatwg.org/#names-and-labels) requires that case-insensitive labels are supported.

Support case-insensitive encoding in TextDecoder API (Fixes #2300)

---

types/defines/versions.d.ts

Hi :wave: ,
This PR adds a `timestamp` field to the type definitions of Version Metadata bindings. Based on my testing, this field is already present on bindings today, and Walshy told me it's fine to add it to types.
cc @WalshyDev

Add timestamp field to version metadata type

---

.github/workflows/release.yml

The Miniflare testing was broken and complaining about this. Not sure how to test without merging it in first, but CI is already broken on main so 🤷

Specify pnpm version in release action

---

.github/workflows/release.yml

Looks like the previous change worked! Let's try this to match the version declared in `workers-sdk/package.json` so we can pick up minor & patch updates at the same time as `workers-sdk`.

Add ^ to pnpm version

---

WORKSPACE
compile_flags.txt
src/workerd/api/r2-admin.c++
src/workerd/api/r2-bucket.c++
src/workerd/api/r2-multipart.c++
src/workerd/api/r2-rpc.c++
src/workerd/io/BUILD.bazel
src/workerd/io/actor-cache.h
src/workerd/io/io-context.h
src/workerd/io/worker.c++
src/workerd/jsg/BUILD.bazel
src/workerd/jsg/async-context.c++
src/workerd/jsg/inspector.h
src/workerd/jsg/jsg.h
src/workerd/jsg/memory.h
src/workerd/jsg/observer.h
src/workerd/jsg/rtti.h
src/workerd/jsg/wrappable.h
src/workerd/server/BUILD.bazel
src/workerd/tests/bench-json.c++
src/workerd/tests/test-fixture.h
src/workerd/util/BUILD.bazel
src/workerd/util/autogate.c++
src/workerd/util/autogate.h
src/workerd/util/canceler.h
src/workerd/util/capnp-mock.h
src/workerd/util/perfetto-tracing.h

This brings us significantly closer to IWYU. Total include size improves significantly by reducing exposure to perfetto and improvements in the underlying capnproto change.
Includes slight buildifer cleanup.
capnproto PR [#2039](https://github.com/capnproto/capnproto/pull/2039)
\- This will require some downstream changes, but the changes here should be ready for review.

[nfc] Clean up JSG and perfetto includes, pull in capnproto include cleanup

---

src/workerd/jsg/jsg.c++
src/workerd/jsg/jsg.h
src/workerd/jsg/jsvalue.c++
src/workerd/jsg/modules.h
src/workerd/jsg/promise.c++
src/workerd/jsg/promise.h
src/workerd/jsg/value-test.c++

Update hash code usage for capnp change

---

src/workerd/server/BUILD.bazel
src/workerd/server/actor-id-impl-test.c++
src/workerd/server/actor-id-impl.c++
src/workerd/server/actor-id-impl.h
src/workerd/server/workerd-api.c++

Enables the instances of `memcmp` inside `ActorIdFactoryImpl` to be tested.

Split ActorIdFactoryImpl into a separate library for testing purposes

---

src/workerd/server/actor-id-impl.c++

This is in line with the ongoing effort to use safer comparisons using `arrayPtr` comparators rather than `memcmp` directly.

Make ActorIdFactoryImpl use arrayPtr equals instead of memcmp == 0

---

README.md

- Add instructions to make the compiler available as just clang, which avoids confusing errors when it is installed as `clang-<version>`.
- Add comment about lld being highly recommended – it turns out that if it is not present Bazel may silently use GNU gold instead, which is able to link workerd correctly but led to much higher link times recently.

README.md: Describe compiler name requirements better

---

src/workerd/api/crypto/aes.c++
src/workerd/api/crypto/asymmetric.c++
src/workerd/api/crypto/crypto.c++
src/workerd/api/crypto/impl.c++
src/workerd/api/crypto/impl.h
src/workerd/api/node/crypto-dh.c++
src/workerd/api/node/crypto-random.c++

Eliminates some duplication and condenses some of the handling of BIGNUM types... just one more of a number of PRs that'll be reworking and cleaning up the crypto impl a bit before coalescing with the node.js crypto impl details.

BIGNUM utility cleanups

---

.bazelrc
.github/workflows/release.yml
.github/workflows/test.yml

bazelbuild/bazel#22785 fixes a bug remote caching bug that prevented us from fetching only top-level targets from cache. Enabling that option should speed up CI runs.
Also increase the number of concurrent Bazel jobs, see bazelbuild/bazel#6394

[CI] Build using --remote_download_toplevel

---

.bazelrc

The Windows build has the most to gain from BwoB, but I guess it's still broken there...

[CI] Fix Windows build by disabling BwoB there

---

samples/eventsource/README.md
samples/eventsource/config.capnp
samples/eventsource/server.js
samples/eventsource/worker.js
src/workerd/api/eventsource.c++
src/workerd/api/eventsource.h
src/workerd/api/global-scope.h
src/workerd/api/tests/eventsource-test.js
src/workerd/api/tests/eventsource-test.wd-test
src/workerd/server/workerd-api.c++
src/workerd/tools/api-encoder.c++

SHIP-9206
~~This is just a draft proposal at the moment, but it should be functional for folks who want to give it a try.~~ Had a couple of folks ask me about this over the past few months so figured I'd go ahead and see about an actual implementation. The format is simple enough that it really doesn't require bringing in any dependencies.
Implements the web platform standard `EventSource` API (https://developer.mozilla.org/en-US/docs/Web/API/EventSource).
There are three non-standard extensions implemented to the API:
1. Passing in a custom fetcher
```js
const ev = new EventSource('https://...', { fetcher: env.myfetcher });
```
2. Creating an `EventSource` from an existing `ReadableStream`
```js
const ev = EventSource.from(readableStream);
```
3. The `EventSource` implements ERM …

Implement EventSource

---

.bazelrc
.github/workflows/test.yml

- Disable the macOS-debug runner for now to avoid macOS build queueing unless we have a proper way to approach this.
- For macOS fastbuild, don't define DEBUG to match Linux configuration
- Drop the nonsensical experimental_objc_fastbuild_options flag.
- Don't try to re-enable assertions for Windows fastbuild – this never took effect as the feature was spelled wrong (needs to be just "disable_assertions"), actually using assertions would likely make the Windows build slower (it is already slower than the macOS/Linux jobs).
- Drop flags to disable optimization in the host configuration for Windows fastbuild. Host tools (e.g. capnpc for generating .capnp.h files) use 'opt' mode by default and we want them to run quickly.
Only apply -Wl,-O2 under release configuration
We turned on linker …

[CI][build] Improve CI configuration to mitigate resource constraints

---

src/workerd/util/sqlite.h

There are also 5 reader locks, but I’m not sure what’s the best way to refer to them yet.  SQLite uses a macro, but we may refer to those locks in a different manner.

Add names for some of the WAL locks

---

src/pyodide/internal/loadPackage.ts
src/pyodide/internal/metadatafs.ts
src/pyodide/internal/readOnlyFS.ts
src/pyodide/internal/setupPackages.ts
src/pyodide/internal/snapshot.ts
src/pyodide/internal/tar.ts
src/pyodide/internal/tarfs.ts
src/pyodide/python-entrypoint-helper.ts
src/pyodide/types/FS.d.ts
src/pyodide/types/Module.d.ts
src/pyodide/types/Pyodide.d.ts
src/pyodide/types/limiter.d.ts
src/pyodide/types/packages_tar_reader.d.ts
src/pyodide/types/runtime-generated/metadata.d.ts

Last batch of types being added to the Pyodide glue code. There's a bit of jankiness around the filesystem (specifically the `info` object which can technically be any type). There was also a spot where the node type for directories was `5` vs `"5"`, but that didn't end up getting used in a critical path. I made them all `"5"` for consistency.

Complete typescript migration for Pyodide glue code

---

src/node/internal/crypto_keys.ts

As per https://github.com/nodejs/node/pull/46043, this adds Symbol.toStringTag getter to KeyObject.

fix: add Symbol.toStringTag to KeyObject instances

---

src/pyodide/internal/topLevelEntropy/lib.ts
src/workerd/server/tests/python/import_tests.bzl

Importing stuff within a `test()` function does not invoke the top-level entropy patches we implemented, so this change should make our testing much more complete. 
Should reproduce https://github.com/cloudflare/python-workers-examples/issues/9.

Run test imports at top level, fix pydantic and numpy imports

---

src/workerd/api/http.c++

Improve user facing error message when dynamically dispatching to a missing script with an egress worker.

---

src/workerd/api/sockets.c++

The `tlsStarter` is an `IoOwn` which means that it gets deallocated when the request's IoContext ends. In the `startTls` implementation we wait for a `flush` to complete before we use the `tlsStarter`, the `flush` may complete after the lifetime of the IoContext at which point the `tlsStarter` will be null and the `KJ_ASSERT_NONNULL` will fail.
This PR throws a JSG error instead which should (hopefully) fail more gracefully.

Fixes Socket::startTls assert failure when request IoContext ends.

---

src/node/internal/internal_path.ts
src/node/path.ts

Adds a placeholder for `matchesGlob` which didn't get released on a Node.js release line, yet. 
Documentation is available at: https://github.com/nodejs/node/blob/ce2faef3a70ae1b8336b2628b7f01b07d5402fbc/doc/api/path.md?plain=1#L282
PR is available at: https://github.com/nodejs/node/pull/52881

add matchesGlob placeholder to node:path

---

src/workerd/api/sql-test.js
src/workerd/util/sqlite.c++

Closes https://github.com/cloudflare/workerd/issues/1300
This PR adds `\r` into the logic that makes sure there is nothing more than whitespace at the end of a prepared statement, otherwise it will throw an error indicating that a prepared statement can only contain one statement.
Accompanying tests have been added to make sure that spaces, CR, LF and CRLF are accepted as whitespace as well that multiple statements are rejected.

Account for CR in prepared statements, add tests

---

samples/async-context/config.capnp

I think it's best to encourage people to use this narrower flag instead of making the entirety of the emulated nodejs API available, as the documentation explains.
I don't think there's any build interactions with samples/ at all, so I manually ran this sample with my changes and confirmed it works.

Only ask for nodejs_als in the async-context sample

---

src/workerd/io/outcome.capnp

loadShed means the server didn't start processing the request. It could happen when server is overloaded or in some other not-very-healthy state.
Not used anywhere yet, the plan is to use for load-shedding experiments. There's downstream change open updating the master copy.

adding loadShed outcome

---

src/workerd/api/gpu/gpu-adapter-info.c++
src/workerd/api/gpu/gpu-adapter-info.h
src/workerd/api/gpu/gpu-adapter.c++
src/workerd/api/gpu/gpu-async-runner.h
src/workerd/api/gpu/gpu-buffer.c++
src/workerd/api/gpu/gpu-device.c++
src/workerd/api/gpu/gpu-device.h
src/workerd/api/gpu/gpu-shader-module.c++

Use the new C++ callback mode of dawn. Replace deprecated getProperties() call with getInfo().

webgpu: new callback mode

---

types/defines/ratelimit.d.ts

Hi :wave:,
This PR adds a simple type definition for Rate Limit bindings.
As it is in beta, I expect this will evolve over time, so I didn't copy most of the documentation into jsdoc.
Happy to take suggestions for the names of the interfaces and anything else, my other idea was `RateLimitBinding`, but not entirely sure if it would fit in with other bindings.
cc @elithrar

Add type definition of Rate Limit bindings

---

src/workerd/api/actor-state.c++
src/workerd/api/http.c++
src/workerd/api/web-socket.c++
src/workerd/api/web-socket.h

Refactor workerd::api::WebSocket such that it no longer needs callers to indicate "locality" to decide whether to register pending events.
Whether to register pending events (and whether to tie the lifetime of the websocket connection to the IoContext) can be determined purely based on existing internal state.
I've reasoned through each case and this should be a non-functional change. I'm somewhat relying on test coverage to back that up, though.
This change was prompted by me trying to figure out when the server side of a websocket terminated in a worker or not (so I could add some appropriate logic) and this was obfuscated by the `setRemoteOnPair` hack.

Remove websocket locality

---

src/workerd/api/crypto/ec.c++
src/workerd/api/crypto/ec.h
src/workerd/api/crypto/impl.h
src/workerd/api/crypto/rsa.c++
src/workerd/api/crypto/rsa.h

Reworking and separating the RSA and EC related key handling code to better organize it in preparation for adding in all of the Node.js key gen and handling code.
Builds on https://github.com/cloudflare/workerd/pull/2353 which must land first

More cleaning up and reorganization of crypto key handling code.(Part 2)

---

samples/BUILD.bazel
src/workerd/server/BUILD.bazel
src/workerd/server/tests/compile-tests/compile-helloworld-test.ok
src/workerd/server/tests/compile-tests/compile-test.sh
src/workerd/server/workerd.c++

This change follows the pattern of other safety changes to use `ArrayPtr` equality rather than `memcmp == 0`, which has bounds checking.
This PR also adds a test that compiled binaries run correctly using `sh_test`.

COMPILED_MAGIC_SUFFIX check from memcmp equals 0 -> arrayPtr equality

---

.github/secret_scanning.yml
src/node/crypto.ts
src/node/internal/crypto.d.ts
src/node/internal/crypto_x509.ts
src/workerd/api/crypto/crypto.c++
src/workerd/api/crypto/crypto.h
src/workerd/api/crypto/ec.c++
src/workerd/api/crypto/impl.c++
src/workerd/api/crypto/impl.h
src/workerd/api/crypto/keys.c++
src/workerd/api/crypto/keys.h
src/workerd/api/crypto/rsa.c++
src/workerd/api/crypto/x509.c++
src/workerd/api/crypto/x509.h
src/workerd/api/node/crypto.h
src/workerd/api/node/tests/crypto_x509-test.js
src/workerd/api/node/tests/crypto_x509-test.wd-test
src/workerd/jsg/jsvalue.c++
src/workerd/jsg/jsvalue.h

Implement the `node:crypto` `X509Certificate` API

Implement node:crypto X509Certificate

---

types/src/generator/index.ts
types/src/generator/parameter-names.ts
types/src/generator/structure.ts
types/src/generator/type.ts
types/src/index.ts
types/src/program.ts
types/src/transforms/ambient.ts
types/src/transforms/comments.ts
types/src/transforms/globals.ts
types/src/transforms/helpers.ts
types/src/transforms/import-resolve.ts
types/src/transforms/importable.ts
types/src/transforms/index.ts
types/src/transforms/internal-namespace.ts
types/src/transforms/iterators.ts
types/src/transforms/overrides/compiler.ts
types/src/transforms/overrides/index.ts
types/test/generator/index.spec.ts
types/test/generator/structure.spec.ts
types/test/index.spec.ts
types/test/transforms/globals.spec.ts
types/test/transforms/overrides/index.spec.ts

This is the first part of landing [Types as a Service](https://github.com/cloudflare/workerd/pull/1959).
This is a relatively large PR, but it's pretty low risk. It mostly contains some refactoring of the type generation code (e.g. files like [types/src/transforms/overrides/compiler.ts](https://github.com/cloudflare/workerd/pull/2379/files#diff-b3672e23392be040c988f7f7a2dac703816fd138336e12d98ab1614cbe169354) which have not changed in functionality). In large part this refactoring is to make it easier for a future PR (another part of #1959) to run this code in a Worker (for instance, changing `import ... from "assert"` to `import ... from "node:assert"` is in support of this goal, as well as the enhancing of the [memory-based compiler host we use for running …

Refactor type generation scripts

---

src/workerd/api/gpu/gpu-adapter.c++
src/workerd/api/gpu/gpu-device.c++
src/workerd/api/gpu/gpu-device.h

Replace the deprecated device.SetUncapturedErrorCallback() with setting the callback in the descriptor used to create the device itself. Needed to create a context to pass on to the callback that will be later on updated when we create the JSG device object, which implements EventTarget.

webgpu: remove device.SetUncapturedErrorCallback()

---

src/workerd/api/sql-test.js
src/workerd/util/sqlite.c++

The error messages now have the error code in them, either something like SQLITE_TOOBIG or SQLITE_FORMAT if it's a known code, or SQLITE_UNKNOWN_ERROR_CODE(%d) if it's not known to us.
SQLite doesn't provide any function to do this for us. It has an internal function `sqlite3ErrName` that looks a lot like the giant switch statement in this commit, but (a) it's not exposed to library consumers, and (b) it's only present if compiled with certain flags like SQLITE_DEBUG that also turn on a bunch of other stuff.
I considered patching SQLite to expose `sqlite3ErrName`, but I think it's easier for workerd maintainers to deal with adding the occasional new case to a switch statement we own than it is to maintain yet another SQLite patch.

Better SQLite error message generation.

---

src/workerd/server/BUILD.bazel
src/workerd/server/tests/compile-tests/compile-test.sh

This PR also sets `no-qemu` as this is causing problems downstream.

Unpin the port for compile-tests using control-fd

---

build/BUILD.dawn

Update dawn wire library build specification which is only used by the external GPU process for now.

webgpu: update dawn wire specification

---

src/workerd/api/crypto/crypto.c++
src/workerd/api/crypto/crypto.h
src/workerd/api/tests/crypto-extras-test.js

Fixes: https://github.com/cloudflare/workerd/issues/2357
/cc @panva

Make deriveBits length argument optional per spec change

---

src/workerd/api/BUILD.bazel
src/workerd/io/BUILD.bazel
src/workerd/io/actor-cache.c++
src/workerd/io/actor-sqlite.c++
src/workerd/io/actor-storage.c++
src/workerd/io/compatibility-date.c++
src/workerd/io/io-context.h
src/workerd/io/observer.h
src/workerd/io/trace.c++
src/workerd/io/worker-entrypoint.c++
src/workerd/io/worker-entrypoint.h
src/workerd/jsg/BUILD.bazel
src/workerd/jsg/exception.h
src/workerd/server/BUILD.bazel
src/workerd/server/actor-id-impl-test.c++
src/workerd/server/actor-id-impl.c++
src/workerd/util/BUILD.bazel
src/workerd/util/uuid.c++
src/workerd/util/uuid.h

This makes it easier to avoid superfluous dependencies, especially in tests.
Making io a smaller target will help us rebuild less code following trivial
changes – any change to a header included in the io target requires all io and
dependent source files to be rebuilt.
Crucially, this also isolates several tests from io/JSG (and by extension V8). Since
we currently make V8 alwayslink, this makes these test binaries much
smaller (~140MB => ~1MB on macOS), improving CI performance as less data
needs to be fetched from cache.

[BUILD] Split up bazel io target

---

types/src/cloudflare.ts
types/src/index.ts
types/src/standards.ts
types/src/transforms/comments.ts
types/test/index.spec.ts

Follow up to https://github.com/cloudflare/workerd/pull/2379, and part 2 of landing https://github.com/cloudflare/workerd/pull/1959.
For some prior context, when we generate types we copy over doc comments from `lib.webworker.d.ts` to the built runtime types. This means that things like `Request.json()` which are present in both the Workers environment and the web have useful comments when you hover over them in editors. This is really useful! But there are a few problems which this PR addresses.
The main _purpose_ of this PR is to ensure that when we generate types, all of the data passed into the generation function ([`printDefinitions()`](https://github.com/cloudflare/workerd/blob/0e30ac6cd5772ca7b1b9d656f392d3f24c5821bf/types/src/index.ts#L145)) is serialisable, to help move towards a …

[types] Refactor doc comment injection

---

src/workerd/jsg/jsvalue.h

Should be a noop for us, since we never call GetPrototype() on an object that would be expected to be the context object

switch to GetPrototypeV2()

---

src/workerd/api/trace.c++
src/workerd/api/trace.h
src/workerd/io/trace.c++
src/workerd/io/trace.h
src/workerd/io/worker-interface.capnp

When set, indicates that the tail worker event was truncated due to the event buffer being full.

Add truncated flag for tail worker events

---

src/workerd/io/trace.c++

Missed this in the original commit that added the truncated flag

Add missed setTruncated call

---

src/workerd/api/http.c++
src/workerd/api/web-socket.c++
src/workerd/api/web-socket.h
src/workerd/io/observer.h

This allows observation of traffic on websocket connections terminating within workers.
I'm not 100% satisfied with either the abstraction or the naming (especially `coupledToLocalWebSocket` as a name for a method which creates a `WebSocketObserver` object), but I couldn't think of a clearly better alternative.
Note that this currently won't observe receives on hibernatable websockets. I'll add a TODO for that.

Add WebSocketObserver

---

src/workerd/api/http-test.js
src/workerd/api/http-test.wd-test
src/workerd/api/http.c++
src/workerd/api/http.h
src/workerd/io/compatibility-date.capnp

RM-18292
Updates the Request object to support specifying a cache mode per the standard. Only undefined, 'no-store' and 'no-cache' may be specified, and the fetch implementation specifically does not implement the semantics for either 'no-store' or 'no-cache' yet. 
Also adds the compatibility flag for `cacheHeaderEnabled`. This just lays the ground work for the additional changes.
The next step is to start adding the support for adding the appropriate header fields in the fetch implementation behind an autogate.

Redoing "#2073: Update Request to support cache option" with compat flags

---

src/workerd/api/global-scope.c++

Even if we usually don't feel like it's worth logging this message, let's log it temporarily to help investigate alarm failures

Log complete alarm errors in global-scope

---

types/defines/email.d.ts

The `ForwardableEmailMessage` interface should expose a `reply` function, but it currently doesn't.This commit adds the missing function to the interface definition.
Please refer to https://developers.cloudflare.com/email-routing/email-workers/runtime-api/#emailmessage-definition
Fixes #2283

[types] Add missing `reply` fn to `ForwardableEmailMessage`

---

src/workerd/api/tests/global-scope-test.js
src/workerd/api/web-socket.c++
src/workerd/api/web-socket.h

```
const [a, b] = new WebSocketPair();
a instanceof WebSocket  // true
b instanceof WebSocket  // true
```
This was requested by a CF internal user and it made sense :-)

Make WebSocketPair iterable

---

src/workerd/api/crypto/impl.c++
src/workerd/api/crypto/impl.h
src/workerd/api/crypto/keys.h
src/workerd/api/crypto/rsa.c++
src/workerd/api/crypto/rsa.h

Separating out more of the node.js crypto key handling support. There's a lot to do with all this so I'm piecing it out into separate PRs that individually are easier to review. This adds methods but does not add the stuff that uses it yet. Tests for these individual pieces will also be added separately. A fair amount of this is adapted from https://github.com/nodejs/node/blob/main/src/crypto/crypto_keys.cc

Implement rsa toPem, toDer, and fromJwk utilities

---

src/workerd/api/worker-rpc.c++
src/workerd/io/worker.c++
src/workerd/jsg/jsvalue-test.c++
src/workerd/jsg/jsvalue.c++
src/workerd/jsg/jsvalue.h
src/workerd/jsg/ser.c++

Refs: https://github.com/cloudflare/workerd/issues/2291

Handle proxy object prototypes more correctly

---

types/defines/d1.d.ts
types/test/types/d1.ts

This is out of sync with prod, which is does accept a type parameter and returns a `D1Result`
cc @vy-ton @geelen

types: Fix D1 run() type

---

src/workerd/api/http-test.js
src/workerd/api/http-test.wd-test
src/workerd/api/http.c++
src/workerd/api/http.h
src/workerd/io/compatibility-date.capnp

Reverts cloudflare/workerd#2409
This broke workers in production again.
Any further attempt to land this change must be reviewed and approved by me before being merged.

Revert "Redoing "#2073: Update Request to support cache option" with compat flags"

---

src/workerd/api/http-test.js

This will be useful for subsequent iterations of changing cache behavior to ensure backwards compatibility is still kept.

Added test for cache functionality. 

---

.devcontainer/Dockerfile
src/cloudflare/internal/test/vectorize/vectorize-api-test.js
src/cloudflare/internal/test/vectorize/vectorize-mock.js
src/cloudflare/internal/vectorize.d.ts
src/cloudflare/vectorize.ts
types/defines/vectorize.d.ts

This updates the types for Vectorize ahead of the GA release.
We have intentionally moved the "current" Vectorize Index to a legacy type, promoting the "new" index to the default `VectorizeIndex` such that it becomes the standard going forward.
This is strictly a types change and sister to
https://github.com/cloudflare/workers-sdk/pull/6252

Update Vectorize types for GA release

---

src/workerd/io/compatibility-date.capnp

Add KV Direct Binding compatibility flag.
EW-8494

Add KV Direct Binding compatibility flag.

---

src/workerd/api/global-scope.c++
src/workerd/io/actor-cache.c++
src/workerd/jsg/exception.h

If an exception is of type OVERLOADED we set `retryCountsAgainstLimites = true` for alarms.

Check exception type to set retryCountsAgainstLimit for alarms

---

.vscode/extensions.json
compile_flags.txt
docs/development.md
justfile

Updates compile_flags.txt to include correct paths for ada-url and simdutf.

fix compile_flags.txt to include correct paths

---

.bazelrc
WORKSPACE
rust-deps/crates/BUILD.cc-1.1.6.bazel
rust-deps/crates/BUILD.cssparser-macros-0.6.1.bazel
rust-deps/crates/BUILD.derive_more-0.99.18.bazel
rust-deps/crates/BUILD.lol_html-1.2.1.bazel
rust-deps/crates/BUILD.lolhtml-1.1.1.bazel
rust-deps/crates/BUILD.serde_derive-1.0.204.bazel
rust-deps/crates/BUILD.syn-2.0.72.bazel
rust-deps/crates/BUILD.thiserror-1.0.63.bazel
rust-deps/crates/BUILD.thiserror-impl-1.0.63.bazel
rust-deps/crates/BUILD.zerocopy-derive-0.7.35.bazel
rust-deps/crates/defs.bzl

- V8 defaults to C++20 as of version 12.7, drop the corresponding override.
- With https://github.com/google/tcmalloc/pull/239 being merged, updating tcmalloc has been unblocked.
- Roll rust deps, apple_support

[build] Simplify V8 build configuration, minor build updates

---

src/node/internal/crypto_hash.ts

It seems unnecessary to initialize a Buffer for non-buffer output encodings and call toString() on an empty string. If I'm not mistaken, any encoding of an empty string, returns an empty string.
The original implementation also has the same exact issue: https://github.com/nodejs/node/blob/82cf0f2f3c9e4c6f9c28cd130e91287d93200373/lib/internal/crypto/hash.js#L161
Node.js fix: https://github.com/nodejs/node/pull/54046

remove unnecessary initialization of buffer

---

src/cloudflare/internal/test/vectorize/vectorize-api-test.js
src/cloudflare/internal/test/vectorize/vectorize-api-test.wd-test
src/cloudflare/internal/test/vectorize/vectorize-mock.js
src/cloudflare/internal/vectorize-api.ts
src/cloudflare/internal/vectorize.d.ts
types/defines/vectorize.d.ts

Sister to https://github.com/cloudflare/workerd/pull/2421
This creates a new shared implementation of the Vectorize type that is common to both v1 and v2, conditionally switching on the version to serve up the correct api. This allows us to keep the module name common as `cloudflare-internal:vectorize-api`

Implement Vectorize GA binding changes

---

src/workerd/api/modules.h
src/workerd/api/pyodide/pyodide.c++
src/workerd/api/pyodide/pyodide.h
src/workerd/util/autogate.c++
src/workerd/util/autogate.h

These changes are needed to load the Pyodide runtime from an external capnproto file. In workerd, we'll keep loading Pyodide in the same way, but we moved this to WorkerdAPI. In our internal codebase, we now download the bundle and call `setPyodideBundleData` when we load the first Python worker. Then when setting up the module registry, we add the bundle from `pyodideBundleGlobal`.
TODO in followups:
1. Make workerd load the bundle in the same way
2. Add support for multiple versions of the Pyodide bundle

Load Pyodide runtime from external capnproto file

---

build/wd_js_bundle.bzl
build/wd_ts_bundle.bzl
src/pyodide/BUILD.bazel
src/workerd/jsg/BUILD.bazel
src/workerd/server/BUILD.bazel

Split off from #2288. This doesn't actually use the rule for anything yet, and perhaps we'll want to move this logic into pyodide-build-scripts eventually. But this will enable us to test against the Pyodide setup code in the source tree.

NFC Add bazel rule to generate external pyodide capnproto bundle

---

src/workerd/io/compatibility-date.capnp

This PR enables worker subrequests to fetch hosts in any port on sites that are grey-clouded or cloudflare proxy standard ports on orange-clouded sites.

EW-8589 add a compat date to support custom ports for worker subrequests

---

src/pyodide/internal/process_script_imports.py
src/pyodide/internal/snapshot.ts
src/pyodide/types/artifacts.d.ts
src/workerd/api/pyodide/pyodide.h

Modifies memory snapshot generation to generate a _package_ snapshot- one that only includes imports of modules that are not present in the user's worker bundle.
Reuses the existing AST walker to collect the import names and pushes them out to the validator.

Generate package memory snapshot for validator.

---

src/workerd/jsg/resource.h
src/workerd/jsg/setup.h

Compilation currently fails with the new `-Wmissing-template-arg-list-after-template-kw` warning, I assume it is an error since Werror is pulled in through a dependency. To resolve this we just need to drop the template keyword – the default template argument will be used as before.

Fix compilation under LLVM 19

---

src/workerd/api/streams/compression.c++

- Eliminate recursion in compression streams writeInternal() 
This avoids having large stack traces when compressing larger chunks of data
and is easier to maintain with the added comments.
- Reduce excessive copying in Compression Streams API 
In the Compression Streams API, introduce a helper class to only shift output
data when this would reduce output vector size significantly. This results in
the leading bytes of the output vector becoming invalid when reading only parts
of it, which requires careful tracking but avoids having to move the output data
with every read from the buffer.
- Increase Compression Streams output buffer size 
Since zlib uses 256KiB of memory per compression stream with default settings, a
size of 16KiB will not increase memory usage by a large proportion. This …

Improve buffering in Compression Streams API

---

.bazelrc
WORKSPACE

- The include and code size optimizations are already enabled in the downstream project.
- Use cleaner syntax when disabling legacy_external_runfiles.

[build] Reduce STL header include overhead, O0 code size

---

src/workerd/api/web-socket.c++
src/workerd/api/web-socket.h
src/workerd/io/compatibility-date.capnp

This is one step towards addressing #2051 (Wrangler changes will also be needed)

Add a compat flag for increasing the WS message size limit

---

src/node/internal/internal_zlib.ts
src/node/internal/zlib.d.ts
src/node/zlib.ts
src/workerd/api/node/node.h
src/workerd/api/node/tests/zlib-nodejs-test.js
src/workerd/api/node/tests/zlib-nodejs-test.wd-test
src/workerd/api/node/zlib-util.c++
src/workerd/api/node/zlib-util.h

Initializes `node:zlib` and implements only `crc32` for now.

add initial zlib module with crc32

---

src/workerd/io/compatibility-date.capnp
src/workerd/io/compatibility-date.h

This new annotation will be used to figure out the Python release that a Python Worker belongs to. The main use case for this is for figuring out memory snapshot compatibility between workers.

Adds pythonRelease annotation to compat flags.

---

src/node/internal/buffer.d.ts
src/node/internal/crypto_hash.ts
src/node/internal/internal_buffer.ts
src/node/internal/internal_stringdecoder.ts
src/node/internal/internal_utils.ts
src/node/internal/validators.ts
src/workerd/api/node/buffer.c++
src/workerd/api/node/buffer.h
src/workerd/api/node/i18n.h

Reduces encoding variable serialization cost between javascript and c++. by converting it to uint8_t we can reduce the "initial" cost we pay by calling almost all buffer functions.

reduce encoding serialization cost

---

src/workerd/api/sql-test.js
src/workerd/util/sqlite.c++

In response to https://github.com/cloudflare/workerd/issues/2471, it would be useful to allow some migrations to completely disable foreign key constraints. However, at the end of the migration, it might be important to know whether any foreign key violations remain, before setting `PRAGMA foreign_keys=ON;`.
This is possible by using `PRAGMA foreign_key_check;`, but right now we only allow that if it contains a single argument, indicating a table name. This PR allows both no-arg and single-arg forms of that pragma.

SQLite: allow `foreign_key_check` for whole DB, not just a single table

---

package.json
pnpm-lock.yaml
src/node/buffer.ts
src/node/internal/crypto_random.ts
src/node/internal/web_crypto.d.ts
src/workerd/api/blob.c++
src/workerd/api/node/tests/buffer-nodejs-test.js

- Adds `File` to `node:buffer`
- Fixes Blob and File typescript definitions
- Fixes passing `NaN` as a `lastModified` to File options.

add file class to node:buffer

---

src/workerd/io/worker.c++
src/workerd/io/worker.h
src/workerd/server/server.c++
src/workerd/util/xthreadnotifier.h

When breakpoint debugging was introduced, it added a new thread, the InspectorService thread. This thread is necessary in order to continue performing WebSocket I/O while the Isolate is paused at a breakpoint. The feature _also_ moved inspector message dispatching onto this same InspectorService thread. For most inspector messages, this turns out to be benign, but not for CPU profiling start/stop messages: those must be dispatched on the thread which we desire to profile. The end result was that breakpoint debugging caused us to profile JavaScript on the InspectorService thread (e.g., anything executed on the Chrome Devtools console) instead of the Isolate thread, as originally intended.
This turns out to be relatively easy to fix, because breakpoint debugging would already dispatch …

EW-8447 Fix CPU profiling

---

src/workerd/jsg/jsg.c++
src/workerd/jsg/jsg.h

While ultimately we want to explore more automatic memory accounting for jsg objects, there's still a need for manual adjustments. This PR adds two new APIs to `jsg::Lock` for manual external memory adjustments.
Why is this needed? Let's say you have a `jsg::Object` that holds onto an internal `kj::Array<kj::byte>` that is never wrapped in a `v8::ArrayBuffer` ... v8 won't never know about that memory allocation for that `kj::Array` unless we manually inform it.
```
class Foo: public jsg::Object {
public:
Foo(jsg::Lock& js) : foo(kj::heapArray<int>(1024).attach(js.getExternalMemoryAdjuster(1024))) {}
private:
kj::Array<kj::byte> foo;
}
```
Manual adjustment is imperfect and should only be used when the need is clear. We want to work on making the adjustments largely automatic when possible …

Adds APIs to jsg::Lock to perform manual external memory accounting.

---

src/workerd/util/sqlite.c++

People keep legitimately running up against this limit. It's not really clear what value it is providing, so let's just match the default.
Fixes #2412

Set SQLITE_LIMIT_FUNCTION_ARG to SQLite's normal default.

---

src/workerd/api/global-scope.c++
src/workerd/api/global-scope.h
src/workerd/api/node/BUILD.bazel
src/workerd/api/node/tests/node-compat-v2-test.js

Also fixes a bug introduced in the build configuration that has causing node.js compat tests to get skipped

Implements setImmediate for Node.js compatibility v2

---

src/workerd/api/streams/internal.c++
src/workerd/api/streams/internal.h
src/workerd/api/tests/abort-internal-streams-test.js
src/workerd/api/tests/abort-internal-streams-test.wd-test
src/workerd/io/compatibility-date-test.c++
src/workerd/io/compatibility-date.capnp

The motivation here is to address an issue with `WritableStream` instances wrapping a `WritableStreamSink` implementation not processing `abort()` calls proactively. Without the flag the `abort()` will be handled lazily, meaning that a consumer must be actively consuming the data written to the stream in order to trigger the abort and close the stream. This is problematic if the consumer has dropped or otherwise stopped reading from the writable's internal buffer ... the pending abort will never be processed and resolved. This means that pending writes and the pending abort itself will never be resolved in those cases. With the flag, the queue of pending writes is drained immediately when `abort()` is called and the stream is transitioned to an error state immediately. This should cause …

Clear WritableStreamSink queue on abort with compat flag

---

README.md
src/workerd/api/encoding.h
src/workerd/api/http.h
src/workerd/api/node/BUILD.bazel
src/workerd/api/streams/internal.c++
src/workerd/api/streams/readable.h
src/workerd/api/streams/standard.c++
src/workerd/api/tests/encoding-test.js
src/workerd/io/io-context.h
src/workerd/server/workerd-api.c++
src/workerd/server/workerd.c++
src/workerd/tools/BUILD.bazel
tools/windows/install-deps.bat

Cleaning out a number of smaller changes I had stashed for a while.
- Emphasize that building on macOS requires Xcode.
- Clean up Windows dependency script, the workaround is no longer needed.
- Fix cargo-culted comment in encoding-test.js
- Drop unused perfetto dependency for node target
- Mark a few classes as final, expand anonymous namespace usage.

[nfc] 08/10/24 Build/Docs cleanup

---

src/workerd/api/streams/compression.c++

This reverts commit #2502, IoContext::current() appears to fail in some cases.

Revert "Enforce worker limits in Compression Streams API"

---

.bazelrc

This change was already applied to the internal repo.  Adding it here will make it more convenient to work on worked, as well.

bazelrc: Add incompatible_strict_action_env to prevent  bazel cache invalidation when switching terminals

---

src/workerd/api/pyodide/pyodide.c++
src/workerd/api/pyodide/pyodide.h
src/workerd/server/workerd-api.c++

This adds a Mutex around the bundleReaders map and makes `getPyodideBundle` return a Maybe<bundle> rather than asserting that the bundle is defined. This means we can get rid of `hasPyodideBundle` in favor of checking whether `getPyodideBundle` returns `none`.

Tidy up pyodide bundle API

---

src/workerd/io/observer.h
src/workerd/io/outcome.capnp
src/workerd/io/worker-entrypoint.c++
src/workerd/util/autogate.c++
src/workerd/util/autogate.h

Add new responseStreamDisconnected request status, to be used when an exception is thrown due to disconnection during deferred proxying, which is common when the client or server hangs up early, particularly when proxying websockets.  Should allow us to differentiate these cases from those where JS is still running, such that a thrown exception could still be caught and handled by the worker.
Also, add instrumentation to report failure during deferred proxying.

Use new "response stream disconnected" status for disconnections during proxying

---

src/node/internal/internal_buffer.ts
src/workerd/api/node/buffer.c++
src/workerd/api/node/tests/buffer-nodejs-test.js

Our implementation was wrong by assuming the second parameter of `utf8Slice()` was the length. The correct implementation was: `utf8Slice(start, end)` where start and end represents the index.
This makes the implementation correct and in par with Node.js' implementations.
Fixes https://github.com/cloudflare/workerd/issues/2538

fix handling of buffer slices

---

src/workerd/api/node/buffer.c++

Improves the performance of base64 and base64url conversion from binary. Applies to `buffer.toString('base64')` and `buffer.toString('base64url')`

improve nodejs buffer base64 and base64url performance

---

src/cloudflare/internal/test/vectorize/vectorize-api-test.js
src/cloudflare/internal/test/vectorize/vectorize-mock.js
src/cloudflare/internal/vectorize-api.ts
src/cloudflare/internal/vectorize.d.ts
types/defines/vectorize.d.ts

This change fixes 2 aspects of Vectorize query options.
1. Options itself should be an optional field.
2. Options.returnMetadata should be of type boolean for Vectorize V1 and of type `VectorizeMetadataRetrievalLevel` for Vectorize V2. The existing type relied on a generic to assign type appropriately for the operation, but did not work as expected for Vectorize V2. It continued to expect a boolean field for V2 as well instead of `VectorizeMetadataRetrievalLevel`.
Follows: https://github.com/cloudflare/workerd/pull/2443

VS-257: Fix Vectorize query options

---

src/workerd/api/http-test.js
src/workerd/api/streams/streams-test.js
src/workerd/api/tests/blob-test.js
src/workerd/jsg/resource.h

This mirrors the approach used for `registerPrototypeProperty()`.

[JSG] Use SetAccessorProperty() in registerReadonlyPrototypeProperty()

---

src/workerd/api/sql-test.js
src/workerd/server/server.c++
src/workerd/util/sqlite-kv.c++
src/workerd/util/sqlite-kv.h

This way, if a Durable Object never actually uses the KV storage interface -- only uses SQL -- we'll never create the table and can skip preparing statements for it.
This will also make it easier for the edge runtime to clean up actors that never had data.

Lazily initialize _cf_KV sqlite table.

---

src/pyodide/internal/snapshot.ts
src/pyodide/types/artifacts.d.ts
src/workerd/api/pyodide/pyodide.h

We now upload via the validator so this code is no longer needed.

Removes Python memory snapshot upload code.

---

types/defines/rpc.d.ts

`run` always returns a Promise and so do individual steps

Fix Workflow TS types

---

.bazelrc
.github/workflows/test.yml
src/workerd/io/worker.c++

This PR enables `-Werror`, when building in the CI. As a result, warnings are treated as a fatal error. This ensures that warnings will be addressed, and won't pile up over time in our codebase. Here are some specific details about the configuration.
* Warnings aren't fatal locally. This is for convenience while working on code.
* Warnings aren't fatal in `external/`. This is because these warnings come from our dependencies, and need to be fixed there.
* Deprecation warnings and `#warning` are not fatal. They're just here to give us a heads up that something will need to be fixed eventually.
* Warnings are only fatal on Linux builds. I didn't want to make this a maddening quest of fixing macOS, Windows AND Linux compiler warnings every time we do a PR.

Do not allow code with warnings to pass CI

---

src/node/.eslintrc.json
src/node/tsconfig.json

This was locally causing issues for me. Using a relative path in `project` causes clion errors to go away.

fix node eslintrc.json project path

---

src/workerd/jsg/struct.h

Strictly speaking this is not backward compatible, but I doubt anyone cares and it has saved me some time while debugging an issue.

more user-friendly jsg exception message

---

.github/workflows/release.yml
.npmrc
Dockerfile.release
WORKSPACE
package.json
pnpm-lock.yaml
src/cloudflare/tsconfig.json
src/node/internal/debuglog.ts
src/node/internal/internal_diffs.ts
src/node/internal/internal_inspect.ts
src/node/tsconfig.json

Currently, we don't have any way of understanding which version of `pnpm` we are using. 
This pull-request:
- Adds `packageManager` field that is used both by `corepack` and `pnpm` which automatically downloads the correct pnpm version.
- Updates `pnpm` to latest version
- Updates 2 bazel plugins in order to update the pnpm version. Unfortunately, the existing versions doesn't support pnpm 9.

use a specific pnpm version

---

BUILD.bazel
package.json
pnpm-lock.yaml
src/workerd/server/BUILD.bazel
src/workerd/server/tests/BUILD.bazel
src/workerd/server/tests/compile-tests/BUILD.bazel
src/workerd/server/tests/inspector/BUILD.bazel
src/workerd/server/tests/inspector/config.capnp
src/workerd/server/tests/inspector/driver.mjs
src/workerd/server/tests/inspector/index.mjs
src/workerd/server/tests/server-harness.mjs

This PR adds a regression test for the CPU profiling bug reported in #1754 and fixed in #2497. It is based on @mrbbot's original reproduction.
I backported the test to the commit just prior to #2497, and confirmed that the test caught the original breakage.
I wrote the test in JavaScript, because it seemed to have the richest ecosystem of tools for working with the Chrome Devtool Protocol. I originally intended to use Playwright to initiate a CDP connection to workerd, but it seemed to make too many assumptions that it was connecting to a browser. I tried the [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface) library next, and it seemed to work well.
Fixes #1754.

EW-8447 Add regression test for CPU profiling

---

types/defines/rpc.d.ts

`StepConfig` was missing from previous type iterations, making the `cloudflare:workers` `Workflow` types kind of unusable :sweat_smile:. 
All utility types are prefixed with Workflow to avoid polluting the `cloudflare:workers` scope

Add StepConfig workflow types

---

src/workerd/io/worker.c++
src/workerd/io/worker.h
src/workerd/server/server.c++
src/workerd/server/tests/inspector/driver.mjs
src/workerd/util/xthreadnotifier.h

This is implicated in a regression: #2564.
This PR adds a test case which reliably expresses a null pointer dereference in workerd (although the test itself frustratingly does not fail). The null pointer dereference could plausibly be the root cause of the segfault in #2564. Reverting the CPU profiling fix causes the null pointer dereference to go away.

EW-8447 Revert CPU profiling fix

---

.github/workflows/release.yml

It seems `version` field is not required whenever there is a `packageManager` field in `package.json`. Shout out to @npaun for finding the bug. Ref: https://github.com/pnpm/action-setup?tab=readme-ov-file#version

fix pnpm-setup workflow on release.yml

---

src/workerd/tests/bench-tools.h

I don't see any reason to use block comments and line continuations here, line comments are used elsewhere in the file and work fine. Also clang-format seems to not like it

NFC Fix comment in bench-tools.h

---

tools/cross/format.py

Fail if command returns nonzero exit code when formatting Use same flags when checking as when formatting as much as possible

MAINT Minor improvements to format.py

---

src/workerd/io/worker.c++
src/workerd/io/worker.h
src/workerd/server/server.c++
src/workerd/server/tests/inspector/driver.mjs
src/workerd/util/xthreadnotifier.h

My initial attempt at a fix made a subtle behavior change which I did not consider fully: instead of a new `incomingQueueNotifier` XThreadNotifier being constructed for every inspector connection, my fix caused all inspector connections to re-use one long-lived XThreadNotifier. This subsequently ran afoul of the fact that XThreadNotifier::awaitNotification() is not cancel-safe: if it is cancelled while awaiting its stored promise, calling awaitNotification() a second time tries to await a moved-from promise.
This PR restores the previous behavior of creating a new `incomingQueueNotifier` XThreadNotifier for every inspector connection. However, instead of constructing it in the WebSocketIoHandler constructor as before, I moved the construction to the `messageLoop()` function …

EW-8447 Fix CPU profiling again

---

justfile
tools/cross/format.py

- Replaced `--check` with `--list-different` to reduce noise (hides the files that does not need formatting) 
- Added `--log-level=warn` on formatting where now it prints only the files that actually changed.

update prettier and clang-format cli options in format.py

---

src/node/internal/compatibility-flags.d.ts
src/node/internal/internal_assert.ts
src/node/internal/internal_errors.ts
src/node/internal/internal_zlib.ts
src/node/internal/internal_zlib_base.ts
src/node/internal/streams_util.d.ts
src/node/internal/validators.ts
src/node/internal/zlib.d.ts
src/node/zlib.ts
src/workerd/api/node/tests/zlib-nodejs-test.js
src/workerd/api/node/tests/zlib-nodejs-test.wd-test
src/workerd/api/node/zlib-util.c++
src/workerd/api/node/zlib-util.h
src/workerd/io/compatibility-date.capnp

Lacks tests but before adding more, I think this is getting ready to have an additional pair of eyes.
Remaining todo:

add several `node:zlib` classes

---

src/node/internal/streams_adapters.js
src/workerd/api/node/tests/streams-test.js

Errors were not appropriately propagating via the streams adapters due to the destroy API being called incorrectly.

Fixup error propagation in Web streams to Node.js streams adapters

---

src/node/internal/internal_zlib_base.ts
src/workerd/api/node/tests/zlib-nodejs-test.js
src/workerd/api/node/zlib-util.c++

Adds zlib destroy test. Adapted to conform to cloudflare workers constraints.

test zlib destroy and add more tests

---

.github/workflows/test.yml

Make sure we actually install llvm-symbolizer, so that traces in CI test failures make sense.

Fix llvm-symbolizer in CI

---

src/workerd/api/global-scope.c++
src/workerd/api/tests/global-scope-test.js

Per the `queueMicrotask(...)` spec... https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#microtask-queuing
```js
globalThis.addEventListener('error', (event) => {
console.log(event.error);
return true;
})
queueMicrotask(() => {
throw new Error('sync error throw in microtask');
});
```
The `'error'` event should preserve async context in case the queueMicrotask originates from within a request:
```
const als = new AsyncLocalStorage();
addEventListener('error', (event) => {
console.log(als.getStore());
});
fetch() {
als.run(123, () => {
queueMicrotask(() => {
throw new Error('boom');
});
});
}
}
```

Report queueMicrotask errors to the error event

---

src/workerd/api/global-scope.c++
src/workerd/api/worker-rpc.c++
src/workerd/io/worker.c++
src/workerd/jsg/async-context.c++
src/workerd/jsg/function.h
src/workerd/jsg/iterator.h
src/workerd/jsg/jsvalue.c++
src/workerd/jsg/modules-new.c++
src/workerd/jsg/modules.c++
src/workerd/jsg/value.h
src/workerd/server/workerd-api.c++

v8 Local handles aren't really supposed to be heap allocated at all. A short while back v8 introduced a new `v8::LocalVector<T>` collection type that more correctly handles the allocation and handling of a collection of locals. Update workerd to use it.

Use v8::LocalVector in multiple places

---

src/workerd/api/node/i18n.c++
src/workerd/api/node/tests/buffer-nodejs-test.js

This was an invalid optimization. If fromEncoding and toEncoding is same, and if the encoding is invalid (such as invalid utf8), the output should have included a result that replaces invalid characters with replacement characters.

fix buffer.transcode if both encodings are same

---

src/workerd/io/worker.c++
src/workerd/jsg/modules-new-test.c++
src/workerd/jsg/modules-new.c++
src/workerd/server/workerd-api.c++

Adds in the part about ensuring ESM evaluation occurs outside of the IoContext if there is one.
Some context for newcomers: I've been slowly working on a new implementation of the module registry in workerd. This is a continuation of that work. Here I implement the bits of the code necessary to ensure that the module is evaluated outside of the IoContext if there is one.
This code currently is not used in production.

More incremental work on new module registry impl

---

src/node/internal/internal_zlib.ts
src/node/internal/zlib.d.ts
src/node/zlib.ts
src/workerd/api/node/tests/zlib-nodejs-test.js
src/workerd/api/node/zlib-util.c++
src/workerd/api/node/zlib-util.h

- Reuses ZlibContext from @anonrig's implementation of the stream-based API.
- Sends the entire input buffer at once, and uses only the finishFlush flag, like Node's does.
- Uses GrowableBuffer to collect the output as it's generated. This is basically kj::Vector, but it can be limited to a maximum size and adds some methods to make usage as a buffer more ergonomic.

zlib one-shot methods

---

.vscode/launch.json
src/cloudflare/internal/pipeline-transform.ts
src/cloudflare/internal/test/pipeline-transform/BUILD.bazel
src/cloudflare/internal/test/pipeline-transform/transform-test.js
src/cloudflare/internal/test/pipeline-transform/transform.wd-test
src/cloudflare/internal/test/pipeline-transform/tsconfig.json
src/cloudflare/pipeline-transform.ts
types/defines/pipeline-transform.d.ts

This PR adds a class called PipelineTransform which allows us to test PipelineTransform implementations before sending them real data from "Cloudflare Pipelines".
It also means that you don't have to deal with streams directly and can just work with JSON/Javascript Objects.

Adding PipelineTransform class

---

src/node/internal/internal_zlib.ts
src/node/zlib.ts
src/workerd/api/node/tests/zlib-nodejs-test.js

Adds remaining constants and remaining tests.

add zlib codes constants

---

src/workerd/io/compatibility-date-test.c++
src/workerd/io/compatibility-date.capnp

Push back the date where nodejs-compat implies nodejs-compat-v2
@dom96 @vickykont ... this would need to go out into a release this week.

Move the default implied on date for nodejs-compat-v2

---

WORKSPACE
build/BUILD.zlib

This PR changes the source of zlib to match what V8 is using, so that we don't have version conflicts between workerd and the internal edgeworker repo.
zlib is built from source. The build config is a translation from the BUILD.gn file into bazel syntax.
Note that this is a bit of a different build process from edgeworker, which uses precompiled binaries from v8 for zlib.

Use V8's zlib

---

.github/workflows/fixup.yml
.github/workflows/labels.yml
.github/workflows/lint.yml
.github/workflows/test.yml

What this does:
- Makes the test workflow responsible for triggering fixup, labels and lint. 
- Cancels the entire workflow if another commit is pushed to the same PR
- Allows all other builds to run through.
This should cut down on the number of runners in use, and lead to less wait time for builds.

Cancel previous builds within the same PR on push

---

justfile
tools/unix/create-internal-pr.sh

Now you can use `just internal-pr` to create or update your internal PR as needed.

Add a convenient script to create internal PRs

---

src/workerd/api/global-scope.c++
src/workerd/api/global-scope.h
src/workerd/api/node/node.h
src/workerd/api/tests/compat-flags-test.js
src/workerd/api/tests/compat-flags-test.wd-test
src/workerd/io/features.h
src/workerd/jsg/jsg.h
src/workerd/jsg/jsvalue.c++
src/workerd/jsg/jsvalue.h

A simple built-in API for determining if a given compat flag is set.
```
const { compatibilityFlags } = globalThis.Cloudflare || {};
console.log(compatibilityFlags['url_standard']); 
```
Internal discussion wiki: (sorry external folks, you won't be able to see this) https://wiki.cfdata.org/display/~jsnell/Exposing+active+compat+flags+to+workers

Implements globalThis.Cloudflare.compatibilityFlags API

---

build/BUILD.zlib

- Drop visibility attribute, only zlib library itself needs to be visible
- Drop explicit includes directive, this is generally bad style in bazel
- Drop support for unsupported architectures, add target_compatible_with for arch-specific targets
Will make another PR that switches to using `local_defines` in the afternoon.

[build] Refactor zlib configuration

---

src/workerd/api/actor.c++
src/workerd/io/compatibility-date.capnp
src/workerd/io/io-channels.h
src/workerd/io/io-context.h
src/workerd/server/server.c++
src/workerd/tests/test-fixture.c++

This will remain `experimental` for some time.
Note that turning this on in local dev would effectively be a no-op, but rather than allow the flag to be set and continue regular operation, we'll throw an exception.

Add `replicaRouting` compat flag

---

README.md
build/BUILD.zlib

Also fixes a potential build failure for arm64 – the `zlib_arm_crc32` target did not have the required crc32 extension enabled. This did not surface on Apple Silicon builds as the extension is supported by all Apple Silicon CPUs and enabled unconditionally.

[build] Further zlib build refactor, document new hardware requirements

---

src/node/internal/internal_zlib.ts
src/workerd/api/node/tests/zlib-nodejs-test.js

This PR translates the following tests from NodeJS:
- test-zlib-truncated.js 
- test-zlib-from-concatenated-gzip.js
- test-zlib-not-string-or-buffer.js
-  test-zlib-from-gzip-with-trailing-garbage.js
-  test-zlib-from-string.js
-  test-zlib-empty-buffer.js 
I've removed any existing tests that were redundant with Node's tests. In the process of implementing these tests, I've found two bugs: 
- unzip was using the wrong ZlibMode [fixed]
-  an issue when streaming multi-member archives [test commented out until this is solved]
I think we don't need any equivalent to this test:
-  test-zlib-no-stream.js (https://github.com/nodejs/node/blob/fc02b88f89f8d5abf5ee4414a1026444c18d77b3/test/parallel/test-zlib-no-stream.js#L4)

Add some more node:zlib tests

---

tools/cross/format.py

Let's speed up the formatters and linters.

parallelize formatter to speed up things

---

src/workerd/api/actor-state.c++

To get a better sense of the prevalence of this usage pattern.

Log when deleteAll is called with an alarm still set on the object

---

src/cloudflare/internal/test/vectorize/vectorize-api-test.js
src/cloudflare/internal/vectorize-api.ts
types/defines/vectorize.d.ts

Allow boolean returnMetadata for Vectorize V2 queries for backward compatibility with Vectorize V1.

feat: Allow boolean returnMetadata for Vectorize V2 queries

---

src/workerd/api/pyodide/pyodide.c++
src/workerd/api/pyodide/pyodide.h

This is a scaled-back version of #2618. 
I'm pushing ahead with this change while we figure out what we're doing with the ArtifactBundler & package loading promises.

Add PyodidePackageManager implementation

---

src/node/internal/internal_errors.ts
src/node/internal/internal_zlib.ts
src/node/internal/internal_zlib_base.ts
src/node/internal/internal_zlib_constants.ts
src/node/internal/zlib.d.ts
src/node/zlib.ts
src/workerd/api/node/BUILD.bazel
src/workerd/api/node/tests/zlib-nodejs-test.js
src/workerd/api/node/zlib-util.c++
src/workerd/api/node/zlib-util.h

Implements:
- `new BrotliCompress()`
- `new BrotliDecompress()`
- `createBrotliDecompress()`
- `createBrotliCompress()`
functions and classes to `node:zlib`

implement brotli classes

---

src/workerd/api/node/tests/zlib-nodejs-test.js

Nice small PR for EOD Friday. Adds two tests from NodeJS. Actually, we'll throw in a third one at no additional cost.
- test-zlib-flush.js (currently fails)
- test-zlib-dictionary.js (all good!)
- test-zlib-close-after-write (all good!)

Three more node:zlib tests

---

src/node/internal/module.d.ts
src/node/module.ts
src/workerd/api/node/BUILD.bazel
src/workerd/api/node/module.c++
src/workerd/api/node/module.h
src/workerd/api/node/node.h
src/workerd/api/node/tests/module-create-require-test.js
src/workerd/api/node/tests/module-create-require-test.wd-test
src/workerd/jsg/modules.c++

The `createRequire()` function is used in node.js to create a `require()` function that can be used from inside an ESM module. This is useful largely for porting existing CommonJS code to ESM as it allows the ESM module to keep using `require()` to load other modules.
This is being implemented in the runtime rather than as a polyfill because it needs to integrate tightly with the module registry implementation.
The implementation is as close to Node.js' as we can currently make it.
Note that the return value of `createRequire()` is a function. In Node.js, this function has additional properties like `require.resolve(...)`, `require.main`, `require.extensions`, and `require.cache`. We are not currently implementing these additional properties but we could in the future if there is a need …

Implement node:module createRequire API

---

src/node/internal/internal_zlib.ts
src/node/internal/internal_zlib_base.ts
src/node/internal/zlib.d.ts

Simplifies zlib internals by removing several typescript types, using `null` as the first parameter of a callback etc.

simplify zlib internals

---

src/node/internal/internal_zlib_base.ts
src/workerd/api/node/tests/zlib-nodejs-test.js

Fixes a bug on `node:zlib` due to using `defaultFlushFlag` instead of `defaultFullFlushFlag`

fix node:zlib flush tests

---

.github/workflows/cla.yml
.github/workflows/issues.yml
.github/workflows/npm.yml
build/BUILD.dawn

- This finally fixes warnings about the deprecated node16 being used for CLAssistant.
- Use short-form for dependencies in BUILD.dawn

Update Github Actions dependencies

---

src/node/buffer.ts
src/node/internal/crypto.d.ts
src/node/internal/crypto_hash.ts
src/node/internal/crypto_keys.ts
src/node/internal/crypto_util.ts
src/node/internal/internal_zlib.ts
src/node/internal/internal_zlib_base.ts
src/node/internal/web_crypto.d.ts
src/node/module.ts
src/node/tsconfig.json
src/node/url.ts
src/workerd/api/node/BUILD.bazel

We no longer need to disable linters for files that use URL or queueMicrotask()

enable linter for module.ts

---

justfile

I find it a lot more convenient than rooting around in the test log

Add just test-stream to run a test with live output

---

src/node/crypto.ts
src/node/internal/validators.ts
src/node/path.ts
src/node/stream/consumers.js
src/node/stream/promises.js
src/node/stream/web.js
src/node/tsconfig.json

Removes eslint-disable on more files and fixes the types along the way.

enable linters on more node.js implementations

---

src/workerd/api/node/zlib-util.c++

Brotli parameters were being read from the wrong argument.

Fix initialization of brotli parameters

---

src/pyodide/internal/python.ts

We want Pyodide to decide we're a browser. It checks a few extra things in 0.26.0 before being convinced of this. I think this is the only change to the loader code required to get Pyodide 0.26.2 working.

Fix feature detection for stable Pyodide 0.26

---

src/cloudflare/internal/test/d1/d1-api-test-common.js
src/cloudflare/internal/test/d1/d1-mock.js

The results format parsing changed in https://developers.cloudflare.com/d1/platform/changelog/#2024-07-26 and we always return `results`.
Also, the `rows_read` value of the results has some inconsistencies between these tests (d1-mock) and our internal worker tests, off-by-one, so replacing with `anything` for now.
```sh
bazel run //src/cloudflare/internal/test/d1:d1-api-test
bazel run //src/cloudflare/internal/test/d1:d1-api-test-with-sessions
```

Fix D1 DO mock and tests

---

src/workerd/server/workerd.c++

I ran into this when regenerating snapshots, should be loud here so we aren't accidentally not using the disk cache when we're supposed to. Unless there are cases where we rely on this silently failing?

Throw error if the python package disk cache dir is missing.

---

src/workerd/api/actor-state.c++
src/workerd/api/actor-state.h
src/workerd/api/sql-test.wd-test
src/workerd/api/sql.c++
src/workerd/api/sql.h
src/workerd/server/server.c++
src/workerd/server/server.h
src/workerd/server/workerd.capnp
src/workerd/tests/test-fixture.c++

Instead, it can be enabled in the workerd config.
In production, it'll be enabled implicitly if the new SQLite-based storage engine is in use. But `workerd` running locally always uses SQLite, even when testing code intended to run against non-SQLite namespaces in production, so we need a config option for workerd.
**Also enable PITR and abort() APIs without "experimental".**
Point-in-time recovery is only supported for SQLite-backed DOs in production; PITR methods will throw for non-SQLite namespaces.
abort() will work for all DOs. I think we've generally agreed this should be made public, but it's especially needed with the PITR APIs since you need a way to restart the object immediately after calling `onNextSessionRestoreBookmark()`.

Allow SQL interface to be enabled without "experimental" compat flag.

---

src/workerd/api/node/tests/zlib-nodejs-test.js
src/workerd/api/node/zlib-util.c++

Uses correct errors and messages for zlib validations.

fix zlib error messages

---

src/workerd/api/node/tests/zlib-nodejs-test.js

We're getting there, I feel it.

port `test-zlib-random-byte-pipes` test to workerd

---

src/workerd/api/node/zlib-util.c++
src/workerd/api/node/zlib-util.h

We are diverging from the original implementation in terms of function signature, but this simplifies our implementation. I am planning on opening a pull-request to Node.js as well to keep the implementations in sync with each other.

remove raiicontext and replace close() calls

---

src/workerd/api/r2-bucket.c++
src/workerd/api/r2-test.js
src/workerd/api/r2-test.wd-test

This commit addresses issue #2572

Fix R2 wildcard etag parsing

---

src/workerd/api/BUILD.bazel
src/workerd/api/tests/new-module-registry-test.js
src/workerd/api/tests/new-module-registry-test.wd-test
src/workerd/jsg/modules-new.c++
src/workerd/jsg/modules.c++
src/workerd/jsg/modules.h
src/workerd/jsg/util.c++
src/workerd/jsg/util.h

More incremental work on new module registry... bit-by-bit slowly getting done....
Starts adding api tests, fixing up some behaviors.

More incremental impl of new module registry

---

src/workerd/api/global-scope.c++

The ordering was incorrect causing a new error to be thrown. This fixes the error thrown.

fix expected only one byte on btoa

---

src/cloudflare/internal/test/workflows/BUILD.bazel
src/cloudflare/internal/test/workflows/workflows-api-test.js
src/cloudflare/internal/test/workflows/workflows-api-test.wd-test
src/cloudflare/internal/test/workflows/workflows-mock.js
src/cloudflare/internal/workflows-api.ts
src/cloudflare/internal/workflows.d.ts
src/cloudflare/workflows.ts

Adds a wrapped binding for Workflow, primarily works by calling a fetcher attached to the pipeline

Add Workflow binding module

---

src/workerd/server/tests/inspector/driver.mjs

Inspector-test currently runs 5 profiles, but we should be able to get by with just 2.

Reduce number of iterations in inspector-test

---

src/workerd/api/actor-state.c++
src/workerd/api/sql-test.js
src/workerd/io/actor-sqlite.c++
src/workerd/io/actor-sqlite.h
src/workerd/server/alarm-scheduler.c++
src/workerd/server/alarm-scheduler.h
src/workerd/server/server.c++
src/workerd/util/sqlite-kv-test.c++
src/workerd/util/sqlite-kv.c++
src/workerd/util/sqlite-kv.h
src/workerd/util/sqlite-test.c++
src/workerd/util/sqlite.c++
src/workerd/util/sqlite.h

And use this to implement deleteAll().
Thus, `deleteAll()` will now delete SQL tables as well, instead of just KV data.

Extend SqliteDatabase with a reset() method that recreates the database

---

types/defines/workflows.d.ts

The types currently suggest that it is in global scope and it is not

Fix types to correctly suggest NonRetryableError is exported in cloudflare:workflows

---

src/node/internal/internal_zlib_base.ts

Found the bug. It seems the execution order was wrong. I couldn't find a proper way to test this, but manually running the tests show no `uncaught exception`.
Fixes https://github.com/cloudflare/workerd/issues/2694

fix the execution order of brotli class

---

src/node/internal/internal_zlib.ts
src/node/internal/internal_zlib_base.ts
src/node/internal/zlib.d.ts
src/workerd/api/node/tests/zlib-nodejs-test.js

This PR implements the `{info: true}` option for zlib. It's not documented for brotli, but the unit tests expect it there too. We return an engine, and the buffer. 
~However, the engine we're returning isn't really legit - we just create it on the fly to return it. Should we fall back to the streaming path when `info: true`, for more fidelity with NodeJS or is this close enough?~ Now going whole-hog and falling back to the streaming implementation when `info: true`

zlib: Add support for info: true option

---

src/workerd/api/node/zlib-util.c++
src/workerd/api/node/zlib-util.h

* Zlib and Brotli use malloc and free by default to manage memory. If they leak, it's an upstream bug.
* However, they also allow for custom allocators to be passed.
* This PR extracts our custom allocator functions AllocForZlib, AllocForBrotli, FreeForZlib into a new class called Allocator.
* Allocator is now used for both the streaming and one-shot implementations.
* I dropped the stuffing of size into the allocated regions because the backing kj::heapArrays are already sized objects.
* At present, the information collected by allocator is not used. However, we could block excessively large allocations, and report allocations to V8 in the future.
* Our current implementation is a hash map of pointers, but what we'd really like is a kind of arena allocator, in my opinion at least.
Closes …

Extract Zlib/Brotli custom allocator

---

src/pyodide/internal/loadPackage.ts
src/pyodide/internal/metadata.ts
src/pyodide/internal/setupPackages.ts
src/pyodide/python-entrypoint-helper.ts
src/pyodide/types/artifacts.d.ts
src/pyodide/types/pyodide-lock.d.ts
src/pyodide/types/runtime-generated/metadata.d.ts
src/workerd/api/pyodide/pyodide.c++
src/workerd/api/pyodide/pyodide.h

Add packages to ArtifactBundler

---

src/workerd/io/BUILD.bazel
src/workerd/io/observer.h
src/workerd/io/worker.c++
src/workerd/io/worker.h
src/workerd/server/server.c++
src/workerd/tests/test-fixture.c++
src/workerd/util/sqlite-test.c++
src/workerd/util/sqlite.c++
src/workerd/util/sqlite.h

https://jira.cfdata.org/browse/STOR-3710

Introduce SqliteObserver and use it to collect stats related to queries and db size

---

src/workerd/util/sqlite-test.c++
src/workerd/util/sqlite.h

Reset the row counters when we create Query, so we calculate rowsRead and rowsWritten correctly.

Reset row counters when creating Query using templates

---

src/workerd/api/sql-test.wd-test
src/workerd/api/sql.h

We intend to make `exec()` automatically memoize prepared statements such that no application should ever be preparing statements manually. So, let's not even ship the API.
It's not yet possible to enable the SQL API in prod without the experimental flag so it's still safe to put `prepare()` back behind that flag.

Un-ship SQL prepared statements.

---

src/workerd/api/actor.c++
src/workerd/api/trace.c++
src/workerd/io/BUILD.bazel
src/workerd/io/io-channels.h
src/workerd/io/io-context.c++
src/workerd/io/io-context.h
src/workerd/io/observer.h
src/workerd/io/trace.c++
src/workerd/io/trace.h
src/workerd/server/server.c++

See downstream PR for discussion.

Add initial lime tracing

---

src/node/crypto.ts
src/workerd/api/node/tests/crypto_random-test.js

Fixes https://github.com/cloudflare/workerd/issues/2716

fix invalid invocation on getRandomValues()

---

src/workerd/api/url.c++

While implementing Ada, we found out that checking if URL is special or not, and getting the default port of a scheme had extremely high cost. Let's apply the same optimizations we did on Ada, on workerd.

speed up url.c++ scheme and port detection

---

WORKSPACE
patches/v8/0019-Implement-cross-request-context-promise-resolve-hand.patch
src/workerd/api/BUILD.bazel
src/workerd/api/tests/cross-context-promise-test.js
src/workerd/api/tests/cross-context-promise-test.wd-test
src/workerd/io/compatibility-date.capnp
src/workerd/io/io-context.c++
src/workerd/io/io-context.h
src/workerd/io/io-own.c++
src/workerd/io/io-own.h
src/workerd/io/worker.c++
src/workerd/jsg/jsg.h
src/workerd/jsg/jsvalue.h

Draft for now until I add tests tests and more tests
```
async fetch(req, env, ctx) {
if (globalThis.resolve === undefined) {
{
const { promise, resolve } = Promise.withResolvers();
setTimeout(resolve, 1000);
ctx.waitUntil(promise);
}
// This is our first request. We will create a new promise and resolver
// pair and store it in a global. This request will then wait for the
// promise to be resolved before continuing.
const { promise, resolve } = Promise.withResolvers();
globalThis.resolve = resolve;
globalThis.promise = promise;
const ab = AbortSignal.abort();
console.log(ab.aborted);
promise.then(() => {
// This will be run within the correct IoContext now...
try {
console.log('test1', ab.aborted);
} catch (err) {
// We would get here if the IoContext was incorrect …
```

Patch v8 to support promise cross-context resolution

---

docs/development.md
tools/cross/format.py

Make sure that we are using the same clang-format version. If v18 has a new version, CI will break and we'll have to manually change the validation on `format.py` which will make sure that all the breaking changes will be fixed.

ensure clang-format is v18.1.8

---

src/workerd/api/sql.h
types/test/types/do.ts

After #2722, we now have a final, very minimal SQLite API for durable objects. So I've just tweaked the TS generation to give a few generics to make things easier to work with. These are the changes:
```diff
diff --git a/.local/types-main/2023-07-01/index.ts b/bazel-bin/types/definitions/2023-07-01/index.ts
index 45460a4d..556a55d3 100755
--- a/.local/types-main/2023-07-01/index.ts
+++ b/bazel-bin/types/definitions/2023-07-01/index.ts
@@ -2778,20 +2778,24 @@ export declare const WebSocketPair: {
};
};
export interface SqlStorage {
-  exec(query: string, ...bindings: any[]): SqlStorageCursor;
+  exec<T extends Record<string, SqlStorageValue>>(
+    query: string,
+    ...bindings: any[]
+  ): SqlStorageCursor<T>;
get databaseSize(): number;
Cursor: typeof SqlStorageCursor;
Statement: …
```

Tweaked TS generation of DO SQlite types

---

.clang-format
.git-blame-ignore-revs
src/workerd/api/blob.h
src/workerd/api/streams/internal.c++
src/workerd/api/streams/queue.h
src/workerd/api/streams/standard-test.c++
src/workerd/api/streams/standard.c++
src/workerd/api/system-streams.c++
src/workerd/api/worker-rpc.h
src/workerd/io/actor-cache.c++
src/workerd/io/actor-sqlite.c++
src/workerd/io/trace.c++
src/workerd/io/worker.c++
src/workerd/jsg/jsg.c++
src/workerd/jsg/url-test.c++
src/workerd/jsg/wrappable.c++
src/workerd/server/server.c++
src/workerd/util/mimetype.c++

This looks much cleaner and readable IMHO. There is also an "Always" option for this, but its output feels less readable to me.
=============
See https://clang.llvm.org/docs/ClangFormatStyleOptions.html#allowshortblocksonasingleline. I don't remember how I found this but it might have been improved/fixed in LLVM 18/19.

Enable clang-format AllowShortBlocksOnASingleLine

---

src/workerd/api/http.h

I'm not 100% sure about the correct place to address https://github.com/cloudflare/workerd/issues/2723. Appreciate some feedback.
Fixes https://github.com/cloudflare/workerd/issues/2723

use correct types for webSocket

---

.github/workflows/npm.yml
package.json
pnpm-lock.yaml

- Roll pnpm dependencies
Some updates are not included to avoid breakage (kicking the can down the road), but we make progress on a number of packages.
- Update workerd NPM package deployment target to node18
Node 16 has been EOL since August 2023.
- Roll esbuild 0.15 : 0.21
=======================
This is a general update PR, I've updated dependencies here before but that was usually focused on specific packages. This does not attempt to update Typescript to 5.6 or update typescript-eslint beyond 8.4.0 (causes lint failures that go over my head).
@penalosa: Any objections to updating the NPM deployment target to node18? Would we need to document this anywhere? I'm also apprehensive about updating esbuild since it's quite outdated by now, it could break the NPM job and we'd only find out …

[build] Roll pnpm dependencies

---

.bazelrc
README.md

Currently, we strongly recommend clang's lld but suggest it "may" be possible to use GNU ld. GNU ld worked in the past but was slow. It currently doesn't work at all due to some errors relating to missing symbols in chromium zlib.
This PR simplifies things by requiring clang lld, and explicitly using it for builds. If a user can install clang, it's simpler to just install lld as well, instead of mixing things.

Always use LLD on Linux

---

src/workerd/api/tests/js-rpc-test.js
src/workerd/api/worker-rpc.c++
src/workerd/jsg/jsvalue.c++
src/workerd/jsg/jsvalue.h

See commit descriptions.
First issue caused spurious Sentry errors.
Other two issues @geelen complained about.

Fix various RPC issues

---

src/workerd/api/crypto/aes.c++
src/workerd/api/crypto/digest.c++
src/workerd/api/crypto/ec.c++
src/workerd/api/crypto/rsa.c++
src/workerd/api/node/crypto-keys.c++
src/workerd/api/util.c++
src/workerd/api/util.h

By using simdutf, we can improve the performance of all base64url encoding operations.

improve encodeBase64Url performance

---

src/workerd/api/actor-alarms-delete-test.js
src/workerd/api/actor-alarms-test.js
src/workerd/api/global-scope.c++
src/workerd/io/BUILD.bazel
src/workerd/io/actor-cache-test.c++
src/workerd/io/actor-cache.c++
src/workerd/io/actor-cache.h
src/workerd/io/actor-sqlite-test.c++
src/workerd/io/actor-sqlite.c++
src/workerd/io/actor-sqlite.h
src/workerd/server/alarm-scheduler.c++
src/workerd/server/server.c++
src/workerd/util/BUILD.bazel
src/workerd/util/sqlite-metadata-test.c++
src/workerd/util/sqlite-metadata.c++
src/workerd/util/sqlite-metadata.h

Implements the setting of the alarm value in the sqlite database, when setAlarm()/getAlarm() methods are called.
Also implements `armAlarmHandler()` and `cancelDeferredDelete()` internally, in a manner similar to ActorCache, rather than calling out to the hook functions.  Currently, only the `setAlarm()` hook function is used, and just to request notification from the AlarmScheduler.
Still need to implement proper sequencing of alarm update vs. commitCallback, but wanted to see if the general approach is OK.

Store alarm value in sqlite database, for sqlite-backed DOs

---

src/workerd/api/crypto/aes.c++
src/workerd/api/crypto/digest.c++
src/workerd/api/crypto/ec.c++
src/workerd/api/crypto/rsa.c++
src/workerd/api/node/crypto-keys.c++
src/workerd/api/util.c++
src/workerd/api/util.h

This reverts commit b3d98e0049a364818ef8428153a8fb2436f99cc3.
I'll follow up on a different PR to fix edgeworker related tests.

Revert "improve encodeBase64Url performance (#2774)"

---

src/workerd/api/crypto/aes.c++
src/workerd/api/crypto/digest.c++
src/workerd/api/crypto/ec.c++
src/workerd/api/crypto/rsa.c++
src/workerd/api/node/crypto-keys.c++
src/workerd/api/util.c++
src/workerd/api/util.h

Applying the suggestion of adding a null terminator before passing the input to `kj::String`
Reverts https://github.com/cloudflare/workerd/pull/2776

Revert the revert of `fastEncodeBase64Url` method

---

tools/unix/create-internal-pr.sh

I'm not sure how it works right now for others. Every time I try to use `just internal-pr` the newly created branch is not up to date with the origin master, and I manually have to run `git pull --rebase origin master`.

improve create-internal-pr.sh

---

.bazelrc
README.md

macOS 12 (released 2021) is now EOL, and Mac developers generally update to the latest OS version quickly.
As a side effect, this implicitly enables the chained fixups linker feature, which improves binary launch times and reduces workerd release binary size by ~65 KB (See https://www.emergetools.com/blog/posts/iOS15LaunchTime for more information).

[build] Bump minimum macOS version to 10.13

---

src/workerd/api/http.c++
src/workerd/api/url.c++
src/workerd/api/util.c++
src/workerd/api/util.h
src/workerd/jsg/BUILD.bazel
src/workerd/jsg/inspector.c++

Introduces `fastEncodeUtf16` function that uses simdutf under the hood to convert utf8 inputs to utf16. The changeset also includes the usage of `simdutf::validate_ascii` to check if an input is a valid ascii.

improve utf8 to utf16 conversion performance

---

tools/cross/format.py

This got out of hand and many developers report problems. All third-party dependencies need to be fetched by bazel if they are a requirement for workerd development.
Feel free to uncomment particular formatters once dependency management is fixed.
This is not a reflection on linters/formatters at all: they are super useful and we should continue increasing the coverage.

disabling all precommit hooks that depend on external binaries

---

tools/cross/format.py

I guess it will go away once clang_format is managed by bazel, but right now it is a nuisanse since we've disable clang_format.

[nfc] invoke check_clang_format only when clang_format is invoked

---

.ruff.toml

Imo these are arbitrary and are often fought with.

[nfc] ruff: disable too many branches/statements

---

src/workerd/api/tests/global-scope-test.js
src/workerd/jsg/resource.h

Miniflare has been using the lack of `Symbol.toStringTag` to detect internal API objects. This is brittle and problematic because for compliance with standard web platform APIs we're supposed to be adding the Symbol.toStringTag to standard types and there are modules in the ecosystem that depend on it. We recently landed a change that adds the Symbol.toStringTag to types but that broke miniflare. This PR adds an alternative symbol to jsg::Objects that can identify themselves as internal.

Add cloudflare internal symbol to resourcetypes

---

src/workerd/api/node/tests/zlib-nodejs-test.js
src/workerd/api/node/tests/zlib-nodejs-test.wd-test
src/workerd/io/compatibility-date.c++
src/workerd/io/compatibility-date.capnp

Ensures that if either nodejs_compat or nodejs_compat_v2 are enabled, then nodejs_zlib will be enabled also
There was a limitation in the original definition of the implied by annotation in that it would only allow specifying a single field. The effect was that `nodejs_zlib` would be implied by `nodejs_compat` but not `noejs_compat_v2`. If I updated it to be implied by `nodejs_compat_v2` then it would transitively work for both `nodejs_compat` and `nodejs_compat_v2` but *wouldn't* do the right thing if the worker had `nodejs_compat, no_nodejs_compat_v2`... Confusing.
This PR modifies the implied by annotation to allow multiple flags to be specified so that it works correct in any combination.

Have nodejs_zlib implied by nodejs_compat_v2

---

src/workerd/api/BUILD.bazel
src/workerd/api/analytics-engine.h
src/workerd/api/data-url.c++
src/workerd/api/encoding.c++
src/workerd/api/encoding.h
src/workerd/api/form-data.c++
src/workerd/api/gpu/gpu.c++
src/workerd/api/memory-cache.c++
src/workerd/api/node/async-hooks.c++
src/workerd/api/streams/encoding.h
src/workerd/api/util.c++
src/workerd/api/util.h
src/workerd/io/BUILD.bazel
src/workerd/io/io-channels.h
src/workerd/io/io-util.c++
src/workerd/io/io-util.h
src/workerd/jsg/BUILD.bazel

Merges 2 implementations and introduces 2 new cc_library targets on bazel.

merge isAsciiWhitespace implementations

---

src/node/internal/util.d.ts
src/node/util.ts
src/workerd/api/node/tests/util-nodejs-test.js
src/workerd/api/node/util.c++
src/workerd/api/node/util.h

This pull-request adds the one of the newest Node.js API: `util.getCallSite()`

add util.getCallSite implementation

---

src/workerd/api/node/BUILD.bazel
src/workerd/api/node/async-hooks.h
src/workerd/api/node/i18n.c++
src/workerd/api/node/i18n.h
src/workerd/api/node/zlib-util.c++

Moves `workerd/io` to implementation_deps and removes unused includes.

simplify workerd/api/node bazel

---

WORKSPACE

A classic cross-compilation experience: the binary claiming to be for ARM64 on Linux was actually an x86_64 executable in disguise. Getting a real ARM binary out of Github Actions was a laborious slog involving the zig toolchain. This PR replaces the binary with one that actually works. Thanks to @danlapid for spotting this one.

Fix binary for clang-format on Linux arm64

---

.bazelrc
.gitignore
build/deps/build_deps.jsonc
build/deps/deps.jsonc
compile_flags.txt
src/workerd/api/BUILD.bazel
src/workerd/api/actor.c++
src/workerd/api/crypto/dh-primes.h
src/workerd/api/hyperdrive.c++
src/workerd/api/hyperdrive.h
src/workerd/api/node/BUILD.bazel
src/workerd/api/node/diagnostics-channel.h
src/workerd/api/node/node.h
src/workerd/server/BUILD.bazel
src/workerd/tools/BUILD.bazel

[build] Factor out api:hyperdrive target
[nfc] Assorted build cleanup
- Add back/expand comments after moving dependencies to update-deps system
- Fix compile_flags.txt for Xcode 16 by adding missing path
- Remove Windows include paths from compile_flags.txt – the team does not
regularly use Windows and the spaces in the file path make using the file to
build code (e.g. clang++ @compile_flags.txt <file>) fail.
- Add -fbracket-depth=512 to compile_flags.txt so that it can be used to
compile workerd-api.c++
[build] Split files off of node and server targets
- Fix missing pragma once in dh-primes.h
[nfc] Clean up Rust-related comments, gitignore

[build] Split up more bazel targets, compile_flags.txt fixes

---

src/workerd/tools/param-names-ast.c++

Fixes https://github.com/cloudflare/workerd/issues/2652
A regression introduced in https://github.com/cloudflare/workerd/commit/fc7f91d59e114f697784e9a2caf9b0e3e93f46c2 meant that parameter names for some APIs were no longer being included in the generated types, since `param-names-ast.c++` didn't import them. This PR updates the includes within `param-names-ast.c++` to match `rtti.c++`.

Fix type params

---

src/workerd/api/cache.c++
src/workerd/api/cache.h
src/workerd/api/memory-cache.c++
src/workerd/api/r2-admin.c++
src/workerd/io/io-context.c++

Splitting this off of #2799, which will take some more work.

[o11y] Fix incorrect R2 span names, add initial cache, memory-cache user spans

---

types/defines/ai.d.ts

As noted in https://github.com/cloudflare/workerd/issues/2470 - the response type from `env.AI.run` with (in my case) `@cf/bytedance/stable-diffusion-xl-lightning`  claims it should return a UInt8Array, but actually returns a ReadableStream.
This is fine when feeding it into a `new Response()` and returning, but is problematic when trying to use the data in other ways.
You can replicate this with the example model usage [here](https://developers.cloudflare.com/workers-ai/models/stable-diffusion-xl-lightning/)
```
[ai]
binding = "AI"
```
```ts
export interface Env {
AI: Ai;
}
async fetch(request, env, ctx): Promise<Response> {
const inputs = {prompt: "cyberpunk cat"};
const response = await env.AI.run(
"@cf/bytedance/stable-diffusion-xl-lightning",
inputs
);
// Expected: …
```

Fix AiTextToImageOutput type from UInt8Array -> ReadableStream

---

build/wd_capnp_library.bzl

It is special and its c++ version is not built but checked into the vcs. It is implicitly available to c++ targets, but needs be built for rust.

[nfc] wd_capnp_library: support dependency on json.capnp

---

src/pyodide/internal/python.ts
src/pyodide/internal/setupPackages.ts
src/workerd/io/compatibility-date.capnp

This ensures that the contents of worker files cannot be accessed prior to taking the snapshot and so won't appear in the linear memory.

Mount python worker files after taking memory snapshot

---

samples/pyodide-fastapi/config.capnp
samples/pyodide-langchain/config.capnp
samples/pyodide-secret/config.capnp
samples/pyodide/config.capnp
samples/repl-server-python/config.capnp
src/workerd/api/pyodide/pyodide.h
src/workerd/io/compatibility-date.capnp
src/workerd/server/tests/python/env-param/env.wd-test
src/workerd/server/tests/python/hello/hello.wd-test
src/workerd/server/tests/python/import_tests.bzl
src/workerd/server/tests/python/random/random.wd-test
src/workerd/server/tests/python/subdirectory/subdirectory.wd-test
src/workerd/server/workerd-api.c++
src/workerd/util/autogate.c++
src/workerd/util/autogate.h

We want to be able to synchronize this behavior change between upload time and runtime. Autogates don't allow us to do this as far as I understand but feature flags do.

Switch from external pyodide autogate to feature flag

---

src/workerd/api/node/zlib-util.h
src/workerd/api/streams/compression.c++
src/workerd/api/streams/compression.h

Enforce lock exists on all compression operations.

enforce isolate lock and track allocations on v8

---

src/pyodide/internal/snapshot.ts

This will avoid any potential parser bugs if the deployment isn't using any packages.

Skip Python parsing of package imports when requirements are empty.

---

src/pyodide/internal/util.ts

We run a lot of important code through this function, this is a simple change that should make it easier to track down which code is broken.

Improve errors thrown by simpleRunPython.

---

src/workerd/io/worker.c++

I don't think we want to keep this is forever ...
Since we don't have a way of testing log output yet in workerd it's difficult to test this reliably. Here's what the log output currently looks from the test (just a sampling)
```
...
workerd/server/server.c++:3851: debug: [ TEST ] cross-context-promise-test:asyncIterWorks
workerd/server/server.c++:3859: debug: [ PASS ] cross-context-promise-test:asyncIterWorks
workerd/server/server.c++:3851: debug: [ TEST ] cross-context-promise-test:crossContextRejectWorks
workerd/io/worker.c++:1213: warning: NOSENTRY Warning: Cross Request Promise Resolve
at Object.reject (<anonymous>)
at rejectTest (worker:238:23)
at Object.fetch (worker:142:14)
workerd/server/server.c++:3859: debug: [ PASS ] cross-context-promise-test:crossContextRejectWorks …
```

Attempt to log the stack where cross-request promises are being resolved

---

src/cloudflare/internal/images-api.ts
src/cloudflare/internal/images.d.ts
types/defines/images.d.ts

IMAGES-1258: Don't pollute global scope with generally named types

---

src/workerd/jsg/url.c++

Fix minor buffer overflow in url.c++
When the protocol string is empty, we should not try to drop a trailing colon. This was found by using a new fuzzer for URL-related APIs.
Fix URL assertion failure found by fuzzing
This aligns canonicalizeOpaquePathname() with the other canonicalize functions.
Also elides a superfluous memory allocation.
Also see the upstream draft PR.

Fix URL bugs found by fuzzing

---

src/pyodide/internal/snapshot.ts

These are always imported so it doesn't make sense to include them in the snapshot filename.

Don't include implicit stdlib snapshot imports in package snapshot key.

---

src/pyodide/internal/snapshot.ts
src/workerd/api/pyodide/pyodide.c++
src/workerd/api/pyodide/pyodide.h

Just some changes/clean up for the EW PR.

Changes to enable download of snapshot in validator.

---

src/node/test.js

Let's expose the classes to be in par with Node.js

expose MockTracker and MockFunctionContext on node:test

---

src/workerd/api/BUILD.bazel
src/workerd/api/node/BUILD.bazel
src/workerd/api/node/util.h
src/workerd/io/BUILD.bazel
src/workerd/tests/BUILD.bazel
src/workerd/util/BUILD.bazel
src/workerd/util/mimetype.h

Adds memory tracking to mimetype and separates several cc libraries to improve build (which is required)

add memory tracking to workerd::mimetype

---

src/workerd/api/trace.c++
src/workerd/io/worker-interface.capnp
src/workerd/io/worker-interface.h

Await response of sendTraces over rpc to fix waitUntilTasks not empty bug

Fix waitUntilTasks not empty when trace worker is over RPC

---

src/node/internal/internal_utils.ts
src/node/internal/streams_adapters.js
src/node/internal/streams_duplex.js
src/node/util.ts
src/workerd/api/node/tests/crypto_hash-test.js
src/workerd/api/node/tests/crypto_hkdf-test.js
src/workerd/api/node/tests/crypto_pbkdf2-test.js
src/workerd/api/node/tests/crypto_random-test.js
src/workerd/api/node/tests/diagnostics-channel-test.js
src/workerd/io/compatibility-date.c++

Removes bunch of `createDeferredPromise` functions in favor of `Promise.withResolvers()` and resolves several TODOs

remove unnecessary deferredPromise declarations

---

src/pyodide/internal/topLevelEntropy/lib.ts

Now that we've removed the old snapshot tests this code is no longer needed anywhere.

Remove SHOULD_GATE_ENTROPY flag

---

src/workerd/api/node/BUILD.bazel
src/workerd/api/node/tests/sys-nodejs-test.js
src/workerd/api/node/tests/sys-nodejs-test.wd-test
src/workerd/jsg/util.c++

Even though it is deprecated, there are people depending on `node:sys`. Still...
@IgorMinar as requested on https://github.com/orgs/cloudflare/projects/24/views/1?pane=issue&itemId=65484840

add node:sys to comply with nodejs_compat

---

src/workerd/jsg/dom-exception.c++
src/workerd/jsg/dom-exception.h

Fixing some clang-tidy recommendatons.

add const & constexpr to dom-exception related functions

---

src/workerd/io/worker.c++
src/workerd/jsg/ser.c++

This is expected to be relatively temporary. V8 is in the process of deprecating and removing the original `GetPrototype()` implementation. Once that original impl is removed, I believe the plan is to rename `GetPrototypeV2()` back to `GetPrototype()`, at which point we'll likely need to change these back. That's ok, we want to make sure there's no issue with updating to the new behavior well in advance of that.

Rename GetPrototype() uses to GetPrototypeV2()

---

src/node/stream/consumers.js

Enablers linter and simplifies implementation by using `Array.fromAsync()`

enable linter and simplify stream/consumers.js

---

src/cloudflare/internal/vectorize-api.ts

In order to support local bindings in miniflare, we have to send requests through the core Vectorize service. This service requires input for `/insert` and `/upsert` operations to be in ndjson format. This PR adds an initialization option that optionally tells the binding to put the input to these operations in ndjson. Existing behavior should be identical.

Support ndjson-format for insert & upsert ops in vectorize api

---

types/defines/rpc.d.ts

We previously passed in an Array of events but have since decided to switch to a single event per Workflow instance. This updates the types.

Update Workflow class type definition to accept a single event

---

src/node/util.ts
src/workerd/api/node/tests/util-nodejs-test.js

Let's add some of the missing `node:util` functions.

add isDeepStrictEqual and isArray to node:util

---

src/cloudflare/internal/workflows-api.ts
src/cloudflare/internal/workflows.d.ts

Terminate is more consistent with the rest of our APIs

Rename abort to terminate in Workflows binding

---

src/cloudflare/internal/workers.d.ts
src/cloudflare/workers.ts
src/node/internal/workers.d.ts
src/workerd/api/worker-rpc.c++
src/workerd/api/worker-rpc.h
src/workerd/io/worker.c++
src/workerd/io/worker.h
src/workerd/server/workerd-api.c++
types/defines/rpc.d.ts

`Workflow` conflicts with the binding class which is also called `Workflow`
Since we have `WorkerEntrypoint`, `WorkflowEntrypoint` feels like a much more appropriate and descriptive name of the base class
This is of course a breaking change, but these are all scoped under `experimental` for now so that is okay

Rename Workflow to WorkflowEntrypoint

---

.bazelrc
.github/workflows/release.yml
.github/workflows/test.yml

- [nfc] Drop duplicated macOS experimental_objc_fastbuild_options flag
- [CI] Use macos-15 image for test job, implicitly transitioning to Apple Silicon
To mitigate our problems with macOS runner rate limiting, switch to the
macos-15 runner image. This means we are implicitly transitioning the test job
to Apple Silicon (macos-13 is x86, macos-15 is Apple Silicon with no x86 option
available outside of paid runners).
This allows us to take advantage of the latest compiler features available in
Xcode 16 (based on LLVM 17), which is not available for macOS 13. Xcode has
good backwards compatibility; based on the macos_minimum_os flag we will
continue to support macOS 13 and later.
Interestingly, the macos-15 build is much faster (~2x based on limited testing),
so this will help avoid having …

[CI] macOS build improvements

---

types/defines/rpc.d.ts

The callback is now always the last argument with an optional `config` as second argument. This allows users to do: 
```
step.do('does not truncate', async () => {
return event.payload.char.repeat(900);
}),
step.do(
'does truncate',
{
retries: {
limit: 5,
backoff: 'constant',
delay: '1 second',
},
},
async () => {
return event.payload.char.repeat(2000);
}
),
```

Make callback the last arg for Workflow do

---

types/defines/rpc.d.ts

While `sleep` allows users to sleep for a duration, `sleepUntil` takes a Date or ms from epoch and sleeps until then

Add sleepUntil in Workflow step functions

---

.bazelrc

This appears to be needed for the clang driver to find LLD when using older clang versions.
=============
This (hopefully) fixes macOS CI release builds.

[build] fix lld linker path

---

.bazelrc
.github/workflows/release.yml

Symlink the ld64.lld binary so that it can be used under the bazel sandbox and add back missing --linkopt prefix.
============
This should actually fix the build – works locally, and we're accounting for differences in HOMEBREW_PREFIX based on x86/Apple Silicon.

[build] fix lld linker path^2

---

.bazelrc
.github/workflows/release.yml

Trying to get bazel to use LLD is turning into groundhog day, I'm not yet ready to give up though.
- This should work – tested the new approach on c9f1b4ac136c3373d7afe1f9674a1dc5978f4c16 by emulating the steps needed for release in the test job and matching the image used for release (macos-13), CI completed successfully.

[build] fix lld linker path^3

---

src/node/buffer.ts
src/workerd/api/node/tests/buffer-nodejs-test.js
src/workerd/api/node/tests/node-compat-v2-test.js

Ref: https://github.com/unjs/unenv/pull/325.

fix invalid this errors on node:buffer

---

src/node/buffer.ts
src/node/internal/internal_buffer.ts

These changes would stop wrangler adding polyfills for `node:buffer` and remove it as a "hybrid module". This would improve the size of the workerd script.

add remaining node:buffer methods

---

src/workerd/api/sql-test.js
src/workerd/util/sqlite.c++

Bug introduced in #2866. See comments for explanation.

SQLite: Fix spurious `BEGIN TRANSACTION should have failed when already in a transaction?`

---

src/workerd/api/BUILD.bazel
src/workerd/api/http.c++
src/workerd/api/tests/fetch-test.js
src/workerd/api/tests/fetch-test.wd-test
src/workerd/io/compatibility-date.capnp
src/workerd/util/strings.c++
src/workerd/util/strings.h

This introduces a non-standard behavior that would become the default. Please review carefully. See the original bug report for context (linked below).
Fixes: https://github.com/cloudflare/workerd/issues/2516

Upper case all http methods in fetch API with compat flag

---

types/defines/rpc.d.ts
types/test/types/rpc.ts

Fixes #2003
`interface` does not extend `Serializable` but `type` does.
```typescript
interface R1 {
field: string;
}
type R2 = {
field: string;
}
```
```R1 extends Serializable``` fails.
```R2 extends Serializable``` ok.
After the patch both `interface` and `type` match `Serializable`.
This fix is a starting point for the issue, there may be a better solution.

Fix returning interface types from rpc methods

---

types/defines/rpc.d.ts

For some reason, Typescript resolves types in a different away compared to abstract classes. As a consequence, it would not apply the overloading properly and always treats `WorkflowStep.do` as a 3 argument function

Fix: change WorkflowStep into an abstract class

---

tools/base.eslint.config.mjs

This would improve the linter performance by not running type checking on javascript files.

disable tseslint on js files

---

src/node/internal/process.ts
src/node/internal/util.d.ts
src/workerd/api/node/BUILD.bazel
src/workerd/api/node/tests/process-exit-test.js
src/workerd/api/node/tests/process-exit-test.wd-test
src/workerd/api/node/util.c++
src/workerd/api/node/util.h
src/workerd/io/io-context.c++

An implementation of `process.exit(...)` as part of Node.js compat.
Unlike in Node.js, calling `process.exit(...)` does not actually exit the workerd process, for obvious reasons. Instead, when called within the scope of a request, calling `process.exit(...)` will cause the current IoContext to be aborted and will call `isolate->TerminateExecution()` to prevent further execution of JavaScript while leaving the isolate in a good state to run other requests.
This needs to be evaluated very carefully. The approach is a bit of a hack and there might be a better way of doing this that I'm not seeing. So let's not rush this in.

Implement process.exit(...) in the runtime

---

src/node/internal/internal_path.ts

Implement win32 implementations of `node:path` and enables linter.

add node:path win32 implementations

---

src/pyodide/BUILD.bazel

This replaces direct eval in pyodide.asm.js with indirect eval, see comment in the commit.

Remove direct eval in pyodide.asm.js

---

src/pyodide/internal/pool/emscriptenSetup.ts
src/pyodide/internal/python.ts
src/pyodide/python-entrypoint-helper.ts
src/pyodide/types/emscripten.d.ts

Instead, just pass `isWorkerd` and then set up lockfile and indexURL in python.ts

Python pools: Remove lockfile and indexURL arguments from getEmscriptenSettings

---

src/node/internal/process.ts
src/node/internal/util.d.ts
src/workerd/api/node/BUILD.bazel
src/workerd/api/node/tests/process-nodejs-test.js
src/workerd/api/node/tests/process-nodejs-test.wd-test
src/workerd/api/node/util.h

Adds process.platform. This can help us test OS specific code. For example: `node:url`

add process.platform

---

src/cloudflare/internal/workflows-api.ts
types/defines/workflows.d.ts

Basically, we won't get NonRetryableError serialization done properly because we would have to implement our own Error Serializer for this which might not be worth it, at least for launch. Even if we fix this later, it's okay to let users throw a raw NonRetryableError anyway.

Make NonRetryableError non-abstract in types

---

src/workerd/api/sql-test.js
src/workerd/io/BUILD.bazel
src/workerd/io/actor-sqlite.c++
src/workerd/io/actor-sqlite.h

I noticed the test was testing for an "internal error", which is always a bug, and implies that in prod an error would have been logged to Sentry. We can make this throw an application-visible error instead. This also makes the test output look less bad.

SQLite: Make foreign key errors on txn commit visible to app.

---

src/node/internal/internal_errors.ts
src/node/internal/internal_path.ts
src/node/internal/internal_url.ts
src/node/url.ts
src/workerd/api/node/tests/path-test.js
src/workerd/api/node/tests/url-nodejs-test.js
src/workerd/api/node/tests/url-nodejs-test.wd-test

Had to update `node:path` posix implementation to make sure new functions added to `node:url` is implemented correctly. The last remaining part of `node:url` is the legacy_url which I'll open a new pull-request to add it.
Adds:
- `fileURLToPath`
- `pathToFileURL`
- `toPathIfFileURL`

add more functions for node:url

---

types/defines/rpc.d.ts

This makes it explicity that you cannot mutate event or payload in any way, because the changes will be not be persisted across engine lifetimes

feat: make workflow event and payload readonly

---

src/workerd/api/actor-state.c++
src/workerd/api/actor-state.h
src/workerd/io/actor-cache.c++
src/workerd/io/actor-cache.h

This exposes the internal `waitForBookmark` method to JavaScript. We’ll need this in order to implement decent consistency models with SQLite replication.

Add waitForBookmark to DurableObjectStorage

---

src/cloudflare/internal/test/workflows/workflows-api-test.js
src/cloudflare/internal/test/workflows/workflows-mock.js
src/cloudflare/internal/workflows-api.ts
src/cloudflare/internal/workflows.d.ts
types/defines/workflows.d.ts

Not only this allows for a better DX, it allows us to customize and add new fields later without breaking changes.
Supersedes https://github.com/cloudflare/workerd/pull/2881

feat: make create instance api take a single options parameter

---

src/cloudflare/internal/workflows.d.ts
types/defines/workflows.d.ts

Adds `waiting` and `waitingForPause` status to `InstanceStatus` to match UI/Wrangler

feat: add remaining workflow instance status types

---

src/node/internal/internal_errors.ts
src/node/internal/internal_querystring.ts
src/node/querystring.ts
src/workerd/api/node/BUILD.bazel
src/workerd/api/node/tests/querystring-nodejs-test.js
src/workerd/api/node/tests/querystring-nodejs-test.wd-test

`node:querystring` is required to land `require('node:url').Url` and used widely across many applications. It is in our benefit to move this to the runtime and reduce the size of the polyfills.

add node:querystring to workerd

---

src/workerd/server/server.c++
src/workerd/server/server.h
src/workerd/tests/test-fixture.c++

There's no need to have the class implementation in the header file.

Move class impl out of server.h

---

src/workerd/api/hibernatable-web-socket.c++
src/workerd/api/node/diagnostics-channel.c++
src/workerd/api/node/util.c++
src/workerd/api/queue.c++
src/workerd/api/trace.c++
src/workerd/api/worker-rpc.c++
src/workerd/io/io-context.c++
src/workerd/io/io-context.h
src/workerd/io/observer.h
src/workerd/io/trace.c++
src/workerd/io/trace.h
src/workerd/io/worker-entrypoint.c++
src/workerd/io/worker-entrypoint.h
src/workerd/io/worker.c++
src/workerd/server/server.c++
src/workerd/tests/test-fixture.c++
src/workerd/util/own-util.h

We're needlessly refcounting the WorkerTracer to make it available via the IoContext::IncomingRequest when the RequestObserver also has a reference and can be used to get it. Also makes more sense to access WorkerTracer via RequestObserver anyway.

Get the WorkerTracer via RequestObserver

---

src/workerd/io/trace.c++
src/workerd/io/trace.h

Eliminate internal nesting of PipelineTracers. Use the resolved on complete promise to propagate traces up to the parent.
This was originally done as part of the larger PR to introduce streaming traces but makes sense to pull out separately here.

Simplify PipelineTracer

---

.bazelrc
BUILD.bazel
WORKSPACE

I hope to use this in CI in the near future to compile x86 release binaries on Apple Silicon to make this process faster and have access to the latest compiler version. That can be discussed in detail on another issue.

Implement support for macOS Apple Silicon => x86_64 cross compilation

---

build/deps/deps.jsonc
build/deps/gen/dep_ssl.bzl
src/workerd/api/crypto/dh.c++
src/workerd/api/node/tests/crypto_dh-test.js

Follow-up to #2745. After confirming that the few cases where DH inputs that are now rejected by boringssl are not being actively used in production, we can return a proper error for them and update the boringssl version for workerd. With the new version, we're moving 13 months forward. Even if the version used internally is out-of-sync for now, the added checks here ensure that the behavior is the same.
Test cases are updated based on the new behavior.

Roll boringssl

---

src/cloudflare/internal/test/workflows/workflows-api-test.js
src/cloudflare/internal/test/workflows/workflows-mock.js
src/cloudflare/internal/workflows-api.ts
src/cloudflare/internal/workflows.d.ts
types/defines/workflows.d.ts

We're moving `get` to `getById` and `getByName` for instances in Workflow binding

Split Workflow get into getById and getByName

---

src/workerd/api/pyodide/pyodide.h
src/workerd/server/workerd-api.c++
src/workerd/util/autogate.c++
src/workerd/util/autogate.h

So we can roll it out gradually

Add autogate that forces on external python bundle loading

---

src/node/internal/internal_querystring.ts
src/node/internal/internal_url.ts
src/node/internal/legacy_url.ts
src/node/internal/url.d.ts
src/node/url.ts
src/workerd/api/node/BUILD.bazel
src/workerd/api/node/tests/legacy_url-nodejs-test.js
src/workerd/api/node/tests/legacy_url-nodejs-test.wd-test
src/workerd/api/node/url.c++
src/workerd/api/node/url.h

Adds all remaining functionality for removing the requirement of the polyfill from wrangler for `node:url` module. (We can remove the hybrid polyfill). It is important to add the remaining modules because `node:url` is one of the most used modules in the ecosystem.
Here's the functionality implemented:
- Legacy `new Url()` class
- `url.urlToHttpOptions`
- `url.format()`
- `url.parse()`
- `url.resolve()`
- `url.resolveObject()`

add complete node:url implementation

---

src/pyodide/internal/workers.py
src/pyodide/python-entrypoint-helper.ts
src/workerd/server/tests/python/BUILD.bazel
src/workerd/server/tests/python/sdk/mock.py
src/workerd/server/tests/python/sdk/sdk.wd-test
src/workerd/server/tests/python/sdk/worker.py

Implements the beginnings of a Python SDK, an API that makes writing Python Workers easier as it avoids dealing with awkward details of the Pyodide JS FFI. This PR implements the following:
* a new `cloudflare.workers` module which contains the API
* a `fetch` function defined in that module which accepts native Python types like HTTPMethod, it calls into Pyodide's `pyfetch` which offers many other niceties
* a `Response` function which creates a new `Response` instance and accepts native Python types like HTTPStatus
* support for returning a Pyodide FetchResponse from the `on_fetch` handler
* a custom `FetchResponse` which makes it possible to access the JS ReadableStream via `body` (this is often used in examples which rewrite a response). This is probably something we want to upstream …

Implements the start of an SDK for Python Workers.

---

src/workerd/api/trace.c++

Currently, any invocation for a stage generates a trace, even for PipelineLogLevel::NONE. The only difference is that NONE does not attach logs, exceptions, or eventInfo to the trace.
This leads us to see traces with a null event for stages you opted to not get traces from, which we often see when there's a FPW in a pipeline that we did not intend to see.
There are quite a few places throughout this and edgeworker that note that we do this to "keep the request tree contiguous", but from my investigation and chats with other people, these traces are not used for anything other than delivery to trace/tail handlers, i.e. this isn't used to report metrics or billing. So there's no reason to filter these out before delivering traces.
This is of course not as efficient as it could be, as we are …

WC-2707 Only submit non-empty traces to trace workers

---

.bazelrc
.github/workflows/npm-types.yml
.github/workflows/npm.yml
.github/workflows/release.yml
.github/workflows/test.yml
build/ci.bazelrc

[build] Define CI-friendly bazel configuration
The only material change is to add keep_going for all bazel invocations. So far
we bailed out early during the build step of the test action based on concerns
about runs that rebuild V8 not failing fast, but it feels more useful to keep
going to get all of the error messages since V8 rebuilds are rare.
[build] Silence noisy Windows warnings
This makes the Windows build log much smaller.

[build] Define CI-friendly bazel configuration, silence noisy Windows warnings

---

src/workerd/api/hibernatable-web-socket.c++
src/workerd/api/node/diagnostics-channel.c++
src/workerd/api/node/util.c++
src/workerd/api/queue.c++
src/workerd/api/trace.c++
src/workerd/api/worker-rpc.c++
src/workerd/io/io-context.c++
src/workerd/io/io-context.h
src/workerd/io/observer.h
src/workerd/io/trace.c++
src/workerd/io/trace.h
src/workerd/io/worker-entrypoint.c++
src/workerd/io/worker-entrypoint.h
src/workerd/io/worker.c++
src/workerd/server/server.c++
src/workerd/tests/test-fixture.c++
src/workerd/util/own-util.h

Suspect that this broke something internally that wasn't caught by tests. Reverting here and in the internal repo
This reverts commit f2e1730.

Revert "Move kj::Own<WorkerTracer> to kj::Rc<WorkerTracer>"

---

src/workerd/api/url-standard.c++
src/workerd/api/url-standard.h

Add placeholders for `URL.createObjectURL()` and `URL.revokeObjectURL()`
Ref: https://github.com/cloudflare/workerd/issues/2969

add placeholders for createObjectURL()

---

src/workerd/api/actor-state.h

`waitForBookmark` will be part of the public API of read replication, but given that we’re still implementing read replication, this should be behind a flag.
I should have done this in #2923.

Put waitForBookmark behind experimental flag

---

src/workerd/io/compatibility-date.capnp

Add compat flag to enable external Python package loading.

---

src/workerd/jsg/modules.c++

Enables compile cache in workerd.

enable compile cache for faster boots

---

src/workerd/jsg/BUILD.bazel
src/workerd/jsg/compile-cache.c++
src/workerd/jsg/compile-cache.h
src/workerd/jsg/modules.c++

Moves compile cache to it's own file to prepare for precompiling node internals.

move compile_cache to jsg/compile_cache

---

src/workerd/api/eventsource.c++

`kj::getCaughtExceptionAsKj()` can move data out of the caught exception, so rethrowing it can result in exceptions with missing data.
Caught via code audit of a similar problem; don't know if it can manifest as visible behavior, but would presumably appear as JS exceptions becoming opaque internal errors, or as empty error descriptions in logs.

EventSource: avoid rethrowing moved-from exception

---

src/pyodide/internal/python.ts
src/pyodide/internal/snapshot.ts

Right now the validator fails to validate a Python Worker that imports packages when the validator is using the baseline snapshot. This should fix it.

Invalidate Python caches earlier so packages are picked up.

---

src/cloudflare/internal/test/vectorize/vectorize-api-test.js
src/cloudflare/internal/test/vectorize/vectorize-mock.js
src/cloudflare/internal/vectorize-api.ts
src/cloudflare/internal/vectorize.d.ts
types/defines/vectorize.d.ts

Add a new Vectorize operation for Bindings: `queryById()` that allows users to query their index using a vector already present in the index.

VS-284: Add Bindings support for Vectorize queryById operation

---

build/cc_ast_dump.bzl
src/workerd/tools/BUILD.bazel

PR #2991 introduced a regression where the API AST dump did not have access to all the required includes. However, an incomplete AST was still being generated despite the missing include error. Add the missing dependencies so that the correct types are generated and enable pipefail for the ast dump/gzip shell commands so that the cc_ast_dump action fails if there are any errors being reported.

Fail cc_ast_dump when AST dump encounters errors, add missing dependencies to API AST dump

---

.ruff.toml
src/pyodide/internal/workers.py
src/workerd/server/tests/python/sdk/sdk.wd-test
src/workerd/server/tests/python/sdk/server.py
src/workerd/server/tests/python/sdk/worker.py

The FormData API does not have a native Python equivalent, but it is a very useful API in Workers. This PR implements it and ties it into the Response API implementation.

Implements more methods on Python Response API and adds FormData API.

---

.github/workflows/release-python-runtime.yml
src/pyodide/upload_bundle.py

This adds a github action that makes the Pyodide capnproto binary bundle and
uploads it to r2.

Add gha to upload Pyodide javascript bundle to R2

---

src/node/util/types.ts
src/workerd/api/node/tests/util-nodejs-test.js

Similar to https://github.com/cloudflare/workerd/pull/3015, we need to add named exports for `node:util/types`

fix node:util/types exports

---

src/workerd/io/BUILD.bazel
src/workerd/io/trace-test.c++
src/workerd/io/trace.c++
src/workerd/io/trace.h

The TraceId implementation will be reused for the new streaming tail worker implementation as well as the internal jaeger tracing impl. This moves the implementation out to workerd so it can be used there. A separate internal PR will update uses of TraceId to use this and remove the old internal implementation

Move TraceId implementation to workerd + some cleanups

---

src/workerd/api/sql-test.js
src/workerd/api/sql.c++
src/workerd/api/sql.h
src/workerd/util/sqlite-test.c++
src/workerd/util/sqlite.c++
src/workerd/util/sqlite.h

`sql.exec()` currently parses the query every time it is invoked. This change makes it so that we retain some number of prepared statements in a cache and reuse them, keyed by the query text. Since query strings are likely commonly internalized strings, cache lookups should be O(1) most of the time, as internalized strings compare equal by identity without the need to compare content.

SQLite: Cache prepared statements behind `sql.exec()`.

---

.bazelproject
.gitignore

Adds a `.bazelproject` file to make it easier for Intellij users to develop workerd.

add .bazelproject to workerd

---

build/wpt_test.bzl
src/workerd/api/wpt/url-test.js
src/wpt/harness.js

Adds the following features to the test harness:
- A single `run` entry point
- An `expectedFailures` option to document which tests we know aren't working yet
- A `skippedTests` option for tests that would make workerd crash
- A `verbose` option to print subtests before they are run.
Implements more WPT assertion/test functions:
- subsetTestByKey
- promise_test (probably still needs further improvements)
- assert_not_equals
- assert_true / assert_falwse
- assert_array_equals
- assert_throws_js
Integrates the following WPT tests:
- Basically the issue here is sorting between a ligature and an emoji

WPT: Add remaining url tests

---

src/workerd/api/sockets.c++

As discovered by clang-tidy `clang-analyzer-cplusplus.Move`.

Fix minor Use-After-Move in sockets API

---

src/wpt/harness.js

Remember kids, just say no to byte-order marks and surrogate pairs.

WPT: Replace invalid characters in test names

---

src/workerd/jsg/jsg.h
src/workerd/jsg/promise.h

Exceptions caught in `v8::TryCatch` scopes need to be rethrown in order for the next try/catch handler down the stack to be notified of them. In some code paths, we rethrow the native `jsg::JsExceptionThrown` exception but don't rethrow the v8 exception using `v8::TryCatch::ReThrow()`.
This commit fixes one such code path which resulted in `IoContext::runImpl`'s `jsg::JsExceptionThrown`'s catch block finding that the corresponding `v8::TryCatch` object hadn't been notified of the termination (and didn't contain an exception).

Fix handling of termination exceptions.

---

src/workerd/io/actor-sqlite-test.c++
src/workerd/io/actor-sqlite.c++

And also fix a potential issue with alarm exception propagation.
Should address https://github.com/cloudflare/workerd/issues/2993
---
* SRS actors: Ensure that deleteAll() always has a commit scheduled during reset
...particularly, in the case where an alarm is set.  Should fix errors seen when calling deleteAll() during an alarm handler.
* SRS actors: Don't attempt alarm deletion at end of handler if the output gate is already broken
May fix cases where a broken output gate could cause an exception to propagate beyond the regular alarm output gate handling.

Sqlite-backed DOs: Allow calling deleteAll() inside an alarm handler
