cloudflare/workerd

src/workerd/api/kv.c++, src/workerd/api/r2-admin.c++, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++
- This allows adding initial tags for KV and R2. Also add lw:top_level_execution span.
=> [o11y] Add convenience functions to add span tags for subrequest

build/wd_rust_binary.bzl, build/wd_rust_crate.bzl
needed for better ew compatibility. Doesn't seem to work on windows at all.
=> [rust] use experimental_use_cc_common_link everywhere but windows

build/wd_rust_binary.bzl, build/wd_rust_crate.bzl, compile_flags.txt, src/rust/cxx-integration-test/cxx-rust-integration-test.c++, src/rust/cxx-integration-test/lib.rs, src/rust/cxx-integration/lib.rs, src/rust/gen-compile-cache/cxx-bridge.c++, src/rust/gen-compile-cache/main.rs, src/workerd/server/workerd.c++
This will allow us to have same crate names (cxx-integration) and not to confuse compiler regarding which one is used.
=> [rust] publishing cxx bridge includes with workerd/ prefix

.github/workflows/test.yml, build/ci.bazelrc
I need to run bazel in lint job, but current setup makes it difficult to reuse settings
=> use ci.bazelrc to drive platform-dependent configuration

src/workerd/io/worker-interface.h
This is a new WorkerInterface class that will be used in the internal PR, see comments to understand what it does.
=> Add LazyWorkerInterface

WORKSPACE, patches/sqlite/0001-row-counts-plain.patch, patches/sqlite/README.md
For the checksum, HTTP archive uses SHA2-256 whereas the SQLite downloads page uses SHA3-256. I manually verified the checksum: 
```
openssl dgst -sha3-256 sqlite-src-3470000.zip
SHA3-256(sqlite-src-3470000.zip)= 91d37d50fc6f6dba05dc4f595368f00da922f0c0859f5efc86d45bdc709690e3
openssl dgst -sha256 sqlite-src-3470000.zip
SHA2-256(sqlite-src-3470000.zip)= f59c349bedb470203586a6b6d10adb35f2afefa49f91e55a672a36a09a8fedf7
```
=> Update SQLite to version 3.47

src/cloudflare/internal/vectorize.d.ts, types/defines/vectorize.d.ts
Fix the typo in the field `vectorsCount`, and replace it with `vectorCount` in the Vectorize V2 Describe response type.
=> [Vectorize] Fix field name for Vectorize describe operation

WORKSPACE, tools/cross/format.py
Adds a few features to format.py that improve compatibility with the internal repo:
- Adds `excludes` to the config, listing directories that should not be formatted
- Uses `bazel build` instead of `bazel fetch`, so that bazel creates some symlinks the internal repo expects to exist.
- Fixes a mistake in the filegroup config for formatters distributed as a `http_archive`
=> format.py: Use bazel build, support excludes

src/rust/cxx-integration/lib.rs, src/rust/cxx-integration/tokio.rs
EW has more complicated setup process and needs to initialize tokio within sbox.
=> [rust] expose init_tokio

justfile
it is way faster than the rest of the format, why should I suffer? :)
=> [nfc] add rustfmt convenience target

src/workerd/io/worker.c++, src/workerd/io/worker.h
Currently Worker::Isolate::Impl does the setup of the context. Namely setting up the console and WebAssembly.Module@@HasInstance. This functionality is useful in general to any context we might create even before we have a Worker::Isolate.
This commit moves this functionality to a publicly facing api.
Another part split from #2936
=> Export setupContext publically to be used by additional contexts.

.github/workflows/test.yml, build/ci.bazelrc
after ci.bazelrc move minimal downloads started to apply to release builds too, which is not what we want.
Sorry for inconvenience @fhanau
=> [nfc] always download outputs in release builds

.bazelrc, .github/workflows/release.yml
Follow-up to #2958, where we added and tested cross-compilation support. This allows us to use Xcode 16 to compile the Intel Mac binary (macos-15 is Apple Silicon-based, macos-13 only has Xcode 15 available) and take advantage of the faster M1-based runners.
- Don't set minimum macOS version for host configuration, host tools are only needed during the build and do not need to be distributed beyond that. This fixes a misleading warning.
==============
Should save some precious macOS runner time. In a follow-up, we will also compile the macOS arm64 binary on GitHub CI, and eventually the Linux arm64 binary. Then all release binaries will be compiled here and we'll be able to automate the NPM publish and NPM types jobs so that releases are fully automated.
=> [CI] Cross-compile Intel Mac release binary

.github/workflows/release.yml
This is needed now that we cross-compile from an Apple Silicon image.
=============
The problem here is that with #3078 the x64 macOS release artifact continues to be a valid x64 binary, but is uploaded as `macOS-ARM64-binary`, which prevents it from being added to tagged releases.
=> [CI] Set right architecture for x64 macOS release artifact

src/node/crypto.ts, src/node/internal/crypto_keys.ts
See https://github.com/cloudflare/workerd/issues/3009
/cc @jasnell
=> [crypto] Clarify the status of crypto keys APIs

src/workerd/io/BUILD.bazel, src/workerd/server/tests/python/BUILD.bazel, src/workerd/util/BUILD.bazel
io-channels.h has a circular dependency with io due to its dependency on io-util.h (parsing the header using bazel is expected to fail accordingly). This means any source file depending on it would need to be in a bazel target depending on io to avoid missing header errors, even if the source file doesn't use io itself. Move it back into io in accordance with IWYU.
\- Fix dependencies for io:actor-id, util:duration-exceeded-logger
\- Fix duration-exceeded-logger.h appearing in two targets
=> [build] Move io-channels.h back into io target

src/workerd/api/sockets.c++, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/trace.h
- Use more descriptive name for IOContext function
=> [o11y] Add rudimentary user tracing support for connect()

src/workerd/api/blob.c++, src/workerd/api/blob.h
Avoid use of the `kj::Array<kj::byte>` type wrapping entirely for reads (`arrayBuffer()` as well as `bytes()`)
=> Have Blob use BufferSource for arrayBuffer() also

build/config/BUILD.bazel, build/wd_js_bundle.bzl, build/wd_ts_bundle.bzl, src/node/BUILD.bazel, src/workerd/jsg/modules.capnp
Extracted from #3004, not used on load yet.
downstream pr 9121
=> add compile cache support to wd_?s_bundle, enable for node

src/workerd/api/blob.c++, src/workerd/api/blob.h, src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/r2-bucket.c++, src/workerd/api/r2-bucket.h, src/workerd/api/streams/common.h, src/workerd/api/streams/internal.c++, src/workerd/api/streams/internal.h, src/workerd/api/streams/standard-test.c++, src/workerd/api/streams/standard.c++, src/workerd/jsg/buffersource.h
Have the streams `readAllBytes(...)` API use `jsg::BufferSource` instead of the `kj::Array<kj::byte>` type binding.
=> Update streams readAllBytes impl to use BufferSource

src/workerd/api/global-scope.c++, src/workerd/api/node/module.c++, src/workerd/api/node/tests/module-create-require-test.js, src/workerd/api/node/tests/module-create-require-test.wd-test, src/workerd/api/node/util.c++, src/workerd/api/tests/new-module-registry-test.js, src/workerd/io/compatibility-date.capnp, src/workerd/io/worker.c++, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h, src/workerd/jsg/setup.h
~~Currently, the top level scope of a Worker script and modules that are imported may use top level await. However, because we restrict the use of i/o in the top level scope, the only thing that can be awaited at the top level scope is a dynamic import, which we require to be resolved synchronously. It is a bit nonsensical to support synchronously resolved dynamic imports at the top level when we can just use static imports more effectively. Additionally, the ecosystem and runtimes are moving to a state where top level await in modules is being strongly discouraged. This compat flag. This compatibility flag will make it impossible to use top level await.~~
(made the change with lots of distractions so keeping as a draft until I can do a second pass to make sure nothing was missed) …
=> Disable top-level await in require with a compat flag

src/pyodide/internal/workers.py, src/workerd/server/tests/python/sdk/server.py, src/workerd/server/tests/python/sdk/worker.py
The big change here is the addition of the Blob API. But there are also some other improvements/fixes:
* Each class instance now exposes a `js_object` property which returns its underlying JS object.
* The FormData API is now compatible with the multidict package's API
* The FormData API can now accept Blobs and returns the Python Blobs too
```
$ bazel run @workerd//src/workerd/server/tests/python:sdk/sdk
```
=> Implements JS Blob API in Python SDK

src/workerd/jsg/BUILD.bazel, src/workerd/jsg/jsg-test.h, src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h, src/workerd/jsg/resource-test.c++, src/workerd/server/workerd-api.c++, src/workerd/util/autogate.c++, src/workerd/util/autogate.h
Enables compile cache behind an autogate flag.
=> enable built-in compile cache behind autogate

src/workerd/api/cache.h, src/workerd/api/global-scope.h, src/workerd/api/http.h, types/test/types/rpc.ts
Fixes https://github.com/cloudflare/workerd/issues/3090
To improve the typing situation when loading dom types in the same environment as workers-types, this PR moves the `URL` type out of `RequestInfo`, in favour of e.g. `fetch()` referencing `fetch(req: RequestInfo | URL)` directly. This matches how dom types are defined.
There should be no user-observable behaviour change for users using just workers-types, but this should improve the situation if e.g. the fetch definition comes from workers-types but the `RequestInfo` definition comes from dom types.
=> Move `URL` out of `RequestInfo` to match DOM types

src/workerd/jsg/modules.h, src/workerd/server/workerd-api.c++
We can use `addBuiltinModule<T>(spec, type)` to add a builtin module, but it imposes the restriction that the instance of `T` we want needs to be made with a zero argument constructor. In a lot of use cases, we want to create it with a static method or a constructor that takes args. So this adds a new overload that takes the object we want to use as the builtinModule. The original version is then implemented in terms of the new version.
=> Add addBuiltinModule from an instance of a template type

.github/workflows/release.yml
These binaries are not added to releases yet, in case the new configuration doesn't work out of the box. Later this will be used to replace the internal Apple Silicon build.
=> [CI] Build release binaries for Apple Silicon

.bazelrc, .github/workflows/release.yml
We now have two separate macOS release builds, but the macOS-cross setup got applied to all release jobs, apparently due to a malformed if condition. Avoid having such a condition entirely.
=> [CI] Fix architecture for macOS releases

.github/workflows/release.yml, README.md
With #3135 Apple Silicon release artifacts are being created properly, add them to tagged releases too.
Xcode 16 appears to be required to build V8 starting with the 13.1 release, update the README to reflect this.
=> [CI] Use GitHub Actions-based binary for Apple Silicon releases

samples/pyodide-fastapi/config.capnp, samples/pyodide-langchain/config.capnp, samples/pyodide-secret/config.capnp, samples/pyodide/config.capnp, samples/repl-server-python/config.capnp, src/cloudflare/internal/test/ai/BUILD.bazel, src/cloudflare/internal/test/ai/python-ai-api-test.wd-test, src/cloudflare/internal/test/d1/BUILD.bazel, src/cloudflare/internal/test/d1/python-d1-api-test.wd-test, src/cloudflare/internal/test/vectorize/BUILD.bazel, src/cloudflare/internal/test/vectorize/python-vectorize-api-test.wd-test, src/workerd/api/BUILD.bazel, src/workerd/api/pyodide/pyodide.h, src/workerd/io/compatibility-date.capnp, src/workerd/server/tests/python/BUILD.bazel, src/workerd/server/tests/python/env-param/env.wd-test, src/workerd/server/tests/python/hello/hello.wd-test, src/workerd/server/tests/python/import_tests.bzl, src/workerd/server/tests/python/py_wd_test.bzl, src/workerd/server/tests/python/random/random.wd-test, src/workerd/server/tests/python/sdk/sdk.wd-test, src/workerd/server/tests/python/subdirectory/subdirectory.wd-test, src/workerd/server/workerd-api.c++, src/workerd/util/autogate.c++, src/workerd/util/autogate.h
Now that we've rolled out the code to use the external bundle, we don't need the builtin bundle anymore.
=> Remove code for Pyodide builtin bundle

src/workerd/util/sqlite.c++
Adds `substring` as an allowed function, which just aliases to `substr`. I ran into this when testing some SQLite queries locally and then porting them to D1.
> "substring()" is an alias for "substr()" beginning with SQLite version 3.34.
https://www.sqlite.org/lang_corefunc.html#substr
=> Add substring (alias of substr) into ALLOWED_SQLITE_FUNCTIONS

src/workerd/api/crypto/aes-test.c++, src/workerd/api/crypto/aes.c++, src/workerd/api/crypto/crypto.c++, src/workerd/api/crypto/crypto.h, src/workerd/api/crypto/digest.c++, src/workerd/api/crypto/digest.h, src/workerd/api/crypto/ec.c++, src/workerd/api/crypto/ec.h, src/workerd/api/crypto/hkdf.c++, src/workerd/api/crypto/impl.c++, src/workerd/api/crypto/impl.h, src/workerd/api/crypto/kdf.h, src/workerd/api/crypto/keys.c++, src/workerd/api/crypto/keys.h, src/workerd/api/crypto/pbkdf2.c++, src/workerd/api/crypto/rsa.c++, src/workerd/api/crypto/rsa.h, src/workerd/api/crypto/scrypt.c++, src/workerd/api/node/crypto-keys.c++, src/workerd/api/node/crypto.c++, src/workerd/api/node/crypto.h
... ensures that all ArrayBuffer instances are using BufferSource rather than external allocations.
=> Ensure that crypto allocations are using BufferSource

src/workerd/io/BUILD.bazel, src/workerd/io/trace-test.c++, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/worker-interface.capnp
This implements the `InvocationSpanContext` class. This type holds a tuple of trace ID, invocation ID, and span ID and will be used in support for the updated streaming tail workers implementation. The basic idea is that every top-level request receives a trace ID which is shared across every invocation the occurs within that request. Every individual invocation has a unique invocation ID, and every span within that invocation receives a monotonically increasing span ID.
While this PR does not currently introduce uses of this type, the idea is for all invocations to always have a root `InvocationSpanContext` and for every child user span created to branch off this root. The current user span then would always have a current `InvocationSpanContext` that would be propagated outward for all …
=> Implement InvocationSpanContext for user tracing / streaming tail workers

src/workerd/io/actor-sqlite-test.c++, src/workerd/io/actor-sqlite.c++
In the case where an SRS actor receives a request to run the alarm handler, and the alarm state is "clean" (i.e. both the local and last-known durably persisted DB state match), and that alarm state is empty, tell the scheduler to unschedule the alarm before cancelling.
Should allow the system to clean up old alarm scheduler entries where the scheduler state is out-of-sync due to a failure occuring between when an alarm deletion is durably persisted and when the scheduler is informed of the alarm deletion.
We already reschedule alarms in the case where a runAlarm request has an earlier time than the "clean" alarm state, but we were avoiding rescheduling in the case where the clean alarm state was empty, under the assumption that returning a CancelAlarmHandler result would be sufficient to …
=> sqlite-backed DOs: Also reschedule alarm requests when persisted alarm has been cleared

src/workerd/io/worker.c++
Let's use a non-deprecated version of the GetCreationContext()
Ref:
```
GetCreationContext is deprecated: Use the version with the isolate argument
```
=> use non-deprecated GetCreationContext()

src/workerd/api/hibernatable-web-socket.c++, src/workerd/api/queue.c++, src/workerd/api/trace.c++, src/workerd/api/trace.h, src/workerd/api/worker-rpc.c++, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/worker-entrypoint.c++, src/workerd/server/server.c++
These will be reused by the streaming Trace implementation that does not use the Trace class. Separate them out.
No functional changes here beyond marking the class as final and deprecating the aliases.
=> Move tracing info types out of Trace class

src/workerd/io/trace.h
Once the internal repo has been updated these can be removed. Not landing this until the internal PR has been landed.
=> Remove deprecated aliases on workerd::Trace

src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker-entrypoint.h, src/workerd/tests/test-fixture.c++
@fhanau ... please consider this one carefully. What I'm not sure about is whether the `InvocationSpanContext` should be held by the `IncomingRequest` or something internal to the `RequestObserver`.
Eventually I'd like to abstract out the `WorkerTracer` here and actually hide that inside the `RequestObserver` and put it entirely behind `SpanBuilder` but that'll come later. Accordingly, however, I don't want to put `InvocationSpanContext` inside the `WorkerTracer`.
The other thing to keep in mind is that we'll need to be able to propagate the `InvocationSpanContext` across subrequests of various kinds so we'll need easy access to it to place it into things like the control header.
How is this expected to be used? Good question! When streaming tail workers is fully operational, the …
=> Create and assign an InvocationSpanContext for every invocation

src/workerd/api/streams/internal.c++
This should at least handle @mrbbot's original repro here: https://github.com/cloudflare/workerd/issues/992
Need to determine if there are other issues given the other comments in that thread. They appear to be unrelated but the examples given are not clear enough to make a proper repro
=> No need to throw when closing a WritableStream that's already closing

src/workerd/api/wpt/url-test.js, src/wpt/harness.js
Previously, our assertion functions were wrong. This PR fixes and adds the failed tests to expected failures list.
=> fix WPT test harness

src/workerd/api/streams/standard.c++, src/workerd/io/compatibility-date.capnp
The TransformStream would originally start with backpressure enabled as it is supposed to but we failed to reapply backpressure when items were enqueued. This meant that after the first write to the TransformStream, no backpressure signaling would occur. Doh! This fixes it.
Unfortunately a compat flag is necessary because suddenly enforcing backpressure correctly could break existing workers that failed to realize it was broken. I noticed this because making the change broke one of our tests.
```
async fetch(req, env, ctx) {
async function sleep(ns) {
await new Promise((res) => setTimeout(res, ns));
}
const strategy = new ByteLengthQueuingStrategy({ highWaterMark: 2024 });
const { writable, readable } = new TransformStream(undefined, strategy);
let writes = 0, reads = 0; …
```
=> Fixup TransformStream backpressure

src/workerd/jsg/BUILD.bazel, src/workerd/jsg/modules.c++, src/workerd/jsg/resource-test.c++, src/workerd/util/autogate.c++, src/workerd/util/autogate.h
Since we rolled out the compile cache to RoW, let's remove it from our codebase.
=> remove autogates for compile cache

src/node/dns.ts, src/node/internal/dns.d.ts, src/workerd/api/node/BUILD.bazel, src/workerd/api/node/dns.c++, src/workerd/api/node/dns.h, src/workerd/api/node/node.h, src/workerd/api/node/tests/dns-nodejs-test.js, src/workerd/api/node/tests/dns-nodejs-test.wd-test
Implements a stub implementation for `node:dns`. Remember that there is still `node:dns/promises` that needs to be stubbed. 
Small note: I'm in the process of investigating fully implementing node:dns in the short term.
=> add stub implementation for node:dns

src/workerd/api/url-standard.c++, src/workerd/api/url-standard.h, src/workerd/api/wpt/url-test.js, src/wpt/harness.js
We were not following the spec in this particular example. Setting a href should throw an error if the input is not a valid URL. The corresponding WPT is now passing.
=> make sure href setter throws if invalid

src/workerd/api/BUILD.bazel, src/workerd/api/r2-api.capnp, src/workerd/api/r2-bucket.c++, src/workerd/api/r2-bucket.h, src/workerd/api/r2-multipart.c++, src/workerd/api/r2-multipart.h, src/workerd/api/r2-test.js, src/workerd/api/r2.h
Give R2 Bindings support for creating/interacting with *SSE-C* encrypted objects.
Tests run on branch `mikkel/R2-2317`. Please merge once feature lands
=> R2-2317 add support for SSE-C via `workerd` bindings

.bazelrc, src/cloudflare/internal/test/ai/BUILD.bazel, src/cloudflare/internal/test/d1/BUILD.bazel, src/cloudflare/internal/test/vectorize/BUILD.bazel, src/pyodide/internal/python.ts, src/pyodide/internal/setupPackages.ts, src/pyodide/internal/snapshot.ts, src/pyodide/internal/tar.ts, src/pyodide/python-entrypoint-helper.ts, src/pyodide/types/FS.d.ts, src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h, src/workerd/server/workerd-api.c++
Moves package loading to `prepareWasmLinearMemory` so that `preloadDynamicLibs` can use the loaded packages instead of the embedded ones.
Also fixes a stack-use-after-scope error in `getPyodidePackage`
```
$ bazel test @workerd//src/cloudflare/internal/test/... --config=asan
```
=> Implements support for external package loading in validator.

src/cloudflare/internal/test/aig/BUILD.bazel
This is needed following #3140, #3166 adds a new python test which also needs the tag.
=> [build] Add missing no-asan tag

src/workerd/api/global-scope.c++
We have some overloaded exceptions that are set as `EXCEPTION_IS_USER_ERROR`. These errors should be reported back to the alarm-manager as user errors, but some are being reported as internal errors.
This PR adds additional logging and does a hackish check to enforce that `broken.exceededMemory` errors during the alarm execution are treated as user errors.
=> Log outputGate broken shouldRetryCountsAgainstLimits for alarms

src/cloudflare/internal/workflows.d.ts, types/defines/workflows.d.ts
Improves types usability, instead of writing
```ts
type Env {
MY_WORKFLOW: Workflow;
}
// ... some logic in other file
env.MY_WORKFLOW.create({
params: {
some_param: 1
} as MyWorkflowParams
});
```
We could do something like
```ts
type Env {
MY_WORKFLOW: Workflow<MyWorkflowParams>;
}
// ... some logic in other file
env.MY_WORKFLOW.create({
params: {
some_param: 1
}
});
```
=> feat: workflow types support generic params

types/defines/rpc.d.ts
Previously, both types were specified as a string, which is not intended behavior. We only allow for a specific formatted string - same as `WorkflowSleepDuration`.
I've added `WorkflowTimeoutDuration` and `WorkflowDelayDuration` for better DX in the types by reducing confusion (otherwise you would see a `WorkflowSleepDuration` in a timeout field) - also gives us flexibility if we need to separate them later.
While this could be a breaking change in the types, we already validate it at runtime, so there are no worries here.
=> feat: better define step retry delay and step timeout types

samples/tail-workers/config.capnp, src/workerd/server/server-test.c++, src/workerd/server/server.c++, src/workerd/server/workerd.capnp
This fixes some issues from #3021, which I noticed while working on something unrelated.
The third commit is more of a suggestion. Do we think anyone is using `logging` yet? If so, maybe I should drop this commit. If not, maybe I should change the commit to actually remove `logging` in favor of the simpler flat array which I've named `tails`... let me know.
=> Improve tail worker support

.github/workflows/type-snapshot.yml, types/defines/d1.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
=> Add snapshot check for workers-types

WORKSPACE, patches/v8/0020-Add-another-slot-in-the-isolate-for-embedder.patch, src/workerd/io/worker.c++, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/setup.c++, src/workerd/jsg/setup.h, src/workerd/jsg/type-wrapper.h, src/workerd/jsg/util.c++, src/workerd/jsg/wrappable.c++
I want to use this to call madvise just before a crash so the V8 heap
for the crashing isolate is part of the core dump.
=> Add API to set and get the V8 cage base address

.github/workflows/type-snapshot.yml, src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/url-standard.h, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts
Fix https://github.com/cloudflare/workerd/issues/3066
=> Add missing api::url::URLSearchParams in Body::Initializer.

src/workerd/io/trace-test.c++, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/worker-interface.capnp
In the streaming tail worker design discussion it was decided that span IDs will follow the otel pattern and will be random 64-bit rather than monotonically increasing counter.
=> Make spanId a random 64-bit rather than using a counter

src/workerd/util/sqlite.h
As per https://www.sqlite.org/walformat.html#wal_locks, SQLite uses 5 locks starting 3 bytes into the locks section of the shared memory file.
=> Add constants for WAL-mode READ locks

WORKSPACE, patches/v8/0021-Add-ValueSerializer-SetTreatProxiesAsHostObjects.patch, src/workerd/api/tests/js-rpc-test.js, src/workerd/api/worker-rpc.c++, src/workerd/api/worker-rpc.h, src/workerd/jsg/jsg.h, src/workerd/jsg/jsvalue.h, src/workerd/jsg/ser.c++, src/workerd/jsg/ser.h, src/workerd/jsg/setup.h
When serializing a value for RPC, if we encounter a `Proxy`, we will check if it claims to be an instance of `RpcTarget` (via the prototype chain) and, if so, treat it as one, wrapping it in a stub with the same semantics as an actual `RpcTarget`.
Additionally, if the `Proxy` claims to be a plain object (the prototype is `Object.prototype`), we will allow this too, wrapping it in a stub that allows access to the object's "own" properties. This is not exactly the same thing as we'd do if it were really a raw object: in that case, we would actually send the object content. However, it is consistent with our access control model, which says that for plain objects, "own" properties are exposed, but for `RpcTarget` instances, only prototype properties are exposed.
A `Proxy` can even be used to …
=> JSRPC: Allow wrapping RPC targets in Proxy objects.

src/cloudflare/ai.ts, src/cloudflare/internal/ai-api.ts, src/cloudflare/internal/aig-api.ts, src/cloudflare/internal/test/aig/aig-api-test.js, src/cloudflare/internal/test/aig/aig-mock.js, types/defines/aig.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
This pr adds a new .run method to ai gateway
Example usage:
```ts
const resp = await env.AI.gateway('my-gateway').run({
provider: 'workers-ai',
endpoint: '@cf/meta/llama-3.1-8b-instruct',
headers: {
Authorization: 'Bearer abcde',
'Content-Type': 'application/json',
'cf-aig-metadata': { user: 123 },
'cf-aig-custom-cost': { total_cost: 1.22 },
'cf-aig-skip-cache': false,
'cf-aig-cache-ttl': 123,
},
query: {
prompt: 'What is Cloudflare?',
},
});
```
=> Add AI Gateway universal run method

src/workerd/api/streams/standard.h
Previously we used std::deque but this has a large memory footprint when empty in practice. Using std::list optimizes memory for the common case of a lot of WritableStreams with empty queues.
=> Use std::list for WritableImpl::writeRequests.

src/workerd/api/trace.c++, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/trace-test.c++, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker-entrypoint.h, src/workerd/io/worker-interface.capnp
Largely preparation for the bigger implementation piece. Getting the basic types implemented.
~~I likely won't land this immediately even with sign offs. Want to progress the design a bit more first. But this lays groundwork.~~ This should be ready to land
Internal discussion: https://wiki.cfdata.org/display/~jsnell/Tail+Workers+2%3A+Streaming+Trace (sorry for those of you following along that don't have access to this)
=> Add basic new streaming tail worker types

src/workerd/api/sockets.c++
This is already covered through the getClient() call below.
CC @zebp
=> Drop duplicate "connect" user tracing span

BUILD.bazel, build/deps/gen/dep_aspect_rules_ts.bzl, build/wd_ts_project.bzl, src/workerd/server/tests/BUILD.bazel, src/workerd/server/tests/inspector/BUILD.bazel, src/workerd/server/tests/inspector/driver.mjs
- Update rules_ts
- Remove TODO to enable Bazel worker protocol for transpiling. This is no longer supported with TS 5.x.
- Elide npm_package for server tests, this should only be used for actual NPM packages. One instance (for type-related tests) remains, but that's more difficult to remove cleanly.
=> [build] TS cleanup

src/workerd/api/actor.h, types/defines/rpc.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts, types/test/types/rpc.ts
The runtime passes in this parameter when invoking alarm(); the `retryCount` property gives a count of the number of previous times the runtime has tried to run this specific alarm event.
The runtime has been passing this parameter to `alarm()` calls since it was originally introduced earlier in the year, in PR #1673, but the parameter declaration has not yet been added to the worker-types TypeScript declarations.  This PR just updates the TypeScript declarations to include this parameter.
=> Add optional AlarmInvocationInfo parameter to Durable Object alarm() method

src/workerd/api/streams/common.c++, src/workerd/api/streams/common.h, src/workerd/api/streams/internal.c++, src/workerd/api/streams/internal.h, src/workerd/api/streams/standard.c++, src/workerd/api/streams/standard.h
Make WritableStream controllers' `maybePendingAbort` members heap-allocated to reduce WritableStream's memory footprint when no abort is pending.
Reduces the footprint by a further ~100 bytes.
=> Moar WritableStream memory optimization

src/workerd/server/server-test.c++, src/workerd/server/server.c++
Say you have a module-syntax Worker that has no `export default`. You then refer to that worker from elsewhere in the workerd config, but you do not specify an entrypoint. What should happen?
In the midst of other changes, PR #3193 turned this into an error, becaues it seemed like obviously it should be. This turns out to have broken Miniflare tests, which often use an empty string as a placeholder Worker that is referenced but never invoked.
So, this PR restores the old behavior.
It turns out, incidentally, that the old behavior is crazier than you'd imagine. See the comments in the test case for details.
=> Undo tightening of rules around default entrypoints in #3193.

types/defines/rpc.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/oldest/index.d.ts
This will allow users to get the instance id directly (without passing it to the event payload itself) - allows users to make instances more observable, allows users to create better globally unique keys (for APIs, or external storage) and so on...
=> feat: add instanceId to the Workflow event type

src/workerd/api/trace.c++, src/workerd/api/trace.h, src/workerd/io/BUILD.bazel, src/workerd/io/compatibility-date.capnp, src/workerd/io/trace.c++, src/workerd/io/trace.capnp, src/workerd/io/trace.h, src/workerd/io/worker-interface.capnp, src/workerd/io/worker.c++, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts
#3177 should land before this (listed as the first comment here). Also see the corresponding upstream PR.
=> [o11y] Provide OTel-compatible user span representation in trace

src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/setup-emscripten.c++, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/setup.c++, src/workerd/jsg/setup.h, src/workerd/server/tests/python/hello/worker.py
This enables JSPI in Python workers. It will not be usable until we also update to the newer Pyodide runtime.
=> Enable JSPI in Python workers

types/defines/ai.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
With growing a growing list of supported models and their capabilities, we are making it simpler to infer input/output types from model names.
From users perspective, they will still be able to call `AI.run("<model-name>", {<inputs>}, {<options>})`, but we are modifying the type definitions to make it easier for future updates.
=> Introducing better Workers AI types

src/cloudflare/internal/ai-api.ts, src/cloudflare/internal/test/ai/ai-api-test.js
Add `lastRequestHttpStatusCode`, `lastRequestInternalStatusCode` to the AI binding.
=> Add http and internal codes to AI Binding

deps/rust/cargo.bzl, src/workerd/api/html-rewriter.c++, src/workerd/api/html-rewriter.h, src/workerd/api/tests/htmlrewriter-test.js, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
lol-html allows you to insert replacement values in various places in a HTML stream. Previously, these replacement values were always strings. However, recently lol-html added support for _streaming_ replacements in https://github.com/cloudflare/lol-html/pull/229. lol-html requires the streams to produce valid UTF-8 data, but it may be written in arbitrary length chunks (even partial UTF-8 characters).
This PR adds support for replacement values that are `ReadableStream`s or `Response`s.
=> html-rewriter: Support streaming content replacements

build/ci.bazelrc
This partially reverts #3203 – python tests still run across platforms, but they are simply too slow for the debug job.
=> [ci] Do not run Python tests for debug CI jobs

src/workerd/api/node/buffer-string-search.h, src/workerd/jsg/BUILD.bazel, src/workerd/util/BUILD.bazel
capnp PR: https://github.com/capnproto/capnproto/pull/2207
Header parsing will be part of the downstream lint checks, I hope to add it to the workerd lint job in a follow-up PR too.
=> [build] Add support for Bazel header parsing

src/workerd/api/http-test-ts.ts, src/workerd/api/http-test-ts.ts-wd-test, src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/io/compatibility-date.capnp
First part of `cache: no-cache` implementation:
- Work-shopping the test infrastructure in workerd.
- Allow no-cache construction
- Update typescript information
Note that the actual implementation is incompelete.
=> Enable cache: no-cache compat flag and enum

types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts
Should fix type issues from #3195.
=> Add types for no-cache

.github/workflows/release.yml, .github/workflows/test.yml
Based on limited testing, Bazel starts up and computes the repo mapping much faster on the windows-2025 (perhaps no longer bottlenecked on I/O?), which should speed up I/O as a whole. The new runner is considered "beta" quality (see announcement https://github.com/actions/runner-images/issues/11228), but unfortunately the Windows runner is rather unstable in general so I see little risk of having more instability from this.
=> [ci] Update Windows runner to Server 2025

types/defines/rpc.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/oldest/index.d.ts
Previously we didn't export the constructor for `WorkflowEntrypoint` in TS types (we always had one in the workerd implementation itself) even though other classes like `DurableObject` or `WorkerEntrypoint` also do it. This makes constructor types in `WorkflowEntrypoint` on par with those two.
=> fix: properly expose `WorkflowEntrypoint` constructor in TS types

src/workerd/api/streams/compression.c++, src/workerd/api/streams/internal.h, src/workerd/api/streams/queue.h
API implementation objects.
A very common use case is to create one or more stream API objects per request. These streams currently have a high native memory overhead even when they are empty. Switching to std::list (which doesn't pre-allocate space for items) significantly alleviates this problem.
For example, now ReadableStreams tend to have <50% of their original memory footprint.
=> Use std::list instead of std::deque for all buffers/queues in streams

src/node/internal/internal_buffer.ts, src/node/internal/internal_utils.ts, src/workerd/api/node/tests/buffer-nodejs-test.js
The behavior of `buffer.toString(encoding)` is not compliant with nodejs API. it throws an error `UNKNOWN_ENCODING: null` (or undefined) because it's being passed as a string "undefined" or "null"
=> fix: Unknown encoding when undefined is used

deps/rust/cargo.bzl, src/workerd/api/html-rewriter.c++, src/workerd/api/html-rewriter.h, src/workerd/api/tests/htmlrewriter-test.js, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
This reverts commit 010d64acbce5aff0f0af3ca69be79cc2c3cc7e2d.
There were two failing test on the internal repo, namely:
- HTMLRewriter disallows ReadableStream replacement content
- HTMLRewriter disallows Response replacement content
However, this is precisely the objective of the original PR.  I'll open a PR in the internal repo to replace these tests. 
Sorry for not thinking to check this the first time I merged.
=> Revert "Revert "html-rewriter: Support streaming content replacement (#3211)""

src/pyodide/internal/workers.py, src/workerd/io/compatibility-date.capnp, src/workerd/server/tests/python/sdk/worker.py
While going through our examples I noticed that these were missing.
=> Implements Response.replace_body and support for cf opts in Py fetch.

src/workerd/jsg/BUILD.bazel, src/workerd/jsg/commonjs.c++, src/workerd/jsg/commonjs.h, src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h
Further cleanup in preparation for finishing the new module registry.
=> Separate commonjs-related types from jsg/modules.h/c++

src/workerd/jsg/commonjs.c++, src/workerd/jsg/commonjs.h
* Remove getProcess/getBuffer since those are exposed as globals now when Node.js compat is enabled.
* Add __filename and __dirname to CommonJsModule in prep to replace/ remove the obsolete NodeJsModule
* Other minor cleanups
=> Further refinement on CommonJS types

src/workerd/api/trace.c++, src/workerd/api/trace.h
These events are so small...
```C++
struct Message final {};
struct Close final {
uint16_t code;
bool wasClean;
};
struct Error final {};
```
That there shouldn't even be any performance penalty to saving them by value rather than by reference.
The nice thing about it is we don't need to save bare references that can easily cause UB or worse (such as a bug we're trying hopelessly to debug atm).
=> Save HibernatableWebSocketEventInfo events by value

.github/workflows/_bazel.yml, .github/workflows/npm-types.yml, .github/workflows/npm.yml, .github/workflows/release-python-runtime.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/type-snapshot.yml, README.md, src/workerd/api/BUILD.bazel
Mainline support for Ubuntu 20.04 ended in September and it is deprecated on GitHub actions starting February 2025. Accordingly, we should build on 22.04 instead, meaning that the two latest LTS releases will continue to be supported. Since 22.04 uses glibc 2.35, the new release will no longer work on systems using a lower glibc version, including Debian Bullseye (mainline support ended in August). Update README.md to reflect this.
CC @penalosa in case this proposed change has any impact on wrangler
=> [ci] Build Linux release binaries on Ubuntu 22.04

.github/workflows/release.yml
We're seeing build failures with the latest MSVC version when optimization is enabled.
Hopefully we can use the 2025 version again once the image is more mature.
=> [ci] Revert release build to windows-2025 runner

src/pyodide/internal/asgi.py
Remove some logs that Mike pointed out, also don't always raise a runtime error and remove fastapi import
=> Clean up to asgi.py

src/pyodide/BUILD.bazel
It unconditionally uses FinalizationRegistry so we need to make a dummy class.
=> Changes for Pyodide 0.27.0

src/pyodide/internal/loadPackage.ts, src/pyodide/internal/metadata.ts, src/pyodide/internal/setupPackages.ts, src/pyodide/internal/snapshot.ts, src/pyodide/types/pyodide-lock.d.ts, src/pyodide/types/runtime-generated/metadata.d.ts, src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h, src/workerd/io/compatibility-date.capnp
Ready for review. Still needs a new bundle generated which I will do after review.
----
Implements changes to use the external package lock (rather than the built-in one) and to fix how we load the stdlib when external package loading is enabled.
=> Fixes to external package loading: use external lock and load stdlib.

package.json, pnpm-lock.yaml, tools/BUILD.bazel, tools/base.eslint.config.mjs, types/eslint.config.mjs
Upon recommendation from @joshuakgoldberg (https://github.com/typescript-eslint/typescript-eslint/issues/10635#issuecomment-2583009860), removing invalid typescript-eslint rule, and removing eslint-prettier-config because it takes too much time running eslint with prettier.
We already have a linter check using `just f` no need to do the same work twice.
PS: This decreases eslint test to 4.1s seconds from 8 on a 88 core machine.
=> remove eslint-prettier-config

src/workerd/api/BUILD.bazel, src/workerd/api/analytics-engine.c++, src/workerd/api/analytics-engine.h, src/workerd/api/global-scope.c++, src/workerd/io/BUILD.bazel, src/workerd/io/features.h, src/workerd/io/io-channels.h, src/workerd/io/io-gate.h, src/workerd/io/io-own.c++, src/workerd/io/io-own.h, src/workerd/io/worker-entrypoint.h, src/workerd/server/alarm-scheduler.c++, src/workerd/util/sqlite.h
Also adds a TODO outlining potential for future modularization.
=> [build] Modularize frankenbuild.c++, assorted include cleanup

build/wpt_test.bzl, src/workerd/api/wpt/url-test.js, src/workerd/api/wpt/urlpattern-test.js, src/wpt/BUILD.bazel, src/wpt/eslint.config.mjs, src/wpt/harness.ts, src/wpt/tsconfig.json
Converts our WPT test harness to TypeScript.
=> Convert WPT test harness to TS

src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h, src/workerd/io/compatibility-date.capnp, src/workerd/server/workerd-api.c++
Changes necessary to avoid hardcoding the package bundle date.
=> Use python packages date from compat date.

src/node/internal/internal_dns_client.ts
Fixes https://github.com/cloudflare/workerd/issues/3325
=> fix node:dns resolveTxt for multiple quotes

src/workerd/api/BUILD.bazel, src/workerd/api/pyodide/pyodide.h, src/workerd/server/tests/python/BUILD.bazel, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h, src/workerd/server/workerd.c++
Implements download of python bundle when running `workerd pyodide-lock` + some other clean up to remove the use of the embedded PYODIDE_LOCK.
```
bazel run @workerd//src/workerd/server:workerd -- pyodide-lock
```
=> Removes usage of embedded PYODIDE_LOCK in C++ code.

src/node/internal/internal_dns_client.ts
=> dns: do not parse JSON when response is not ok

src/cloudflare/internal/ai-api.ts, src/cloudflare/internal/test/ai/ai-api-test.js, src/cloudflare/internal/test/ai/ai-mock.js, types/README.md, types/defines/ai.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
usage:
```ts
env.AI.models()
env.AI.models({search: 'llama'})
env.AI.models({page:3, per_page: 5})
env.AI.models({task: 'Text Generation'})
```
=> Add model list and search to AI binding

src/cloudflare/br.ts, src/cloudflare/internal/br-api.ts, src/cloudflare/internal/test/br/BUILD.bazel, src/cloudflare/internal/test/br/br-api-test.js, src/cloudflare/internal/test/br/br-api-test.py, src/cloudflare/internal/test/br/br-api-test.wd-test, src/cloudflare/internal/test/br/br-mock.js, src/cloudflare/internal/test/br/python-br-api-test.wd-test
Browser rendering team is migrating from a simple Fetcher binding into a JS wrapped binding.
This pull requests adds a very simple wrapped binding that only exposes the already existing `.fetch()` method for existing worker.
Follow up pr's will include adding custom methods to this new binding once it starts being used.
=> Add Browser Rendering JS wrapped binding

src/node/net.ts, src/workerd/api/node/tests/net-nodejs-test.js
> Co-authored-by: @vicb 
This enables the usage of mongodb and mysql in workerd. mysql package is still not supported but this unblocks several errors.
```
[wrangler:inf] GET / 200 OK (436ms)
before mongo
listDocuments
Connected to MongoDB
Documents:
{
_id: new ObjectId('6787f5abdbedb3f0a155db7d'),
name: 'Alice',
age: 30
}
{ _id: new ObjectId('6787f5abdbedb3f0a155db7e'), name: 'Bob', age: 25 }
{
_id: new ObjectId('6787f5abdbedb3f0a155db7f'),
name: 'Charlie',
age: 35
}
finally
after mongo
[wrangler:inf] GET /favicon.ico 200 OK (87ms)
```
=> update node:net to enable mongodb and mysql usage

.bazelrc, WORKSPACE, build/deps/build_deps.jsonc, build/deps/gen/dep_aspect_bazel_lib.bzl, build/deps/gen/dep_aspect_rules_js.bzl, build/deps/gen/dep_aspect_rules_ts.bzl, build/deps/gen/dep_buildifier_darwin_amd64.bzl, build/deps/gen/dep_buildifier_darwin_arm64.bzl, build/deps/gen/dep_buildifier_linux_amd64.bzl, build/deps/gen/dep_buildifier_linux_arm64.bzl, build/deps/gen/dep_buildifier_windows_amd64.bzl, build/deps/gen/dep_capnp_cpp.bzl, build/deps/gen/dep_cargo_bazel_linux_arm64.bzl, build/deps/gen/dep_cargo_bazel_linux_x64.bzl, build/deps/gen/dep_cargo_bazel_macos_arm64.bzl, build/deps/gen/dep_cargo_bazel_macos_x64.bzl, build/deps/gen/dep_cargo_bazel_win_x64.bzl, build/deps/gen/dep_cxxbridge_cmd.bzl, build/deps/gen/dep_rules_rust.bzl, build/deps/gen/dep_simdutf.bzl, deps/rust/BUILD.cxxbridge-cmd
- With latest rules_rust, -Cembed-bitcode=n is set automatically if LTO is
disabled, no need to add it manually
- Rust crate data is no longer passed at compile time, so use compile_data
in cxxbridge-cmd build file
=> 01-15-25 Roll deps

src/workerd/api/BUILD.bazel, src/workerd/api/node/BUILD.bazel, src/workerd/io/BUILD.bazel, src/workerd/jsg/url.c++, src/workerd/server/BUILD.bazel, src/workerd/server/server-test.c++, src/workerd/tools/BUILD.bazel
This was making io depend on the `gen-compile-cache` binary, which created a bottleneck and delayed building source files in io and its dependents.
Drive-by: Fix LLVM 20 operator warnings
I have confirmed that downstream CI passes with this change.
=> [build] Do not have //src/workerd/io depend on src/cloudflare, src/node

src/pyodide/internal/python.ts, src/pyodide/internal/snapshot.ts, src/pyodide/python-entrypoint-helper.ts
And fix workerd's --snapshot-to-disk functionality.
We don't need this deferred upload stuff anymore so take it out.
=> Clean up snapshot upload code

src/workerd/server/tests/python/BUILD.bazel, src/workerd/server/tests/python/sdk/proxy.js, src/workerd/server/tests/python/sdk/sdk.wd-test
Some explanation of the failure here: The `internet` outbound in workerd is the one that `fetch` targets, so since we fetch packages in workerd and this test points `fetch` at a custom _Python_ server, it goes into an infinite loop due to the Python server attempting to load packages from ... itself.
Solution here is to create a JS proxy that either sends the requests onto the Python server or to the internet.
=> Fixes Python SDK tests when external package loading is enabled.

src/workerd/api/actor.c++, src/workerd/api/hyperdrive.c++, src/workerd/api/web-socket.c++
This is more descriptive:
Websocket::constructor => websocket_open
actor_subrequest => durable_object_subrequest
hyperdrive_dev => hyperdrive_connect to match downstream name
Downstream PR to follow.
=> [o11y] Adjust user span naming

src/node/BUILD.bazel, src/node/internal/internal_timers.ts, src/node/internal/internal_timers_promises.ts, src/node/timers.ts, src/node/timers/promises.ts, src/node/tsconfig.json, src/workerd/api/node/BUILD.bazel, src/workerd/api/node/tests/timers-nodejs-test.js, src/workerd/api/node/tests/timers-nodejs-test.wd-test
Once this lands, we can directly connect to mysql using "mysql" npm package from workers.
=> add node:timers module

types/defines/ai.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
We are moving types for supported models under a new NPM package (https://www.npmjs.com/package/@cloudflare/ai-types).
This PR removes all the model specific types and converts AI.run() into a generic function.
=> Updated types for Workers AI

build/wpt_test.bzl, src/workerd/api/wpt/url-test.ts, src/wpt/harness.ts
WPT tests are now declared as text bindings and executed with unsafeEval. This way they can do IOContext things. 
This PR also fixes promise_test to store each promise created and await them all before evaluating the test results.
=> WPT: Run tests with unsafeEval so they can use IOContext

src/node/internal/internal_timers.ts, src/workerd/api/node/tests/timers-nodejs-test.js
Calling `TImeout#refresh` does not update `#timer` making it impossible to cancel
/refresh the timer.
=> fix(node:timers) calling refresh breaks the timers

src/workerd/server/workerd.c++
For now this only makes baseline snapshots but I'll extend it to make package snapshots when I need it.
=> Add a new subcommand to workerd for making a Python snapshot

src/workerd/server/tests/python/BUILD.bazel, src/workerd/server/tests/python/import_tests.bzl, src/workerd/server/tests/python/py_wd_test.bzl
This allows us to say which combinations don't work, which is more explicit than saying which ones do work.
Release note: None
=> py_ew_test: Add skip_flags argument

src/workerd/api/tests/new-module-registry-test.js, src/workerd/api/tests/new-module-registry-test.wd-test, src/workerd/jsg/commonjs.c++, src/workerd/jsg/commonjs.h, src/workerd/jsg/modules-new-test.c++, src/workerd/jsg/modules-new.h, src/workerd/server/workerd-api.c++
First of a series of PRs that'll finish up the new module registry impl and testing ... there's a lot more to do here, just splitting into reasonably consumable/reviewable chunks. The focus here is on completing functionality, afterwards I'll make a pass at improving basic implementation details and perf nits.
=> Continue work on new module registry

samples/tail-workers/tail.js, samples/tail-workers/worker.js, src/workerd/api/hibernatable-web-socket.c++, src/workerd/api/queue.c++, src/workerd/api/trace.c++, src/workerd/api/worker-rpc.c++, src/workerd/io/trace-stream.c++, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker.c++, src/workerd/server/server.c++
This PR starts to add instrumentation for various parts of the streaming tail workers work. Note that the approach this takes right now is generally a straw man that we need to evaluate. We have to support *both* legacy and streaming tail workers and right now the legacy tail workers instrumentation (using `getWorkerTracer()`) is untouched/unchanged with this approach but it means having to dual-instrument the various places in the code where we publish the event. That's... less than ideal. We can coalesce APIs here with a bit more effort. Consider this PR to be the place to discuss the various API options here. Does this work or should we try for a better/cleaner approach?
@rohinlohe ... just for visibility so you can see things are moving
=> Start instrumenting for streaming tail workers

src/workerd/api/crypto/crc-impl.c++, src/workerd/api/crypto/crc-impl.h, src/workerd/api/crypto/crypto.c++, src/workerd/api/crypto/crypto.h, src/workerd/api/crypto/endianness.c++, src/workerd/api/crypto/endianness.h, src/workerd/api/tests/crypto-streams-test.js
Since openssl does not support crc32 as a digest algorithm I extended our support through a new self implemented class and took the initial implementation out to it's own class.
Solves internal ticket #8999
=> Add crc32 algorithm to DigestStream

src/workerd/util/sqlite-test.c++, src/workerd/util/sqlite.c++
This way, if the VFS throws a JSG error, it can propagate to the application, instead of the application getting a mysterious SQLITE_IOERROR message.
=> Make SQLite pass through VFS exceptions to the caller.

src/workerd/io/actor-sqlite.c++
If the database is broken, this will just throw another exception. ImplicitTxn's destructor already has the same check, it was just missing here.
=> Don't rollback ExplicitTxn if broken.

src/node/internal/util.d.ts, src/node/util.ts, src/workerd/api/node/tests/util-nodejs-test.js, src/workerd/api/node/util.c++, src/workerd/api/node/util.h
This is an experimental API and just got recently changed.
Latest update: https://github.com/nodejs/node/pull/56584
=> update util.getCallSites() implementation to follow node.js

src/node/internal/internal_timers.ts, src/node/internal/internal_timers_promises.ts, src/node/internal/timers.d.ts, src/workerd/api/node/BUILD.bazel, src/workerd/api/node/node.h, src/workerd/api/node/tests/timers-nodejs-test.js, src/workerd/api/node/tests/timers-nodejs-test.wd-test, src/workerd/api/node/timers.c++, src/workerd/api/node/timers.h
Fixes https://github.com/cloudflare/workerd/issues/3377
=> use internal setImmediate/clearImmediate fns for node:timers

src/node/internal/internal_timers_promises.ts, src/workerd/api/node/tests/timers-nodejs-test.js
Fixes https://github.com/cloudflare/workerd/issues/3364
Fixes https://github.com/cloudflare/workerd/issues/3363
=> fix node:timers abort callback reset

src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h
The specification for import assertions strongly recommends that embedders reject import attributes and types they do not understand/implement. This is because import attributes can alter the interpretation of a module and are considered to be part of the unique key for caching a module. Throwing an error for things we do not understand is the safest thing to do. However, historically we have not followed this guideline in the spec and it's not clear if enforcing that constraint would be breaking so let's first try to determine if anyone is making use of import assertions. If we're lucky, we won't receive any hits on this and we can start enforcing the rule without a compat flag.
=> Add diagnostic logging to determine import assertion use

src/workerd/api/web-socket.c++
One is a spurious (and prolific) error appearing in our sentry.
The other is a serious issue that could cause messages to be dropped when using auto-responses, but is probably exceedingly rare.
=> Fix two WebSocket API bugs

src/pyodide/internal/readOnlyFS.ts, src/workerd/io/compatibility-date.capnp, src/workerd/server/tests/python/BUILD.bazel, src/workerd/server/tests/python/seek-metadatafs/a.py, src/workerd/server/tests/python/seek-metadatafs/seek-metadatafs.wd-test
We calculated the total size of the file in readOnlyFS in a way that only worked for tarfs and not for metadatafs.
=> Fix SEEK_END for Python metadatafs

src/workerd/api/deferred-proxy.h
Our current implementation of await_transform() requires that we return a result by value, by dint of returning `auto`. An upcoming capnproto patch will change await_transform()'s behavior to just be a pass-through, deferring the actual awaiter construction to a new `operator co_await` implementation. By returning `decltype(auto)`, we become compatible with capnproto both before and after that patch.
=> DeferredProxyCoroutine::await_transform() perfectly-forwards result

src/workerd/api/tests/new-module-registry-test.js, src/workerd/api/tests/new-module-registry-test.wd-test, src/workerd/jsg/commonjs.c++, src/workerd/jsg/commonjs.h, src/workerd/jsg/modules-new-test.c++, src/workerd/jsg/modules-new.h, src/workerd/server/workerd-api.c++
Breaks things downstream, not sure why.
Reverts cloudflare/workerd#3372
=> Revert "Continue work on new module registry"

.github/workflows/test.yml
We added arm64 runners recently which may have increased CI congestion.
- Disable Linux x64 debug job, we'll rely on the arm64 one
- Since we're here, clean up handling of the Windows runner, which got removed and then added back previously.
I also meant to move the Linux asan job from x64 to arm64 which is somewhat faster, but that would require a change to required CI jobs so not something I want to get into now.
=> [ci] Adjust runner configurations to reduce stalls

src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/api/container.c++, src/workerd/api/container.h, src/workerd/api/rtti.c++, src/workerd/io/BUILD.bazel, src/workerd/io/container.capnp, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/workerd-api.c++, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
Implemented here:
- Basic lifecycle (start/monitor/destroy/signal)
- Connecting to a TCP port in the container, either as a raw socket or HTTP.
Not implemented yet:
- Intercepting outgoing connections from container (`listenTcp()`).
- Starting the DO with an already-running container.
- Hibernating while container is running.
- vsocks
- stdio interception
- Any sort of local testing with workerd (only the production runtime is fully wired up for now).
=> Initial implementation of DO-attached containers API

src/workerd/jsg/setup.c++
Starting with 13.3 we need to put each Isolate in its own IsolateGroup, otherwise they share a pointer cage, which causes out-of-memory or overflow of code space.
Felix: As I recall you already tried this patch with success - see chat.
=> Create an isolate group per isolate

.github/workflows/cla.yml, samples/hello-wasm/Cargo.lock, samples/hello-wasm/Cargo.toml
- GitHub warns about an outdated dependency (idna Rust crate) being vulnerable. This is only used as a transitive dependency in a sample however – update Rust deps for the sample to fix this.
- The CLA check CI job ran when closing a PR so far, leading to a confusing comment when closing a PR that would not pass the CLA job even though the point of CLA passing is now moot. Accordingly, we should only run the CLA when opening or synchronizing a PR.
I manually confirmed that the sample still works.
=> [CI] Fix minor dependency vulnerability, fix CLA job running when closing a PR

src/cloudflare/internal/ai-api.ts, src/cloudflare/internal/test/ai/ai-api-test.js, types/defines/ai.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
Add new option to the AI binding
- `returnRawResponse` aims to enable users to have a more granular control over the response coming from the AI binding
=> Add returnRawResponse to AI binding options

src/node/net.ts
Fixes https://github.com/cloudflare/workerd/issues/3425
=> stop reading empty buffers on node:net

src/node/async_hooks.ts, src/workerd/api/node/tests/async_hooks-nodejs-test.js
Reverting some changes in order to align with the polyfill behavior.
=> align async_hooks behavior with polyfills

src/workerd/api/container.c++
@kenton suggested adding this line to fix the issues we were finding with the containers integration. Seems to be fixing all of the problems we were finding!
=> Containers: wait for up/down streams to finish resolving the connectImpl promise

src/workerd/server/server.c++
To detect the main worker having a self loop, we need to compare the current WorkerService with the WorkerService corresponding to the tail worker. If service refers to an EntrypointService, that means we have to compare to the underlying worker instead.
As reported by @penalosa. Tracked this down together with @jmorrell.
=> [o11y] Fix segfault with tail worker self loop

src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server-test.c++, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++
This interface evolved from early beginnings where we didn't really know where we were going, and as a result was quite warty in the way that it reported entrypoints:
* It would report each _method_ of stateless entrypoints with a separate call, rather than reporting the whole entrypoint at once. All of the implementations had to group these back into entrypoints using HashMaps.
* It reported a Durable Object class as if it were an entrypoint with a single method called "class". This sort of made sense back when there was a fixed list of handler names, but the introduction of RPC made this very weird.
Evidence of why this was a bad interface can be seen in the first commit of this PR, which introduces tests for three different bugs that I discovered just while refactoring this interface. …
=> Refactor: Make ValidationErrorReporter interface better.

src/workerd/io/BUILD.bazel, src/workerd/io/io-context.h, src/workerd/io/limit-enforcer.h, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++, src/workerd/util/BUILD.bazel, src/workerd/util/exception.h
When we grow WebAssembly memory in a specific way, we can get into a situation where the isolate gets terminated and the termination waiter signal doesn't reach the isolate. This resulted in a promise being rejected with a "Promise will never complete" exception. This PR fixes this so that a more descriptive exception is used.
=> Fixes "promise will never complete" when exceeding memory.

src/workerd/api/global-scope.c++
These logs can became noisy and don't add much at this point. 
This PR removes them
=> Remove noisy alarm debug logs

src/cloudflare/internal/test/ai/python-ai-api-test.wd-test, src/cloudflare/internal/test/aig/python-aig-api-test.wd-test, src/cloudflare/internal/test/br/python-br-api-test.wd-test, src/cloudflare/internal/test/d1/python-d1-api-test.wd-test, src/cloudflare/internal/test/vectorize/python-vectorize-api-test.wd-test
This is confusing and means these only ever run under one Python version.
=> Don't hardcode python_workers_development in certain Py wd-tests.

src/pyodide/BUILD.bazel, src/pyodide/internal/metadata.ts, src/pyodide/types/pyodide-bucket.d.ts
The pyodide-bucket was only used to get the package URL, but we can hardcode this in metadata.ts instead as it won't be changing.
=> Don't embed pyodide-bucket into Python Worker.

src/pyodide/internal/loadPackage.ts, src/workerd/server/workerd-api.c++
We've seen some flaky test failures which seem to be caused by a failure to fetch these. Let's add better errors to see what status codes are actually returned.
If we see 429s we'll implement retry logic in a separate PR.
=> Check HTTP status code when fetching Py pkg/bundle.

src/pyodide/internal/loadPackage.ts, src/pyodide/internal/metadata.ts, src/pyodide/internal/setupPackages.ts
This fixes two problems:
* the `install_dir` no longer being the source of truth of where a package belongs, now using `package_type`
* dependencies of stdlib packages not being loaded properly
=> Fix issues loading stdlib packages on newer Python versions.

src/pyodide/BUILD.bazel, src/pyodide/internal/loadPackage.ts, src/pyodide/internal/python.ts, src/pyodide/internal/setupPackages.ts, src/pyodide/internal/snapshot.ts, src/pyodide/types/pyodide-lock.d.ts
While working on https://github.com/cloudflare/workerd/pull/3451 I ran into issues with the newer Python version and package bundle. libssl is now expecting libcrypto and other dynlibs to be present in /usr/lib/ so we need to overlay the openssl tarball in that directory, this is what this PR implements.
=> Fixes to load dynlib on newer Python versions correctly.

build/wd_test.bzl, src/cloudflare/internal/test/ai/BUILD.bazel, src/cloudflare/internal/test/aig/BUILD.bazel, src/cloudflare/internal/test/br/BUILD.bazel, src/cloudflare/internal/test/d1/BUILD.bazel, src/cloudflare/internal/test/vectorize/BUILD.bazel, src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h, src/workerd/server/server.h, src/workerd/server/tests/python/BUILD.bazel, src/workerd/server/tests/python/import_tests.bzl, src/workerd/server/tests/python/py_wd_test.bzl, src/workerd/server/workerd.c++
This isn't as good as having actual validator coverage but it should help catch a lot of the problems we're having at validation time.
On top of #3476.
=> Create and use snapshot by default in all `wd_py_test`s

src/workerd/jsg/BUILD.bazel, src/workerd/jsg/util-test.c++, src/workerd/jsg/util.c++, src/workerd/util/autogate.c++, src/workerd/util/autogate.h
...to make it easier to correlate internal error logs with user error reports.
=> Add "wderrid" error IDs to opaque "internal error" exceptions

.ruff.toml, src/workerd/api/pyodide/pyodide.c++, src/workerd/server/tests/python/BUILD.bazel, src/workerd/server/tests/python/dont-snapshot-pyodide/dont-snapshot-pyodide.wd-test, src/workerd/server/tests/python/dont-snapshot-pyodide/worker.py
Importing pyodide before `finalizeBootstrap()` is called causes mayhem.
=> Make sure we don't import pyodide into memory snapshot.

src/workerd/api/pyodide/pyodide.c++, src/workerd/server/tests/python/BUILD.bazel
cc @danlapid. If you want I can turn the ruff "line too long" lint back on, but it is common to disable this because ruff also comes with a formatter that itself wraps long lines and does not always agree with the ruff linter about when a line should be wrapped.
=> Cleanup some stuff accidentally commited in #3499

src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/api/global-scope.h, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server-test.c++, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts
For every top-level export, `ctx.exports` will contain a corresponding property which acts as a binding to that export. If the export is a simple object or `WorkerEntrypoint`, then the `ctx.exports` property is a service binding. If the export is a Durable Object class (and it has been configured with storage), the `ctx.exports` property is a DO namespace binding.
So you can do: `ctx.exports.MyEntrypoint.someRpc()`
And it calls `someRpc()` on the entrypoint named `MyEntrypoint`, as if you had called it over a service binding.
This is marked experimental for now since it won't work on the edge until further changes are made to our control plane.
=> Implement automatic self-referential bindings via ctx.exports.

build/wd_test.bzl
I broke the Python tests on windows in #3415. This fixes it.
=> Fix Python wd_tests on windows

src/workerd/api/pyodide/pyodide.c++, src/workerd/server/tests/python/BUILD.bazel, src/workerd/server/tests/python/filter-non-py-files/filter-files.wd-test, src/workerd/server/tests/python/filter-non-py-files/worker.py
ArrayBuilder assumes the array we are constructing has the exact size given. For constructing variable size arrays, we need a `kj::Vector`.
=> Make `PyodideMetadataReader::getWorkerFiles` not fail when it filters files

src/workerd/server/workerd.c++
If you accidentally pass a directory path instead of a capnp config file to `workerd serve $path` you get an uncaught exception:
```
*** Uncaught exception ***
kj/filesystem-disk-unix.c++:365: failed: mmap: Invalid argument
```
This change adds an assertion that the provided path is a file type. Invoking `workerd serve` with a directory now results in the following error:
```
> workerd serve samples/tail-workers/
workerd serve: samples/tail-workers/: Config path is not a file.
workerd serve --help' for more information.
```
=> Prevent exception when passing directory instead of file

src/cloudflare/internal/test/d1/d1-api-test-common.js
New fields added to the D1 query responses, so adjust the tests to not fail because of the extra fields since we are using `assert.deepEqual` from `node:assert`.
Since we are running these tests in our internal CI, we don't want them to fail with the new fields.
=> Extend D1 binding tests with extra fields added soon

tools/cross/internal_build.py
Display internal pipelink link in case of failure, or error message in case internal PR is not up-to-date.
=> Add error message in internal build log

src/workerd/api/sql-test.js, src/workerd/util/sqlite.c++
https://www.sqlite.org/lang_analyze.html recommends a bunch of things one can do to optimize the performance of the query planner.  Most folks using Durable Objects will probably be best served by just calling `PRAGMA optimize` after making schema changes.
A couple of notes about this commit:
* `PRAGMA optimize` may call `ANALYZE` on all tables, including the internal `_cf_` tables, so we have to allow `ANALYZE` even on otherwise disallowed table names.
* Calls to `ANALYZE`, either directly or via `PRAGMA optimize`, cause the creation of the `sqlite_stat1` table.  This caused some noise in sql-test.js as I had to update tests that depend on (a) the particular set of tables in the database and (b) the particular size of the database.
=> sqlite: allow pragmas and statements needed to run the query optimizer

.github/workflows/cla.yml, .github/workflows/semgrep.yml
The semgrep CI action is very slow and produces many false positives. It is currently the 3rd largest consumer of action run time for workerd, worsening the current runner exhaustion issue which leads to massive queueing of CI workflows. This can slow down the entire development cycle – limit the action to a nightly run, which matches the workers-sdk setting.
Since we're here, only run the (much lighter) CLA assistant workflow on PR comments, not on issue comments. This will reduce the total workflow invocation count somewhat.
CC @hrushikeshdeshpande – this matches previous action on https://github.com/cloudflare/workers-sdk/pull/7309 and https://github.com/cloudflare/stpyv8/pull/123.
=> [ci] Limit Semgrep, CLA assistant CI actions

src/workerd/server/server-test.c++, src/workerd/server/server.c++
It turns out miniflare intentionally generates configs that define a socket for every export, regardless of whether the export is a valid stateless entrypoint. Miniflare currently has no way to tell which entrypoints are valid. As a result, this warning prints spuriously any time someone runs `wrangler dev` with Durable Objects defined.
We should find a better fix for this, but for now, let's remove the warning.
=> Temporarily comment out log warning about bad ServiceDesignators.

src/workerd/server/tests/python/py_wd_test.bzl
"python" is the tag we use downstream
=> [nfc] mark py_wd_tests as python

src/workerd/api/urlpattern.c++, src/workerd/api/urlpattern.h, src/workerd/api/wpt/urlpattern-test.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
Ada fixes this already but I don't want to expose 2 different API surface while putting it behind an autogate.
Splitting https://github.com/cloudflare/workerd/pull/3529 into multiple PRs
=> use correct constructor for URLPattern

src/workerd/api/wpt/urlpattern-test.ts
URLPattern.compareComponent is not part of the spec and we shouldn't run WPT on them.
This actually points out a bug in our web-platform tests runner: `'urlpattern-compare.tentative.https.any.js': {},` this shouldn't succeed. This means that the first 2 lines in WPT is not followed. @npaun Can you take a look at this?
----
PS: the first 2 lines are:
```
// META: global=window,worker
// META: script=resources/urlpattern-compare-tests.tentative.js
```
=> skip all unnecessary urlpattern tests

src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/tests/global-scope-test.js, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts
The bug in https://github.com/cloudflare/workerd/issues/3175 is caused by the fact that the function `getGPU` in `global_scope.c++` is set to only work in a `DurableObject`, and that is not the case in local development.
The fix is simple: Instead of setting the wgpu flag to be always on, enable it only in CI.
As long as `wgpu` is meant to be only accessible in `DureableObjects`, this fix should suffice.
I hope I didn't miss anything, and I'm happy to iterate on it otherwise.
Output of the `Bazel run all tests (dbg)` task:
Output of `bazel test --config=cli -c dbg --cache_test_results=no //...`:
=> Fix `console.log(globalThis)` crash #3175

src/workerd/api/pyodide/pyodide-test.c++, src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h
For most of these checks, we should only be comparing on the first component of a dotted import name. We also need to handle folders with `__init__.py` which are also modules.
This fixes the test failure in #3505.
We could consider removing the `dont-snapshot-pyodide` test, since this gives us unit testing coverage of that logic. Or perhaps we should just combine `filter-non-py-files` and `dont-snapshot-pyodide` into a single integration test covering this file.
=> Test filterPythonScriptImports and fix some problems

src/workerd/jsg/setup.c++, src/workerd/server/workerd.c++
This will make it easier to test tail worker output within wd_test.
=> Add --predictable flag to `workerd test`

src/pyodide/internal/python.ts, src/pyodide/types/Pyodide.d.ts, src/pyodide/types/emscripten.d.ts, src/workerd/server/tests/python/hello/worker.py
It's not trivial to test this in workerd, but I will follow up with a test in workers-sdk.
```
bazel run @workerd//src/workerd/server/tests/python:hello_development@
```
<details><summary>Before</summary>
<p>
```
workerd/server/server.c++:4470: debug: [ TEST ] python-hello
Loading hashlib, lzma, pydecimal, pydoc-data, sqlite3, ssl
Loaded hashlib, lzma, pydecimal, pydoc-data, sqlite3, ssl
workerd/io/worker.c++:1871: info: console.log(); message() = ["Does this work?"]
Does this work?
```
</p>
</details> 
<details><summary>After</summary>
<p>
```
workerd/server/server.c++:4470: debug: [ TEST ] python-hello
Loading hashlib, lzma, pydecimal, pydoc-data, sqlite3, ssl
Loaded hashlib, lzma, pydecimal, pydoc-data, sqlite3, ssl
Does this work?
Does this work?
workerd/server/server.c++:4478: debug: …
```
=> Fixes Python print()s not showing up in `wrangler dev`.

src/workerd/api/sql-test.js, src/workerd/io/actor-sqlite.c++, src/workerd/io/actor-sqlite.h, src/workerd/util/sqlite-metadata.c++, src/workerd/util/sqlite-metadata.h
D1’s Sessions API for read replicas relies on the `getCurrentBookmark` and `waitForBookmark` methods doing something reasonable rather than throwing an exception.
=> Implement just enough to make D1’s Sessions API work in local dev

.bazelrc, build/ci.bazelrc
This makes python tests run significantly faster on CI.
=============
Turns out that optimizing a larger subset of V8 can further improve python test performance (~~\~2x faster in local testing~~ looks like a smaller speedup on CI, local results were based on DEBUG being enabled). Tests currently take ~9 mins to run on Windows which was <3 mins not too long ago, this change will help mitigate this regression. We could optimize all of V8 to simplify things here, but this subset should work well for now.
=> [build] Apply more V8 optimizations to improve test performance

src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/api/container.c++, src/workerd/api/container.h, src/workerd/io/worker.c++, src/workerd/io/worker.h
This way we can construct the `Container` API object with a correct value for the `.running` property.
=> Check container status before invoking actor constructor.

compile_flags.txt
Without this patch, if I open the project in a devcontainer from macos, I get the following error from clangd, and broken go-to-definition etc:
```
In included file: 'bits/wordsize.h' file not foundclang(pp_file_not_found)
features-time64.h(20, 10): Error occurred here
sqlite.h
/workspaces/workerd/src/workerd/util/sqlite.h
```
The problem is that `FROM mcr.microsoft.com/vscode/devcontainers/base:dev-bookworm` brings in an aarch64 ("arm64") debian base image by default on arm macos. This provides `/usr/include/aarch64-linux-gnu` instead of `/usr/include/x86_64-linux-gnu`.
I have put aarch64 lower down on the include path than x86_64, just in case someone on desktop linux has some crazy multiarch/cross compilation setup going on. I have no idea whether this will work, or cause other …
=> fix devcontainer setup on aarch64 macos

.github/workflows/internal-build.yml, .github/workflows/lint.yml, .github/workflows/test.yml, .github/workflows/type-snapshot.yml, build/cc_ast_dump.bzl
- CcInfo and cc_common will need to be imported in a future Bazel version, and find_cpp_toolchain / use_cpp_toolchain need to be imported from rules_cc based on the starlarkification effort.
- the _cc_toolchain attribute is obsolete with CC toolchain resolution, which is always-on in Bazel 8.
Drive-by: Fix not having to run tests for docs/ changes on CI.
=> [bazel] Improve cc toolchain handling to prepare for further starlarkification

src/pyodide/internal/snapshot.ts, src/pyodide/types/runtime-generated/metadata.d.ts, src/workerd/api/pyodide/pyodide-test.c++, src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h
* Fixes a regression which caused breakage in validator-upload test.
* Fixes another bug: only .py filenames are considered in pkg imports now in JS (this was inconsistent with the validator)
@hoodmane it's possible I missed something here, but I think we need the `importToModuleFilename` check so I brought it back.
=> Fixes Python pkg import processing.

src/workerd/api/cache.c++, src/workerd/api/cache.h
Adds support for url.full tag, scaffolding is added to support for cache_control tags but this is not yet complete.
Also see the downstream PR.
=> [o11y] Implement Cache API span tags

src/wpt/harness/harness.ts, src/wpt/url-test.ts
Adds some hooks requested by @anonrig to the WPT harness which can be implemented to modify the test:
- before: run code before the test
- after: run code after the test
- replace: perform an arbitrary modification to the code of the test
The replace hook is used in this PR to enable the test`toascii.window.js` by removing the DOM manipulation stuff from it, just like NodeJS does.
=> WPT harness hooks: before, after, replace

build/wd_test.bzl, package.json, pnpm-lock.yaml, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
- Notably updates typescript (5.5 -> 5.6) and node types (20 -> 22). typescript-eslint and @types/node were only partially updated based on new errors/lints from imported types.
- Clarify a TODO message about a possible TS configuration improvement – this would be feasible now that we have TS 5.6 but is not a priority for now.
=============
Brings the Nodejs and node types versions back in sync. Also allows us to clean up the dependabot PRs.
=> Update npm dependencies

src/wpt/harness/harness.ts, src/wpt/url-test.ts
* Fixes `assert_throws_dom`. We copy-pasted some code from WPT that uses `constructor = this.DOMException`, but we could just use `constructor = DOMException` which both works properly and gets rid of a TypeScript error.
* Also gave a better explanation for why we don't enable `url-setters-a-area.window.js` -- it's redundant.
=> WPT: Fix harness and enable tests in url/historical.any.js

src/workerd/jsg/setup.c++
https://chromium-review.googlesource.com/c/v8/v8/+/6286748 has landed. We can get rid of getUuid() and use GetHashSeed() for uniqueness check.
We go from 128 bits to 64 bits but since this is only used for testing, I think we can get away with collisions.
=> add a todo for IsolateBase::getUuid()

src/pyodide/internal/setupPackages.ts, src/pyodide/types/runtime-generated/metadata.d.ts, src/workerd/api/BUILD.bazel, src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h, src/workerd/api/pyodide/requirements.c++, src/workerd/api/pyodide/requirements.h
The current state of things is that the logic for gathering package requirements is duplicated in TS and C++. This PR moves it into workerd so that the same implementation can be used in workerd and EW.
=> Refactor to use C++ implementation of requirement gathering for Python.

src/workerd/api/basics.c++, src/workerd/api/basics.h, src/workerd/api/http-test.js, src/wpt/dom/abort-test.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
This fix is so simple I'm worried I'm missing something. 
It looks like we just... forgot to implement `Event.target` at all. 
Given that we don't support hierarchical events, we can use exactly the same logic we use for `Event.currentTarget`.
Fixes three WPT tests for AbortSignal.
=> WPT dom/abort: Fix missing target on events

src/workerd/api/sql-test.js, src/workerd/util/sqlite.c++
The [SQLite
documentation](https://www.sqlite.org/pragma.html#pragma_optimize) for `PRAGMA optimize` says:
> To see all optimizations that would have been done without actually
> doing them, run "PRAGMA optimize(-1)".
We parsed the mask as a `uint` (which makes sense for a mask!), but that precludes us from parsing negative literals and caused `PRAGMA optimize(-1)` to fail.  Parsing as an `int32_t` admits this statement.
(I chose to use `int32_t` rather than `int` because SQLite uses a 32-bit integer for the mask.)
Annoyingly, SQLite’s internal `sqlite3GetInt32` function doesn’t allow you to write a negative number with hex strings, so the best way to flip (almost) all the bits using hex is using the 0x7fffffff literal.
=> sqlite: Parse number part of PragmaSignature: NULL_OR_NUMBER as an int32_t

src/workerd/api/http-standard-test.js, src/workerd/api/http-test-ts.ts, src/workerd/api/http-test.js, src/workerd/api/http.h, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
WinterTC recently agreed that conformant implementations should, at the very least, support the `'default'` value for `Response.prototype.type` property and, if the runtime implements `Response.error()`, the `'error'` value -- even if the implementation otherwise does not implement CORS.
=> Add Response.prototype.type property

src/workerd/api/http.h
WinterTC is recommending that non-browser runtimes ignore certain CORS related options and properties that are not relevant to non-browser runtimes.
=> Ignore unsupported fetch options and properties as recommended

src/workerd/api/cache.c++, src/workerd/api/eventsource.c++, src/workerd/api/global-scope.c++, src/workerd/api/html-rewriter.c++, src/workerd/api/http-standard-test.js, src/workerd/api/http-standard-test.wd-test, src/workerd/api/http.c++, src/workerd/api/http.h, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
Builds on https://github.com/cloudflare/workerd/pull/3590 to implement `Response.error()`.
WinterTC will be including `Response.error()` is the fetch subset that compliant runtimes should implement, and `Response.error()` is necessary for nodejs_compat. 
Fixes: https://github.com/cloudflare/workerd/issues/3591
=> Implement Response.error()

src/workerd/api/queue.c++, src/workerd/io/compatibility-date.capnp
The intent is that the event can be considered done when the
queue() handler's returned promise resolves, allowing acked/nacked
message info to be returned back to the queues infrastructure sooner,
rather than requiring all waitUntil'ed work to finish first. This has
two important benefits:
1. This will keep consumer invocations from getting slowed down by
slow/hung waitUntil'ed tasks.
1. This will keep consumer invocations from failing due to failing
waitUntil tasks.
This notably makes queue() handlers behave more like fetch() handlers, which should make them more intuitive for most users.
=> Add compat flag for queue consumers to not block on waitUntil'ed work

src/workerd/api/container.c++, src/workerd/api/container.h, src/workerd/io/container.capnp, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
We are just defining in the container capnp schema the `environmentVariables` property, and the `env` property in the start options. 
The user will be able to pass environment variables like this:
```
this.ctx.container.start({ 
env: {
A: "C",
C: "A",
},
});
```
If the container image is already configured to have `A=C`, it will override it and set `A` to `B`. New environment variables are just appended. It's up to the container runtime to implement this behaviour correctly.
=> Be able to pass environment variables in containers start()

src/node/internal/process.ts, src/node/internal/util.d.ts, src/workerd/api/node/tests/process-nodejs-test.js, src/workerd/api/node/tests/process-nodejs-test.wd-test, src/workerd/api/node/util.c++, src/workerd/api/node/util.h, src/workerd/io/compatibility-date.capnp, src/workerd/jsg/jsg.h, src/workerd/jsg/setup.c++, src/workerd/jsg/setup.h, src/workerd/server/workerd-api.c++
Autopopulates the process.env from bindings in local dev. A similar PR will be needed internally to enable it there as it won't be automatic.
See caveats: https://github.com/cloudflare/workerd/pull/3311#issuecomment-2586475148
=> Provide mechanism for autopopulating node.js process.env

src/workerd/api/BUILD.bazel, src/workerd/api/hibernatable-web-socket.c++, src/workerd/api/queue.c++, src/workerd/api/tail-worker-test-dummy.js, src/workerd/api/tail-worker-test-invalid.js, src/workerd/api/tail-worker-test-invalid.wd-test, src/workerd/api/tail-worker-test-receiver.js, src/workerd/api/tail-worker-test.js, src/workerd/api/tail-worker-test.wd-test, src/workerd/api/trace.c++, src/workerd/api/worker-rpc.c++, src/workerd/io/observer.h, src/workerd/io/trace-stream.c++, src/workerd/io/trace-stream.h, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker-interface.capnp, src/workerd/io/worker.c++, src/workerd/server/server.c++
* Fixes UAF in server.c++ handling
* Simplifies trace-stream implementation
* Ensures that the outcome event is sent in fetch request traces
* Still needs to ensure that outcome is sent in all other types of invocations
* Still needs tests, tests, and more tests.
* Tests to verify that throwing an error in the tail worker handler works as expected
* Tests to verify that all of the various ways a worker invocation can complete will appropriately trigger an outcome event
* Tests to verify that all internal state is cleaned up and not leaked
@fhanau .... opening this as a draft and handing it over to you for next steps..
=> Fixup the streaming tail worker implementation

src/workerd/api/trace.h, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
Internal PR: #9943
Exposes CPU/Wall time in the trace workers api instead of hiding it behind the UnsafeTraceMetrics binding now that we have the confidence we can safely expose this without any spectre issues.
=> Expose cpu and wall time in TraceItem

src/node/internal/crypto_random.ts
=> enable eslint and typescript warnings for crypto_random

src/pyodide/internal/snapshot.ts, src/pyodide/types/artifacts.d.ts, src/pyodide/types/runtime-generated/metadata.d.ts, src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h
This simplifies our life when we have to adjust the logic for what goes into the package snapshots. For now leave the old functions to make it easier to migrate.
=> Python: Make new C++ function `getPackageSnapshotImports`

src/node/net.ts
Simplifies the types. Currently it throws a compile error which I'm trying to solve.
```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
src/node/net.ts(120,22): error TS2323: Cannot redeclare exported variable 'Socket'.
src/node/net.ts(198,17): error TS2323: Cannot redeclare exported variable 'Socket'.
```
=> simplify node:net types

src/workerd/api/url-standard.c++, src/workerd/api/url-standard.h, src/workerd/jsg/jsg.h, src/workerd/jsg/rtti.h, src/workerd/jsg/value-test.c++, src/workerd/jsg/value.h, src/workerd/jsg/web-idl.h, src/wpt/url-test.ts
* Adds jsg::USVString, which is guaranteed not to contain invalid characters in UTF8. This type is intended to make it convenient and consistent to implement Web APIs which say they take a USVString without having to deal with this issue every time.
* Updates url-standard to use USVStrings as specified by the WHATWG URL spec.
=> Fix some WPT url tests failing due to invalid surrogates in UTF8

src/node/crypto.ts, src/node/internal/crypto.d.ts, src/node/internal/crypto_keys.ts, src/node/internal/crypto_sign.ts, src/node/internal/internal_errors.ts, src/node/internal/streams_writable.d.ts, src/workerd/api/node/BUILD.bazel, src/workerd/api/node/crypto-keys.c++, src/workerd/api/node/crypto.c++, src/workerd/api/node/crypto.h, src/workerd/api/node/tests/crypto_sign-test.js, src/workerd/api/node/tests/crypto_sign-test.wd-test
Implements the `node:crypto` `createSign(...)`/`createVerify(...)`/`crypto.sign(...)`/`crypto.verify(...)` APIs. RSA and ed25519 are currently test to work, other key types aren't verified yet. DSA likely does not work, for instance. Will be working on expanding tests next but this ought to be able to land.
Reviewers: some familiarity with the Node.js implementation is likely necessary to review this for correctness.
=> Implement node:crypto sign and verify APIs

.bazelrc, README.md, WORKSPACE, build/deps/gen/dep_ada_url.bzl, build/deps/gen/dep_aspect_rules_js.bzl, build/deps/gen/dep_build_bazel_apple_support.bzl, build/deps/gen/dep_capnp_cpp.bzl, build/deps/gen/dep_simdutf.bzl
- With the new apple_support version including https://github.com/bazelbuild/apple_support/pull/354, macOS builds should be able to build with just the Xcode Command Line Tools, although CI uses full Xcode so this is not tested. Numerous folks ran into issues with this, hopefully this will make it easier for people to get started with workerd.
- Enable `use_plus_in_repo_names` for common options, ported from #3492 by @ujohnny where Windows CI was somehow failing perpetually by cherry-picking the commit.
=> [build] Roll select dependencies, enable use_plus_in_repo_names

src/workerd/jsg/README.md, src/workerd/jsg/rtti.h, src/workerd/jsg/type-wrapper.h, src/workerd/jsg/value-test.c++, src/workerd/jsg/value.h
```
bazel run @workerd//src/workerd/jsg:value-test
```
=> Implements kj::HashSet support for jsg.

src/workerd/api/pyodide/pyodide-test.c++, src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h, src/workerd/server/tests/python/vendor_dir/vendor_dir.wd-test, src/workerd/server/tests/python/vendor_dir/worker.py
* Python: Clean up pyodide.h a bit
This removes the no longer used APIs and moves more functions to PythonModuleInfo.
* Python: Update getPackageSnapshotImports() to handle vendor directory
This adds vendor directory handling to `getPackageSnapshotImports()` and so makes package vendoring work correctly.
=> Make Python package vendoring work

src/pyodide/internal/python.ts
Just a simple check to ensure an incorrectly build version of the pyodide bundle cannot be released.
=> Adds Pyodide version check to prevent incorrect bundle release

src/pyodide/internal/setupPackages.ts, src/pyodide/types/runtime-generated/metadata.d.ts, src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h
Little clean up and follow up to https://github.com/cloudflare/workerd/pull/3538
=> Return kj::HashSet from Python's getTransitiveRequirements.

src/cloudflare/internal/env.d.ts, src/cloudflare/workers.ts, src/workerd/api/BUILD.bazel, src/workerd/api/modules.c++, src/workerd/api/modules.h, src/workerd/api/node/util.c++, src/workerd/api/tests/disable-importable-env-test.js, src/workerd/api/tests/disable-importable-env-test.wd-test, src/workerd/api/tests/importable-env-test.js, src/workerd/api/tests/importable-env-test.wd-test, src/workerd/io/compatibility-date.capnp, src/workerd/io/worker.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/setup.c++, src/workerd/jsg/setup.h, src/workerd/server/workerd-api.c++
PR marked as a draft until we're certain this is what we want....
```js
import { env } from 'cloudflare:workers';
console.log(env.FOO);  // Undefined, outside request io context
fetch(req) {
console.log(env.FOO);  // 'BAR', inside request io context
// ...
}
}
```
~~Gated by a compat flag that is off by default~~ The flag is now on by default.
* `allow_importable_env`
* `disallow_importable_env`
Mutations of the env properties are passed through to the underlying object so will be reflected on the `env` argument passed into the handlers.
Note that this is *not* directly tied to `process.env`... this exposes the regular `env`/`bindings` via the import when accessed within the context of a request. As such, any modules used by your worker can access the bindings without …
=> Implement importable env

src/workerd/api/queue.c++
I thought that deferring the drain() in all cases could potentially be useful (e.g. what if an exception gets thrown from somewhere in this method without getting caught?), but that was dumb. This change (A) moves it to only the code path where we aren't already calling finishScheduled (which waits on waitUntilTasks), and (B) properly attaches references to the necessary state that can be accessed from JS.
Follow-up to #3596
=> Fix new queue waitUntil drain() logic

src/workerd/jsg/setup.c++
Since we updated v8 to 13.4, we can now remove the compile flags for 13.4
=> remove v8 13.4 compile flags

src/workerd/api/pyodide/pyodide.c++, src/workerd/server/tests/python/vendor_dir/vendor_dir.wd-test
This error was thrown when a worker bundle has multiple modules with the same filename.
I changed a few other `insert`s to `upsert` just in case.
```
bazel run @workerd//src/workerd/server/tests/python:vendor_dir_development@
```
=> Fixes "inserted row already exists in table" error in Python.

.bazelrc, .github/workflows/release-python-runtime.yml, .github/workflows/release.yml, .github/workflows/type-snapshot.yml, Dockerfile.release, WORKSPACE, build/ci.bazelrc, src/workerd/api/basics.h
[build] 03-05-25 Bazel cleanup
- It turns out that Bazel never uses the CXX env variable – when we need to specify the right path to clang, providing CC is sufficient
- For some V8 dependencies, replace googlesource mirror with the GitHub repository itself
- Drop superfluous repo_mapping and Windows overrides that are no longer needed for V8
[nfc] Fix -Wdangling-field warning
- LLVM 20 produces a warning since the type ptr is initialized with a constructor
argument that will go out of scope. Initializing it with the ownType class
variable instead resolves the warning.
=> [build] 03-05-25 Bazel cleanup

src/pyodide/python-entrypoint-helper.ts, src/workerd/api/pyodide/pyodide.c++
This fixes a regression introduced by https://github.com/cloudflare/workerd/pull/3505.
I've looked into moving when setupPatches gets called but it depends on pyodide being initialised... whereas the memory snapshot stuff seems to require being called before pyodide initialisation is finalised.
Anyway, I'd love @hoodmane's thoughts on this when he's back.
=> Fixes asgi import at top-level failing.

src/node/crypto.ts, src/node/internal/crypto.d.ts, src/node/internal/crypto_cipher.ts, src/workerd/api/node/BUILD.bazel, src/workerd/api/node/crypto-keys.c++, src/workerd/api/node/crypto.c++, src/workerd/api/node/crypto.h, src/workerd/api/node/tests/crypto_cipher-test.js, src/workerd/api/node/tests/crypto_cipher-test.wd-test
Implementing the node:crypto cipher apis. ~Not yet ready for a full code review.~
Working:
* `createCipheriv(...)`
* `createDecipheriv(...)`
* `publicEncrypt()`
* `publicDecrypt()`
* `privateEncrypt()`
* `privateDecrypt()`
TODO: (will come in a separate PR)
* `getCipherInfo()`
=> Implement node:crypto cipher/decipher

src/workerd/api/BUILD.bazel, src/workerd/api/basics.h, src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/tests/request-client-disconnect.js, src/workerd/api/tests/request-client-disconnect.wd-test, src/workerd/io/worker-entrypoint.c++, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++
How it works:
- An AbortController is added as a member of WorkerEntrypoint. 
- Its AbortSignal is passed through via ServiceWorkerGlobalScope and Request through to JS, so it can be accessed via `Request.signal`.
- If the client disconnects, and we've both not produced a response or thrown an exception, the AbortSignal is triggered.
=> Implement Request.signal to detect client disconnects

src/workerd/api/sql.c++, src/workerd/api/sql.h, src/workerd/util/sqlite-kv-test.c++, src/workerd/util/sqlite-kv.h, src/workerd/util/sqlite-test.c++, src/workerd/util/sqlite.c++, src/workerd/util/sqlite.h
We bill for:
- SQL queries issued via the JavaScript SQL API.
- DO old-style key/value storage operations.
Anything else, we assume is an internal query, and not billed.
=> SQLite: Don't bill for internal queries.

types/defines/rpc.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
Reverts cloudflare/workerd#3636 after reports of breakage for users who use type rather than interface to define their env type
=> Revert "Add TS support for importable env"

src/workerd/io/io-context.h
We're seeing errors getting reported from actors trying to run promises without an active request. We've determined this is from tasks trying to run after an actor's IO context has been aborted. This change stores the abort exception in the `IoContext` and rethrows it in `IoContext::run`.
=> Rethrow abort exception on IoContext::run

src/cloudflare/internal/test/workflows/workflows-api-test.js, src/cloudflare/internal/test/workflows/workflows-mock.js, src/cloudflare/internal/workflows-api.ts, src/cloudflare/internal/workflows.d.ts, types/defines/workflows.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
Closes WOR-496
We want to allow users to batch create instances in the same request - this implies that the RPC limit is shared for the batch.
=> feat: add createBatch API for Workflows binding

src/cloudflare/internal/d1-api.ts, src/cloudflare/internal/test/d1/d1-api-test-with-sessions.wd-test, src/workerd/io/compatibility-date.capnp
We no longer need the `enable_d1_with_sessions_api` experimental compatibility flag since the `withSession()` method should be exposed to everyone.
Internally: CFSQL-1220
```
bazel run //src/cloudflare/internal/test/d1:d1-api-test-with-sessions
bazel run //src/cloudflare/internal/test/d1:d1-api-test
```
=> Make the D1 Sessions API default allowed for everyone

src/pyodide/internal/workers.py, src/workerd/io/compatibility-date.capnp, src/workerd/server/tests/python/sdk/worker.py
Implements a Python native `Request` class based on https://developer.mozilla.org/en-US/docs/Web/API/Request/Request.
The API tries to match the `Response` API as closely as possible.
```
$ bazel run @workerd//src/workerd/server/tests/python:sdk_development@
```
=> Implements Request class in Python SDK.

types/defines/rpc.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
This adds a namespaced type for importable env, `Cloudflare.Env`. This can be provided by a user `.d.ts` file via something like:
```ts
declare namespace Cloudflare {
interface Env {
string: 'hello world';
json: { key: 'value' };
SECRET: string;
}
}
```
This will be generated by `wrangler types` in the near future
=> Importable env types, take 2

src/workerd/io/worker.c++
We observed this error in production when testing containers.
This change was technically composed by Claude Code. Transcript: https://claude-workerd-transcript.pages.dev/ensure-constructed
Claude was surprisingly quick to narrow down where the problem might be, given just the error message.
However, ultimately it needed hints to figure out the actual problem, and the code it initially proposed as the fix was not very good (though its choice to use `KJ_ON_SCOPE_FAILURE` was interesting!).
The code in this commit may have been written by it, but only after very explicit prompting from me on what to do.
I think I would have found and fixed the problem more quickly without Claude, but its ability to reason about the code is nevertheless impressive.
=> Fix "actor still initializing when getHandler() called" with containers.

src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/server/server-test.c++, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
The `Response` encoder has long had a non-standard option `encodeBody: "manual"` which says: "Do not automatically compress the body according to content-encoding; assume the bytes I provide are already compressed."
However, this only allowed you to construct a `Response` to return with manual encoding. If you made at outgoing HTTP request, and the response was compressed, there was no way to stop the runtime from automatically decompressing it. This commit adds such a way: setting `encodeResponseBody: "manual"` as an option to `fetch()`.
(Of course, `encodeResponseBody` is a non-standard option, but `encodeBody` is as well.)
🚨🚨 THIS PR WAS WRITTEN BY CLAUDE.AI 🚨🚨
(with a lot of prompting by me -- [see trascript](https://claude-workerd-transcript.pages.dev/))
This was an experiment to see …
=> Ask Claude to implement `encodeResponseBody: "manual"` option.

src/workerd/io/io-context.c++, src/workerd/io/io-context.h
Also ignore future aborts if abort has already been called once. This was originally implied by the behavior of fulfiller since calling reject more than once will ignore future calls.
=> Use IoContext::abort more consistently

src/cloudflare/internal/d1-api.ts
The recent changes to make `D1DatabaseWithSessionAPI` the default class returned for the D1 binding (see https://github.com/cloudflare/workerd/pull/3700) broke some vitest pool tests that use the returned class name and were expecting `D1Database`.
This PR just merges `D1DatabaseWithSessionAPI` with its parent class `D1Database` since now we will roll out the `withSession()` method to everyone, and returns the `D1Database` class.
=> CFSQL-1220: Rename the D1 binding class to the previous name to fix vitest tests

src/workerd/io/worker.c++
This should work:
```
class Foo {
async fetch(req, env, ctx) { ... }
}
export default new Foo();
```
But it had a slight bug: `validateHandlers()` did not report the `fetch` method as existing. This meant you couldn't actually deploy a worker defined this way as the upload validator on the server side would reject it for not implementing `fetch`.
I asked Claude Code to fix it (as a test... I knew what the problem was). Transcript: https://claude-workerd-transcript.pages.dev/validate-handlers
=> Fix exporting a class instance as an entrypoint.

src/workerd/io/compatibility-date.capnp, src/workerd/io/worker-entrypoint.c++
When I implemented Request.signal (#3488), we wanted to avoid introducing any surprising new behaviour. As a result, any subrequests created from the incoming request have an `ignoreForSubrequests` flag applied to them. This flag makes it so these outgoing subrequests won't be cancelled even if the incoming request is cancelled. But this is, itself, peculiar behaviour, so this PR adds a compat flag to prevent this behaviour.
- Enable: `abort_signal_not_ignored_for_subrequests`
- Disable/default: `abort_signal_ignored_for_subrequests`
There's a whole lot of negation in this one, so a sanity check on the code would be kindly appreciated.
=> Put Request.signal ignoreForSubrequests behaviour behind a compat flag

src/workerd/api/actor-state.c++
- The previous error messaged first mentioned workerd. But most people don't configure things directly through workerd, they use Wrangler.
- The previous error message only mentioned wrangler.toml, even though now wrangler.jsonc is the default
=> Improve error message when SQL not enabled for Durable Objects

tools/cross/format.py
Otherwise, when using `format.py` locally we won't pick up updates to the tools.
See discussion here:
https://github.com/cloudflare/workerd/pull/3732
=> Always rebuild bazel tool in format.py

types/defines/d1.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
These fields are already returned by the D1 API so adding them in the D1 Binding official types.
Example of response (see the `result.meta` field):
```
{
"result": [
{
"results": [
{
"1": 1
}
],
"success": true,
"meta": {
...
"served_by_region": "WNAM",
"served_by_primary": true,
"timings": {
"sql_duration_ms": 0.2084
},
"duration": 0.2084,
...
}
}
],
"errors": [],
"messages": [],
"success": true
}
```
=> Extend D1 meta information - served_by_region/served_by_primary and sql_duration_ms

types/defines/pipelines.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/oldest/index.d.ts
@penalosa pointed out that the type generated is quite complex by wrangler types where there is no default generic param on the pipelines binding. Adding a default here and then making it consistent on PipelineTransformationEntrypoint
https://github.com/cloudflare/workers-sdk/pull/8528#discussion_r2002193772
Also moved the comment about the run method on to the correct line
@oliy @cmackenzie1
=> Updated 'cloudflare:pipelines' module binding & transformation defaults for generic params

src/workerd/api/html-rewriter.c++, src/workerd/api/tests/htmlrewriter-test.js
This PR adds two tests that cause a stack overflow in workerd:
- `stackOverflow1`: A single replacement function generates a lot of output bytes
- `stackOverflow2`: The replacement function runs many times
I've also implemented the idea we came up with to limit the depth of the promise chain: waiting on `writePromise` after every thunk call. As expected, this fixes `stackOverflow2` but not `stackOverflow1`. Therefore I commented out `stackOverflow1` for now.
I'd like to merge this quick fix to see if the sentry errors go away, but it's not a full fix. The next step would be to implement an internal buffer in `Rewriter` and flush that to the `inner` (output sink) after each thunk call.
There's also another potential situation where a ReadableStream is used to provide the replacement. In …
=> Reproduce HTMLRewriter stack overflow using JS code + quick fix

src/node/_tls_common.ts, src/node/internal/internal_errors.ts, src/node/internal/internal_tls.ts, src/node/internal/internal_tls_common.ts, src/node/internal/internal_tls_wrap.ts, src/node/internal/url.d.ts, src/node/tls.ts, src/rust/net/BUILD.bazel, src/rust/net/lib.rs, src/workerd/api/node/BUILD.bazel, src/workerd/api/node/tests/net-nodejs-test.js, src/workerd/api/node/tests/tls-nodejs-test.js, src/workerd/api/node/url.c++, src/workerd/api/node/url.h
The following pull-request:
- Adds createSecureContext() function but only supports options with no values. this is done to unblock mysql2 from working in cloudflare workers where no custom ssl options are passed.
- Adds checkServerIdentity() for validating a PeerCertificate according to the host.
=> add createSecureContext and checkServerIdentity to node:tls

.vscode/launch.json, src/workerd/api/BUILD.bazel, src/workerd/api/kv-test.js, src/workerd/api/kv-test.wd-test, src/workerd/api/kv.c++, src/workerd/api/kv.h, src/workerd/io/limit-enforcer.h, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
Creating a new part in the binding for new bulk gets, along with tests for regular gets and the bulk gets
We consider we have a POST endpoint in SGW and we send the keys in a json format as such:
```
{
"keys": ["key1", "key2"]
}
```
However, we decided that the binding here will only be a passthrough and everything will processed in the endpoint. On top of that, since everything is processed in the binding and comes as a single response, we don't need extra logic to process metadata, we just need to make sure that the binding responds what we what. Because of these two things, we added two more parameters in the request body:
```
{
"keys": ["key1", "key2"],
"type": "text",
"withMetadata": true
}
```
We added tests for:
Regular gets:
- 400s
- 500s
- 200s with text, json, stream and …
=> feat: add new option for bulk gets for kv

src/node/_tls_common.ts, src/node/internal/internal_tls_common.ts, src/workerd/api/node/tests/tls-nodejs-test.js
This is the last remaining function provided in "_tls_common" module. We can now remove the polyfill from it.
cc @vicb would you mind updating the polyfill for `_tls_common`?
=> add missing translatePeerCertificate function

src/pyodide/internal/workers.py, src/workerd/io/compatibility-date.capnp, src/workerd/server/tests/python/sdk/worker.py
For now a simple decorator that transforms any `request` argument to the Python `Request` class. In the future we will make it do more things like transform the `env` argument for bindings.
Happy to bikeshed the name, I chose `event` because that's what the Rust workers use.
```
$ bazel run @workerd//src/workerd/server/tests/python:sdk_development@
```
=> Implements decorator for Python event handlers.

.bazelrc
This is more consistent with the V8 build, and reduces code size.
==========
macOS binary size goes down by 8.5MB (2.4%) when using default settings; the `__TEXT,__gcc_except_tab` and `__TEXT,__unwind_info` segments see an especially large (20%+) reduction.
=> [build] Disable exceptions for V8 and friends

src/workerd/api/tests/js-rpc-test.js, src/workerd/api/worker-rpc.c++, src/workerd/api/worker-rpc.h
This PR adds a sample that demonstrates that it's not possible to construct a `WorkerEntrypoint` in userland with a user-provided `ctx` object. Instead, this error appears:
```
workerd/server/server.c++:3880: error: Uncaught exception: workerd/jsg/_virtual_includes/iterator/workerd/jsg/value.h:1473: failed: remote.jsg.TypeError: Failed to construct 'WorkerEntrypoint': constructor parameter 1 is not of type 'ExecutionContext'.
```
This is important for the Vitest integration because we need to be able to (within a single "real" execution context):
- Construct a WorkerEntrypoint with a custom execution context
- wait for all `waitUntil`s in the custom execution context to be settled
- Do some assertions
This works with default export-style workers, because the `fetch()` method can just be …
=> Constructing a `WorkerEntrypoint` from userland

build/BUILD.wpt, build/deps/gen/dep_wpt.bzl, build/deps/shared_deps.jsonc, build/wpt_get_directories.bzl, build/wpt_test.bzl
This is a follow up for #3777. When a dependency is shared, we can't assume the name of the repo we're in -- it has to be absolute.
=> Make BUILD.wpt path absolute

src/workerd/io/compatibility-date.capnp
This PR enables the compat flag which had been experimental and tested in FL for overriding cache rules when cache settings specified in the request cf object.
=> CACHE-11937: enable cache rules request cf overrides compat flag

src/workerd/api/cache.c++, src/workerd/api/queue.c++, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker-entrypoint.h, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++, src/workerd/tests/test-fixture.h
To demonstrate the power of Arc<T> I have converted one of the most important use-cases.
This makes ownership of Worker more explicit and easier to understand. I left comments where the code was forced to be different (for better imo).
downstream 10086
=> kj::Arc<Worker>

src/node/internal/process.ts, src/workerd/api/modules.c++, src/workerd/api/node/util.c++, src/workerd/io/worker.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/setup.c++, src/workerd/jsg/setup.h, src/workerd/server/workerd-api.c++
This means that `disallow_importable_env` will disable both importable env and `process.env`, which is likely what anyone using this flag wants. (Source: Me, the only known person who even wants `disallow_importable_env`.)
This also allows us to delete a lot of code.
Although this is techincally a breaking change since these fetaures have already shipped, it seems highly unlikely that someone has managed to deploy code which both sets `disallow_importable_env` and also `nodejs_compat_populate_process_env` and depends on `process.env`. This will get harder once `nodejs_compat_populate_process_env` becomes the default on `2025-04-01`.
=> Change process.env implementation to be based on importable env.

src/workerd/api/hibernatable-web-socket.c++, src/workerd/api/node/diagnostics-channel.c++, src/workerd/api/node/util.c++, src/workerd/api/queue.c++, src/workerd/api/tail-worker-test.js, src/workerd/api/trace.c++, src/workerd/api/worker-rpc.c++, src/workerd/io/observer.h, src/workerd/io/trace-stream.c++, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/tracer.c++, src/workerd/io/tracer.h, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker.c++, src/workerd/server/server.c++
First commit is very simple refactoring to facilitate cloning trace events. Second commit removes reportTailEvent() and instead uses WorkerTracer to report events to the tail stream writer. This means duplication in adding trace events is abstracted away.
- Note that Outcome event reporting is not folded into this class at present.
- Note that this can cause the legacy trace size limit to the Streaming model – this will be cleaned up once we transmit all event data over the stream layer.
- As a side effect, streaming tail worker now supports headers in fetch handler onset events, update tests accordingly
- This will make it easy to support Return and SpanOpen/SpanClose events.
=> [o11y] Consolidate adding trace events for legacy and streaming tail workers

.bazelrc, build/BUILD.dawn
-fno-exceptions is not available with clang-cl, which causes lots of warnings on CI. Use the equivalent /GX- flag instead.
=> [build] Fix disabling exceptions on v8 and friends on Windows

src/pyodide/BUILD.bazel, src/pyodide/helpers.bzl
Factoring out repeated copy_file and capnp_embed logic
=> Python: pyodide BULD.bazel minor cleanup

build/python/packages_20240829_4.bzl, build/python/packages_20250324_1.bzl, build/python_metadata.bzl
This goes together with:
https://github.com/cloudflare/pyodide-build-scripts/pull/11 
which changes the generated bazel file to match the new expected format.
Use "Hide whitespace" to review.
=> Python: Put tag and lockfile hash in info section in package bzl file

src/workerd/api/web-socket.c++
Throwing and later catching is not necessary due to the existence of tryParse method.
=> simplify websocket constructor url validation

build/python_metadata.bzl, src/pyodide/pyodide_extra.capnp, src/workerd/io/compatibility-date.capnp, src/workerd/server/workerd-api.c++, src/workerd/util/autogate.c++, src/workerd/util/autogate.h
This has been out to RoW for a while now, so let's make it default.
=> Remove external package loading autogate/compat flag and make default.

src/workerd/api/http.c++, src/workerd/api/tests/global-scope-test.js, src/workerd/api/util.c++, src/workerd/api/util.h, src/workerd/api/web-socket.c++
This is not a breaking change since we already disallow it but rather throw an Internal Error whenever a user passes a URL with username/password state.
After this change, we now throw a JSG error which will be propagated to the end-user in a clear way.
=> remove authorization properties from url in websocket constructor

.github/workflows/type-snapshot.yml
The old commit has disappeared?
Pointing to a v2.9.1 tag as of today.
=> [build] update stick-pull-request-comment

build/BUILD.wpt, build/wpt_get_directories.bzl, build/wpt_test.bzl, src/wpt/BUILD.bazel, src/wpt/fetch/api-test.ts, src/wpt/harness/harness.ts, src/wpt/urlpattern-standard-test.ts, src/wpt/urlpattern-test.ts
This is a giant one (and it's still a draft), so I'd suggest reviewing commit-by-commit.
- By fiddling with the arguments passed, we can calculate relative paths in a less brittle manner.
- Add the WPT CA certificate and enable network connections for WPT tests.
- Better relative path logic here too. Trying to make a flat namespace like workerd bindings act like a file system willo always be clunky, but now stuff like '../resources/xhr.js` can be interpreted correctly.
- Added several new harness functions: `assert_greater_than`, `assert_regexp_match`, `promise_rejects_js`, `promise_rejects_exactly`, `add_cleanup`/`add_completion_callback`.
- Made tests involving fetching from an external server work properly. We also support relative URLs and give WPT tests a fake sense of location …
=> WPT fetch api tests

src/workerd/io/actor-sqlite.c++, src/workerd/io/actor-sqlite.h, src/workerd/util/BUILD.bazel, src/workerd/util/sqlite-test.c++, src/workerd/util/sqlite.c++, src/workerd/util/sqlite.h
We should break output gates and reset actors in the event that we catch the following exceptions because they implicitly roll back any transaction:
[SQLITE_FULL](https://www.sqlite.org/rescode.html#full): database or disk full
[SQLITE_IOERR](https://www.sqlite.org/rescode.html#ioerr): disk I/O error
[SQLITE_BUSY](https://www.sqlite.org/rescode.html#busy): database in use by another process
[SQLITE_NOMEM](https://www.sqlite.org/rescode.html#nomem): out of memory
https://www.sqlite.org/lang_transaction.html#response_to_errors_within_a_transaction
=> Break actor on errors that rollback transactions

src/workerd/api/blob.c++, src/workerd/api/blob.h, src/workerd/api/form-data.c++
The concat operation returning a kj::Array was causing an extraneous data copy. Eliminate the extra copy and simplify a few other bits
=> Avoid unnecessary extraneous copy in blob/file

src/workerd/api/web-socket.c++
See internal PR 10195 for reasoning 😅
=> Remove superflous throw from web-socket handling

build/deps/dep_pyodide.bzl
So we can reuse this logic from edgeworker
=> Python: Bazel setup use @workerd// prefix

.devcontainer/Dockerfile, .github/workflows/_bazel.yml, .github/workflows/release-python-runtime.yml, .github/workflows/release.yml, .github/workflows/type-snapshot.yml, Dockerfile.release, README.md, build/ci.bazelrc, compile_flags.txt, docs/development.md, doxyfile
I hit https://github.com/llvm/llvm-project/issues/67449 similar to https://github.com/dtolnay/cxx/issues/1436 in #3822 
This was fixed in llvm-18: https://github.com/llvm/llvm-project/commit/078651b6de4b767b91e3e6a51e5df11a06d7bc4f
clang-18 is available since Debian stable (bookworm) and Ubuntu LTS (24.04)
=> use llvm 18

types/defines/cf.d.ts, types/defines/images.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
The types for Cloudflare Images are out of date - this updates the types for both RequestInitCfPropertiesImage and the references for images binding.
=> Update types for Cloudflare Images

src/workerd/api/BUILD.bazel, src/workerd/api/modules.c++, src/workerd/api/modules.h, src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h, src/workerd/api/pyodide/requirements.c++, src/workerd/api/pyodide/requirements.h, src/workerd/api/pyodide/setup-emscripten.c++, src/workerd/api/pyodide/setup-emscripten.h, src/workerd/api/rtti.c++, src/workerd/api/rtti.h, src/workerd/server/BUILD.bazel, src/workerd/server/server.c++, src/workerd/server/workerd-api.c++
Spiritual successor to #2811. Resolves downstream's dependency on workerd.capnp.h by moving workerd-only python code into server target.
=================
Decided to do some cleanup to kill time on a flight. This will eliminate workerd.capnp as a superfluous linker input upstream. We also manage to no longer compile requirements.c++ twice.
=> [build] Clean up pyodide target deps and headers, resolving workerd.capnp dependency

src/workerd/io/tracer.c++
=> [o11y] Bump trace size limit to 256KB

src/workerd/api/hibernatable-web-socket.c++, src/workerd/api/node/diagnostics-channel.c++, src/workerd/api/node/util.c++, src/workerd/api/queue.c++, src/workerd/api/tail-worker-test.js, src/workerd/api/trace.c++, src/workerd/api/worker-rpc.c++, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/trace-stream.c++, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/tracer.c++, src/workerd/io/tracer.h, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker.c++, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++, src/workerd/util/own-util.h
- Add rudimentary user tracing support
- Add support for fetch response info, ancillary fields like script tags
- Extend lifetime of outcome event for fetch handler so that exception outcome can be reported correctly.
Upstream PR to follow.
=> [o11y] Expand and refactor STW support

src/workerd/api/http-standard-test.js, src/workerd/util/mimetype.c++
Fixes #3326
Added application/dns-json as a recognized text mimetype to prevent warning messages when calling .text() on a Response with that content type.
Added a test to verify that the warning is no longer triggered.
---
_This PR was assisted by Claude Code_
=> Add application/dns-json to recognized text mimetypes

src/node/internal/internal_tls_wrap.ts
This is making things harder for users that depend on libraries that does not expose default configurations.
=> do not throw on rejectUnauthorized option

src/workerd/api/BUILD.bazel, src/workerd/api/global-scope.h, src/workerd/api/tests/navigator-test.js, src/workerd/api/tests/navigator-test.wd-test, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts
Adding navigator.hardwareConcurrency because it also exists on Node.js. There are libraries that depend on this to run tests etc.
=> add navigator.hardwareConcurrency

src/node/internal/process.ts
This adds non-experimental and non-deprecated features of `process.features` object for nodejs_compat.
=> add process.features* to node:process

build/BUILD.wpt, build/wd_test.bzl, build/wpt_test.bzl, src/workerd/api/node/BUILD.bazel, src/workerd/api/node/tests/net-nodejs-tcp-server.js, src/workerd/api/node/tests/net-nodejs-test.js, src/workerd/api/node/tests/net-nodejs-test.wd-test, src/workerd/api/node/tests/sidecar-supervisor.mjs, src/workerd/api/node/tests/tls-nodejs-tcp-server.js, src/workerd/api/node/tests/tls-nodejs-test.js, src/workerd/api/node/tests/tls-nodejs-test.wd-test, src/wpt/BUILD.bazel, src/wpt/harness/harness.ts
wd_tests can have an optional _sidecar_, which is a script that runs in parallel to the test and exits once the test terminates. This option is so far used to run a backend server so we can test how workerd works as a client. We do this for node:net, node:tls and WPT tests.
Currently, all of these sidecars use hardcoded ports. This is inconvenient in cases where another process is already using that port, and especially in cases where Bazel runs several copies of a test in parallel.
This PR addresses this issue by providing a `num_ports=n` option, which assigns `n` ports to both the sidecar and the test. The assigned ports are passed through environment variables like `PORT_1`, `PORT_2`, etc.  Ports are selected by a NodeJS script (the supervisor) that binds to port 0, checks the assigned …
=> Provide dynamic port assignments for wd_test sidecars

src/workerd/api/memory-cache.h, src/workerd/api/web-socket.h, src/workerd/jsg/iterator.h
These will end up being very minor impact but worth doing. Trades the less memory-efficient std::deque for the slightly less performant but more memory-efficient std::list in a couple of cases.
=> Switch to std::list from std::dequeue in web socket

src/workerd/api/node/zlib-util.c++, src/workerd/api/node/zlib-util.h, src/workerd/api/streams/compression.c++, src/workerd/api/streams/compression.h, src/workerd/jsg/jsg-test.c++, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/setup.c++, src/workerd/jsg/setup.h
The initial implementation of `jsg::ExternalMemoryAdjustment` allowed for some changes in external memory usage to be made without an isolate lock being held. For example, an adjuster could be moved or destroyed at any time. If the isolate is locked, the change is reported immediately to V8. Otherwise, the change can be _deferred_, by storing an atomic value in the jsg Isolate keeping track of pending memory adjustments. The next time the isolate lock is taken, the pending adjustment is reported to V8.
This PR extends this functionality by allowing all memory adjustments, including construction, `adjust()`, and `set()`, to be deferred if needed.
I also created `jsg::ExternalMemoryTarget` which wraps a reference to an isolate, providing a `getAdjustment()` method to construct an …
=> Allow ExternalMemoryAdjustment when isolate lock isn't held

src/workerd/api/html-rewriter.c++, src/workerd/api/tests/htmlrewriter-test.js
This PR follows up on #3758 to provide a more solid fix. 
The chained `writePromise` is no longer used. Instead, every time lol_html generates output, we store it in `outputBuffer` (just a `kj::Vector`). `outputBuffer` is flushed to the output sink after each handler thunk. If more than 128 MB accumulates in `outputBuffer`, we poison the `Rewriter`, preventing users from causing arbitrary memory usage.
As a result of this PR, the test `stackOverflow1` now passes (lots of output from one handler), and `stackOverflow2` continues to pass.
=> HTMLRewriter: no more write promise chaining

src/node/internal/internal_errors.ts, src/node/internal/internal_net.ts, src/node/internal/streams_duplex.js, src/node/internal/streams_writable.js, src/workerd/api/node/BUILD.bazel, src/workerd/api/node/tests/net-nodejs-tcp-server.js, src/workerd/api/node/tests/net-nodejs-test.js, src/workerd/api/node/tests/net-nodejs-test.wd-test, src/workerd/api/node/tests/streams-nodejs-test.js, src/workerd/api/node/tests/streams-nodejs-test.wd-test
- Fixes Duplex.destroy() to use correct method.
- Fixes Writable stream highwaterMark for value 0.
- Fixes `node:net` bytesWritten getter.
- Adds lots and lots of tests.
- Fixes error codes.
- Fixes NodeError messages getting cut
=> improve node:net stability and test coverage

src/workerd/api/crypto/x509.c++, src/workerd/api/kv.c++, src/workerd/api/unsafe.c++, src/workerd/io/trace-stream.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/jsvalue.c++, src/workerd/jsg/jsvalue.h
KJ_MAP will allocate the array of v8::Local<T>'s on the heap which is technically not allowed. While most of these places are not necessarily problematic as is, the general pattern is. Let's prefer to use `v8::LocalVector` where appropriate instead.
=> Use v8::LocalVector where appropriate

src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/node/tests/net-nodejs-test.js, src/workerd/jsg/jsvalue-test.c++, src/workerd/jsg/jsvalue.c++, src/workerd/jsg/jsvalue.h
Browsers do not throw an error when passed NaN value to clearTimeout and clearInterval. On workerd, this throws an error under UBsan builds.
```
src/workerd/io/_virtual_includes/io-helpers/workerd/io/io-timers.h:30:32: runtime error: nan is outside the range of representable values of type 'unsigned long'
```
This fixes this issue.
=> improve clearTimeout and clearInterval compatibility

.bazelrc, src/cloudflare/internal/test/ai/BUILD.bazel, src/cloudflare/internal/test/aig/BUILD.bazel, src/cloudflare/internal/test/autorag/BUILD.bazel, src/cloudflare/internal/test/br/BUILD.bazel, src/cloudflare/internal/test/d1/BUILD.bazel, src/cloudflare/internal/test/vectorize/BUILD.bazel, src/workerd/server/tests/python/BUILD.bazel, src/workerd/server/workerd.c++
We explicitly enable V8's ASan/LSan support here, and add a LSan suppression from the canonical GN build.
=> [build] Run tests previously disabled under ASan

src/workerd/api/basics-test.c++, src/workerd/api/basics.c++
Fixes potential use-after-free, if the underlying kj::HashMap grows enough during iteration to trigger reallocation.
=> EventTarget: Recheck handler map on each handler iteration

src/wpt/BUILD.bazel
Although I was testing the sidecar changes locally with WPT fetch API tests, it turns out I didn't push my local changes. This PR _actually_ re-enables the WPT fetch tests. Sorry for the brainfart.
=> Re-enable WPT fetch tests

build/wpt_test.bzl, src/workerd/api/api-rtti-test.c++, src/workerd/api/global-scope.h, src/workerd/api/urlpattern-standard.h, src/workerd/io/compatibility-date.capnp, src/workerd/tools/param-names-ast.c++, src/workerd/util/autogate.c++, src/workerd/util/autogate.h, src/wpt/BUILD.bazel, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts, types/src/generator/type.ts
This PR adds a new compat flag named `urlpattern_standard` which replaces the URLPattern implementation with Ada backed one. It will be automatically enabled on May 1st, 2025.
Fixes https://github.com/cloudflare/workerd/issues/3533
Fixes https://github.com/cloudflare/workerd/issues/327
=> enable spec-compliant URLPattern under compat flag

src/workerd/api/r2-bucket.c++, src/workerd/api/r2-bucket.h, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
As we move closer to being able to enable the V8 Sandbox hopefully in
the not too distant future, our `kj::Array<kj::byte>` type wrapper impl
will end up either needing to be phased or changed due to the requirement
that all ArrayBuffer/TypedArrays will need to be allocated from within
the isolate rather than using external memory. This change will mean
any APIs that return a `kj::Array<kj::byte>` will cause the array to
be copied into a freshly allocated `ArrayBuffer` rather than wrapped.
Because the `Checksums` property accessors are already copying, if we
kept these methods as is we would end up allocating and copying twice
on every call. Let's no do such silly things. This PR modifies the
accessors to return jsg::BufferSource instances that are allocated within
the isolate, ensuring …
=> Update R2Bucket to use jsg::BufferSource

src/workerd/api/BUILD.bazel, src/workerd/jsg/jsg.c++
Impl of the external memory accounting is being looked at again, temporarily disable use.
=> Temporarily disable string memory accounting

src/workerd/api/node/tests/sidecar-supervisor.mjs
Some CI runners are so slow (looking at you, TeamCity) that we're pre-emptively failing the test while the sidecar is still setting up. This PR removes the custom timeout of 10 attempts to connect to the sidecar. Instead, we'll keep retrying forever until Bazel times out the test itself.
=> Sidecar port assignment: let bazel manage timeouts

src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h, src/workerd/jsg/jsg.h, src/workerd/server/workerd-api.c++
Refactor to have PyodideMetadataReader instances to be created under isolate lock.
Also, avoid a handful of unnecessary string copies and improve some code style in new module registry stuff.
Replace a couple more `jsg::alloc<T>` uses with `js.alloc<T>`
=> Refactor constructor for PyodideMetadataReader and other cleanups

src/workerd/api/BUILD.bazel, src/workerd/jsg/jsg.c++
This reverts commit d5076b98fe64b019c080059116c7030a076b6ba9.
=> Revert "Temporarily disable string memory accounting (#3928)"

src/workerd/api/BUILD.bazel, src/workerd/api/tests/websocket-client-error-sidecar.js, src/workerd/api/tests/websocket-client-error-test.js, src/workerd/api/tests/websocket-client-error-test.wd-test, src/workerd/server/BUILD.bazel, src/workerd/server/server-test.c++, src/workerd/server/server.c++, src/workerd/util/BUILD.bazel, src/workerd/util/websocket-error-handler.c++, src/workerd/util/websocket-error-handler.h
This already works in production and is tested internally.
This commit ports the solution to workerd so that it works in local
development as well.
Websockets can be used with Workers in two main ways:
1. Eyeball connecting to a Worker acting as a websocket server
2. Worker connecting to an origin websocket server
This commit adds test for both of these cases.
=> Convert websocket exceptions to JS exceptions.

src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/tests/global-scope-test.js
Working on incrementally adopting more use of the jsg abstractions where appropriate.
In this case, queueMicrotask really has no reason to use v8::Function directly, and the work to compile the args list was unnecessary since we know the function will be called with no arguments.
=> Update queueMicrotask to use jsg::Function

src/pyodide/python-entrypoint-helper.ts
This will ensure that the asgi module is always present in Python Workers. There is a potential that this is a breaking change, but I _think_ even if a worker defines their own asgi.py module then it will be imported instead of the injected one (local imports have priority over imports from search path in Python), so no breakage here.
=> Python Workers: always inject asgi module.

src/workerd/api/node/tests/tls-nodejs-test.js, src/workerd/api/sockets.c++, src/workerd/api/sockets.h, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
This enables developers to understand why their closed promise is resolving if they call socket.starttls()
=> add upgraded attribute to socket class

src/workerd/api/hyperdrive.c++, src/workerd/api/node/tests/tls-nodejs-test.js, src/workerd/api/sockets.c++, src/workerd/api/sockets.h, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
Build on top of https://github.com/cloudflare/workerd/pull/3945. Please review the last commit only.
Adds a "secureTransport" property to socket class.
=> add secureTransport attribute to socket class

src/workerd/api/basics.c++, src/workerd/api/basics.h, src/workerd/api/tests/abortsignal-test.js, src/workerd/api/tests/abortsignal-test.wd-test
Add AbortSignal test that fails under asan, and also a (possibly incorrect) fix.
It looks like `AbortSignal::any(signals)`:
- creates a new "any" AbortSignal
- for each `sig` in`signals`, adds an "abort" event listener lambda that extracts the abort reason from "sig" and calls `triggerAbort()` on the "any" AbortSignal
The lambda seems to intentionally avoid directly capturing strong references to either "sig" or the "any" AbortSignal.  The rationale for the latter is that `sig.addEventListener(..., {signal})` will itself capture a strong reference to `signal`, but it does not...  It uses `signal` to create an `abortHandler` via `signal->newNativeHandler()`, but `newNativeHandler()` seems to also intentionally avoid capturing strong references to signal.
So if a GC occurs after the last JS …
=> Add AbortSignal test that fails under asan

src/workerd/api/global-scope.c++, src/workerd/io/actor-cache.c++, src/workerd/io/actor-cache.h, src/workerd/io/actor-sqlite.c++, src/workerd/io/actor-sqlite.h
This commit logs periodically when an alarm handler is canceled to debug infinite retries on canceled alarms.
=> Log periodically when an alarm handler is canceled

src/node/internal/internal_tls.ts, src/node/internal/internal_tls_constants.ts, src/node/tls.ts
Adds remaining methods/constants for node:tls so we can make it a fully supported nodejs module.
=> add remaining methods/constants for node:tls

src/wpt/fetch/api-test.ts, src/wpt/harness/harness.ts
* Adds promise_rejects_dom to harness
* Enables the WPT tests for fetch abort.
- Our implementation seems to be quite far off from the spec unfortunately.
=> WPT: Enable fetch/api/abort tests

.github/workflows/_bazel.yml, .github/workflows/test.yml, build/ci.bazelrc
The check "workers-sdk-test" is a required check that depends on "test". 
That means it depends on the entire matrix to succeed. 
In reality it only actually depends on test linux-arm. 
Currently all of "test" is a required check because of it.
Another problem is that it currently only runs once all of "test" succeeds instead of right after it's actual dependencies succeed.
This commit changes that so workers-sdk-test depends only on test-linux. 
A new check that only runs the test on the linux with empty suffix configuration.
This should restore our ability to choose which test jobs are required and which aren't.
=> Speed up workers-sdk-test.

samples/tail-workers/config.capnp, src/workerd/api/tail-worker-test.wd-test, src/workerd/io/trace-stream.c++, src/workerd/io/trace.c++, src/workerd/io/tracer.c++, src/workerd/server/server.c++, src/workerd/util/autogate.c++, src/workerd/util/autogate.h
- Drop obsolete TODO – with the refactored implementation, tracing STWs is already supported.
=> [nfc] Fold up streaming tail worker autogate, use the compat flag instead

src/workerd/api/crypto/crypto.h, src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h, src/workerd/api/url.h, src/workerd/jsg/wrappable.c++, src/workerd/server/workerd-api.c++
Update pyodide sources to replace jsg::alloc with js.alloc
=> Refactor pyodide ArtifactBundler for move to js.alloc

src/workerd/io/BUILD.bazel, src/workerd/io/actor-sqlite-test.c++, src/workerd/io/actor-sqlite.c++, src/workerd/util/autogate.c++, src/workerd/util/autogate.h
Behind a 'reschedule-desynced-sqlite-alarms' autogate.
=> Request that sqlite-backed DO alarms get rescheduled when out-of-sync

build/python_metadata.bzl, src/pyodide/BUILD.bazel, src/workerd/api/pyodide/pyodide-test.c++
* Make development version fully determined from python_metadata.bzl
* Set pyodide_version back to "dev" in development PythonSnapshotRelease data
=> Python: Followup improvements after #3956

src/pyodide/internal/pool/emscriptenSetup.ts, src/pyodide/internal/snapshot.ts, src/pyodide/internal/util.ts, src/pyodide/python-entrypoint-helper.ts
We don't need to call reportError. If we call the function and throw from there, first error stack will include ReportError, which is not ideal. On top of that we don't need to call console.warn on each stack line.
=> simplify error reporting for pyodide

BUILD.bazel
=> remove prettierc bazel setting

src/node/internal/internal_net.ts, src/node/internal/internal_tls_common.ts, src/node/internal/internal_tls_wrap.ts, src/workerd/api/node/tests/net-nodejs-test.js
These options break Redis and mssql client. 
Redis reproduction:
```typescript
import { createClient } from 'redis';
async fetch(request, env, ctx): Promise<Response> {
const client = createClient({})
await client.connect()
await client.hSet('user-session:123', {
name: 'John',
surname: 'Smith',
company: 'Redis',
age: 29
})
const rows = await client.hGetAll('user-session:123');
// Return the result as JSON
const resp = new Response(JSON.stringify(rows), {
headers: { "Content-Type": "application/json" },
});
return resp;
},
} satisfies ExportedHandler<Env>;
```
Mssql reproduction:
```typescript
import sql from 'mssql';
async fetch(request, env, ctx): Promise<Response> {
const config = {}
const conn = await sql.connect(config);
const rows = await …
```
=> ignore certain values for nodejs redis and mssql client

build/wpt_test.bzl, justfile, src/wpt/harness/harness.ts
* Adds new recipe to justfile, `just new-wpt-test test_name` that automatically writes the needed boilerplate for Bazel/Typescript to get the new test running.
* Adds a new environment variable `GEN_TEST_CONFIG=1`. If specified, the harness will print out an initial test config for the new test suite, at the end of the test output. For example,
```typescript
// Copyright (c) 2017-2022 Cloudflare, Inc.
// Licensed under the Apache 2.0 license found in the LICENSE file or at:
//     https://opensource.org/licenses/Apache-2.0
import { type TestRunnerConfig } from 'harness/harness';
"aborting.any.js": {},
"bad-strategies.any.js": {},
"bad-underlying-sinks.any.js": {},
"byte-length-queuing-strategy.any.js": {},
"close.any.js": {},
"constructor.any.js": {}, …
```
=> Add just new-wpt-test to generate initial config

src/workerd/io/io-context.h
In WorkerEntrypoint::request, we set up draining as part of the returned promise. But if an exception is thrown by IoContext::run separately from the returned promise, the IncomingRequest is dropped during unwinding without draining! So with this we just wrap context.run in evalNow to make sure any thrown exceptions are caught.
=> Return abort exception error through promise in IoContext::run()

src/workerd/api/global-scope.c++
For Python Workers the global scope is instantiated before a Worker::Isolate is created and with just a plain jsg::Lock rather than a Worker::Isolate::Lock. That means FeatureFlags::get(js) will fail.
Having this KJ_REQUIRE here does not serve any purpose as these APIs are already behind a compat flag in the JSG_RESOURCE definition.
There's something to be said about whether FeatureFlags::get(js) should even rely on Worker::Isolate::Lock but that does not need to be resolved in this PR. This PR is meant to provide an immediate fix to allow Python Workers to set nodejs_compat_v2.
=> Fix Python Workers when nodejs_compat_v2 is enabled.

src/workerd/api/basics.c++, src/workerd/api/basics.h, src/workerd/api/eventsource.c++, src/workerd/api/http.c++, src/workerd/api/streams/internal.c++, src/workerd/api/streams/readable.c++, src/workerd/api/streams/standard.c++, src/workerd/api/streams/writable.c++, src/workerd/api/tests/abortsignal-test.js, src/workerd/api/tests/abortsignal-test.wd-test, src/workerd/api/tests/js-rpc-test.js, src/workerd/api/worker-rpc.c++, src/workerd/api/worker-rpc.h, src/workerd/io/worker-interface.capnp
Step right up folks, that's right, we've got abort signals that you can pass over RPC.
Now you can create an abort controller, then pass the signal to a function over RPC so you can tell it to abort later.
```js
export class VeryUseful extends WorkerEntrypoint {
async countToInfinity(signal) {
for (let i = 0; ; i++) {
if (signal.aborted) {
return i;
}
}
const ac = new AbortController();
const promise = env.VeryUseful.countToInfinity(ac.signal);
while (Math.random() <= .9)
;
ac.abort();
console.log("We got to", await promise);
```
Please let me know if you can think of any more tests this PR is missing.
=> Make AbortSignal cloneable

src/workerd/api/BUILD.bazel, src/workerd/api/self-logger-test.js, src/workerd/api/self-logger-test.wd-test, src/workerd/server/server.c++
This gets around the current limitation by allowing exactly one extra layer of depth. 
This should be enough for any real use case. 
Tail workers can now tail the same worker but they will not tail themselves. 
I believe this is what users would expect and is similar to what they get in prod.
=> Local dev: allow tailing the same worker

.github/CODEOWNERS
Based on previous discussions, I know we need to ask the Wrangler team to look at generated type changes. 
I'm wondering if it would be ok for us to be able to just change experimental types, though? It seems like we're using this for internal stuff that shouldn't affect users.
Happy to close this if it's not a good idea
=> Speed up reviews for experimental type changes

src/workerd/api/BUILD.bazel, src/workerd/api/basics.h, src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/tests/request-client-disconnect.js, src/workerd/api/tests/request-client-disconnect.wd-test, src/workerd/io/compatibility-date.capnp, src/workerd/io/worker-entrypoint.c++, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++
This PR re-enables the support for `Request.signal` on incoming requests that I originally added in #3488 and #3727. These changes were originally reviewed and approved in those PRs.
However, these changes caused a regression in production and had to be reverted in #3735. AbortSignals were never cloneable, and trying to clone any Request with the `signal` property set would fail. But with my PR, the `signal` property was now always set in a very common case, the request received by a worker in its fetch handler.
AbortSignal will now be cloneable once #3922 is merged. The second commit to this PR adds a regression test which now fails but will work once #3922 is merged.
=> Re-merge Request.signal PR

build/deps/gen/dep_capnp_cpp.bzl, src/workerd/api/basics.c++, src/workerd/api/container.c++, src/workerd/api/queue.c++, src/workerd/api/streams/standard.c++, src/workerd/io/actor-cache.c++, src/workerd/io/io-context.c++, src/workerd/io/worker-interface.c++, src/workerd/server/server.c++
This eliminates some memory allocations for promise continuations and improves code size.
See capnp PR for context: https://github.com/capnproto/capnproto/pull/2286
=> [nfc] Use Request::sendIgnoringResult() to elide promise continuations

src/workerd/api/node/zlib-util.c++
Fixes #4022.  
For regular member functions, we can just explicitly instantiate the template for the entire class, instead of listing each function signature. However, if the member function has template arguments of its own, it still needs to be listed separately.
@anonrig Could you please check that this works locally for you as well - I don't want to end up swapping one linker problem for another.
=> Fix explicit template instantiations in zlib-util.c++

src/node/internal/filesystem.d.ts, src/workerd/api/BUILD.bazel, src/workerd/api/filesystem.c++, src/workerd/api/filesystem.h, src/workerd/api/node/BUILD.bazel, src/workerd/api/node/filesystem.c++, src/workerd/api/node/filesystem.h, src/workerd/api/node/node.h, src/workerd/api/rtti.c++, src/workerd/io/BUILD.bazel, src/workerd/server/workerd-api.c++
> Work in progress.
Example usage internal usage:
- fs.getResource() will return different classes that extend from "Node" class depending on the root path of the file.
```typescript
import { default as fs } from 'node-internal:filesystem';
const resource = fs.get('/bundle/hello.jpeg');
resource.getStat() // Returns: { name, ... }
resource.asyncOnly;
resource.syncOnly;
resource.readable;
resource.writable;
const fd = resource.getFd();
fd.close();
``
=> add node:fs base classes

.github/workflows/daily-release.yml
This should avoid superfluous releases being published on weekends.
=> [ci] Do not publish automated releases when there are no changes since last auto-release

src/workerd/api/form-data-memory-test.c++, src/workerd/api/headers-test.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/resource.h, src/workerd/jsg/rtti.h
[nfc] minor JSG simplifications to improve compile times
Cleaning up this and similar structures will help reduce code size since lots
of downstream code inherits from it.
[nfc] JSG memory tests: Only include required types
This makes the test binaries much smaller.
============
Cleaning up some old branch/stashes. Review this using `git diff -w` for clarity.
=> [nfc] Assorted JSG simplifications

src/workerd/server/server.c++
C++ tests have a small note specifying the elapsed time of each test within the suite. Although workerd's JS test output is similar, it didn't previously include the duration. The value is automatically specified in an appropriate unit (e.g. us, ms, s)
Example output:
```
workerd/server/server.c++:4351: debug: [ PASS ] WebCryptoAPI:import_exportOkp_importkey_x448HttpsAny (634μs)
workerd/server/server.c++:4338: debug: [ TEST ] WebCryptoAPI:import_exportRsa_importkeyHttpsAny
workerd/server/server.c++:4351: debug: [ PASS ] WebCryptoAPI:import_exportRsa_importkeyHttpsAny (1.864743s)
workerd/server/server.c++:4338: debug: [ TEST ] WebCryptoAPI:import_exportSymmetric_importkeyHttpsAny
workerd/server/server.c++:4351: debug: [ PASS ] WebCryptoAPI:import_exportSymmetric_importkeyHttpsAny …
```
=> Add test duration to wd-tests too

build/wpt_test.bzl, src/wpt/BUILD.bazel, src/wpt/WebCryptoAPI-test.ts, src/wpt/encoding-test.ts, src/wpt/fetch/api-test.ts, src/wpt/harness/harness.ts
* Support functions from several `/common/` files:
- gc.js
- sab.js (SharedArrayBuffer)
- subset_tests.js
* Stub implementation of `format_value`
* `expectedFailures` and `skippedTests` can now contain regexes if WPT generates a pile of similar error messages.
Now that we're running everything in WebCryptoAPI, there are two effects:
1. We can remove the ad-hoc WPT-derived tests from the internal repo, as these will be easier to keep maintained.
2. The tests are now pretty slow, and take more than 60 s to run so they might time out in CI. I'm not sure what the best solution would be...
=> WPT test harness improvements

src/workerd/api/tail-worker-test.js, src/workerd/io/trace-stream.c++, src/workerd/io/tracer.c++
- [o11y] Support STW event scheduledTime
- [o11y] Support env in tailStream
The ctx argument will be suported in a follow-up.
- [o11y] Provide unique span IDs for streaming tail worker
- [o11y] Add initial timestamp support
We might do this completely differently (possibly providing tracee time instead of tracer time), but having timestamps available aids evaluation.
=> [o11y] Support more STW features

src/pyodide/python-entrypoint-helper.ts, src/workerd/server/tests/python/durable-object/worker.py
Allows us to define entrypoint class handlers that take fewer than 4 arguments.
=> Python: Make a relaxed call to Python entrypoint class handlers

src/pyodide/internal/metadata.ts, src/pyodide/python-entrypoint-helper.ts, src/pyodide/types/Pyodide.d.ts
We should also make `MetadataReader.getPyodideVersion()` return the right value so we can have conditional code before the runtime is loaded, but for now we don't need it.
=> Python: Repalce USING_OLDEST_PYODIDE_VERSION with pyodide.version, NFC

src/pyodide/internal/python.ts, src/pyodide/internal/util.ts, src/pyodide/python-entrypoint-helper.ts
This is a partial revert of #4001. Without this help, edgeworker tests show:
```
2.267743795s	1m10	2025.4.1200-4-gdecc02ecd-dev error   workerd/io/worker.c++:287
script startup threw exception; id = 79b9b0009762ad21278ebf245600582fefcdd203d9aeb3efaa2105eb948f6b2f;
description = jsg.TypeError: Cannot read properties of undefined (reading 'snapshotSize');
trace =   at pyodide-internal:snapshot:140:43; ownerId = 1212; zoneId = test-zone;
scriptId = m.python; cordon = paid; process = shared
```
AKA not a traceback, and not even the name of the function the error occurred in. With this help, we get a nice traceback in the edgeworker logs.
cc @anonrig
=> Python: Add back in reportError

src/workerd/api/crypto/ec.c++, src/workerd/api/crypto/hkdf.c++, src/workerd/api/crypto/pbkdf2.c++, src/wpt/BUILD.bazel, src/wpt/WebCryptoAPI-test.ts
- [HKDF, PBKDF2: Allow outputLen = 0 to conform to spec](https://github.com/cloudflare/workerd/commit/b8d006da6c97e4df44d60f9513c9e0ecd4c229dd)
- [EllipticKey, EdDsaKey: Fix memory corruption for outputLen = 0](https://github.com/cloudflare/workerd/commit/ce42e23e125b07222bda922b5caf27bca42108e9)
=> deriveBits: Fix incorrect behaviour when outputLen = 0

src/workerd/api/trace.h, src/workerd/io/trace-stream.c++, src/workerd/io/trace-test.c++, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/tracer.c++, src/workerd/io/worker-interface.capnp, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts
The definitions differed by having int32_t or int64_t, respectively.
=> [o11y] Harmonize span tag types between existing tracing and user tracing/Streaming Tail Worker

src/workerd/api/actor-state.h, src/workerd/api/basics.h, src/workerd/api/blob.h, src/workerd/api/crypto/impl.h, src/workerd/api/crypto/kdf.h, src/workerd/api/global-scope.h, src/workerd/api/http.h, src/workerd/api/memory-cache.h, src/workerd/api/node/buffer-string-search.h, src/workerd/api/pyodide/requirements.h, src/workerd/api/queue.h, src/workerd/api/sockets.h, src/workerd/api/streams/common.h, src/workerd/api/trace.h, src/workerd/io/actor-cache.h, src/workerd/io/io-context.h, src/workerd/io/io-own.h, src/workerd/io/trace.h, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/jsg/function.h, src/workerd/jsg/jsg.h, src/workerd/jsg/promise.h, src/workerd/jsg/resource.h, src/workerd/jsg/setup.h, src/workerd/jsg/type-wrapper.h, src/workerd/jsg/util.h, src/workerd/util/sqlite-kv.h
While typedef works just fine, I don't think we need two different syntaxes for doing the same thing in our codebase.
=> Use using instead of typedef for consistency

src/pyodide/internal/loadPackage.ts, src/pyodide/internal/metadata.ts, src/pyodide/internal/python.ts, src/pyodide/internal/setupPackages.ts, src/pyodide/python-entrypoint-helper.ts, src/pyodide/types/runtime-generated/metadata.d.ts, src/workerd/api/pyodide/pyodide.h, src/workerd/server/workerd-api.c++
LOAD_WHEELS_FROM_ARTIFACT_BUNDLER, has become equal to !IS_WORKERD and LOAD_WHEELS_FROM_R2 has become equal to !IS_WORKERD. So I removed these two variables and all code behind `!LOAD_WHEELS_FROM_R2 && !LOAD_WHEELS_FROM_ARTIFACT_BUNDLER` which is always `false`.
=> Python: Clean up package loading, NFC

src/pyodide/internal/metadata.ts, src/pyodide/internal/python.ts, src/pyodide/internal/snapshot.ts, src/pyodide/types/artifacts.d.ts, src/pyodide/types/emscripten.d.ts, src/pyodide/types/runtime-generated/metadata.d.ts, src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h
This reduces the number of global variables in `snapshot.ts` from 8 to 2. The two new global variables are `LOADED_SNAPSHOT_META` which contains information about a snapshot we loaded and `CREATED_SNAPSHOT_META` which contains information about a snapshot we are in the process of creating.
=> Python: Clean up state in snapshot.ts, NFC

package.json
This is required because we're using pnpm>=10
=> add esbuild to pnpm onlyBuiltDependencies

.bazelrc, tools/cross/format.py
Before this trying to format workerd from the internal repo on an ew-rosetta machine would fail with a non-descriptive: 
`ERROR: Config value 'rosetta-arm64' is not defined in any .rc file` 
This commit makes the error message a bit more descriptive but also fixes the issue by defining a small no-op config for rosetta-arm64.
=> [NFC] Enable formatting workerd in ew-rosetta

src/workerd/jsg/util.h
on all functions (except v8 fast api), handleScope is created automatically. this pull-request avoids creating the handleScope twice.
This change improves the performance by **20-25%!!!** (on all functions in workerd)
- Before
```
SlowAPI             348050 ns       348007 ns         1976
SlowAPIWithLock     300119 ns       300090 ns         2299
```
- After
```
SlowAPI             291597 ns       291551 ns         2410
SlowAPIWithLock     239857 ns       239840 ns         2845
```
=> remove duplicate handleScope creation

src/workerd/api/tail-worker-test-dummy.js, src/workerd/api/tail-worker-test-invalid.js, src/workerd/api/tail-worker-test-receiver.js, src/workerd/api/tail-worker-test.js, src/workerd/io/trace-stream.c++, src/workerd/io/trace-test.c++, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/tracer.c++
- [o11y] Support ctx attribute in tailStream(), clarify that only one event is passed at a time
- [o11y] Provide parent span ID in SpanOpen event
API design may still change here, so this is isolated in one commit to make reverting easier if needed.
=> [o11y] Support ctx attribute in tailStream(), clarify that only one event is passed at a time

src/workerd/io/io-context.c++, src/workerd/io/io-context.h
Debugging is hard if you don't know who's dropping requests. However, getting a stack trace on destruction is expensive. So to help with debugging missing `IncomingRequest`, we can instead pass the `SourceLocation` of the caller of `delivered()` and use that instead. That should at least help with identifying what the last request was that was handled in an agnostic way.
=> Add source location for the last delivered() IncomingRequest

src/pyodide/internal/workers.py, src/pyodide/python-entrypoint-helper.ts, src/workerd/server/tests/python/BUILD.bazel, src/workerd/server/tests/python/python-rpc/python-rpc.wd-test, src/workerd/server/tests/python/python-rpc/worker.js, src/workerd/server/tests/python/python-rpc/worker.py
Relatively large PR which introduces Workers RPC support for Python. The aim is to make it easy to call functions defined in other Python and JS Workers, to do this all arguments are converted to/from JS where appropriate.
The implementation relies on a number of wrappers as well as conversion functions:
* The binding `env` object is wrapped via the `handler` decorator, it gets wrapped in a class that intercepts calls to `Fetcher` bindings (i.e. `env.ServiceBinding`) and then another class that intercepts calls made on that binding. All arguments passed to these calls are wrapped in a call to `serialize_to_js` and the returned value from the call is wrapped in a call to `serialize_to_python`.
* The `serialize_to_python` and `serialize_to_js` functions convert Python and JS arguments to JS …
=> Implements Python RPC + test suite.

src/workerd/api/basics.c++
We're going to have to put AbortSignal RPC support behind a compat flag ASAP, because it spuriously causes the outcome of a request to show `exception` even though things work fine. First we need to make sure no one is using this feature.
=> Log whenever AbortSignal is used over RPC

src/workerd/api/node/tests/process-exit-test.js, src/workerd/api/sql-test.js, src/workerd/api/unsafe.c++, src/workerd/api/worker-rpc.h, src/workerd/io/io-channels.h, src/workerd/io/io-context.h, src/workerd/io/worker-interface.c++, src/workerd/io/worker-interface.h, src/workerd/server/server-test.c++, src/workerd/server/server.c++, src/workerd/server/server.h, src/workerd/server/tests/unsafe-module/unsafe-module-test.js
This started with me refactoring the actor handling in `server.c++` to make it more amenable to changes I want to make.
Along the way, I realized there were actual bugs here, and fixed a few:
1. In production, when an actor becomes broken, all existing stubs become broken. Reusing the stubs continuously throws the same error. But in workerd, this was not the case: instead, the next call on a stub would start a new instance of the actor, "fixing itself". It's important that workerd match production so that people can properly test their code, so this fixes the bug.
2. RPC calls on broken stubs were producing "internal error", and under the hood a "PromiseFulfiller was never fulfilled" Sentry error. They should now rethrow the correct exception. (This affects production, too.)
3. The type …
=> Refactor actor handling in workerd, including some bugfixes

.bazelrc, WORKSPACE, build/deps/deps.jsonc, build/deps/gen/dep_com_google_protobuf.bzl, build/deps/v8.bzl, compile_flags.txt, src/pyodide/helpers.bzl
This is the name under which abseil is available in Bazel Central Registry, working towards transitioning to bzlmod.
=> EW-9223 Transition abseil dependency to canonical name

src/workerd/io/trace-stream.c++, types/defines/trace.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
This should be easier to process in the tail worker. Note that only the JS side is updated and we still use a plain array internally, this makes this change simpler and avoids needing e.g. capnp definition changes.
Alongside this change, update the name of the handler for these events to "attributes", which is more descriptive.
=> [o11y] Update Streaming Tail Worker Attributes definition

types/defines/rpc.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
corresponding workers-sdk PR: https://github.com/cloudflare/workers-sdk/pull/9179
the Cloudflare namespace was conflicting with the Cloudflare global when both generated types and @cloudflare/workers-types existed. This renames the namespace (not user facing) to CF to prevent this.
=> Rename Cloudflare namespace in types to CF

src/pyodide/helpers.bzl, src/pyodide/internal/pool/builtin_wrappers.ts, src/pyodide/types/emscripten.d.ts
This is a fix for a problem with package snapshots in 0.26.0a2. 0.26.0a2 tests if wasm-type-reflection is supported by the runtime and if so uses it to avoid function pointer casting instead of a JS trampoline. We cannot stack switch through the JS trampoline so we need to make sure that when stack switching is available, we don't use JS trampolines. When 0.26.0a2 was released, wasm-stack-switching implied wasm-type-reflection.
Unfortunately there is a bug (fixed in 0.26.0a3...) that made the assumption that if the runtime that we use to make a snapshot supports wasm-type-reflection, the runtime we use it in will too.
Later, JSPI was rewritten not to depend on wasm-type-reflection, but the implication was left in the v8 codebase until a few weeks ago. So our snapshots expect to be able to …
=> Python: Fix 0.26.0a2 package snapshots against v8 13.7

types/defines/rpc.d.ts, types/generated-snapshot/2021-11-03/index.d.ts, types/generated-snapshot/2021-11-03/index.ts, types/generated-snapshot/2022-01-31/index.d.ts, types/generated-snapshot/2022-01-31/index.ts, types/generated-snapshot/2022-03-21/index.d.ts, types/generated-snapshot/2022-03-21/index.ts, types/generated-snapshot/2022-08-04/index.d.ts, types/generated-snapshot/2022-08-04/index.ts, types/generated-snapshot/2022-10-31/index.d.ts, types/generated-snapshot/2022-10-31/index.ts, types/generated-snapshot/2022-11-30/index.d.ts, types/generated-snapshot/2022-11-30/index.ts, types/generated-snapshot/2023-03-01/index.d.ts, types/generated-snapshot/2023-03-01/index.ts, types/generated-snapshot/2023-07-01/index.d.ts, types/generated-snapshot/2023-07-01/index.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/oldest/index.d.ts, types/generated-snapshot/oldest/index.ts
Reverts cloudflare/workerd#4110
turns out it was user-facing 😅 
see: https://github.com/cloudflare/workers-sdk/pull/9179#pullrequestreview-2825546001
=> Revert "Rename Cloudflare namespace in types to CF"

npm/workers-types/README.md
Wrangler v4 will turn on dynamic runtime type gen by default in the`wrangler types` command, which we will recommend over @cloudflare/worker-types. This PR updates the package readme to reflect this. 
(also fixes an image link that was broken on npm)
=> chore: update workers-types package README

src/pyodide/internal/introspection.py, src/pyodide/internal/workers.py, src/pyodide/python-entrypoint-helper.ts, src/pyodide/python-entrypoint.js
Turns out WorkerEntrypoint support for Python is broken due to the validator needing to know at least one method that it exports. This should fix it.
=> Fixes WorkerEntrypoint methods not being reported in validator.

src/workerd/api/tests/new-module-registry-test.js, src/workerd/jsg/modules-new-test.c++, src/workerd/jsg/modules-new.c++, src/workerd/jsg/modules-new.h, src/workerd/server/server.c++, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h
Extracted from the larger workerd PR #4029 to help split that up more... updates the new module registry to use a consistent view of the `file:///bundle` file root.
=> Update new modules registry to align with vfs

src/workerd/io/promise-wrapper-test.c++, src/workerd/jsg/fast-api-test.c++, src/workerd/jsg/fast-api.h, src/workerd/jsg/jsg-test.h, src/workerd/jsg/resource-test.c++, src/workerd/jsg/resource.h, src/workerd/jsg/type-wrapper.h, src/workerd/jsg/util-test.c++, src/workerd/jsg/value-test.c++
This pull-request removes support for using v8::Isolate* type as a parameter. Also starting from this pull-request, we no longer check for the parameter types in order to detect if a function is fast api compatible or not, because in reality everything is v8::Local<v8::Value>...
- v8::Isolate* - we can do the same thing via jsg::Lock&, and actually v8::Isolate* parameter is equal to js.v8Isolate parameter. so there is no need to have this
=> simplify type-wrapper by removing support from certain types

src/pyodide/python-entrypoint-helper.ts
Methods like `scheduled` aren't special in DO/RPC, so we do not proxy them to `on_scheduled`. But there are also other methods that we haven't been proxying.
This is just a quick PR to fix this.
=> Fix the list of proxied special methods for DO/RPC in Python.

src/pyodide/internal/workers.py, src/workerd/server/tests/python/durable-object/worker.py
Specifically the error is:
```
workerd/io/worker.c++:2116: info: uncaught exception; source = Uncaught (in promise); stack = PythonError: Traceback (most recent call last):                                                                                                                            
File "/lib/python3.12/site-packages/workers.py", line 905, in wrapper                                                                                                                                                                                                  
py_args = [python_from_rpc(arg) for arg in args] …
```
=> Fixes regression in Python DO on_alarm handling.

src/workerd/api/basics.c++, src/workerd/api/tests/abortsignal-test.wd-test, src/workerd/api/tests/js-rpc-socket-test.wd-test, src/workerd/api/tests/js-rpc-test.wd-test, src/workerd/io/compatibility-date.capnp
There were zero instances of the log message "An AbortSignal was serialized for RPC" over the weekend, so it seems like no one was relying on this feature.
Put it behind the compat flag `enable_abortsignal_rpc` so as to avoid users being surprised by odd behaviours.
=> Put AbortSignal RPC behind a compat flag

src/pyodide/internal/introspection.py, src/pyodide/internal/workers.py, src/pyodide/python-entrypoint-helper.ts, src/pyodide/types/Pyodide.d.ts, src/workerd/server/tests/python/durable-object/worker.py
Turns out we are incorrectly wrapping calls within RPC classes. This PR fixes that.
```
bazel run @workerd//src/workerd/server/tests/python:durable-object_development@
```
=> Fixes wrapping of Python to Python calls.

.bazelrc, WORKSPACE, build/rust_toolchains.bzl, src/rust/BUILD.bazel, src/rust/cxx-integration-test/lib.rs, src/rust/cxx-integration/tokio.rs, src/rust/gen-compile-cache/main.rs, src/rust/python-parser/lib.rs, src/rust/rustfmt.toml, src/workerd/tools/param-extractor.rs
will keep everything consistent.
Also extracted rust_toolchains.bzl while I'm at it (separate commit)
=> adopting downstream's rustfmt rules

.bazelrc
When using LLVM20, we receive certain errors. This follows the same pattern of EW changes.
=> ignore llvm20 warnings

src/workerd/api/BUILD.bazel, src/workerd/api/tests/worker-test.js, src/workerd/api/tests/worker-test.wd-test, src/workerd/io/compatibility-date.capnp, src/workerd/io/worker.c++
Enables the usage of `eval()` and `new Function()` on startup phase of the main module. Potentially enabling libraries such as Fastify to be used within Cloudflare Workers.
Starting June 1st, 2025, the following code works:
```js
strictEqual(eval('1+1'), 2);
// or even this
strictEqual((await import('module-that-has-eval-in-it)).default, 2);
async fetch(request, env, ctx) {
return new Response('Hello World!');
},
};
```
=> enable eval() and new Function on startup

src/workerd/io/trace-stream.c++, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/tracer.c++, src/workerd/io/worker-interface.capnp
1st commit is a refactor – should be slightly less efficient (one more branch per loop iteration) but that is negligible.
2nd commit should resolve some of the span timestamp/parent span issues we've seen in testing. No downstream changes are required. As noted in the TODOs, this is needed since we don't have instrumentation at span creation time and span context propagation is incomplete – synthesizing the span events at the end is much easier for now than to build those things and will unblock evaluation on the edge.
=> [o11y] Improve span tracing support, using CompletedSpan internally for now

src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/resource.c++, src/workerd/jsg/resource.h, src/workerd/jsg/setup.c++, src/workerd/jsg/setup.h
Remove obsolete stuff relating to `Symbol.asyncDispose`/`Symbol.dispose`. Once we update workerd to 13.7 we should be able to drop the additional patches that polyfill the `GetDispose()` and `GetAsyncDispose()` APIs.
=> Cleanup the AsyncDispose symbols

src/workerd/api/streams/internal.c++, src/workerd/api/urlpattern-standard.c++, src/workerd/jsg/function.h, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/jsvalue.h, src/workerd/jsg/ser.c++
Direct use of `v8::Isolate::GetCurrent()` is something that we've tried to avoid but does creep in every so often. Let's provide a more useful utility to avoid it a bit better.
=> Add jsg::Lock::current() to replace v8::Isolate::GetCurrent()

src/workerd/api/streams/compression.c++, src/wpt/compression-test.ts
Returning a TypeError here fixes some WPT test failures. Also add a TODO for enabling tests we'll soon be able to support.
===============
This should not require a compat flag as discussed in chat – we're merely changing the error type when the user provides invalid data to be decompressed. (We also change the error code when compression fails, but this check is more of an internal safeguard, it should only be triggered if there is a bug in our implementation).
=> Improve spec compliance for Compression Streams API

src/workerd/api/tests/js-rpc-test.js, src/workerd/api/worker-rpc.c++, src/workerd/io/io-context.c++, src/workerd/io/io-context.h
This introduces `IoContext::makeReentryCallback()`, which takes a function intended to run under the isolate lock, and returns a function which can be invoked _outside_ the lock, and which will do all the necessary things to enter the isolate. This has proven more complicated than it looks. See the doc comment for details.
I created this for a different use case, but in this PR I went ahead and used it to clean up how JsRpcTarget works, as I was fairly unhappy with the existing code.
This fixes at least one bug with RPC: If you made an RPC call during blockConcurrentlyWhile, and passed it a callback, calls to the callback would be blocked until the end of blockConcurrencyWhile. This goes against the usual semantics of blockConcurrencyWhile, which says that interactions initiated from …
=> Refactor how RPCs are delivered

src/workerd/jsg/value.h
Small optimization to get rid of unnecessary ToString() on a string.
=> avoid string coercion as much as possible

src/workerd/jsg/setup.c++, src/wpt/compression-test.ts
These will be enabled by default starting from Node.js v24.
=> enable v8's explicit-resource-management and float16array

src/workerd/io/compatibility-date.capnp, src/workerd/io/worker-entrypoint.c++, src/workerd/server/server-test.c++
See comments in compatibility-date.capnp for explanation. Miniflare needs this.
cc @penalosa
=> Implement connect_pass_through experimental compat flag.

src/workerd/jsg/fast-api.h, src/workerd/jsg/type-wrapper.h, src/workerd/jsg/value.h
Ref: https://groups.google.com/g/v8-dev/c/VVwE1vp0zKw
It seems FastOneByteString is a lot faster than Local<Value>
=> use v8::FastOneByteString instead of Local<Value>

src/workerd/jsg/fast-api-test.c++, src/workerd/jsg/fast-api.h
Disallow kj::promise for now to understand if it's causing an issue with v8 fast api.
=> disallow kj::Promise in v8 fast api

src/wpt/streams-test.ts
Making sure that the tests we have in workerd cover everything that was tested in the internal copy of the WPT tests.
=> WPT streams: enable more subtests

src/workerd/server/tests/weakref/BUILD.bazel
It flakes for the default timeout size 15 seconds.
=> increase timeout duration of js-weak-ref-test

.github/workflows/deps-updater.yml
Let's roll our own dependency updater
=> add automatic dependency updater

src/pyodide/internal/workers.py, src/workerd/server/tests/python/durable-object/worker.py, src/workerd/server/tests/python/python-rpc/worker.py
This is to match behaviour with JS which does initialise these.
=> Initialise ctx/env fields on Python entrypoint superclass constructors.

src/wpt/compression-test.ts
A small handful of the WPT compression tests fetch files from the wptserve backend. However, starting the sidecar is relatively slow and it's only worth doing it if we have a bunch of tests like the fetch/api tests. 
This PR properly skips the tests, because some of them spuriously pass on Windows. Today, @erikcorry also had spurious passes on Unix.
=> Cleanly disable WPT compression tests that require sidecar

src/workerd/server/tests/server-harness.mjs, src/workerd/server/tests/weakref/BUILD.bazel, src/workerd/server/tests/weakref/test.mjs
This test timing out is quite weird - presumably happens because of unclean process exit, since the worker doesn't have anything which would cause it to "hang" necessarily. The CI logs also possibly point to the same problem that I'm hypothesizing:
```
==================== Test output for //src/workerd/server/tests/weakref:js-weak-ref-test:
TIMEOUT: //src/workerd/server/tests/weakref:js-weak-ref-test (Summary)
TAP version 13
/private/var/tmp/_bazel_runner/95172a8db72435c774c2789dc64209fb/execroot/_main/bazel-out/darwin_arm64-fastbuild/testlogs/src/workerd/server/tests/weakref/js-weak-ref-test/test.log
workerd/server/server.c++:3994: info: Inspector is listening
INFO: From Testing //src/workerd/server/tests/weakref:js-weak-ref-test:
workerd/server/server.c++:3994: info: Inspector is …
```
=> Verbose logging to debug flaky weakref tests

src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h
This is a continuation of #4082. I had left `ScriptSource` still containing a weird callback because I didn't think I needed to update it. Turns out I do actually need to update it to avoid some ugliness later.
Luckily this turned out to be a much smaller refactor. I would have done it in the first place had I realized.
=> Refactor: Give Worker::Script::ScriptSource same treatment as ModulesSource.

build/deps/v8.bzl, patches/v8/0023-Add-more-sandbox-APIs.patch, src/workerd/jsg/buffersource.h, src/workerd/jsg/jsg.h, src/workerd/jsg/setup.c++, src/workerd/jsg/value.h
Reallocate ArrayBuffer backings if they are not in the correct sandbox.
If sandbox is not in use, the SandboxContains call always returns true, and no action is taken.
=> Changes to support sandboxing

src/workerd/api/node/node.h, src/workerd/api/rtti.c++, src/workerd/jsg/modules.h
Allows us to selectively register built-in modules from a capnp bundle... for instance, to allow us to selectively register certain modules when the experimental flag is enabled.
This can be used, for instance, to allow us to land `node:fs` and `node:http` work-in-progress without that impacting production before we're ready.
=> Add addBuiltinModule variant with filter function

src/workerd/jsg/modules-new-test.c++, src/workerd/jsg/modules-new.c++, src/workerd/jsg/modules-new.h, src/workerd/server/BUILD.bazel, src/workerd/server/fallback-service.c++, src/workerd/server/fallback-service.h, src/workerd/server/server.c++, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h, src/workerd/server/workerd.capnp
Adds fallback service support, with a new POST based implementation for the fallback service,
Adds extension module support,
Enables registering the module registry for service worker syntax so things like the internal use of `node:util` inspect can be used for improved console output locally just like when using ESM syntax workers.
Moves the fallback service implementation out of server.c++ to a separate compilation unit.
=> Implement fallback service support for new module registry impl

src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/kv-test.js, src/workerd/api/kv-test.wd-test, src/workerd/api/kv.c++, src/workerd/api/kv.h, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts
Adding temporary `deleteBulk` method would allow us to test our JSRPC implementation before replacing `delete` method for the binding.
=> feat: Add deleteBulk method for JSRPC testing

.github/workflows/deps-updater.yml
Instead of running with the default GITHUB_TOKEN, we now run with the DEVPROD_PAT.
I also added a manual trigger, so we can create a roll deps PR any time.
=> Update deps updater so it can trigger workflow runs

.github/workflows/cla.yml
If we can't trust our own bot, who can we trust?
=> Allow workers-devprod to bypass CLA

src/cloudflare/internal/workflows.d.ts, types/defines/rpc.d.ts, types/defines/workflows.d.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/latest/index.d.ts, types/generated-snapshot/latest/index.ts
Related to WOR-638
We need to expose `InstanceRetention` as an additional field to `WorkflowInstanceCreateOptions`, thus allowing custom retention periods through binding-shim.
=> feat: Add `WorkflowRetentionDuration` to `WorkflowInstanceCreateOptions`

src/workerd/api/sockets.h, src/workerd/api/sql-test.js, src/workerd/api/sql.c++, src/workerd/api/sql.h, src/workerd/server/server-test.c++
Start making some api types disposable starting with Socket and Sql Cursor. This is really just to demonstrate how we can start making some of our types supports dispose/async dispose. We don't have many types that actually have a lifecycle in which disposal is relevant but the few we do have can be adapted easily.
example:
```js
await using socket = connect('...');
// socket automatically closes when scope exits.
```
=> Make Socket async disposable, and Sql Cursor sync disposable

src/workerd/jsg/type-wrapper.h
This is deprecated in the next version of V8, and
for a while it has merely called v8::Isolate::GetCurrent() so we might as well make it clear what we are doing.
See also https://chromium-review.googlesource.com/c/v8/v8/+/6589896
=> Stop using deprecated context->GetIsolate.

src/wpt/harness/harness.ts, src/wpt/harness/test.ts, src/wpt/streams-test.ts
This PR is the first step in cleaning up the implementation of `test`/`async_test`/`promise_test`. 
For this one, I focused only on how the test result gets sent from the test up to our harness for reporting. This part doesn't derive from WPT code, and is our own custom implementation. 
This change captures some error messages that were previously lost. As a result, I had to add a few more failures for the streams module.
This work is also a prerequisite for WPT.fyi reports, because we previously didn't capture the names of individual subtests that were skipped or passing -- we only had tests that errored out.
In another PR, I'll try to clean up the implementations of step, done, etc. and make the promise hierarchy simpler to understand.
=> WPT harness: refactor how Test results are captured

src/workerd/api/filesystem.c++, src/workerd/api/filesystem.h, src/workerd/api/node/tests/fs-test.js, src/workerd/api/tests/webfs-test.js, src/workerd/io/worker-fs.c++, src/workerd/io/worker-fs.h, src/workerd/server/bundle-fs-test.c++
Larger commit goes through an improves the error reporting, ensuring that most of the c++ thrown errors have proper node.js style error codes, etc.
Makes it so that the underlying worker-fs api does not throw js errors on its own but instead returns an FsError code. This allows the WebFS and Node.js fs implementations to choose the appropriate error codes for each.
=> Make improvements to node:fs error handling

MODULE.bazel, WORKSPACE, build/BUILD.zlib, build/deps/v8.bzl, patches/v8/0023-Add-more-sandbox-APIs.patch, patches/v8/0024-bazel-Port-concurrent-mksnapshot-support.patch, patches/v8/0025-bazel-Port-V8_USE_ZLIB-support.patch, patches/zlib/0001-Add-dummy-MODULE.bazel.patch
[build] Port zlib to bzlmod
The bzlmod transition may have regressed us to using stock zlib based on it
being pulled in by another dependency and the bzlmod zlib being chosen over the
WORKSPACE one.
[build] Enable zlib and concurrent mksnapshot support in V8
This will improve performance when hashing snapshots, and when building V8.
===========
I didn't look closely, but while developing this it appeared that we have regressed to using stock zlib through bzlmod, which would make compression/decompression performance worse.
I observed a noticeable speedup for wd-tests with this on macOS (where -DEBUG is enabled by default, that's another issue to address)
=> [build] Enable zlib and concurrent mksnapshot support in V8

src/wpt/fetch/api-test.ts
No idea why it started flaking recently, but let's stop annoying everyone with failed builds for now
=> WPT fetch api disable flaky test

src/workerd/util/abortable.h, src/workerd/util/stream-utils.c++
The method becomes non-virtual in https://github.com/capnproto/capnproto/pull/2319 We can remove overrides now.
=> remove AsyncInputStream::read overrides

.github/workflows/internal-build.yml, .github/workflows/lint.yml, .github/workflows/test.yml
These jobs are required and if we don't run them we can't land docs-only changes.
Undos https://github.com/cloudflare/workerd/pull/3552
=> [nfc] always run ci jobs

build/ci.bazelrc
If a bazelrc config only has `test` settings then you can't pass it when you `build`. This PR moves these settings to common so that bazel won't complain if you do `bazel build --config=wpt-report`.
=> wpt-report bazelrc config must be common:

src/workerd/api/analytics-engine-impl.h
Increases the limit of maximum number of blob bytes you can write in a single Analytics Engine event from 5120 bytes to 32KB
=> chore: bump Workers Analytics cumulative blob limit to 32KB

src/pyodide/internal/python.ts, src/pyodide/internal/setupPackages.ts, src/workerd/server/tests/python/vendor_dir/worker.py
We have two functions that adjust the sys path in Python Workers. The first one (adjustSysPath) only runs when not restoring from a snapshot, so it is effectively immortalised in the memory snapshots. To avoid needing to regenerate all the memory snapshots (which for package snapshots would be a problem) we just rearrange the path at the same time as when we add the vendor path to the sys path.
```
$ bazel run @workerd//src/workerd/server/tests/python:vendor_dir_development@
Python sys.path: ['/session', '/lib/python312.zip', '/lib/python3.12', '/lib/python3.12/lib-dynload', '/session/metadata', '/session/metadata/vendor', '/lib/python3.12/site-packages', '/session/lib/python3.12/site-packages']
```
=> Move vendor dir in Python search path just before site-packages.

.github/workflows/test.yml
Required to unblock several pull-requests.
=> fix missing workflow permissions for sticky-pull-request-comment

src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/api/actor.h, src/workerd/io/actor-sqlite.h, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/BUILD.bazel, src/workerd/server/facet-tree-index-test.c++, src/workerd/server/facet-tree-index.c++, src/workerd/server/facet-tree-index.h, src/workerd/server/server-test.c++, src/workerd/server/server.c++, src/workerd/server/server.h, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h, src/workerd/server/workerd.capnp, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts
This is a new experimental Durable Objects feature. It requires the `--experimental` CLI flag and `experimental` compat flag to use. I fully expect that we may end up changing the design once we've played with it, and that's fine. This isn't intended to become generally available any time soon.
Multifaceted Durable Objects are Durable Objects (DOs) which are composed of multiple "facets" implemented by different isolates. Each facet is written like a regular DO class, but all the facets run together on the same machine to implement the DO. Each facet has its own storage in the form of a SQLite database, but these databases are all stored together as one logical object.
A multifaceted DO has a "main" facet which implements its public interface. This works exactly like a regular Durable …
=> Experimental feature: Durable Object Facets

src/workerd/api/BUILD.bazel, src/workerd/api/kv-instrumentation-test.js, src/workerd/api/kv-test.wd-test
This sets up a streaming tail worker for the existing KV tests, and then asserts against the telemetry that they emit today. Copies the approach in the [tail worker tests](https://github.com/cloudflare/workerd/blob/main/src/workerd/api/tail-worker-test.js).
There is no KV implementation in workerd so the existing KV tests [mock each response](https://github.com/cloudflare/workerd/blob/main/src/workerd/api/kv-test.js#L9). I could duplicate this logic into a separate test file to not disturb the existing tests, but thought that keeping everything together makes sense. As we extend the instrumentation logic this will likely encourage us to improve the coverage in the existing tests.
=> Extend existing KV test with instrumentation assertions

.github/workflows/_bazel.yml
For some reason this step takes 16 minutes on Windows. It only takes a couple seconds on Mac and Linux.
I assume these usage stats are not actually that important to collect on every build, so let's disable it.
=> Don't report disk usage in Windows build.

src/workerd/api/container.c++
Reverts cloudflare/workerd#4365
This is not the correct solution, per internal conversation.
=> Revert "update internal state on container.destroy"

.bazelrc
This suppresses the following warning on Windows
```
bazel-out/x64_windows-opt/bin/src/workerd/io/_virtual_includes/io\workerd/api\blob.h(115,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
115 |   friend class File;
|                ^
|                ::workerd::
1 warning generated.
```
=> suppress unnecessary microsoft-unqualified-friend warning

src/cloudflare/internal/ai-api.ts, src/cloudflare/internal/test/ai/ai-api-test.js, src/cloudflare/internal/test/ai/ai-mock.js
Workers AI is extending its binding to allow for passing ReadableStreams as inputs,
this will only be supported for a few models and will be fully backwards compatible.
For newer models, users will be able to send bigger media files as raw JS ReadableStream
objects. This will result in faster inference responses.
=> Add support for readable streams in AI binding

src/workerd/jsg/ser.c++
This is required for downstream v8 13.9 change.
=> handle native errors on value serializer

src/workerd/api/container.c++, src/workerd/io/container.capnp, src/workerd/server/container-client.c++, src/workerd/server/tests/container-client/test.js
Allows the user doing:
```javascript
this.ctx.container.monitor().catch(err => console.log(err.exitCode)); // exitCode will be defined if the error is due to the container exiting
```
=> containers: allow setting the exit code from a container runtime, and throw an error instead from jsg Container

types/defines/ai.d.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/latest/index.d.ts, types/generated-snapshot/latest/index.ts
This property was already optional before, but the `?` was removed by mistake by another contributor
=> Fix autorag id property when initializing the autorag class

src/pyodide/internal/python.ts, src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h, src/workerd/server/tests/python/vendor_dir/vendor_dir.wd-test
The recent change to our search path caused an existing worker which had a `workers.py` file in their bundle to fail. This happened because our own code imports `workers.py` (which is also what our SDK entrypoint is), so it attempts to import the user's module instead of our SDK module.
I have changed our code to not move the path where the user's code is before the site-packages path (where the SDK is). This change also now means that if a worker places a module that shares the name with their main module in the vendor directory, it will attempt to import the file in the vendor directory. I think that what we want to do is just fail validation in that case and that's what I implemented here too.
I have implemented a validation test in the parent repo for this too.
```
$ bazel run …
```
=> Fixes regression with SDK imports in Python search path.

src/workerd/api/BUILD.bazel, src/workerd/api/actor-state.c++, src/workerd/api/actor.c++, src/workerd/api/actor.h, src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/worker-loader-test.js, src/workerd/api/worker-loader-test.wd-test, src/workerd/api/worker-loader.c++, src/workerd/api/worker-loader.h, src/workerd/io/io-channels.h, src/workerd/io/worker.h, src/workerd/server/server.c++, src/workerd/server/server.h, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h, src/workerd/server/workerd.capnp
This is an experimental-only feature and will probably remain so until we play around with it a bit. Similar to facets (#4123), the interface is likely to change based on testing. This is also strictly an implementation in workerd -- the production runtime would need a very different implementation.
A Worker loader binding allows you to start an isolate from code provided at runtime, and then talk to that isolate.
```js
let id = "foo";
let worker = env.LOADER.get(id, () => {
// This callback is called if the given worker ID is not loaded yet.
// (If a Worker with the same ID is already loaded by this loader, the
// existing worker is returned without calling the callback.)
// The callback returns the Worker's code. It can be async.
return {
compatibilityDate: "2025-06-01",
// Specify the …
```
=> Experimental feature: Dynamic worker loading

src/pyodide/internal/_workers.py, src/workerd/server/tests/python/sdk/worker.py
In JS it appears we can pass either `undefined` or `null` to `new Response`. So passing in `None` in Python works just fine. This PR changes the SDK to allow `None` to be passed to the `Response` constructor.
This was reported on Discord.
=> Adds support for passing None to Python SDK's Response API.

src/workerd/api/crypto/crypto.c++, src/workerd/api/filesystem.c++, src/workerd/api/http.c++, src/workerd/api/streams/standard-test.c++, src/workerd/api/streams/standard.c++, src/workerd/api/worker-rpc.c++, src/workerd/server/server.c++, src/workerd/util/sqlite.c++
There doesn't seem to be appetite to fix the formatter, but these are really hard to read, so let's just disable the formatter locally in the problem areas.
=> Locally disable clang-format on lambdas inside struct initializers.

src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h, src/workerd/api/pyodide/setup-emscripten.c++, src/workerd/api/pyodide/setup-emscripten.h, src/workerd/io/worker.h, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h
While this work made sense at the time it is growing to be more of a maintenance burden than it's worth. Our runtime is not really built to support isolates with multiple contexts.
Work was never done to actually make use of this in production because we are not currently focusing on performance of python cold starts.
This commit can be reverted in the future if we want to revisit this approach, but for now, it's better to reduce the tech debt by getting rid of it.
Because of other features we are currently developing it is likely that we'll have a better solution to python cold starts that doesn't require multiple contexts and would eliminate the need for this anyway.
=> Revert most of the work for pyodide isolate pools.

src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/api/worker-loader-test.js, src/workerd/io/worker.h, src/workerd/server/server-test.c++, src/workerd/server/server.c++, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts
Previously, the caller of `facets.get()` would always provide the actor class and (optionally) `id`. If the facet was already running, these values would be compared against the running copy, and the facet would be reset if they didn't match.
This proves to be a bit problematic:
* Comparing ActorClass objects for equality proves to be more difficult than expected. With dynamic worker loading, the actor class may have dynamically-specified `props`, and comparing `props` for equality is not really possible since it's an arbitrary value. We could say that if you call `dynamicWorker.getActorClass()` multiple times, even with the same inputs, the returned classes are considered "different", but this would probably lead to facets restarting unexpectedly.
* The API is aesthetically inconsistent …
=> Change ctx.facets.get() to take a callback for start info. 

build/deps/v8.bzl, patches/v8/0027-Implement-additional-Exception-construction-methods.patch, src/workerd/io/worker-interface.capnp, src/workerd/jsg/jsvalue.c++, src/workerd/jsg/jsvalue.h, src/workerd/jsg/ser-test.c++, src/workerd/jsg/ser.c++, src/workerd/jsg/ser.h
In v8's ValueSerializer, Errors are handled differently than ordinary objects in that arbitrary own properties are not serialized by default. This commit patches V8 to optionally treat Errors as host objects allowing us to serialize all own properties of Error objects. This also allows us to support additional Error constructors that v8's API does not support by default, such as `AggregateError` and `SuppressedError`, as well as allowing us to serialize the workers specific additional own properties that we attach to some errors.
Critically, this will also allow us to attach a faithful serialization of an error to the `details` property of a kj::Exception for tunneled exceptions.
Creating initially as a draft PR to get some initial feedback to make sure this is the right approach we want …
=> Add TreatErrorsAsHostObjects to v8, customize Error serialization

src/pyodide/internal/jaeger.ts, src/pyodide/internal/metadata.ts, src/pyodide/python-entrypoint-helper.ts, src/pyodide/types/runtime-generated/metadata.d.ts, src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h, src/workerd/io/worker-source.h, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server.c++, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h, src/workerd/tests/test-fixture.c++
Python Workers need to be initialised at the top-level, but the IoContext is not available in that case. The Jaeger tracing grabs the current request's span via the IoContext. This PR (and the upstream PR) implements an alternative path of grabbing a span, by passing it through to InternalJaegerTrace when it is created. This enables Python to log spans at the top-level.
This enables us to remove the last special code path for Python initialisation (which had a number of limitations) and simplifies Python init significantly.
=> Implements support for jaeger tracing at top-level for Python.

src/node/internal/filesystem.d.ts, src/node/internal/internal_fs_callback.ts, src/node/internal/internal_fs_sync.ts, src/workerd/api/filesystem.c++, src/workerd/api/filesystem.h, src/workerd/api/node/BUILD.bazel, src/workerd/api/node/tests/fs-cp-test.js, src/workerd/api/node/tests/fs-cp-test.wd-test
Implements the `node:fs` `fs.cpSync()`, `fs.cp()`, `fsPromises.cp()` APIs
=> Implement node:fs cp APIs

src/workerd/tests/BUILD.bazel, src/workerd/tests/bench-api-headers.c++, src/workerd/tests/bench-global-scope.c++, src/workerd/tests/bench-json.c++, src/workerd/tests/bench-kj-headers.c++, src/workerd/tests/bench-mimetype.c++, src/workerd/tests/bench-util.c++
Current benchmarks are too fast to be used as a baseline, and creates false results.
=> increase benchmark iterations&durations

src/workerd/tests/bench-global-scope.c++, src/workerd/tests/bench-util.c++
Reduce iteration counts due to
> This benchmark contains 1702 system calls, totalling 7.1 s of execution time. Since they cannot be consistently instrumented, those calls are not included in the measure. Please switch to [the Walltime instrument to accurately measure system calls](https://codspeed.io/docs/instruments/walltime). Learn more [about measurement and system calls](https://codspeed.io/docs/instruments/cpu/overview#system-calls).
=> reduce iteration count of benchmarks

src/node/internal/internal_inspect.ts, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/BUILD.bazel, src/workerd/server/json-logger-test.c++, src/workerd/server/json-logger.c++, src/workerd/server/json-logger.h, src/workerd/server/log-schema.capnp, src/workerd/server/server-test.c++, src/workerd/server/server.c++, src/workerd/server/server.h, src/workerd/server/workerd.c++, src/workerd/server/workerd.capnp
This commit adds structured logging support to workerd. This is disabled by default but can be enabled with the structuredLogging configuration option.
When enabled workerd will output json log messages to stdout. The two sources of logs are c++ logs/errors and js errors.
=> Structured Logging

src/workerd/api/http.c++
There are only three call sites for setUnguarded. Two of them are already known to be valid header names and values. Let's move the validation of the header name and value out of the setUnguarded method and into the set method itself. This should eliminate some unnecessary work in the other two call sites.
=> Small simplification to Headers setUnguarded

src/pyodide/internal/_workers.py, src/workerd/server/tests/python/workflow-entrypoint/worker.js, src/workerd/server/tests/python/workflow-entrypoint/workflow.py
This PR includes breaking changes on the `step` API. Workflows are still experimental and under active development
- bugfix `step.do` to await for Js promise rejection
- new error translation layer between Python exceptions and Js errors (for now custom exceptions won't be catchable)
- new DAG optional params - users are now able to define a list of dependencies (other steps they depend on) and have them be executed (in parallel or sequentially). See [this diff](https://github.com/cloudflare/workerd/compare/caio/python-workflows-2?expand=1#diff-5a01b2a830d4f6b351d55e7100a3762882d709d39e2a5cdb89f1398d80a8b34b)
- removes the option to call a step with a callable as the second param - makes the API more uniform
- adds coverage for these additions in the existing test
=> Python Workflows API improvements

src/workerd/io/BUILD.bazel, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server.c++, src/workerd/server/server.h, src/workerd/util/BUILD.bazel, src/workerd/util/strong-bool-test.c++, src/workerd/util/strong-bool.h
This commit defines a macro which allows us to define "strong boolean" types. In particular, these types never implicitly convert to or from `bool`, or each other. This allows for greater type safety, especially in places where functions accept multiple `bool` parameters right next to each other. The call sites of such functions are notoriously difficult to maintain, as switching the order of two `bool` parameters will change the semantics of every call site, but will not introduce any compilation failures to alert you to the change.
A common way to define a strong boolean is to use an `enum class Foo: bool { NO, YES }` type. That pattern is a big improvement in terms of type safety over standard booleans. It has a couple flaws, however:
- Contextual boolean conversion is impossible
- …
=> [nfc] Add WD_STRONG_BOOL() macro

src/workerd/util/strong-bool.h
Needed for the implementation of KJ_STRINGIFY.
=> [nfc] Add missing kj/string.h header to strong-bool.h

src/workerd/io/actor-sqlite-test.c++, src/workerd/io/actor-sqlite.c++, src/workerd/io/actor-sqlite.h
ActorSqlite captures the first exception thrown by an output gate promise, so that it can continue to throw the exception on subsequent storage operations. The capture is done via a TaskSet error handler, with the assumption that all its tasks came via the output gate.
However, the TaskSet had an additional source of tasks that did not come from the output gate: When we reschedule an alarm later, we intentionally do not take an output gate lock, since we don't need to hold the gate open for it to complete.  If an alarm rescheduling task failed, the error handler would set ActorSqlite's "broken" exception.  This would cause subsequent storage operations throw exceptions -- but the actor's output gate would not be broken, so subsequent requests would not automatically go to a new instance …
=> ActorSqlite: treat moved-later alarm rescheduling exceptions as not breaking output gate

src/workerd/util/strong-bool-test.c++, src/workerd/util/strong-bool.h
I belatedly recalled that I shouldn't be using functional-style casts, since they implicitly perform a const_cast. In this case, it's not a big risk, but in theory someone could change a strong bool type to some other type with a non-const `operator bool()`, causing a safety issue.
The type already supports static_cast, of course, but no one's going to want to use that.
=> [nfc] Add StrongBool::toBool()

src/workerd/io/actor-cache.c++
=> Only log ActorCache::deleteAll errors to sentry if they're interesting

src/workerd/api/node/node.h, src/workerd/api/node/tests/http-agent-nodejs-test.wd-test, src/workerd/api/node/tests/http-client-nodejs-test.wd-test, src/workerd/api/node/tests/http-nodejs-test.wd-test, src/workerd/api/node/tests/http-outgoing-nodejs-test.wd-test, src/workerd/api/node/util.c++, src/workerd/io/compatibility-date.capnp
This pull-request enables the following modules and functions behind a compat flag
- `node:_http_agent`
- Agent
- globalAgent
- `node:_http_client`
- ClientRequest
- `node:_http_common`
- _checkIsHttpToken
- _checkInvalidHeaderChar
- chunkExpression
- continueExpression
- methods
- kIncomingMessage
- `node:_http_incoming`
- IncomingMessage 
- `node:_http_outgoing`
-  validateHeaderName
- validateHeaderValue
- kUniqueHeaders
- kHighWaterMark
- parseUniqueHeadersOption
- OutgoingMessage
- `node:http`
- validateHeaderName
- validateHeaderValue
- METHODS
- STATUS_CODES
- ClientRequest
- request
- get
- WebSocket
- OutgoingMessage
- Agent
- globalAgent
- IncomingMessage
- `node:https`
- get
- request
- Agent
- globalAgent 
cc @vicb
=> put http and https modules behind compat flag

.devcontainer/Dockerfile, src/node/internal/internal_buffer.ts, src/node/internal/internal_fs_utils.ts, src/node/internal/process.d.ts, src/node/internal/public_process.ts, src/workerd/api/node/process.c++, src/workerd/api/node/process.h, src/workerd/api/node/tests/fs-test.js, src/workerd/api/node/tests/fs-test.wd-test, src/workerd/api/node/tests/process-nodejs-test.js, src/workerd/io/io-context.h, src/workerd/io/worker-fs.c++, src/workerd/io/worker-fs.h
Updates the process v2 implementation to support `process.cwd()`, `process.chdir()` and `process.umask`.
`cwd()` is integrated into the virtual filesystem where the default cwd is `/bundle`, and it is stored as a property of the tmpfs as that matches the same FS context (in theory turning virtual tmpdir into a virtual fs state).
`process.umask` is just supported as a non-failing stub supporting umask validations but never actually applying the umask as we don't have a vfs with fine-grained permissions, but it still makes sense not to throw on these operations for FS-based code.
=> Add support for process cwd, chdir and umask in process v2

samples/hello-wasm/Cargo.lock, samples/hello-wasm/Cargo.toml, samples/hello-wasm/src/lib.rs
Hello maintainers!   I found a minor build issue in the hello-wasm sample, which can be easily fixed.
The original hello-wasm sample depended on an outdated version of wasm-bindgen that is no longer compatible with the latest Rust toolchain.
```
error: older versions of the `wasm-bindgen` crate are incompatible with current versions of Rust; please update to `wasm-bindgen` v0.2.88
```
This PR updates the dependencies to fix the issue and also includes a few minor type corrections.
=> Update dependencies in samples/hello-wasm to support latest Rust

src/workerd/io/trace-stream.c++
The given "Streaming tail session canceled" error we observed happens if we receive the outcome event in the tail stream handler and the promise for the js call where we provide the outcome event to user code gets canceled. This promise can be canceled for a number of reasons that the user is responsible for, such as an exception thrown in the outcome event handler or hitting the CPU limit, as was shown in testing. Additional testing showed that if there is a JS exception thrown in handlers other than the outcome handler, we do not get the given error. It does not indicate the runtime behaving unexpectedly?
**Why do we have this error?**
Looking at git history, it turns out that I originally added the error when fixing an issue where the tail stream handler failed to get the outcome …
=> EW-9285 Drop inaccurate stream cancellation error message

src/workerd/api/basics.c++, src/workerd/api/basics.h, src/workerd/io/compatibility-date.capnp, src/wpt/BUILD.bazel, src/wpt/dom/events-test.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts
Per the spec, the currentTarget property of an Event should be null if the event is not being dispatched.
Fixes: https://github.com/cloudflare/workerd/issues/4558
Fixes: https://github.com/cloudflare/workerd/issues/4556
~~@danlapid @kentonv ... I'm hoping this can be something we don't need a compat flag for. Whatcha think?~~
Adds a new `pedantic_wpt` compat flag for these kinds of fixes. Additional changes will be made incrementally using `implied_by` compat flags so that'll bundle all these types of changes together.
/cc @npaun
=> Correctly handle the event.currentTarget property

src/workerd/io/trace-stream.c++, src/workerd/io/tracer.h
This is no longer needed now that the top-level span is owned by WorkerTracer.
Also see the corresponding downstream PR.
=> [o11y] Fold up WorkerTracer weak reference

samples/nodejs-compat-http/README.md, samples/nodejs-compat-http/config.capnp, samples/nodejs-compat-http/worker.js
Adds a simple `node:http` sample.
It would be good to also have a sample that shows use of some other popular module that uses http (like got, or simple-get) but we can add that later.
=> Add node:http sample

src/pyodide/python-entrypoint-helper.ts, src/pyodide/python-entrypoint.js
Implements support for default WorkerEntrypoint in Python workers:
```python
from workers import Response, WorkerEntrypoint
class default(WorkerEntrypoint):
async def on_fetch(self, req):
return Response("hello")
```
=> Implements default entrypoint support for Python.

src/workerd/jsg/fast-api-test.c++, src/workerd/jsg/fast-api.h
We disallow kj::Promise but not jsg::Promise. Let's disallow it.
=> disallow jsg::Promise in v8 fast api

.github/actions/setup-runner/action.yml
This should have already been working, but the benchmark run now appears to be broken due to trying to link with the system linker.
Trying to fix benchmark build, which appears to be broken suddenly.
=> [ci] Always use lld in CI on Linux

src/pyodide/internal/_workers.py, src/pyodide/internal/workers.py, src/pyodide/internal/workflows.py, src/pyodide/python-entrypoint-helper.ts, src/workerd/server/tests/python/workflow-entrypoint/workflow.py
- updates the entrypoint helper to include a module dedicated to workflows (similarly to `cloudflare:workflows`)
- adds `wait_for_event` in the workflow step wrapper
=> Adds wait for event and workflows module

src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h, src/workerd/server/server.c++, src/workerd/server/server.h, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h, src/workerd/server/workerd.c++
Moves where Python deps (bundle and built-in packages) are downloaded so that the download can be accomplished asynchronously in the main workerd thread.
```
$ bazel run @workerd//src/workerd/server/tests/python:durable-object_0.26.0a2@
$ bazel run @workerd//src/workerd/server/tests/python:import/urllib3_0.27.7@ --test_tag_filters=-none
$ bazel run @workerd//src/workerd/server:workerd -- pyodide-lock
```
=> Fetch Python deps asynchronously in the main thread.

src/workerd/api/filesystem.c++, src/workerd/api/filesystem.h, src/workerd/api/global-scope.h, src/workerd/api/tests/webfs-test.js, src/workerd/jsg/exception.h, src/wpt/fs-test.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts
Reworks the Webfs implementation to be more correct and pass more of the WPT's.
Simplifies things a bit by removing the sync fs api for now (we can add it back in later)
=> More refinement of webfs impl

src/pyodide/internal/pool/emscriptenSetup.ts, src/pyodide/types/emscripten.d.ts
This should make debugging the bootstrap much easier.
=> Emscripten bootstrap: Propagate errors in ` _createPyodideModule` correctly

src/workerd/api/http.h, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/latest/index.d.ts, types/generated-snapshot/latest/index.ts, types/test/types/rpc.ts
This PR updates `Service<T>` so that:
- Returns `Fetcher<T>` when `T` is a `WorkerEntrypoint` class (Current behavior)
- Returns `Fetcher<InstanceType<T>>` when `T` is a `WorkerEntrypoint` constructor
- Returns  `never` when `T` is a `DurableObject` or `WorkflowEntrypoint`
- Returns `Fetcher` otherwise
This will enable `wrangler types` to infer the RPC methods from the default export with `Service<typeof import("./worker").default>` next.
Ref: https://github.com/cloudflare/workers-sdk/pull/9897
=> feat(types): allow Service<T> to handle non-WorkerEntrypoint default export

build/wd_test.bzl, build/wpt_test.bzl, src/workerd/api/node/tests/sidecar-supervisor.mjs, src/wpt/fetch/api-test.ts
* Make sure randomization is used unless it's explicitly disabled
* Make the supervisor assign _all_ of those weird ports WPT uses, even if we don't currently need them for tests.
=> Some fixes for sidecar IP randomization

src/workerd/io/limit-enforcer.h, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++
This allows us to perform some build cleanup in the downstream build (see downstream PR).
=> [nfc] Add no-op method to LimitEnforcer

src/workerd/api/basics-test.c++, src/workerd/api/hibernatable-web-socket.c++, src/workerd/api/http.c++, src/workerd/api/trace.c++, src/workerd/io/worker-entrypoint.c++, src/workerd/jsg/iterator-test.c++, src/workerd/jsg/promise.c++, src/workerd/jsg/promise.h, src/workerd/jsg/util-test.c++, src/workerd/util/sqlite.c++
This allows us to expand clang-tidy coverage downstream.
=> [build] Comply with clang-tidy misc-throw-by-value-catch-by-reference, minor code cleanup

src/workerd/jsg/fast-api.h, src/workerd/jsg/type-wrapper.h, src/workerd/jsg/value.h
This change will remove the conversion of string like to v8::FastOneByteString.
=> remove v8::FastOneByteString support

src/workerd/server/json-logger-test.c++, src/workerd/server/json-logger.c++, src/workerd/server/json-logger.h, src/workerd/server/tests/structured-logging/BUILD.bazel, src/workerd/server/tests/structured-logging/structured-logging-json.wd-test, src/workerd/server/tests/structured-logging/structured-logging-test.mjs, src/workerd/server/workerd.c++
Many startup and config errors are logged through ProcessContext. These logs up until now were logged in plain text even when structuredLogging was enabled.
This change adds support for structured logging at startup. This change is still limited as any logs and errors during parsing of the configuration will still be logged as plain text.
But this should minimize those to the absolute minimum.
One important thing to note, in order to not duplicate any logic from TopLevelProcessContext, error logs from StructuredLoggingProcessContext go to STDERR instead of STDOUT.
=> Support Structured Logging at startup.

src/cloudflare/internal/http.ts, src/cloudflare/workers.ts, src/node/_http_common.ts, src/node/_http_server.ts, src/node/http.ts, src/node/https.ts, src/node/internal/compatibility-flags.d.ts, src/node/internal/events.ts, src/node/internal/http.d.ts, src/node/internal/internal_errors.ts, src/node/internal/internal_http_client.ts, src/node/internal/internal_http_incoming.ts, src/node/internal/internal_http_outgoing.ts, src/node/internal/internal_http_server.ts, src/node/internal/internal_http_util.ts, src/node/internal/internal_https_server.ts, src/node/internal/internal_net.ts, src/node/internal/process.d.ts, src/node/internal/public_process.ts, src/node/internal/validators.ts, src/node/tsconfig.json, src/workerd/api/node/node.h, src/workerd/api/node/tests/BUILD.bazel, src/workerd/api/node/tests/http-outgoing-nodejs-test.js, src/workerd/api/node/tests/http-server-nodejs-server.js, src/workerd/api/node/tests/http-server-nodejs-test.js, src/workerd/api/node/tests/http-server-nodejs-test.wd-test, src/workerd/io/compatibility-date.capnp
Implements the remaining modules necessary to add `http.createServer`. Starting from today, the following code works without any issues:
```js
import http from 'node:http';
import { strictEqual, ok } from 'node:assert';
import { nodeCompatHttpServerHandler } from 'cloudflare:workers';
export const testHttpServerMultiHeaders = {
async test(_ctrl, env) {
const { promise, resolve } = Promise.withResolvers();
const server = http.createServer(function (req, res) {
strictEqual(req.headers.host, 'yagiz');
res.writeHead(200, { 'Content-Type': 'text/plain' });
res.end('EOF');
server.close();
});
server.listen(8080, async function () {
const res = await env.SERVICE.fetch('https://cloudflare.com', {
headers: [['host', 'yagiz']],
});
strictEqual(res.status, 200); …
```
=> implement node:http server-side modules

src/workerd/api/headers.c++, src/workerd/jsg/jsg-test.c++, src/workerd/jsg/promise.h
- [nfc] Avoid two instances of use-after-move
One of these only affects a test, but the other one could lead to memory not being fully accounted for.
- [nfc] drive-by: Clean up superfluous JSG promise code
rejectionCount was only partially cleaned up and caused a compiler warning, for OpaqueWrapper<T, true> we can inherit the identical methods from the superclass and don't need to define them again.
=> [nfc] Avoid two instances of use-after-move

src/pyodide/internal/_workers.py, src/pyodide/internal/metadata.ts, src/pyodide/python-entrypoint-helper.ts, src/workerd/io/compatibility-date.capnp, src/workerd/server/tests/python/sdk/sdk.wd-test, src/workerd/server/tests/python/sdk/server.py, src/workerd/server/tests/python/sdk/worker.py
As a team we decided to remove global handlers in Python Workers and instead standardise on a `Default` class which defines the handler methods. This PR implements a new compat flag which enforces the usage of this class.
This PR also renames the default WorkerEntrypoint to start with a capital letter rather than lowercase.
```
bazel run @workerd//src/workerd/server/tests/python:sdk_development@
```
=> Adds compat flag which disables global Python handlers.

src/workerd/api/crypto/crc-impl.c++, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/worker.c++
Soon, I intend to land a new clang-tidy plugin downstream which squawks if we have functions which accept more than one boolean parameter.
We run our clang-tidy with warnings-as-errors for as much of our codebase as we can, including some workerd directories. This PR resolves the lints which cropped up in workerd when I ran it.
In doing so, I discovered a couple minor bugs in our heap snapshot functionality.
=> Resolve several multiple-bool-args lints

src/node/internal/internal_fs.ts, src/node/internal/internal_fs_callback.ts, src/node/internal/internal_fs_promises.ts, src/node/internal/internal_fs_sync.ts, src/node/internal/internal_fs_utils.ts, src/workerd/api/node/tests/fs-test.js
Fixup some node:fs callback API arguments checks and simplify type defs for encodings.
=> Fixup node:fs callback api arg checks

src/workerd/io/trace-stream.c++, src/workerd/io/worker-interface.capnp
Provide the right outcome for the Streaming Tail Worker event, instead of always returning OK. This includes support for propagating the result via RPC.
Overlaps with #4540, should try to stitch these together cleanly.
=> [o11y] Return STW outcome properly

src/workerd/api/trace.c++, src/workerd/io/tracer.c++
This bug is proving quite stubborn, gather more information
=> [o11y] Log stack trace for tail event after close error

src/workerd/api/filesystem.c++, src/workerd/api/node/tests/fs-misc-test.js, src/workerd/io/worker-fs.h
* Limit paths to a total of 4096 characters total. Note that this includes percent-encoded characters, so a path like `/a/b/c/d/e/%ZZ` counts as 14 characters... the path limit is checked after percent-encoding normalization (percent encodings that aren't actually necessary are decoded)
* Limits path to a total of 48 path segments. For example, a path like '/a/b/c' counts as 3 segments, while a path like `/a/b/c/' counts as 4.
The limits here are completely arbitrary. We can set them to whatever we'd like. They are intended specifically just to place a reasonable limit so that paths themselves don't eat up too many resources on their own.
=> Implement vfs path limits

src/node/http.ts, src/workerd/api/node/tests/http-nodejs-test.js
Adds missing exports that is added via polyfill. Now we can get rid of the http polyfill. cc @vicb 
```
export {
_connectionListener,
CloseEvent,
maxHeaderSize,
MessageEvent,
setMaxIdleHTTPParsers,
WebSocket,
} from "unenv/node/http";
```
=> add missing http exports

src/workerd/api/worker-loader.c++, src/workerd/io/io-channels.h
Required for the internal PR for selectively preserving the own content
=> Add can disown content flag to DynamicWorkerSource

samples/helloworld_esm/worker.js, src/pyodide/internal/_workers.py, src/workerd/io/worker.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/jsvalue.c++, src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h, src/workerd/jsg/promise.h, src/workerd/jsg/util-test.c++, src/workerd/jsg/util.c++, src/workerd/jsg/util.h, src/workerd/jsg/value.h
Use the recently added JS error serialization mechanism to preserve JS error details in tunneled errors. Internal test changes are required (separate PR opened there).
The new mechanism adds an options struct used to customize how the kj::Exception is handled. 
The options include the ability to ignore the serialized data, selectively include the stack, selectively log, and decide how to handle non-object serializations. By default, the mechanism will ignore stack and ignore non-object serializations (e.g. in case someone does `throw 'foo'` and the serialized detail is not actually an error object. This matches the original behavior.
DOMExceptions are still handled specially, ignoring the serialized detail.
=> Use new js error serialization to preserve error details

build/deps/dep_pyodide.bzl, build/python_metadata.bzl, src/pyodide/create_vendor_zip.py, src/pyodide/make_snapshots.py, src/pyodide/tool_utils.py, src/pyodide/upload_bundles.py
Updated make_snapshots to take an optional Python version. I also made it print the data to put into python_metadata. Vendor file entries get an abi field which is either the Python version they depend on or None if they work in all Python versions.
=> Python: Make vendor tests keep track of Python version if necessary

src/pyodide/internal/metadatafs.ts, src/pyodide/internal/readOnlyFS.ts, src/pyodide/internal/setupPackages.ts, src/pyodide/internal/snapshot.ts, src/pyodide/internal/tar.ts, src/pyodide/internal/topLevelEntropy/lib.ts, src/pyodide/types/filesystem.d.ts
If the goal is to narrow the type from `type | undefined` to `type`, it's better to do it with `!` since we still get some type checking. It's also shorter.
=> Python ts MAINT: Remove some type assertions

samples/helloworld_esm/worker.js, src/pyodide/internal/_workers.py, src/workerd/io/worker.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/jsvalue.c++, src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h, src/workerd/jsg/promise.h, src/workerd/jsg/util-test.c++, src/workerd/jsg/util.c++, src/workerd/jsg/util.h, src/workerd/jsg/value.h
This reverts commit 9e98c6f36f486f048aa831d3f4efa3fbdb85b402.
Ran into some quirks in prod during rollout, reverting first then will investigate
=> Revert "Use new js error serialization to preserve error details (#4698)

src/node/internal/internal_http_incoming.ts, src/node/internal/internal_http_server.ts, src/workerd/api/node/tests/http-server-nodejs-test.js
Adds the missing socket attribute to IncomingMessage. After landing this, we can remove the experimental attribution from the compat flag.
=> add socket attribute to IncomingMessage

src/node/internal/internal_net.ts, src/node/internal/internal_tls_wrap.ts
Partial fix to https://github.com/cloudflare/workerd/issues/4724
After this change, we have a new error, which requires a little bit more investigation:
```
workerd/server/server.c++:4781: error: Uncaught exception: workerd/io/io-context.c++:1317: failed: remote.jsg.Error: The Workers runtime canceled this request because it detected that your Worker's code had hung and would never generate a response. Refer to: https://developers.cloudflare.com/workers/observability/errors/
```
=> do not call destroy.bind()

src/node/os.ts, src/node/tls.ts, src/node/util.ts, src/workerd/api/node/tests/tls-nodejs-test.js, src/workerd/api/node/tests/util-nodejs-test.js, src/workerd/io/compatibility-date.capnp
Adds EOL methods to be removed on a future date. Let's keep this open for now and make sure we have all the methods that are EOL in a single compat flag.
=> introduce nodejs_compat eol methods

src/cloudflare/node.ts, src/workerd/api/node/tests/BUILD.bazel, src/workerd/api/node/tests/http-server-nodejs-global-test.js, src/workerd/api/node/tests/http-server-nodejs-global-test.wd-test, src/workerd/api/node/tests/http-server-nodejs-test.js
Since calling `listen()` on the node:http Server is largely boilerplate, we can simplify the ergonomics by allowing the user to pass the server directly into httpServerHandler and having it call `listen()` for the user if it hasn't already been called. Code that is already written for node.js that is ported without modifications would likely still be just calling `listen` but this should make things easier overall.
```js
import http from 'node:http';
import { httpServerHandler } from 'cloudflare:node';
const server = http.createServer((req, res) => {
res.end('hello world');
});
export default httpServerHandler(server);
```
=> Small improvement to the httpServerHandler ergonomics

src/workerd/io/compatibility-date.capnp, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++
In order to have proper validation for Workflows I think we will need a similar setup as DOs: ValidationErrorReporter now has a `addWorkflowClass` that behaves similarily as `addActorClass`. (This will need a internal PR in order to work properly).
This will be useful in cases that a user exports a class but doesn't extend from `WorkflowEntrypoint` (meaning they won't get `ctx` and `env` and see weird errors).
=> feat: add Workflows to ValidationErrorReporter

src/pyodide/internal/metadata.ts, src/pyodide/internal/python.ts, src/pyodide/internal/snapshot.ts, src/pyodide/python-entrypoint-helper.ts, src/pyodide/types/emscripten.d.ts, src/workerd/api/pyodide/pyodide.h, src/workerd/io/compatibility-date.capnp
This PR implements dedicated memory snapshot support in Python Workers. These dedicated snapshots are intended to be returned via the validator and then stored in the WorkerBundle.
Run down of features this PR implements:
* new compatibility flag marked `experimental` which enables code paths to generate and load dedicated snapshots.
* ~~new exceptions `PythonRuntimeError` and `PythonUserError` to help us distinguish between internal errors in our runtime code and user code errors~~ https://github.com/cloudflare/workerd/pull/4746
* dynamic libraries are now loaded from the vendored packages directory when necessary
* hiwire custom serialiser/deserialiser for global JS objects that our internal code references with a user-facing error message if their code attempts the same at the …
=> Implements dedicated snapshots for Python Workers.

src/workerd/io/tracer.c++, src/workerd/io/tracer.h
This should address the 'reported tail stream event after stream close' warnings seen in testing.
=> [o11y] Defer STW outcome event reporting

src/workerd/api/node/async-hooks.h
And avoid throwing unimplemented error when asyncID and triggerAsyncID are called.
Needed in order to support frameworks like `fastify`
=> Implement no-op emitDestroy method for AsyncResource

src/workerd/io/tracer.c++
This case can happen when there are no tail events delivered to the tracer at all (such as when a worker interface gets set up without being used for an event), so this may not indicate an error.
=> [o11y] Drop overzealous log in STW outcome reporting

src/pyodide/internal/_workers.py
Just this import is responsible for ~250ms of CPU time, which breaks our validation tests, though strangely doesn't break the validation in production.
=> Moves http.client import to reduce CPU time when importing Py SDK.

src/workerd/server/json-logger.c++
The new structured logging functionality used `puts()` to write the logs to stdout.
`puts()` is an ancient C stdio function. It doesn't write directly to stdout, but rather a C stdio `FILE` structure representing stdout. This structure has a buffer.
Now, if stdout is an internactive terminal, then the FILE for stdout is automatically configured to line-buffer mode, meaning it will flush the buffer whenever a newline character is written to it. So when testing structured logging on the terminal, everything would appear to work great.
But if stdout is a disk file, pipe, socket, etc., then stdio will use file-buffering mode, which means it won't flush the buffer until it fills up. The buffer is probably something like 4096 or 8192 bytes.
This means that logs might be delayed -- or might not …
=> Fix structured logs getting stuck in the buffer.

src/workerd/server/tests/python/BUILD.bazel, src/workerd/server/tests/python/sdk/worker.py
It turns out we weren't running these tests because the `test` method wasn't under the `Default` class. This PR fixes this.
=> Fixes Python SDK test to use the new default entrypoint correctly.

.github/workflows/release-python-runtime.yml
See https://github.com/cloudflare/workerd/pull/4838/commits/42a32b346ad845adc6149cca6eabacaf37f0fbd8 for what this does. I will drop that commit before merging.
=> Python: Make release-python-runtime push changes to python_metadata.bzl to branch

.github/workflows/release-python-runtime.yml, build/python_metadata.bzl, src/pyodide/upload_bundles.py
I manually tested both with the flag off and with it on and both work as expected.
=> release-python-runtime: Don't update released bundles by default

src/workerd/api/memory-cache.c++
For the cache_hit path entry_size is already set by getWithFallback
=> Fix double write of entry_size

src/workerd/server/server.c++
The previous code was guarding against a case that should never happen in workerd, and if it did would be a bug. Simplify to avoid confusion and possible issues later.
=> Always grab the owned source from a dynamic source

build/deps/gen/dep_capnp_cpp.bzl, src/workerd/api/cache.c++, src/workerd/api/container.c++, src/workerd/api/headers-test.c++, src/workerd/api/http.c++, src/workerd/api/kv.c++, src/workerd/api/queue.c++, src/workerd/api/sockets.c++, src/workerd/io/worker.c++, src/workerd/server/container-client.c++, src/workerd/server/fallback-service.c++, src/workerd/server/server-test.c++, src/workerd/server/server.c++
Updating uses of deprecated `kj::HttpHeaders` API
=> Replace deprecated capnp set/add methods with setPtr/addPtr/addPtrPtr

src/workerd/api/http.c++, src/workerd/api/sockets.c++, src/workerd/api/tests/http-socket-test.js, src/workerd/util/stream-utils.c++, src/workerd/util/stream-utils.h
- Fix: Redirects for `internalNewHttpClient`
- Fix: Read all data for redirects.
=> Fix Redirects for internalNewHttpClient

src/workerd/api/tests/eventsource-test.js
None of the test bits here should actually hit the internet, routing all EventSource instances through the env.subrequest fetcher should redirect those back to the workers own default export.
Old backlogged issue that I finally managed to get around to.
=> Update the eventsource test to use the fetcher option

src/pyodide/eslint.config.mjs, src/pyodide/internal/_workers.py, src/pyodide/python-entrypoint-helper.ts, src/workerd/io/compatibility-date.capnp, src/workerd/server/tests/python/python-rpc/worker.py
Without this patch, `context.waitUntil()` fails with borrowed proxy destroyed at end of function call error message.
=> Python: Patch context.waitUntil to prevent problems with proxy lifetimes

src/workerd/api/r2-bucket.c++, src/workerd/api/r2-test.js
When passing headers in to `onlyIf` actions on the R2 Binding, if an ETag is not quoted, it would be returned as an empty array, rather than erroring.
=> R2-3382: Throw Error on Invalid ETag

build/python_metadata.bzl, src/workerd/io/compatibility-date.capnp
0.28.2 is apparently broken in prod
=> Revert "Python: Mark 0.28.2 compat date not experimental (#4865)"

src/workerd/api/global-scope.c++, src/workerd/api/messagechannel.c++, src/workerd/api/messagechannel.h, src/workerd/api/streams/standard.c++, src/workerd/jsg/fast-api-test.c++, src/workerd/server/workerd-api.c++
Doesn't quite get us to where we can delete `jsg::alloc` but closer at least
=> Replace jsg::alloc uses with js.alloc

src/workerd/api/BUILD.bazel, src/workerd/api/tail-worker-test-jsrpc.js, src/workerd/api/tail-worker-test-receiver.js, src/workerd/api/tail-worker-test.js, src/workerd/api/tail-worker-test.wd-test, src/workerd/api/worker-rpc.c++
EW-9282 EW-9451 Fix missing onset event for JSRpc edge cases 
If we invoke a customEvent, we should generally report an onset event to the tracer right away. Under the STW model, we must do so if there's any chance for events like spans/logs being generated from JS (this wasn't the case with LTW so far).
For JSRPC, we would only create an onset event after we were able to successfully get a function or property to call, but we may invoke JS code before that (e.g. if a JS getter method produced a log). Accordingly, set the onset as soon as we know the function name to report with it to avoid getting errors based on other events being sent before the onset.
Note that this does result in traces being generated in some error cases (e.g. when a function lookup fails), but this is arguably the …
=> EW-9282 EW-9451 Fix missing onset event for JSRpc edge cases, add JSRpc regression test

src/node/internal/internal_buffer.ts, src/workerd/api/node/tests/util-nodejs-test.js
I'm not sure why we have this implementation in the first place. This new change aligns with Node.js - https://github.com/nodejs/node/blob/27e2d816176e823b79e6f3040fc06eadf70b741a/lib/buffer.js#L551
=> fix Buffer.isBuffer returning true for true

src/workerd/io/worker.c++, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/resource.h
This is the first of a set of PRs in preparation for the final push to enable the new module registry in the downstream project. 
I will be moving the capnp module implementation out to workerd as part of this, and to do so we need to rework how the capnp::SchemaLoader is accessed. 
Instead of it living on the `Worker::Api` object, the intent here is for it to eventually live on the module registry. 
However, it's a bit tricky because right now the capnp module TypeWrapper extension requires that the `SchemaLoader` instance is passed in as part of the TypeWrapper configuration. 
I will be changing that so that the capnp module typewrapper can pull it off the `jsg::Lock` instead, via either of the new module registry implementations, but to do so I first need to clean up a few other bits …
=> Simplify tryResolveMainModule to use js.resolveModule

src/workerd/io/compatibility-date.capnp
Related to EMAIL-1245
On an effort to not break older user workers when send_email queuing is done, we introduce a compat flag `emailSendingQueuing` - this is because email queuing will potentially need some behavior breaking changes (e.g.: managed message-ids).
Marked as experimental for now
=> feat: add email queuing compat flag for email sending queuing

src/workerd/api/base64-test.c++, src/workerd/api/base64.c++, src/workerd/api/base64.h
Avoid an additional copy when returning results to JS by using a jsg::BufferSource as the output type. Since we are running in the v8 sandbox now, kj::Array<kj::byte> allocations that are not backed by a v8::BackingStore are more expensive because they require a copy to get the data into the sandbox.
(`TD` == Technical Debt)
=> [TD] Update api/base64 to use jsg::BufferSource

src/workerd/io/compatibility-date.capnp
@anonrig @jasnell This PR update the comment as the flag is no more experimental (ref #4722)
One thing I note is that the [http](https://developers.cloudflare.com/workers/runtime-apis/nodejs/http/#server-side-methods) and [https](https://developers.cloudflare.com/workers/runtime-apis/nodejs/https/#server-side-methods) docs mention:
That does not sound right as I think `enable_nodejs_http_modules` should also be enabled (not sure about the behavior when only the server flag is used?)
If the docs are wrong, could you please create a PR to fix that?
Thanks!
=> Update the comment for the enable_nodejs_http_server_modules flag

.bazelrc, .github/workflows/release.yml, .github/workflows/test.yml, build/rust_toolchains.bzl, build/wd_ts_type_test.bzl, justfile, src/workerd/api/BUILD.bazel, src/workerd/jsg/BUILD.bazel
- Silence warnings with updated protobuf
- rustc hasn't stabilized the clmul feature with the version we use in workerd yet – drop it for now to avoid warnings
- Simplify bazel target directives
==========
Mostly just getting rid of compiler warnings that started appearing recently.
=> [build] 08-28-25 build fixups

src/workerd/api/tail-worker-test-jsrpc.js, src/workerd/api/tail-worker-test.js, src/workerd/api/worker-rpc.c++
In #4881, we fixed the missing/delayed Onset issue for some cases, but to handle logs etc. being created in constructors we need to set the event before invoking JS at all. This requires some slight code duplication so we can access the method name in time.
=> EW-9282 EW-9451 Further fix errors with Onset event being reported too late

src/workerd/api/streams/compression.c++, src/workerd/api/streams/internal.c++, src/workerd/api/streams/internal.h, src/workerd/api/streams/queue-test.c++, src/workerd/api/streams/queue.c++, src/workerd/api/streams/queue.h, src/workerd/api/streams/standard.c++, src/workerd/api/streams/standard.h, src/workerd/api/web-socket.h, src/workerd/io/trace-stream.h, src/workerd/jsg/BUILD.bazel, src/workerd/jsg/iterator.c++, src/workerd/jsg/iterator.h, src/workerd/util/checked-queue.h, src/workerd/util/weak-refs.h
Reverts the update to have streams use the new checked queue. There's an issue that needs to be investigated so just revert the lot and I'll reapply once resolved.
=> Revert "Update src/workerd/api/streams/queue.h"

src/workerd/api/crypto/rsa.c++, src/workerd/api/streams/queue.c++, src/workerd/api/streams/standard.c++
copyFrom throws nice exception rather than aborts the process in case of overlapping memory
=> replacing std::copy with ArrayPtr::copyFrom

src/node/console.ts, src/workerd/api/node/tests/BUILD.bazel, src/workerd/api/node/tests/console-nodejs-test.js, src/workerd/api/node/tests/console-nodejs-test.wd-test
In reality, node:console differs from globalThis.console and supports additional features. The existing polyfill implementation for node:console just uses globalThis.console methods underneath. For the sake of removing the polyfills from wrangler, here's the implementation.
Polyfill also adds several variables that is not documented (and not used generally out there) such as the following methods/attributes that I didn't add this to this pull-request. I'm not sure if we should add them. I'm leaving this discussion to the reviewers. Ref: https://github.com/unjs/unenv/blob/main/src/runtime/node/console.ts
=> add node:console implementation

src/workerd/server/server.c++
Found using the upcoming clang lifetime safety feature.
=> Fix UaF in server

src/wpt/fetch/api-test.ts
This PR updates the status of some WPT tests to match our recent discussions
- Turn on redirect-mode tests because they do contain some non-cors stuff as well
- Omit any tests relating to:
- CSP
- CORS
- Referrer
- Header filtering
- DOM stuff
- Browser specific stuff
- Although we're probably never going to have it I left these as disabled instead of omitted. This is because we technically might be able to add it later:
- Keepalive
- Integrity
- Ambient credentials
- Please let me know anything here ought to really be nuked
=> [wpt] Update status of some fetch tests

src/workerd/api/kv-instrumentation-test.js, src/workerd/api/r2-instrumentation-test.js, src/workerd/api/tail-worker-test-receiver.js, src/workerd/api/tail-worker-test.js, src/workerd/io/trace-stream.c++, src/workerd/io/trace-test.c++, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/tracer.c++, src/workerd/io/worker-interface.capnp, src/workerd/server/server.c++, types/defines/trace.d.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/latest/index.d.ts, types/generated-snapshot/latest/index.ts
This implements the Streaming Tail Worker API as discussed previously, should be a lot more elegant and less error-prone.
What isn't cleaned up yet:
- Commit history, splitting this into more digestible commits (possible to some extent)
- Many TODOs are cleared up, one is added about the Onset spanId.
- We have good tests for the spanId field defined for SpanOpen, its meaning has changed and it's now actually called spanId. We'd still want more coverage for the outer spanId defined in TailEvent, which is not included in tests as we only look at the inner event so that tests are deterministic (TailEvent includes timestamp) @mar-cf if you want to develop tests that should be helpful still, or I can add them here
Downstream PR to follow.
=> EW-9365 [o11y] Implement proper Streaming Tail Worker API

src/node/internal/internal_dns_promises.ts, src/node/internal/internal_errors.ts, src/node/perf_hooks.ts, src/node/timers.ts, src/node/zlib.ts, src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/node/node.h, src/workerd/api/node/tests/BUILD.bazel, src/workerd/api/node/tests/perf-hooks-nodejs-test.js, src/workerd/api/node/tests/perf-hooks-nodejs-test.wd-test, src/workerd/api/performance.c++, src/workerd/api/performance.h, src/workerd/api/rtti.c++, src/workerd/io/compatibility-date.capnp, src/workerd/jsg/jsg.h, src/workerd/jsg/resource-test.c++, src/workerd/jsg/resource.h, src/workerd/jsg/rtti.h, src/workerd/server/workerd-api.c++, src/wpt/BUILD.bazel, src/wpt/performance-timeline-test.ts, types/generated-snapshot/experimental/index.d.ts, types/generated-snapshot/experimental/index.ts, types/generated-snapshot/latest/index.d.ts, types/generated-snapshot/latest/index.ts
Adds node:perf_hooks module and several global Performance prefixed classes.
=> add perf_hooks module and global Performance classes

src/node/internal/public_process.ts, src/workerd/api/node/tests/process-nodejs-test.js
This implements all Node.js process exports as either stubbed or no-op functions.
This ensures we have a comprehensive interface across all process features being stubbed out.
=> Implement all process exports as stubbed or unimplemented

src/pyodide/internal/metadata.ts, src/pyodide/internal/python.ts, src/pyodide/internal/snapshot.ts, src/pyodide/python-entrypoint-helper.ts, src/pyodide/types/runtime-generated/metadata.d.ts, src/workerd/api/pyodide/pyodide.c++, src/workerd/api/pyodide/pyodide.h
We've ran into the "experimental" gotcha by using the global compatibilityFlags field, so this introduces a custom API for the Python runtime which returns all compat flags even if they're experimental.
=> Retrieve experimental compat flags in Python runtime differently.

.npmrc
rules_js always lays out packages without 'hoisting' so we want any native usage of pnpm to match
=> chore(bazel): ensure pnpm run outside Bazel has similar behavior

src/workerd/api/r2-admin.c++, src/workerd/api/r2-bucket.c++, src/workerd/api/r2-instrumentation-test.js
`R2::head()` deserves it's own span name, and the bucket admin methods do too.
Depends on https://gitlab.cfdata.org/cloudflare/ew/edgeworker/-/merge_requests/11390 to update the allowlist
=> [R2 instrumentation] Update R2 span names

src/workerd/io/worker-modules.h, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h
There is a fair amount of duplicated code for module initialization between workerd and the internal repo. This starts the process of consolidating by moving a handful of utility methods over to worker-modules.h. A follow-up next step will be to update the internal code to use these from the shared location.
this builds on #5070 which must land first.
=> Begin consolidating duplicated legacy module registry init code

src/workerd/api/pyodide/pyodide.h, src/workerd/io/BUILD.bazel, src/workerd/io/worker-modules.c++, src/workerd/io/worker-modules.h, src/workerd/server/workerd-api.c++
Allows reuse of the same state creation code in both workerd-api.c++ and the internal repo equivalent.
I'm working on consolidating all of the code that is used to initialize the module registry so that we can share as much as possible between workerd and the internal project to simplify maintenance and help make enabling the new module registry in the production environment easier.
This will be the first of a few PRS that will be moving the python-specific initialization code out to shared locations as much as possible.
=> Move python module metadata state creation to worker-modules.c++.

src/workerd/api/modules.h, src/workerd/api/tests/new-module-registry-test.js, src/workerd/io/worker.c++, src/workerd/jsg/modules-new.c++
* Ensure the `cloudflare-internal:*` specifiers are registered as builtin-only
* Pre-resolve the `node:process` and `node:buffer` specifiers when the new module registry is in use to avoid pumping the microtask queue prematurely during top-level scope evaluation.
=> Some minor fixups with new module registry

src/node/internal/public_process.ts, src/workerd/api/node/tests/process-nodejs-test.js
Adds a simple implementation for _rawDebug.
Also adds _events, _eventsCount, _maxListeners event properties.
And adds _disconnect, _handleQueue, _pendingMessage, _channel, _send all as undefined.
=> Add further process private exports

src/workerd/io/io-context.c++
Reverts cloudflare/workerd#5132
Appears to be causing segfaults
=> Revert "Log warning on IoContext timeout with pending tasks"

src/cloudflare/internal/aig-api.ts
Exclude here is a no-op and as a result `UniversalGatewayOptions` is equivalent to `GatewayOptions`. The intent here was to use Omit.
=> UniversalGatewayOptions Exclude ==> Omit

src/workerd/io/io-context.c++
Reverts cloudflare/workerd#5152.
This PR was determined not to be the cause of our recent issues, and should be re-applied.
=> Revert "Revert "Log warning on IoContext timeout with pending tasks""

src/workerd/api/kv-instrumentation-test.js, src/workerd/api/kv.c++
Follow up to https://github.com/cloudflare/workerd/pull/5120
While documenting these attributes I found two more small issues:
- `kv_list` didn't set `cloudflare.kv.response.size`
- all methods except `kv_put` use `cloudflare.kv.query.keys`. For consistency I've also switched to it there even though we don't currently allow you to pass multiple keys in.
=> [KV Instrumentation] More KV attribute tweaks

src/node/internal/public_process.ts, src/workerd/api/node/tests/process-nodejs-test.js
Ensures `Object.process.toString.call(process)` gives `[object process]`.
=> fix: process toString support

src/pyodide/internal/snapshot.ts
We need to include the soMemoryBases and loadOrder from the original memory snapshot.
=> Fix stacked memory snapshot generation

src/workerd/api/node/process.c++, src/workerd/io/trace-stream.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/jsvalue.c++
Using js.obj(arrayPtr, arrayPtr) overload in favor of js.obj() due to performance. also uses strIntern for repetitive objects
=> improve js.obj() usages across the repository

src/workerd/api/actor-state.c++, src/workerd/api/sql.c++, src/workerd/io/actor-sqlite-test.c++, src/workerd/io/actor-sqlite.c++, src/workerd/io/actor-sqlite.h, src/workerd/util/sqlite-kv.c++, src/workerd/util/sqlite-kv.h, src/workerd/util/sqlite-test.c++, src/workerd/util/sqlite.c++, src/workerd/util/sqlite.h
This PR implements `allowUnconfirmed` for KV puts and deletes in SQLite-backed DOs.  See the commits and comments for the detailed design.
=> Implement allowUnconfirmed for SQLite-backed DOs

src/workerd/api/tail-worker-test.js, src/workerd/io/tracer.c++, src/workerd/io/tracer.h, src/workerd/io/worker-entrypoint.c++, src/workerd/server/server.c++
- Reland "EW-9366 Report fetch response earlier"
This reverts commit 8612789.
- [o11y] Fix tail worker return reporting for fetch event exceptions
We still need to report the fetch return code following an exception.
=> Reland "EW-9366 Report fetch response earlier"

WORKSPACE, build/deps/v8.bzl, patches/v8/0030-bind-icu-to-googlesource.patch
Per documentation: https://bazel.build/external/migration#bind-targets
=> refactor(bzlmod): remove bind of @icu

src/workerd/io/compatibility-date.capnp
Now that we've confirmed this works we should enable it implicitly for our users.
=> Adds enable date for python_dedicated_snapshots.

src/workerd/server/container-client.c++
https://docs.docker.com/reference/api/engine/version/v1.49/#tag/Container/operation/ContainerKill - a successful response should be a 204 not 200. 
Currently we are seeing `Stopping container failed with: <empty body because its actually successful>` when we shut down a container in local dev.
=> containers: Fix expected status code when sending a signal to the container.

src/workerd/api/BUILD.bazel, src/workerd/api/streams/standard.c++, src/workerd/api/tests/request-clone-test.js, src/workerd/api/tests/request-clone-test.wd-test
Fixes https://github.com/cloudflare/workerd/issues/5175
=> fix request#clone not working with js-backed streams
