README.md
This PR adds basic instructions for using prebuilt binaries distributed via `npm`, and `wrangler dev --experimental-local` for testing.
=> Add `npx`/`wrangler` instructions to `README.md`

.github/workflows/cla.yml
With the CLA Assistant able, when a PR is opened it will check if the person has signed the CLA before, and if not, add a comment like this:
The link there goes to https://www.cloudflare.com/cla/ 
* Signatures will be stored in a file in this repo: `signatures/version1/cla.json` (this is configurable, and could even be in a separate repo)
* For users or bots who should not be required to sign the CLA, there's an `allowlist:` option in this file.
* There's currently no way to make an exception for "trivial changes" (fixing typos, etc)
=> Enable CLA Assistant on this repo

.github/workflows/cla.yml
CLA Assistant has a feature to lock a PR after merge.  We want this disabled.
Also moving signature to a separate branch for now.
=> Disable CLA Assistant locking PR's

README.md
Due to a rare issue explained in #41, I've added instructions to clean the cache and try rebuilding.
=> Updated README with instructions to clean build cache.

src/workerd/jsg/rtti-test.c++, src/workerd/jsg/rtti.capnp, src/workerd/jsg/rtti.h
This is what clients actually need to know if this is a built-in type or JS type.
=> jsg rtti: move implementation types to a separate enum

src/workerd/io/worker.c++
Failures that lead to alarm retries may in fact be JSG errors.
=> Cleanup: Do not log tunneled exceptions that cause alarm retries

src/workerd/jsg/jsg.h, src/workerd/jsg/value.h
It does not work when I try to add an ArrayPtr<byte> member field to a JSG_STRUCT, so we should remove the documentation of it. The functionality appears to have been removed in
ca17240f28279292f5fa8ae281965ee982a9cac7 without updating the comments.
=> Remove ArrayPtr<byte> from list of supported jsg wrapping types

src/workerd/io/worker.c++, src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h
Modules registered with addOnDemand method will be parsed and instantiated when all other imports failed.
=> jsg: dynamic imports

src/workerd/io/observer.h, src/workerd/io/worker.c++
A small observability addition.
=> Add LockTiming::waitingForOtherIsolate()

src/workerd/api/trace.c++, src/workerd/api/trace.h, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/worker-interface.capnp
Adds a property called `dispatchNamespace` on `TraceItem` so that Workers for Platforms customers can tell which namespace a script emitted trace events from.
=> Add dispatchNamespace to TraceItem

src/workerd/api/streams/README.md, src/workerd/api/streams/internal.c++, src/workerd/api/streams/internal.h, src/workerd/api/streams/queue-test.c++, src/workerd/api/streams/queue.c++, src/workerd/api/streams/queue.h, src/workerd/api/streams/readable.c++, src/workerd/api/streams/readable.h, src/workerd/api/streams/standard.c++, src/workerd/api/streams/standard.h, src/workerd/jsg/buffersource.c++, src/workerd/jsg/buffersource.h
Fixup streams tee backpressure regression and offset/size calculation bug.
=> Fixup streams bugs

src/workerd/api/api-rtti-test.c++, src/workerd/jsg/rtti-test.c++, src/workerd/jsg/rtti.h
With this it is now possible to fully handle recursive types.
=> rtti: symbol table to lookup structures

src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/io/actor-cache-test.c++, src/workerd/io/actor-cache.c++, src/workerd/io/actor-cache.h
This PR provides a way for a worker to wait for its writes (including those performed with allowUnconfirmed) to be flushed to storage. Note that if there is no flush currently pending, the JSG method will provide a resolved promise and the current task will continue through its microtask queue instead of yielding to other tasks.
=> Add explicit flush to Durable Object storage interface

src/workerd/jsg/rtti.h
Some unsigned long linux types are unsigned long long on mac.
=> jsg: adding long long types to rtti

src/workerd/io/trace.h, src/workerd/io/worker.c++
Also, stop the globals_instantiation span before top_level_execution.
=> Add more Jaeger spans to Worker constructor

src/workerd/api/r2-bucket.c++, src/workerd/api/r2-bucket.h
This allows JSON.stringify() to work on the result of head/list again
=> add toJSON implementation for R2Checksums

src/workerd/api/streams/standard.c++
```
const ws = new WritableStream();
const writer = ws.getWriter();
writer.close();
writer.close();
```
... would cause an internal error when it needed to be a user-facing error.
=> Change internal error to user facing error on writer double close

src/workerd/io/worker.c++
Sometimes we specify a class name as the entrypoint for a worker but fail to define the worker as an actor. The entrypoint is in the script but we cannot use it in this case, so let's emit a different error to help debug these issues.
=> Emit different error if a non-actor is looking for a class entrypoint

src/workerd/api/streams/internal.c++, src/workerd/api/streams/queue.c++, src/workerd/api/streams/queue.h, src/workerd/api/streams/readable.c++, src/workerd/api/streams/standard.c++, src/workerd/api/streams/standard.h
* Allows multiple respond/respondWithNewView to partially resolve readAtLeast byob reads.
* Fix IdentityTransformStream minBytes calculation
* Properly calculate atLeast with multi-byte views
/cc @harrishancock
=> Improved support for readAtLeast byob reads

src/workerd/api/kv.c++, src/workerd/api/kv.h, src/workerd/server/workerd-api.c++
We want to start injecting some headers in the multi-tenant runtime.
=> Add an ability to inject an arbitrary set of headers to KV requests

src/workerd/api/web-socket.c++
Browsers set the compression extension by default when `new WebSocket()` is called, since the API doesn't give the caller control over that header. See step 9 of whatwg's [opening handshake process](https://websockets.spec.whatwg.org/#websocket-opening-handshake) for websockets.
---
I think we can leave the `fetch()` implementation as is, since you could easily just set the extension header yourself:
```
let resp = await fetch(request, {
headers: {
"Upgrade": "websocket",
"Sec-WebSocket-Extensions": "permessage-deflate"
}
});
```
=> Request compression when calling `new WebSocket()` by default

src/workerd/io/actor-cache-test.c++, src/workerd/io/actor-cache.c++, src/workerd/io/actor-cache.h, src/workerd/io/io-context.c++, src/workerd/io/worker.c++, src/workerd/io/worker.h
Previously, we allowed scheduled flushes to continue after the Worker::Actor experienced shutdown. This meant that we would effectively commit to storage whatever write operations were in the write buffer when an actor became broken. Instead, we now cancel any scheduled flushes. There may still be in-flight flushes containing coalesced batches of writes from before the actor shut down.
=> Add explicit shutdown to ActorCache when the Worker::Actor is shutdown

src/workerd/api/kv.c++
Middleware might restrict the size of the URL that would get generate. Set a sane unrealistic upper bound that's guaranteed to get through to the KV worker. This should make error messages reliably clear when a name provided is too long.
=> Add baseline enforcement within the runtime

src/workerd/io/observer.h, src/workerd/io/worker.c++
This turned out to be unnecessary, since implementations of IsolateObserver can already receive arbitrary identifiers by other means.
=> Remove `id` parameter from IsolateObserver::created()

src/workerd/io/worker.c++, src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h
Built-in TypeScript modules were previously unable to import other built-in TypeScript modules due to a bug in the table indexing.
Adds a new internal-only scope for built-in modules.
Also adds the ability for built-ins to be sourced from jsg::Object's not just typescript.
=> Enable built-in modules to import internal modules

src/workerd/api/kv.c++, src/workerd/api/kv.h
Remove a bunch of boilerplate used to construct the `HttpClient` for a `KvNamespace`.
=> Cleanup KV HttpClient construction

src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker-entrypoint.h, src/workerd/server/server.c++
It turns out this is always redundant because if Jaeger tracing is enabled, `RequestObserver::getSpan()` returns non-null, and we can get the `Tracer` object from that.
Historically, `Tracer` was used for more than just Jaeger tracing, but the other usage was split off into the `WorkerTracer` class a few months ago. So, there's just no need to pass `Tracer` separately anymore.
Note that we should probably take this a few steps further and remove the `Tracer` class altogether, while moving the concept of spans over to `observer.h`, where it more naturally belongs at this point. I may work on that a bit later, but this simple cleanup seems worth merging as-is.
=> Cleanup: Don't pass `Tracer` to `WorkerEntrypoint::construct()`.

src/workerd/io/compatibility-date.capnp
We'd like to do a release of `workerd` to npm pretty soon—this bumps the compatibility date so the package version will work.
=> Bump compatibility date for release

.github/workflows/release.yml
This PR creates a GitHub Actions workflow to automatically create a release of `workerd` when the maximum supported compatibility date changes. A follow up PR will use the binaries uploaded to the release in order to publish a new version of `workerd` on npm
=> GitHub Actions workflow for automatic releases

types/BUILD.bazel, types/src/index.ts, types/src/program.ts, types/src/standards.ts, types/src/transforms/ambient.ts, types/src/transforms/comments.ts, types/src/transforms/helpers.ts, types/src/transforms/importable.ts, types/src/transforms/index.ts, types/src/transforms/overrides/index.ts, types/test/index.spec.ts
> This is blocked on merging #133 
This follows on from @mrbbot's work, by parsing the outputted type definitions along with `lib.webworker` and `lib.webworker.d.ts`. It does two major things:
- Attach doc comments from `lib.webworker` to the generated workers types, which gives much better documentation for standard types.
- Generate two versions of the types:
- [`api.ts`](https://gist.github.com/penalosa/204f40ba0719fb815db75ba28239f4fd#file-api-ts) which contains importable versions of the types. Importantly, they're only importable as types, not as values.
The intention here is that it will be possible to type a worker in combination with an ambient `lib.dom` or `lib.webworker` declaration, as the ambient declaration will provide global (value) versions of `Response` and `fetch` …
=> Generate an exportable and ambient version of the TypeScript types

src/workerd/tools/BUILD.bazel, src/workerd/tools/api-encoder.c++, types/BUILD.bazel, types/src/index.ts, types/src/program.ts, types/test/index.spec.ts
> Blocked on #136 
This generates a `bazel-bin/types/definitions/*/api.d.ts` and `bazel-bin/types/definitions/*/api.ts` file for the following compatibility dates:
> The expandable diff shows how the (ambient) types have changed from the directly preceding older date
<details>
<summary><code>latest</code>, the current up to date version of the runtime</summary>
<div>
<br/>
```sh
diff bazel-bin/types/definitions/2022-08-04/api.d.ts bazel-bin/types/definitions/latest/api.d.ts
```
```diff
515a516,539
> declare abstract class ReadableStreamBYOBRequest {
>   readonly view: Uint8Array | null;
>   respond(param0: number): void;
>   respondWithNewView(param0: ArrayBuffer | ArrayBufferView): void;
>   readonly atLeast: number | null;
> }
> declare abstract class ReadableStreamDefaultController<R = …
```
=> Generate multiple types, one for each compatibility date that changes type signatures

src/workerd/api/global-scope.h, src/workerd/api/http.h, types/BUILD.bazel, types/README.md, types/defines/cf.d.ts, types/defines/d1.d.ts, types/defines/pages.d.ts, types/defines/queues.d.ts, types/src/index.ts, types/src/transforms/importable.ts, types/test/index.spec.ts
A directory of TypeScript files can now be passed to the type generation scripts containing extra definitions appended to the
output. These don't correspond to `workerd` runtime APIs as their implementations are defined elsewhere (e.g. FL, Pages), so it doesn't make sense to include them in the C++ source code.
We kind of do this already with `JSG_TS_DEFINE` in `global-scope.h`...
https://github.com/cloudflare/workerd/blob/ad5665449bcdd117349ff563df7ab2e9163fd369/src/workerd/api/global-scope.h#L416-L515
...but this directory makes it easier to add definitions that don't have a logical C++ location. We can also use this for APIs that are only implemented internally and not ready to be open-sourced yet.
=> Add support for TypeScript-only definitions

src/workerd/api/analytics-engine.h
We want the Analytics Engine binding to be of type `AnalyticsEngineDataset` and the events to be of type `AnalyticsEngineDataPoint`.
=> Add overrides for Analytics Engine

samples/tcp/config.capnp, samples/tcp/gopher.js, src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/sockets.c++, src/workerd/api/sockets.h, src/workerd/api/system-streams.c++, src/workerd/api/system-streams.h, src/workerd/server/server.c++, src/workerd/server/workerd-api.c++, src/workerd/tools/api-encoder.c++
Depends on https://github.com/capnproto/capnproto/pull/1567.
This PR implements a new `connect` API which establishes a connection with a TCP server, then exposes that connection through two streams. In workerd this connection can be established directly or via a HTTP proxy. Examples of both are demonstrated using a new sample which implements a [Gopher](https://en.wikipedia.org/wiki/Gopher_(protocol)) client.
Testing using the sample provided:
```
$ bazel run //src/workerd/server:workerd -- serve $PWD/deps/workerd/samples/tcp/config.capnp --watch --verbose
```
Testing using custom code:
```
$ bazel run @workerd//src/workerd/server:workerd -- serve $PWD/my-config.capnp --watch --verbose
$ tinyproxy -d -c tinyproxy.conf
$ nc -l 6666
```
* Verified that streams get closed properly when `nc` …
=> Implements API for connecting to TCP servers in workers

src/workerd/api/trace.c++, src/workerd/api/trace.h, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker-interface.capnp
Custom events do not currently get a timestamp assigned, instead being logged with an unix epoch value. Create a custom event info, empty for now, so that we can correctly set the timestamp.
=> call setEventInfo() for custom events

src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/worker-entrypoint.c++
The TraceCustomEventImpl is a custom event and when handling it the incomingRequests list is empty, causing getCurrentIncomingRequest() to fail.
A new version of IoContext::now() is introduced for when we already have an incoming request available.
=> fix context.now() when handling a trace

src/workerd/io/worker-entrypoint.c++
Instead of setting event info in the general
custom event handler, let these custom events
set it themselves.
=> set event info in custom event

src/workerd/io/worker-entrypoint.c++, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h
Automatically run garbage collection after each EW test to catch kj::Own/IoOwn issues.
=> During testing the GC will run after every test.

src/workerd/jsg/util.c++
Currently, workers have to rely upon the `Error.message` value to determine if their durable object is broken. Usually, the worker will want to retry their request to reinitialize their durable object and continue work. Thus we want to set a property like the existing `Error.remote` property to convey that the the request failed because the durable object became broken.
=> Provide a way to determine if a durable object is broken from errors

src/workerd/api/trace.c++, src/workerd/api/trace.h, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/worker-interface.capnp
Adds support for script tags in trace events by introducing an optional string array property on `TraceItem` called `scriptTags`. Because most Workers will never have script tags on them this property is optional and undefined if no tags are defined.
=> Add scripts tags to Trace Workers

.github/workflows/labels.yml
Adds a new github action that will block merging of a PR if it has the label `needs-internal-pr`. This is not a perfect solution, of course, but allows us to easily flag PRs that should not be landed without a corresponding Workers PR ready to go (which requires manual confirmation)
=> Add action to block merging if PR labeled `needs-internal-pr`

WORKSPACE, src/workerd/api/sockets.c++, src/workerd/api/sockets.h, src/workerd/server/server.c++
This is a simplified version of https://github.com/cloudflare/workerd/pull/200, containing just the diff required to be able to merge https://github.com/capnproto/capnproto/pull/1579.
=> Update sockets to use new pipelining support in capnproto.

src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h, src/workerd/jsg/util.c++, src/workerd/jsg/util.h
Uses externalized strings for built-in modules to avoid copying built-ins into every isolate's heap. Results in a significant reduction in memory use per isolate for built-ins.
=> Use externalized strings for built-in js/ts modules

src/workerd/io/worker-interface.c++, src/workerd/io/worker-interface.h
Depends on https://github.com/capnproto/capnproto/pull/1586/.
In internal repo:
```
$ bazel test //src/edgeworker/tests:sockets/sockets-tcp-test.ew-test-bin@force-process-sandboxing
```
=> Implements RpcWorkerInterface::connect.

src/workerd/api/http.c++, src/workerd/api/http.h
In order to support global Fetchers which are backed by anything other than a subrequest channel, we need to support having a normal 'kj::Own'ed OutgoingFactory.
=> Support non-"IoOwn"ed 'OutgoingFactory's in Fetcher

WORKSPACE, patches/v8/0001-Allow-manually-setting-ValueDeserializer-format-vers.patch, patches/v8/0002-Allow-manually-setting-ValueSerializer-format-versio.patch, patches/v8/0003-Make-icudata-target-public.patch, patches/v8/0004-Add-ArrayBuffer-MaybeNew.patch, patches/v8/0005-Revert-bazel-Add-hide-symbols-from-release-fast-buil.patch, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/resource.h, src/workerd/jsg/setup.c++, src/workerd/jsg/setup.h, src/workerd/jsg/tracing-test.c++, src/workerd/jsg/wrappable.c++, src/workerd/jsg/wrappable.h
V8's `EmbedderHeapTracer` API is going away, and integration with cppgc is the replacement.
Compared to #171, this PR is much more conservative, only making the minimal changes necessary to move off the deprecated APIs before the deadline. #171, in contrast, proposes much deeper design changes to JSG's reference hierarchy. These design changes may have advantages, but I think we need to evaluate those advantages independently of the urgent need to switch APIs. Once this more conservative PR is landed, then we can consider broader design changes.
Additionally, I went ahead and implemented an optimization: I integrated with `EmbedderRootsHandler` to allow wrappers to be collected during minor GCs (aka "scavenges"). V8 has a trick here where it'll propose collecting any _unmodified_ API …
=> Switch from EmbedderHeapTracer to cppgc

types/defines/queues.d.ts
This commit adds relevant docstring to sendBatch method in Queues API, which was previously not supported.
=> Add sendBatch definition to @cloudflare/workers-types

src/workerd/io/trace.c++, src/workerd/io/trace.h
When starting to record a Jaeger span, we do two different clock reads -- we read the calendar clock for the timestamp, and we read from the monotonic clock for the start of the span duration.  We also allow callers to override the timestamp, to record a span that started earlier.  But this override was only affecting the timestamp, not the start of the span duration, so durations for overridden spans were incorrect.
Ideally, we'd want callers to provide both the monotonic and calendar clock measurements for their span overrides, but as a stopgap we can compute the elapsed calendar time at the time of the override and subtract it from the current monotonic clock time, to estimate the intended duration start time.
(The official Jaeger C++ library has a more complex system, allowing users …
=> Fix overridden Jaeger span duration

src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h
~~Builds on #201 which would need to land first~~
Implements a per-process cache for compiled built-in js/ts modules aimed at reducing the peformance impact of loading those repeatedly across many isolates. ~~This is purely experimental right now so this PR will remain as a draft for the time being.~~
=> Experimental code cache for built-in js/ts modules

src/workerd/io/worker.c++
We already catch exceptions generated by the app itself, but under certain circumstances, our calls to the V8 API in this callback can throw.
I am actually not even sure how to trigger such an exception but there was one odd crash report in production.
=> Properly handle JS exceptions in promise rejection callback.

src/workerd/io/worker.c++, src/workerd/io/worker.h
When testing via fiddle this code path was hit. 
@kentonv should `connect` be implemented in all classes which extend WorkerInterface/HttpService? if not are there any other `connect` codepaths which are likely to be hit in production and so should be implemented?
=> Implement missing Worker::Isolate::SubrequestClient::connect.

src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker-entrypoint.h, src/workerd/io/worker-interface.c++, src/workerd/io/worker-interface.h, src/workerd/server/server.c++
Not 100% sure whether I understood the purpose of each of these classes. In particular, is there anything special I need to do in the RevokableWorkerInterface implementation?
Just checking that build succeeds:
```
$ bazel build //src/ew/tests:sockets/sockets-tcp-test.ew-test-bin
```
=> Enforce WorkerInterface::connect to be implemented in all subclasses.

src/workerd/api/global-scope.h, src/workerd/api/http.h, src/workerd/api/sockets.c++
This resolves my comment from #180.
=> Hide `connect()` function entirely when the flag is not enabled.

src/workerd/api/sockets.c++, src/workerd/api/sockets.h
This addresses my unresolved comments from #162.
=> Fix `tsl` typo and comment about address validation

src/workerd/api/actor.c++, src/workerd/io/io-channels.h, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/jaeger-test.c++, src/workerd/io/jaeger.c++, src/workerd/io/jaeger.h, src/workerd/io/observer.h, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server.c++
This is a sketch of a better interface for trace spans that does not involve a `Tracer` object. Instead, anything which needs to produce traces receives a `SpanParent`, which is a reference to a parent span, and can create children from that.
An additional goal of this refactoring is to eliminate the dependency on Jaeger which also allows us to eliminate the dependency on Protobuf. Jaeger is one system that these traces could feed into, but by abstracting the API we can potentially support many different trace collectors.
The classes are designed such that if no tracing is active, no extra memory allocations are needed.
This is very incomplete. I'm uploading it for discussion purposes.
The interface proposal is in `trace.h`. The rest is showing how some things would change to use this.
=> Improve representation of trace spans.

src/workerd/api/actor-state.c++, src/workerd/api/r2-rpc.c++, src/workerd/io/actor-cache.h, src/workerd/io/actor-storage.c++, src/workerd/io/actor-storage.capnp, src/workerd/io/actor-storage.h, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/promise-test.c++
These functions are no longer preferred in favor of `JSG_[FAIL_]REQUIRE()`. Luckily, they were only in limited use in the durable object and r2 code.
=> Cleanup: Take out jsg error throwing functions

src/workerd/io/compatibility-date.capnp
We don't want to bake the version or "Experimental" flag in the name.
=> Rename nodejs compat flag to remove version

types/src/generator/structure.ts, types/src/generator/type.ts, types/test/generator/structure.spec.ts, types/test/generator/type.spec.ts
This PR fixes the TypeScript types of `waitUntil`s to accept `Promise<any>` rather than `Promise<void>`.
See 
https://www.typescriptlang.org/play?target=99#code/MYewdgzgLgBMCGwAWBTGBeG8Du8CWsCyKEAdCAA4pgAUAREanQJQDcAUOwCYrAA28AE5oAZgFcwwKHnAwQfLgHV8UAKphpfGhUEgAtnggoAXDAAKug0YA8ANxB4uAPman7jjvKUr1mmoxRSHj4UKBR6JCgoCmMAeli+EAQ+JBBoWJY2GHiYQF4NwCI99i9lAl88LQCglBCwiKiY+MTk1PSWUihUWhpmDCcYAG8AX2YsnMA+DcAiXc4efiFRCSkZMBgwFGwStQ1y7UtDE3Ndm3gwAE8XNwcuDlX1ny2KxFQqmvC6SOi4hKT4FLSoDJGrGysTygAA9zgoAAeFBAglgQyAA.
=> Fix `waitUntil` types to accept any `Promise` as opposed to just `Promise<void>`

src/workerd/io/trace.h
#141 introduced some new uses of `uint` without a corresponding `using kj::uint;`. [`Build & Release` CI](https://github.com/cloudflare/workerd/actions/workflows/release.yml) has been failing since.
=> Use `kj::uint` to fix macOS builds

src/workerd/api/html-rewriter.c++, src/workerd/api/http.c++, src/workerd/api/kv.c++, src/workerd/api/r2-bucket.c++, src/workerd/api/r2-rpc.c++, src/workerd/api/streams/common.h, src/workerd/api/streams/internal.c++, src/workerd/api/streams/internal.h, src/workerd/api/streams/readable.c++, src/workerd/api/streams/readable.h, src/workerd/api/streams/standard.c++, src/workerd/api/streams/standard.h
The `ReadableStreamJsSource` class was a bit overly complicated. This PR allows us to eliminate it entirely through a number of key refactors.
* We eliminate all uses of `removeSource` and direct uses of `ReadableStreamSource` outside of internal streams. This means moving methods like `tryGetLength(...)` and `pumpTo` directly onto `ReadableStream`.
* We refactor `readAllText()` and `readAllBytes()` to use pure JS read loops when reading from JS-backed streams. This eliminates the expensive pass through `ReadableStreamJsSource` that we were performing (and thus bouncing in an out of the event loop / isolate lock on every read.
* We refactor the pumpTo implementation for JS-backed streams to be more efficient, using default reads for both default and byob JS-backed streams.
* We clarify …
=> Refactor out ReadableStreamJsSource

WORKSPACE, src/workerd/server/server-test.c++, src/workerd/server/server.c++, src/workerd/server/server.h, src/workerd/server/workerd.c++
We will wait for all in-flight requests to complete, without accepting any new requests.
Depends on: https://github.com/capnproto/capnproto/pull/1598
Addresses part of #101.
=> Gracefully drain process on SIGTERM.

src/workerd/api/trace.c++, src/workerd/api/trace.h, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/worker-interface.capnp
Added new event info type for email events. This will contain the from, to and raw size of the email.
=> new event info type email

WORKSPACE, src/workerd/server/BUILD.bazel
This improves throughput by 30% as tested by `wrk` running against `samples/hello`.
=> Use tcmalloc for memory allocation.

README.md
Almost certainly users don't need to do a full bazel clean for this scenario.
=> Recommend alternative to bazel clean in README.md

samples/async-context/config.capnp, samples/async-context/worker.js, src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/node/async-hooks.c++, src/workerd/api/node/async-hooks.h, src/workerd/api/node/node.h, src/workerd/jsg/README.md, src/workerd/jsg/async-context.c++, src/workerd/jsg/async-context.h, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/setup.c++, src/workerd/jsg/setup.h, src/workerd/server/workerd-api.c++, src/workerd/tools/api-encoder.c++
Initial experimental async context tracking (internals only). ~~This is intended to set the stage for an eventual implementation of `AsyncLocalStorage` (and later the proposed TC-39 `AsyncContext` proposal that is based on `AsyncLocalStorage`.)~~
This initial PR seeks ~~only~~ to add the internal book keeping for the async context, including implementing the basic v8 promise hooks, as well as attaching the async context tracking to `setTimeout`, `setInterval`, and `queueMicrotask`. 
This PR ~~does not~~ implements the `AsyncLocalStorage` API as well.
Note that we eventually expect V8 to implement these core mechanisms as part of the `AsyncContext` proposal implementation as that moves forward in TC-39, but that will be some time off and there's no guarantee that proposal *will* advance …
=> Initial implementation of async context tracking

build/wd_api_bundle.bzl, src/node/BUILD.bazel, src/node/README.md, src/node/buffer.ts, src/node/internal/bufferImpl.ts, src/node/tsconfig.json, src/workerd/jsg/BUILD.bazel, src/workerd/jsg/modules.capnp, src/workerd/jsg/modules.h
This has all the changes as #258 except the actual usage in `workerd-api.c++`. Thus it won't break ekam build while I figure it out.
=> node compatibility typescript infrastructure

src/workerd/server/BUILD.bazel
Appraently, tcmalloc is linux-only.
=> Fix MacOS build by not using tcmalloc.

src/workerd/api/util-test.c++, src/workerd/api/util.c++, src/workerd/api/util.h
Handle scenario where the content-type header has
multiple params.
=> fix content-type param extraction

WORKSPACE, src/workerd/server/server-test.c++, src/workerd/server/server.c++, src/workerd/server/server.h, src/workerd/server/workerd.c++
This reverts #255, which reverted #244.
The test failure was caused by the Cap'n Proto submodule not having been updated in the internal repo. That has since been fixed.
=> Revert "Revert "Gracefully drain process on SIGTERM.""

src/workerd/api/sockets.c++, src/workerd/api/sockets.h, src/workerd/api/system-streams.c++, src/workerd/api/system-streams.h
This is a more basic version of https://github.com/cloudflare/workerd/pull/205. The main change in semantics here is that the `closed` promise will now have any errors propagated to it (from the readable/writable stream close calls). The rest is a major refactor to reuse the existing `newPromisedStream`.
```
$ bazel test //src/ew/tests:sockets/sockets-tcp-test.ew-test-bin --config=asan --test_timeout 5
```
=> Refactors Sockets closed promise handling.

src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h, src/workerd/server/server-test.c++, src/workerd/server/server.c++, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h
Hey! 👋 Currently, when multiple nanoservices are configured with service worker scripts, they'll all use `worker.js` as their script origin. This means if an error is thrown, it's difficult to identify which script threw from inspecting the stack trace. We hit this issue in Miniflare, when attempting to locate source maps for service workers: https://github.com/cloudflare/miniflare/blob/5ecaae2b482feb583d8eeca2310785ea4d68165c/packages/tre/src/plugins/core/prettyerror.ts#L37-L41.
This PR adds a new `name` option for configuring the script origin of service worker scripts. Rather than making `serviceWorkerScript` a `:group` with `name`, I've added a new `serviceWorker` union member to maintain text-format compatibility.
=> Use service name as service worker script name

WORKSPACE, build/wd_api_bundle.bzl, src/node/BUILD.bazel, src/node/README.md, src/node/buffer.ts, src/node/internal/bufferImpl.ts, src/node/tsconfig.json, src/workerd/jsg/BUILD.bazel, src/workerd/jsg/modules.capnp, src/workerd/jsg/modules.h
Third time's the charm. No changes, just rebased on top of fresh capnp revision. 
This reverts commit e88bae5f3817d5d40c06a7b988fd284be1a96b98.
=> Revert "Revert "node compatibility typescript infrastructure""

src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/url-standard-test.c++, src/workerd/io/compatibility-date.capnp
Added a new flag to enable the use of spec compliant URL parsing when doing a redirect. There was a previous flag to enable the use of this new class but it was not used when calling the redirect() method, hence the need for a new flag.
=> Redirect spec flag

src/workerd/jsg/setup.c++
https://github.com/cloudflare/workerd/pull/282 is a better more complete change but this addresses an immediate bug.
=> Clear root context frame under lock

WORKSPACE, patches/v8/0006-bazel-Allow-compiling-on-macOS-catalina-and-ventura.patch
This patch adds a patch to allow building workerd on macOS Catalina to Ventura.
Fix https://github.com/cloudflare/workerd/issues/45
Signed-off-by: Dhi Aurrahman <dio@rockybars.com>
=> macos: Allow compiling on catalina to ventura

src/workerd/tests/test-fixture.c++
looks like it is already included in most environments somehow, but others need it.
=> add missing header

src/workerd/api/actor-state.c++, src/workerd/io/actor-cache-test.c++, src/workerd/io/actor-cache.c++, src/workerd/io/actor-cache.h
Since we already batch write operations within a transaction, we can remove the limitation on maximum number of keys. This is trivial for puts and unawaited deletes. However, we had not yet batched deletes where the worker awaits the count of how many pairs are actually deleted. This PR involves a fair amount of refactoring until we reach a point where it is easy to understand what has functionally changed for counted deletes and confirm that there are no obvious side effects for removing our limitation. Hopefully, it will be easier to modify the actor cache flush code in the future.
=> Remove limitation on maximum number of keys in write operations

src/workerd/api/trace.h
EmailInfo attributes were incorrectly declared which prevented them from being serialized into the trace event.
=> fix email info declaration

src/workerd/jsg/jsg-test.c++, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/setup.c++, src/workerd/jsg/setup.h
The `jsg::Lock::getUuid()` will lazily create a random uuid for the
isolate instance. It is expected that this will primarily be used for
logging/diagnostics in DO cases. The uuid is generated lazily so there
is zero cost if the uuid is never used.
( Prompted by a chat with @bcaimano )
Another option would be to just log the memory address of the isolate itself but the requirement here is that the uniqueness be relatively guaranteed for the lifetime of the process, which we can't guarantee with the pointer address. We could also use a simple counter but that would likely require a lock. lazily creating the uuid here seems Good Enough (tm).
=> Allow an isolate to have a simple random uuid

src/workerd/api/streams/standard.c++, src/workerd/io/io-context.h
Also, add a new `awaitIo()` overload which accepts a callback and errorback, which we need here.
=> Make PumpToReader stay on its own IoContext

.bazelrc, build/kj_test.bzl, src/workerd/util/BUILD.bazel, src/workerd/util/symbolizer.c++
When linked it, looks for $LLVM_SYMBOLIZER environment variable and uses it for stacktrace symbolication.
To use it with bazel you should add `--config=fastdbg --test_env=LLVM_SYMBOLIZER=llvm-symbolizer-15`
to your test command.
=> stack-trace symbolizer using llvm-symbolizer subprocess

src/workerd/api/streams/standard.c++, src/workerd/api/system-streams.c++
Original commit description by @jasnell:
Because kj::AsyncOutputStream does not have an explicit end, some impls use their destructor to perform final writes, some of those using held bare refs to other objects. If the EncodedAsyncOutputStream happens to be held by an IoOwn (or some other mechanism that extends its lifetime past that of those deeply nested bare refs) then we can have a problem.
Here, we modify EncodedAsyncOutputStream to free inner when either end or abort are called, effectively neutering it and allowing the inner to perform any additional cleanup it needs on end.
=> Neuter the EncodedAsyncOutputStream on end/abort

src/workerd/jsg/util.h
At the moment trying to unwrap a jwk wrapped key
fails since v8Str() cannot handle char arrays.
=> v8Str: add support for char arrays

src/workerd/api/kv.c++, src/workerd/api/kv.h, src/workerd/api/r2-admin.c++, src/workerd/api/r2-admin.h, src/workerd/api/r2-bucket.c++, src/workerd/api/r2-bucket.h, src/workerd/api/r2-multipart.c++, src/workerd/api/r2-multipart.h, src/workerd/api/r2-rpc.c++, src/workerd/api/r2-rpc.h, src/workerd/io/compatibility-date.capnp, src/workerd/jsg/README.md, src/workerd/jsg/buffersource-test.c++, src/workerd/jsg/buffersource.c++, src/workerd/jsg/buffersource.h
Prior to this change, R2/KV would allow post-call modification of the ArrayBuffer. This updates it to copy by default and detach with enablement of a compat flag.
=> Update R2/KJ to avoid mod-after-put when using ArrayBuffer

src/workerd/api/kv.c++, src/workerd/api/kv.h, src/workerd/api/r2-admin.c++, src/workerd/api/r2-admin.h, src/workerd/api/r2-bucket.c++, src/workerd/api/r2-bucket.h, src/workerd/api/r2-multipart.c++, src/workerd/api/r2-multipart.h, src/workerd/api/r2-rpc.c++, src/workerd/api/r2-rpc.h, src/workerd/io/compatibility-date.capnp, src/workerd/jsg/README.md, src/workerd/jsg/buffersource-test.c++, src/workerd/jsg/buffersource.c++, src/workerd/jsg/buffersource.h
Reverts cloudflare/workerd#309
This change was merged prematurely, the team hasn't reached consensus on this approach. Some possible concerns:
* What is the performance impact of copying? Is it worth the cost to force copying on existing users?
* Is detaching ArrayBuffers a good API? Will it possibly confuse people who are trying to pass the same ArrayBuffer to multiple calls?
It's possible we'll re-land this exactly the same once we've talked this through.
=> Revert "Update R2/KJ to avoid mod-after-put when using ArrayBuffer"

npm/workers-types/README.md, npm/workers-types/entrypoints.svg, src/workerd/tools/BUILD.bazel
This PR generates types for the `2022-10-31` (default on for `url_standard`) and `2022-11-30` (default on for `streams_enable_constructors` and `transformstream_enable_standard_constructor`) compatibility dates, both of which change the public type surface.
It also adds a diagram to clarify which entrypoint should be selected for which compatibility date.
=> Add `2022-10-31` and `2022-11-30` types entrypoints and diagram

.bazelrc, build/kj_test.bzl, src/workerd/util/BUILD.bazel, src/workerd/util/symbolizer.c++
we already have `-DEKAM_BUILD=1` in our make file.
=> reland stack-trace symbolizer with ekam protection

src/workerd/api/http.c++, src/workerd/api/http.h
Previously we would throw explicitly for certain unimplemented properties. In discussing the matter in wintercg with other implementers, it was decided that returning undefined or reasonable defaults for unsupported features was preferable. This updates several cases in `Request` and `Response`.
=> Improve fetch spec compliance for Request/Response

src/workerd/io/compatibility-date.capnp
Will be used, for instance, to incrementally work on experimental Node.js compatibility stuff separately from the nodejs_compat flag that will be used to enable the stuff that's stable.
=> Adds a catch-all experimental compatibility flag for incremental work

src/workerd/api/actor.c++, src/workerd/api/actor.h, src/workerd/io/compatibility-date.capnp, src/workerd/io/io-channels.h, src/workerd/io/io-context.h, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++
Right now this isn't implemented in workerd's ActorChannel, as this is an internal-only experimental method.
Still need to add a commit to hide `getExisting` from being generated by workers-types
@MellowYarker as primary reviewer
=> Add experimental `getExisting` method to DurableObjectNamespace

src/workerd/api/http.c++
The check was placed in the wrong location, and the test was buggy so spuriously passed.
=> Actually block use of `Request.integrity`.

src/workerd/api/global-scope.c++, src/workerd/api/html-rewriter.c++, src/workerd/api/node/async-hooks.c++, src/workerd/api/node/async-hooks.h, src/workerd/io/io-context.h, src/workerd/jsg/README.md, src/workerd/jsg/async-context.c++, src/workerd/jsg/async-context.h, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/promise.c++, src/workerd/jsg/promise.h, src/workerd/jsg/setup.c++, src/workerd/jsg/setup.h
There are two key changes here:
* Elimate the root context frame: It occurred to me that we really do not need a root AsyncContextFrame instance at all since there's nothing actually being stored there ever. Just have AsyncContextFrame::current() return an empty kj::Maybe in that case and treat the nullptr as equivalent to the root frame.
* Makes use of an obscure v8 API that allows setting continuation context for promises and tasks. Allows a number of simplifications.
Also fixes a couple of minor bugs.
=> Simplify and refine async context tracking

src/workerd/io/actor-cache-test.c++, src/workerd/io/actor-cache.c++, src/workerd/io/actor-cache.h
This is just doing the same thing for deletes (both muted and batch) that we already do for puts and alarm writes. Sorry for letting this sit for so long without finishing it up (especially since deletes should benefit the most from not needing transactions due to a quirk within cockroach transaction pipelining).
---
This PR is the same as #337, but this time from a branch in the main repo as opposed to a branch on my fork (so that CI will finish in a reasonable amount of time). Sorry for the noise -- I've now updated my local setup to make it much harder for me to make this mistake again.
=> Optimize single-batch delete flushes in ActorCache

src/workerd/io/cdp.capnp, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++
Allows a workerd inspector client to be fully trusted, enabling a greater range of devtools capabilities (including memory profiling and timeline)
=> Allow workerd inspector client to be fully trusted

src/workerd/api/node/node.h, src/workerd/jsg/resource.h, src/workerd/jsg/rtti.h
For use only by built-in TypeScript modules, this provides an import that gives information on the currently set compatibility flags.
e.g.
```
import { default as flags } from 'worker:compatibility-flags';
console.log(flags.nodeJsCompat); // true|false
```
The flags are set as readonly booleans on the export.
Note that this does introduce an issue if we rename any of the compatibility flags. Right now renaming will cause a compile error in the native code because the `getWhatever` method names will change. However, we won't get errors during compile for the typescript side unless we also someone automatically generate a ts.d for this built-in from the capnp definitions.
=> Add workerd:compatibility-flags internal built-in module

src/workerd/api/sockets.c++, src/workerd/api/sockets.h
=> Reject TCP socket `closed` promise when proxy rejects connections.

src/workerd/jsg/util-test.c++, src/workerd/jsg/util.c++
This commit resolves a TODO about refactoring code for different error types in `decodeTunneledException`. This should make the code more maintainable if there are future additions. I also added some test cases for handling compile errors and DOM exceptions since tunneling them was not tested before and adding them made it easier to spot potential bugs while refactoring the function.
=> Refactor JSG exception decoding, add relevant test cases

src/workerd/api/actor-state.c++, src/workerd/io/actor-cache-test.c++, src/workerd/io/actor-cache.c++, src/workerd/io/actor-cache.h
We had previously removed the limitation on non-transaction writes. This work does the extra steps required to remove impediments in DurableObjectTransaction/ActorCache::Transaction.
=> Remove limit on total entries in a DurableObjectTransaction

src/workerd/api/http.h, src/workerd/api/url-standard.h, src/workerd/api/url.h
=> Fixup buggy URLSearchParams iterators

src/workerd/api/streams/standard.c++
=> Cleanup PumpToReader further

src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server.c++
Since we may want to make the components (notably ActorObserver) separately, it turns out that we want to take the lock slightly before constructing the Worker::Actor.
=> Take Worker::Lock by reference when constructing a Worker::Actor

src/workerd/api/crypto-impl-asymmetric.c++, src/workerd/api/crypto-impl-test.c++, src/workerd/api/crypto-impl.c++
This commit improves error handling in the Web Crypto API:
- Do error checking for a few functions that can produce openssl errors and did not have error checking previously. This should result in more meaningful errors being reported.
- Examine errors more thoroughly in `throwOpensslError`, this is necessary as some error codes in different libraries have the same value, this could result in the wrong error being recorded unless the library code is checked too.
- Add a new test case to ensure that the function is now working correctly.
=> Extend and harden crypto api error handling

samples/nodejs-compat/worker.js, src/node/internal/internal_errors.ts, src/node/internal/internal_format.ts, src/node/util.ts
Supported:
Questionable (might not implement these, but if we do it will be later)
* inspect
* deprecate
* debug/debuglog
* toUSVString
* MIMEType (experimental added in 19.x)
* parseArgs() (experimental added in 19.x, backported, not relevant?)
* stripVTControlCharacters (not relevant?)
* isDeepStrictEqual
Won't implement:
* transferableAbortController/transferableAbortSignal
* deprecated util.is* methods
=> Add Node.js Compat utils implementation

types/defines/queues.d.ts
To support partial batch ack, extend `Message` and `MessageBatch` types with `ack()`, `retry()`, and `ackAll()` methods.
=> Extend Message and MessageBatch types

src/workerd/api/kv.h
Currently the types are correct if you do:
```js
const myArrayBuffer = env.KV.get("myKey", "arrayBuffer")
```
But incorrect if you do:
```js
const myArrayBuffer = env.KV.get("myKey", { type: "arrayBuffer", cacheTtl: 60 })
```
=> Fix KVNamespace get() types when passing KVNamespaceGetOptions

src/workerd/api/global-scope.c++, src/workerd/io/worker.c++, src/workerd/io/worker.h
While we were correctly observing that exceptions had happened in the event outcome, we were not logging these exceptions in the trace, which makes debugging difficult for worker developers.
=> Report js exceptions from alarm handlers in traces

src/workerd/api/form-data.c++, src/workerd/api/form-data.h, src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/url-standard.c++, src/workerd/api/url-standard.h, src/workerd/api/url.c++, src/workerd/io/compatibility-date.capnp, src/workerd/jsg/iterator.h
Implementation of the proposed `headers.getSetCookie()` API
~~The API is still not 100% finished so we likely don't want to land just yet. Deno folks have asked (through wintercg) if we could coordinate on the release of this so that it hits multiple runtimes at the same time, allowing us to get a bit more of a bang-for-the-buck announcing the common API.~~ The spec change has landed, this should be just about ready to go.
~~Note: this is *potentially* a breaking change due to the change in the way the iterator is handled. Previously, our iterator would inappropriate munge `set-cookie` headers together. This change separates them properly for both `entries()` and `values()`. Do we need a compatibility flag tor this behavior change?~~ Added a compatibility flag
Refs: …
=> Implement headers.getSetCookie()

src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/sockets.c++, src/workerd/api/sockets.h
This is a breaking change to the API, but one that should make it more consistent with other implementations.
=> Change TCP Socket's `connect` to take a SocketAddress struct.

src/workerd/api/actor-state.c++, src/workerd/io/worker.c++, src/workerd/io/worker.h
For implementation reasons, we cannot confirm the presence of an alarm handler during the invocation of a durable object's constructor. That said, we also cannot confirm the absence of that handler either. Let's just lean on the alarm runner to do the right thing when the time comes.
=> Allow setAlarm to be invoked in Durable Object constructors

src/workerd/api/sockets.h
@jasnell  suggested I make this change.
Tested with upstream tests:
```
$ bazel test //src/ew/tests:sockets/sockets-tcp-proxy-newproto-test.ew-test-bin --config=asan --test_timeout 15
```
=> Use JSG_READONLY_PROTOTYPE_PROPERTY in sockets.

src/workerd/io/compatibility-date.capnp
Before the flag, exceptions are not tunneled to a dynamic dispatch caller. After the flag, they will be..
=> Add compatibility flag for dynamic dispatch exception tunneling behavior

WORKSPACE, build/BUILD.sqlite3, src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/io/BUILD.bazel, src/workerd/io/actor-sqlite.c++, src/workerd/io/actor-sqlite.h, src/workerd/server/server-test.c++, src/workerd/server/server.c++, src/workerd/server/workerd.capnp, src/workerd/util/BUILD.bazel, src/workerd/util/sqlite-kv-test.c++, src/workerd/util/sqlite-kv.c++, src/workerd/util/sqlite-kv.h, src/workerd/util/sqlite-test.c++, src/workerd/util/sqlite.c++, src/workerd/util/sqlite.h
Each DO gets its own separate SQLite database.
There is no change to the storage API (for now). We simply use SQLite to store keys and values behind the traditional DO storage API.
This was a weird project where the first 10% of the project (creating the SQLite/KJ bindings) took 90% of the time, and the remaining 90% (implementing Durable Objects in terms of it) took 10% of the time.
I think the plan is for @TrevorSundberg to review this.
/cc @xortive @bcaimano @a-robinson @bretthoerner who are probably interested.
=> Allow Durable Objects to be stored persistently on local disk using SQLite

src/workerd/api/streams/common.h, src/workerd/api/streams/readable.c++, src/workerd/api/streams/readable.h, src/workerd/api/streams/standard.c++, src/workerd/api/streams/standard.h, src/workerd/api/streams/transform.c++, src/workerd/api/streams/writable.c++, src/workerd/api/streams/writable.h
Previous fix broke ability to create a ReadableStream outside of an IoContext.
=> Relax overly strict IoContext checking for ReadableStreams

src/workerd/api/node/async-hooks.c++, src/workerd/api/node/async-hooks.h, src/workerd/jsg/async-context.c++, src/workerd/jsg/async-context.h
Additions to AsyncLocalStorage in Node.js that serve a dual purpose:
1. They align the API closer to the expected AsyncContext.wrap api (AsyncLocalStorage.bind == AsyncContext.wrap). It uses the existing naming from AsyncResource for consistency with the existing API.
2. They eliminate the need to use AsyncResource. We will keep AsyncResource for backwards compatibility as part of the larger Node.js compat story, but these cover all of the key use cases of AsyncResource for context tracking.
The TC-39 `AsyncContext` proposal is expected to include `AsyncContext.wrap(...)` (which is the same as `AsyncLocalStorage.bind(...)` and some version of a `AsyncContext.snapshot()` (naming still to be determined).
Refs: https://github.com/nodejs/node/pull/46387
```js
// The AsyncResource use case... …
```
=> Adopt proposed new Node.js AsyncLocalStorage apis to replace AsyncResource use cases

types/defines/cf.d.ts
Example: `➜  ~ curl https://kian.org.uk/cf.json | jq '.botManagement'`
```json
{
"corporateProxy": false,
"verifiedBot": false,
"staticResource": false,
"detectionIds": [
33554817
],
"score": 1
}
```
=> types: add botManagement.detectionIds to cf.d.ts

src/workerd/api/crypto-impl-asymmetric.c++
Commit messages and comments should explain the changes reasonably well, please let me know if you find anything unclear.
One issue that merits discussion is whether to validate imported RSA keys. Calling validateRsaParams() should only reject keys that are unreasonably large or possibly insecure based on the modulus size or exponent, but may break existing scripts that import such keys. Fortunately, the other changes add some key size checks during signing and should be sufficient to prevent internal errors even if unreasonably small keys are imported.
For signing with RSASSA-PKCS1-v1_5, in very few cases errors will be reported where there previously was no error (e.g. when importing a key of exactly 62 or 63 bytes, using SHA256 as the hash digest and trying to use it for signing). I …
=> Improve Webcrypto error handling, resolve several internal errors and add clarifying comments

src/workerd/api/streams/compression.c++, src/workerd/api/streams/compression.h, src/workerd/jsg/README.md, src/workerd/jsg/jsg.h, types/src/transforms/overrides/compiler.ts
With deflate-raw, we have all required data formats for the current Compression Streams API version. Also see the eponymous internal branch.
=> Add support for deflate-raw and check for trailing or incomplete data in Compression Streams

.github/workflows/npm.yml
`ReferenceError: WORKERD_VERSION is not defined` was being thrown when installing with Yarn PnP. In the npm publishing GitHub actions workflow for `workerd`, we were missing an `esbuild` define to replace `WORKERD_VERSION` with a constant when building `node-shim.ts`. This change copies the define from the `node-install.ts` and `node-path.ts` builds.
=> Add missing `--define:WORKERD_VERSION` to `Build node-shim` step

src/node/buffer.ts, src/node/events.ts, src/node/internal/internal_assert.ts
Hey! 👋 This PR adds some missing default exports and removes an extraneous `assert` export, to match the behaviour of Node.js:
```js
import assert from "node:assert";
import * as all_assert from "node:assert";
import buffer from "node:buffer";
import events from "node:events";
console.log(typeof assert); // function
console.log(assert.assert); // undefined
console.log(all_assert.assert); // undefined
console.log(typeof assert.AssertionError); // function
console.log(typeof all_assert.AssertionError); // function
console.log(typeof buffer); // object
console.log(typeof events); // function
```
Given `nodejs_compat` hasn't been released publicly yet, I guess the removing `assert` change doesn't need to be behind a compatibility flag?
=> Add `default` exports for `node:{buffer,events}` and remove `assert` export on `node:assert`

src/node/buffer.ts, src/node/internal/buffer.d.ts, src/node/internal/internal_buffer.ts, src/node/internal/internal_stringdecoder.ts, src/node/string_decoder.ts, src/workerd/api/node/buffer-nodejs-test.js, src/workerd/api/node/buffer.c++, src/workerd/api/node/buffer.h, src/workerd/api/node/string-decoder-test.js, src/workerd/api/node/string-decoder-test.wd-test
Prerequisite for Node.js Streams ... https://nodejs.org/dist/latest-v19.x/docs/api/string_decoder.html
The implementation here is taken nearly entirely from Node.js itself. Deno's polyfill is incomplete so I didn't want to use that as a basis.
=> Add Node.js Compat StringDecoder

src/workerd/api/crypto-impl-asymmetric.c++, src/workerd/api/crypto-impl-hkdf.c++, src/workerd/api/crypto-impl-pbkdf2.c++, src/workerd/api/crypto.h
- Allow specifying deriveBits and deriveKey usages when importing public ECDH keys. This behavior is already supported when importing raw ECDH keys and is more intuitive even though the usages are not required for public keys, see comments.
- Create CryptoKeyUsageSet::derivationKeyMask() to include both derive operations
- Deletes two superfluous assertions in importEllipticRaw – the validation right afterwards is more thorough and provides better error handling.
Please let me know if you find anything unclear
=> Allow specifying usages when importing public ECDH key, deriveBits/deriveKey refactor

src/workerd/api/global-scope.c++, src/workerd/api/http.c++, src/workerd/api/sockets.c++, src/workerd/api/sockets.h, src/workerd/api/streams/internal.c++, src/workerd/api/streams/readable.c++, src/workerd/api/streams/readable.h
Followed the advice in https://github.com/cloudflare/workerd/pull/205#pullrequestreview-1225144756.
There are actually two changes here:
- Closing the socket on `whenWriteDisconnected` (which I'm unsure about as I wasn't able to repro when it triggers)
- Closing the socket when `allowHalfOpen=false` (the default) and ReadableStream reads an EOF.
=> Implements Socket allowHalfOpen option.

src/workerd/api/crypto-impl-asymmetric.c++
Addresses the suggestion in https://github.com/cloudflare/workerd/pull/415 – the usage set is actually required to be empty when importing public ECDH keys. Since we currently allow derive* usages and used to allow usages in CryptoKeyUsageSet::publicKeyMask() for public spki and jwk, only log a warning for now. The TODO comment describes how to check for an empty set if this proves to not produce warnings.
Upstream PR is available
=> Disallow importing public ECDH keys with non-empty usage

types/defines/email.d.ts
Very small change to remove unused type parameter from the `EmailMessage` type. This was causing issues when the [`noUnusedParameters`](https://www.typescriptlang.org/tsconfig#noUnusedParameters) option was enabled.
Closes #395
=> Remove unused `Body` type parameter from `EmailMessage`

src/workerd/api/BUILD.bazel, src/workerd/io/BUILD.bazel, src/workerd/io/io-channels.h, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/io-gate.c++, src/workerd/io/limit-enforcer.h, src/workerd/io/observer.h, src/workerd/io/promise-wrapper.h, src/workerd/io/trace.c++, src/workerd/io/worker-entrypoint.h, src/workerd/io/worker-interface.h, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/jsg/BUILD.bazel, src/workerd/util/BUILD.bazel
This commit allows for the use of traces without needing to bring all of workerd/io with them.
thread-scopes.h is used fairly often just to get
isPredictableModeForTest() so it makes sense not to pull all of workerd/util for one function.
Additionally a linter was run workerd/jsg/BUILD
=> Breaking out trace and thread-scopes

WORKSPACE, src/workerd/api/sockets.c++, src/workerd/api/sockets.h, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker-entrypoint.h, src/workerd/io/worker-interface.c++, src/workerd/io/worker-interface.h, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server.c++
Depends on https://github.com/capnproto/capnproto/pull/1633
Tested with changes to gopher.js script (https://gist.github.com/dom96/1fda0c3fc62b68f403f98583763e1ea6)
```
$ bazel run @workerd//src/workerd/server:workerd -- serve $PWD/deps/workerd/samples/tcp/config.capnp --watch --verbose --experimental
$ curl -v localhost:8080
```
=> Implements TLS support for TCP sockets (with default TLS settings).

build/cc_ast_dump.bzl, rust-deps/BUILD.bazel, rust-deps/crates/BUILD.bazel, src/workerd/tools/BUILD.bazel, src/workerd/tools/param-extractor.rs
api.ast.json consumes 2.5GB in the output directory, compressing it saves 2.4GB of storage. The saving is useful in devhouse and for github actions (linux SSD size 14GB).
Test: build bazel //... && bazel test //...
=> Switch to api.ast.json.gz instead of api.ast.json

src/node/internal/events.ts, src/node/internal/process.ts
Provides an "implementation" of process.nextTick intended only for internal module use. The idea here is to make porting of existing Node.js built-ins easier. The polyfill is really just an alias for queueMicrotask, which implements different timing and error handling semantics but should be close enough for it hopefully not to matter.
=> Polyfill internal process.nextTick for Node.js compat

.github/workflows/test.yml
Intended to help to identify space issues on runners.
=> Add disk usage info to test plan

.bazelrc
[reuse_sandbox_directories](https://bazel.build/reference/command-line-reference#flag--reuse_sandbox_directories) should be a flag worth using in all cases. While there is scant documentation the only potential issue with it I was able to find is [bazel #17310](https://github.com/bazelbuild/bazel/issues/17310) (resolved on upstream bazel but not yet released, unlikely to affect us though). It is a non-experimental option since bazel v6.
The flag significantly reduces the sandbox setup/teardown overhead and provides a large compilation speedup on M1 macOS and a noticeable speedup on Linux x86, especially on systems with slow disk I/O (based on Orion's testing), it should be worth enabling globally.
Let's merge this once we have integrated #361, that way we can use the non-experimental …
=> bazel: Reuse sandbox directories

samples/nodejs-compat-streams/README.md, samples/nodejs-compat-streams/config.capnp, samples/nodejs-compat-streams/worker.js, src/node/_stream_duplex.js, src/node/_stream_passthrough.js, src/node/_stream_readable.js, src/node/_stream_transform.js, src/node/_stream_writable.js, src/node/internal/events.ts, src/node/internal/internal_buffer.ts, src/node/internal/internal_errors.ts, src/node/internal/internal_stringdecoder.ts, src/node/internal/internal_utils.ts, src/node/internal/streams_compose.js, src/node/internal/streams_duplex.js, src/node/internal/streams_legacy.js, src/node/internal/streams_pipeline.js, src/node/internal/streams_promises.js, src/node/internal/streams_readable.js, src/node/internal/streams_transform.js, src/node/internal/streams_util.js, src/node/internal/streams_writable.js, src/node/internal/validators.ts, src/node/stream.js, src/workerd/api/node/streams-test.js, src/workerd/api/node/streams-test.wd-test, src/workerd/jsg/modules.c++
While there is still a lot to do here to finish up adding tests, adding the Web streams adapters, and implementing the utility consumers, this PR is already rather large at 7700+ lines changed. It's still gated as experimental so I'll iterate on this to take care of the remaining todos in a separate PR.
Derived from: https://github.com/nodejs/readable-stream
TODO:
=> Add initial port of Node.js Compat Streams

build/wd_ts_type_test.bzl, src/workerd/api/global-scope.h, src/workerd/api/http.h, types/BUILD.bazel, types/defines/cf.d.ts, types/test/types/cf.ts, types/test/types/tsconfig.json, types/tsconfig.json
- Type `Request#cf` based on type parameter, allowing `Request` construction with `RequestInitCfProperties`
- Make `RequestInitCfProperties` and `IncomingRequestCfProperties` extend `Record<string, unknown>`, allowing incoming requests to be passed directly to fetch, and custom properties to added when making requests to service bindings
- Make all `IncomingRequestCfPropertiesGeographicInformation` fields optional, making it easier to access `cf` geo-properties whilst still maintaining correctness
Closes #324
Closes #397
=> Fixup `cf` types

src/workerd/api/url-standard-test.c++, src/workerd/api/url-standard.c++, src/workerd/api/url-standard.h
Added as part of the standard URL API as a mechanism for validating that a URL string can be parsed without incurring the additional cost of creating and catching an error.
=> Implement URL.canParse

src/workerd/api/global-scope.c++, src/workerd/api/http.c++, src/workerd/api/util.c++, src/workerd/api/util.h, src/workerd/io/observer.h, src/workerd/io/worker.c++, src/workerd/util/thread-scopes.c++, src/workerd/util/thread-scopes.h
This adds logging when a worker accesses the `request.cf.botManagement` metadata property. ~~We attempt to be smart about it, only logging once per worker instance per process, and we disable the logging when internally cloning or JSON serializing the value. However, this could still yield false positives. For instance, if the user just simply destructures the object, or iterates over the values without actually intending to access the `botManagement` property, this will get triggered.~~
An alternative approach would be to proxy the individual fields of the `botManagement` object itself. That approach would likely yield more accurate logging with fewer false positives but is slightly more invasive, requiring us to either wrap the entire `botManagement` value in a Proxy or define a …
=> Log accesses to the request.cf.botManagement property

src/workerd/api/global-scope.c++, src/workerd/api/trace.c++, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/worker-entrypoint.c++, src/workerd/jsg/promise.h
This should allow tracing spans recorded during async JS to be attributed to the incoming request that set them up, rather than the heuristic of using most recently received active request.  This should make DO traces more intuitive.
=> Capture request trace info in async contexts

WORKSPACE, src/workerd/api/sockets.c++, src/workerd/api/sockets.h, src/workerd/server/server.c++
Capnproto: https://github.com/capnproto/capnproto/pull/1635
**Note**: Tests will fail here until I merge the capnproto change.
With script: https://gist.github.com/dom96/68f1ecf9b4f148696551cf637b7de2e4
```
$ bazel run @workerd//src/workerd/server:workerd -- serve $PWD/deps/workerd/samples/tcp/config.capnp --watch --verbose --experimental
$ curl -v localhost:8080
```
Logs: https://gist.github.com/dom96/0de7148b7b5a99de709b48a00d095187
=> Implements startTls for TCP sockets.

src/workerd/api/http.c++, src/workerd/api/http.h
To support the following case (specifically, a response stream failing after the response has been returned and having the async context properly propagate), we have to capture the current AsyncContext when the `Response` object is created and ensure that we enter that context before starting the read loop for the given stream.
```
const als = new AsyncLocalStorage();
addEventListener('unhandledrejection', () => {
console.log(als.getStore());
});
fetch() {
return als.run(123, () => {
return new Response(new ReadableStream({
async pull(c) {
c.enqueue('this will cause an unhandled rejection');
}
}));
});
}
};
```
=> Capture the current AsyncContextFrame when Response is created

README.md, samples/async-context/config.capnp, samples/durable-objects-chat/config.capnp, samples/helloworld/config.capnp, samples/helloworld_esm/config.capnp, samples/nodejs-compat/config.capnp, samples/static-files-from-disk/config.capnp, samples/tcp/config.capnp, samples/unit-tests/config.capnp
Updated the compatibility date in all the samples & tested they still work - of which they all do other than `nodejs-compat` which throws:
```
service main: Uncaught Error: No such module "node-internal:buffer".
imported from "node-internal:internal_buffer"
```
However, this is unrelated to the compat date change.
Also added a small example of how compatibility dates & flags work in the sample config from the top-level README.
=> Update compat date in samples, add flags to README

src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h, src/workerd/server/workerd-api.c++
enables recording timing/memory/usage information
EW PR 5129
=> module registry observer

src/workerd/api/streams.h, src/workerd/api/streams/identitytransformstream-backpressure-test.js, src/workerd/api/streams/identitytransformstream-backpressure-test.wd-test, src/workerd/api/streams/internal.c++, src/workerd/api/streams/internal.h, src/workerd/api/streams/transform.c++, src/workerd/api/streams/transform.h, src/workerd/api/streams/writable.c++, src/workerd/api/streams/writable.h
Enables optional use of writer.desiredSize/writer.ready for backpressure signaling with IdentityTransformStream and FixedLengthStream. See included test for example use.
=> Implement backpressure signaling for IdentityTransformStream writable

samples/nodejs-compat-crypto/README.md, samples/nodejs-compat-crypto/config.capnp, samples/nodejs-compat-crypto/worker.js, src/node/crypto.ts, src/node/internal/crypto.d.ts, src/node/internal/crypto_random.ts, src/workerd/api/node/crypto.c++, src/workerd/api/node/crypto.h, src/workerd/api/node/node.h
Currently only a bit of scaffolding and the basic random APIs (e.g. randomInt, randomFill, etc). More will be added incrementally.
=> Initial impl of Node.js crypto

src/workerd/api/r2-bucket.h
When listing R2 objects, a `cursor` is only returned when `truncated` is `true`. This change encodes this constraint in TypeScript, similar to `KVNamespaceListResult`.
Closes #315
=> Add strict `R2Objects` types

src/workerd/api/actor.h
These properties/parameters can only take certain values. Rather than using a `string` type, this change defines literal union types for the possible values.
Closes #316
=> Add strict Durable Object `jurisdiction`/`locationHint` types

WORKSPACE, src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/io/actor-cache-test.c++, src/workerd/io/actor-cache.c++, src/workerd/io/actor-cache.h, src/workerd/io/actor-sqlite.c++, src/workerd/io/actor-sqlite.h, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server.c++, src/workerd/util/sqlite-kv.c++, src/workerd/util/sqlite-kv.h
This factors out a new abstract interface implemented by `ActorCache` and `ActorSqlite`, thus allowing `DurableObjectStorage` to use that interface and do away with the ugly `OneOf` situation.
`ActorCache` already implements an interface `ActorCacheInterface` which is shared with `Transaction`, but is too narrow for our new use case. So we need a new interface in between. I felt it would be too confusing for the existing `ActorCacheInterface` to keep that name, so I renamed it to `ActorCacheOps`. I then couldn't think of any good name for the new intermediate interface, so I made it `ActorCacheInterface`. Hopefully this doesn't create too much confusion but I am open to other names if anyone has any ideas.
This also changes the constructor of `Worker::Actor` to allow customization of …
=> Refactor / cleanup sqlite integration

src/workerd/util/sqlite-test.c++, src/workerd/util/sqlite.c++, src/workerd/util/sqlite.h
This allows SQLite's built-in locking to be used to protect multiple `SqliteDatabase` instances opening the same in-memory file and operating on it from different threads.
This introduces a new `SqliteDatabase::LockManager` interface which can be overridden. Arguably, an alternative could have been to extend the KJ filesystem API to support OS advisory locks. I settled on `LockManager` for a few reasons:
* In WAL mode, SQLite also does synchronization through shared memory. The VFS layer's interface to this is weird: the shared memory is treated as a facet of the database file. But in practice, the default VFS implementation opens a separate file for this. Obviously kj::File isn't going to grow an interface to hold extra "shared memory", but having to go back up to the enclosing directory …
=> Provide hooks to implement and customize SQLite locking.

src/workerd/api/crypto-impl-asymmetric.c++, src/workerd/io/worker.c++, src/workerd/jsg/jsg.h, src/workerd/util/sentry.h
While I was at it, I decided to cleanup some spots where we weren't using `JSG_WARN_ONCE`. I also improved those
macros to accept a variadic number of macro args (btw I noticed `LOG_IF_INTERESTING` and `LOG_NOSENTRY` may be misusing `__VA_ARGS__` in the 0 variadic args case - missing a `##` but I decided not to touch them to avoid scope creep).
I seem to have lost permission to the main workerd repo so I've forked for now until I figure out how to restore.
Hmm... bugs.ew-test is failing when I migrate
```
Worker tried to Send 'Expect' header
```
in edgeworker.c++ for some reason. The error gets printed in the logs but doesn't match the `@LOG` test directive. Hmm...
=> Macros to periodically warn

.github/workflows/npm.yml, .github/workflows/release.yml, npm/lib/node-platform.ts
_(followup to #502, thanks @c0b41 for spotting the missing binaries)_
Windows uses the `.exe` extension to recognise files as executable. Bazel outputs `workerd.exe` instead of `workerd` on Windows. These changes make sure we always include the extension where necessary.
=> Use `.exe` extension in Windows npm releases

build/wd_ts_bundle.bzl
=> bazel: fix resources paths to work correctly from external repo

Dockerfile.release, npm/lib/node-install.ts, npm/workerd-linux-64/package.json
A few more fixes for the `npm` release, now that Windows is supported natively. See commit descriptions for rationale.
=> Assorted `npm` release fixes

src/workerd/api/util.c++
...due to error seen when running structureClone(request.cf).
(disables functionality in PR #374)
=> Temporarily disable request.cf.botManagement logging

src/workerd/api/form-data.c++
One loop was missed during #487, being lost in a git stash.
=> Additional work for #487

src/workerd/api/web-socket.c++, src/workerd/api/web-socket.h
We await a `jsg::Promise` at the end of pumping. This means someone else could release our state before the final continuation runs. That's fine.
=> Bugfix: WebSockets can already be released when we finish pumping

.bazelrc
Later xcode toolchains fail to compile zlib under bazel. This change adds a workaround based on https://github.com/bazelbuild/bazel/issues/17956.
Without this change, zlib compilation generates errors like: external/zlib/gzread.c:35:15: error: call to undeclared function 'read'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
Test: bazel build @zlib//:zlib
=> Add compilation fix for zlib

WORKSPACE, patches/v8/0008-Disable-bazel-whole-archive.patch
This patches V8 to not use the alwayslink parameter (corresponding to the `--whole-archive` linker flag on Linux) for several  V8 and ICU-related libraries. This reduces binary sizes by ~1MB on Linux and ~19MB on macOS for opt binaries. macOS sees a much larger improvement since bazel uses --ffunction-sections and section garbage collection by default for opt Linux binaries it while we do not yet use the equivalent -dead_strip linker flag on macOS.
I will take a deeper look at V8's code base to confirm this is safe before converting to a non-draft PR.
=> Disable V8/ICU whole-archive flag, improving file size

types/defines/cf.d.ts
The description was backwards. Score 1 is bot, 99 is human.
=> Fix request.cf's botManagement.score description

.github/workflows/labels.yml, .github/workflows/npm-types.yml, .github/workflows/npm.yml, .github/workflows/release.yml, .github/workflows/test.yml
- Compress release binaries using gzip and provide compressed executables on the release page. This significantly reduces download sizes (see comments)
- Non-compressed binaries are no longer available – before merging we should make sure wrangler is prepared for this change
- Release binaries are stripped of debug symbols. There shouldn't be many debug symbols in the first place since workerd is compiled without -g, but this still improves the file size (~4MB on Linux)
- Some Github Actions refactoring, `${{ }}`expression syntax is not required in if conditions
There should be no need to upload compressed NPM binaries directly – the NPM publish action will download and decompress the release binary and then use npm pack/publish to create a compressed tarball as before.
=> Provide compressed release artifacts

.bazelrc, BUILD.bazel, build/kj_test.bzl, build/wd_cc_binary.bzl, src/workerd/server/BUILD.bazel
This adds the `-dead_strip` flag to the linker options on macOS when optimization is enabled, effectively replicating bazel's approach on Linux where `--ffunction-sections` `--gc-sections` flags are enabled by default under the `opt` configuration.
Based on the Mach-O binary format no compiler flag changes are needed, dead code stripping is linker-only.
optimized workerd binary size: `67.9MB -> 60.2MB`
Up for discussion: I wasn't planning to enable this for fastbuild mode and only modified the .bazelrc file to show that the change won't break test cases, but based on local testing it might be a tiny bit faster since the linker generates and writes binaries with much fewer symbols. For `crypto-impl-asymmetric-test`, linking takes 1.5s instead of 1.8s and fastbuild binary size is down from …
=> [bazel] Enable dead code stripping on macOS

src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/setup.c++, src/workerd/util/sentry.h
We already had a near identical macro in use in source files, let's provide it for more general usage with some warnings.
=> Add macros to throw in debug builds and log in production

.gitignore, .vscode/launch.json, .vscode/tasks.json, docs/vscode.md
The existing launch.json would only allow debugging workerd commands taking single arguments and didn't support inspecting source code or locals. The single argument problem is discussed in https://github.com/microsoft/vscode/issues/83678.
This change sets the source directory location and uses a debug build that supports symbols. This change assumes that the user is debugging the workerd serve command and they are prompted for a config to run.
=> workerd: make debugging in vscode work

src/workerd/api/crypto-impl-asymmetric.c++, src/workerd/server/workerd.c++
Based on the `JSG_WARN_ONCE_IF()` statements added in recent changes to the Web Crypto/Compression Streams APIs, errors can be thrown without breaking existing code in several but not all situations where there should be an error.
As a first step, throw errors where we can safely do so, which simplifies the code in several spaces; a future PR will create configuration flags to return errors in the other cases without breaking existing code.
Also fix a compiler warning about an unused variable that occurs in the implementation of FileWatcher for macOS/BSD.
Also see the eponymous upstream branch.
=> Provide Crypto/Compression API errors where safe, fix macOS compiler warning

src/workerd/api/actor-state-test.c++, src/workerd/api/crypto-impl-aes-test.c++, src/workerd/api/crypto-impl-asymmetric-test.c++, src/workerd/api/streams/queue-test.c++, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/jsg/jsg-test.c++, src/workerd/jsg/jsg-test.h, src/workerd/jsg/jsg.h, src/workerd/jsg/setup-test.c++, src/workerd/jsg/setup.c++, src/workerd/jsg/setup.h, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h
This uses a V8 patch. If the patch isn't present, it automatically skips it and relies on V8 to figure things out the normal way.
The patch is needed in order to work around issues in our internal environment, especially the fact that /proc/self/maps is not accessible. The patch isn't needed when using workerd stand-alone.
=> Manually tell V8 where the stack starts whenever we enter it.

src/workerd/api/sockets.c++, src/workerd/api/sockets.h, src/workerd/api/streams/internal.c++, src/workerd/api/streams/internal.h, src/workerd/api/streams/readable.c++, src/workerd/api/streams/readable.h
Without this detaching the ReadableStream fails when the stream was read from before `startTls` was called.
=> Ignore disturbed status of ReadableStream when detaching for startTls.

src/workerd/io/worker.c++, src/workerd/jsg/util.c++, src/workerd/jsg/util.h
This commit does the following:
- Preserves the original message for internal exceptions that pass through jsg::annotateBroken(). It turns out that we only expect to see non-JSG messages in situations where `Worker::Actor::Impl::makeStorage()` throws. Up until recently, all storage interfaces had trivial construction, so it was never an issue. Since this is difficult to do in a testing environment, I have verified the messages manually.
- Reorganizes cases when making a `DecodedException` so that kj exceptions get their own branch with a default exception.
- Sanitizes jsg-internal exceptions when extracting descriptions for use with the worker logging.
- Logs at info level when we annotate an exception with brokenness.
=> Do not sanitize internal error messages in jsg::annotateBroken()

src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/worker.c++, src/workerd/io/worker.h
Should allow better support of tracing in use cases where there are multiple IoContexts per Isolate.
=> Move trace info async storage key from IoContext to Worker::Isolate

src/workerd/api/crypto-impl-asymmetric.c++, src/workerd/api/crypto.c++, src/workerd/api/crypto.h
This patch implements the Web Crypto Secure Curves X25519 and Ed25519.
Caveats/Potential issues:
- Error messages for NODE-ED25519 have been largely updated to refer to Ed25519. This reduces code complexity and still results in descriptive messages as Ed25519 is the underlying algorithm.
- Node no longer allows raw private imports for NODE-ED25519 – comments about deviating from Node's approach are no longer needed
- Is there a better name for `EdDsaKey` now that it's shared between both Eddsa and Eddh?
- There's ternary operator in a few spots – I can switch to branches if that style is preferred
- It might be possible to do this in one class using `kj::OneOf<KeyAlgorithm, EllipticKeyAlgorithm >` – I wanted to avoid breaking the JSG integration for now
- Test cases to be added
=> Implement Secure Curves API

src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/setup.h
As requested in review of #544.
(I didn't update `jsg/README.md` because that document currently doesn't cover how to obtain an isolate lock in the first place, which is where it would make sense to mention this.)
=> Add requested comments / debug checks on V8StackScope.

src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h
as it is written now hash will always be computed of an empty string.
=> fix use-after-move

src/workerd/jsg/promise.h
unless there's something subtle going on, this field is not initialized.
=> initialize Promise::markedAsHandled

src/workerd/api/basics.c++, src/workerd/api/crypto.c++, src/workerd/api/form-data.c++, src/workerd/api/global-scope.c++, src/workerd/api/http.c++, src/workerd/api/kv.c++, src/workerd/api/node/async-hooks.c++, src/workerd/api/r2-admin.c++, src/workerd/api/r2-bucket.c++, src/workerd/api/streams/encoding.c++, src/workerd/api/urlpattern.c++, src/workerd/api/util.c++, src/workerd/io/io-context.c++, src/workerd/io/worker.c++, src/workerd/jsg/async-context.c++, src/workerd/jsg/dom-exception.c++, src/workerd/jsg/function.h, src/workerd/jsg/jsg.h, src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h, src/workerd/jsg/promise.h, src/workerd/jsg/type-wrapper.h, src/workerd/server/workerd-api.c++
Addresses a couple cleanup items on PR #547:
- Renames a few cases of `jsgLock` variables to `js` to match convention.
- Adds a `jsg::Lock::v8Context()` convenience function and updates code to use it.
=> jsg::Lock cleanup

src/workerd/jsg/async-context.c++, src/workerd/jsg/async-context.h
* Reset the tracing storage key in IoContext when the context is destroyed.
* Do not store a key if the key has already been reset
* Compare pointers and not hash in operator=
=> A couple of minor improvements to AsyncContextFrame::StorageKey

src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/io/compatibility-date.capnp, src/workerd/server/server-test.c++
This is protected by a new compatibility flag since the current plan is
to only allow it in local development. As such, I've marked it as
experimental since AFAIK doing so is the way to prevent users from
enabling it in production. But I don't know if that'll make it awkward
for miniflare to use, and if so what our possible alternatives are.
---
Ignore the first commit, it's just #543. The second commit is what's new here.
=> Support calling the queue() handler of a worker via a service binding

src/cloudflare/internal/sockets.d.ts, src/cloudflare/sockets.ts, src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/sockets.h, src/workerd/server/workerd-api.c++
Tested upstream. The `connect` method now needs to be imported via the `cloudflare:sockets` module.
=> Moves global TCP socket `connect` to `cloudflare:sockets` module.

patches/v8/0008-Disable-bazel-whole-archive.patch
PR df8c353c0d7eb757c6d460522bbd1a1d3751ab46 changed the v8 linking options. The partial revert is necessary locally to build on Linux without linker breakage.
Test: bazel build //src/workerd/server:workerd (on Linux)
=> Partial revert of 'Disable V8 whole-archive flag, improving binary size'

src/workerd/api/actor-state.c++, src/workerd/api/global-scope.c++, src/workerd/api/http.c++, src/workerd/api/queue.c++, src/workerd/api/util.c++, src/workerd/api/util.h
This is ugly and horrible but hopefully temporary. While we are logging the cf.botManagement uses, since we are using a Proxy to catch accesses and Proxy is not supported via structuredClone, we end up having to intercept and handle the case where `request.cf` is passed off to structuredClone.
It's *possible* we might have to do this elsewhere if folks are passing request.cf off to other things that using the v8 serializer? I certainly hope not.
=> Account for botManagement proxy in structuredClone

build/wd_js_bundle.bzl
fixes build in situations when module name is a prefix of another: e.g. node:streams and node:streams/consumer
=> wd_js_bundle nested modules fix

src/workerd/api/sockets.c++, src/workerd/api/sockets.h
Changes the `connect`'s options API to take a secureTransport enum instead of a bool:
```js
connect("address:port", { secureTransport: "off" })
connect("address:port", { secureTransport: "allow" })
connect("address:port", { secureTransport: "use" })
```
Context: https://github.com/cloudflare/workerd/pull/562#discussion_r1176646406
=> Socket's connect API now takes a secureTransport enum instead of bool.

src/workerd/io/compatibility-date.c++, src/workerd/io/compatibility-date.h, src/workerd/tools/BUILD.bazel, src/workerd/tools/api-encoder.c++
Add _all_ compatibility flags (except nodejs) to the `experimental` types entrypoint
=> Add experimental flags to experimental types entrypoint

.vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, README.md, tools/windows/bazel-env.bat, tools/windows/install-deps.bat, tools/windows/vsconfig.json
Assorted changes to try to make setup and build on Windows simpler.
* Adds an installer script for the workerd's dependencies on Windows (tools/windows/install-deps.bat).
* Adds a command-line environment script to set up environment variables for building on Windows (tools/bazel-env.bat).
* Adds vscode settings to simplify setup on Windows.
* Defines BAZEL_WINSDK_FULL_VERSION and BAZEL_VC explicitly to address issues when the Windows machine has multiple versions of Visual Studio and/or the Windows SDK installed.
=> Simplify Windows setup and build

.vscode/launch.json, .vscode/tasks.json, docs/vscode.md
Adds an additional launch target 'workerd test case' to make it easy to debug tests.
=> workerd add tests that can be debugged within vscode

samples/nodejs-compat-module/README.md, samples/nodejs-compat-module/bar.js, samples/nodejs-compat-module/config.capnp, samples/nodejs-compat-module/foo.js, samples/nodejs-compat-module/worker.js, src/node/internal/process.ts, src/node/internal/streams_adapters.js, src/node/process.ts, src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h, src/workerd/server/workerd-api.c++, src/workerd/server/workerd.capnp
Just an initial proof-of-concept on the idea of a Node.js module type.
This type of module that can be included in the worker bundle allows for requiring node.js built-ins without the `node:` specifier-prefix and would expose the common Node.js globals
There is some complexity here that would still need to be worked through. This will remain a draft PR until we determine if this is the way we'd want to go.
=> Add Node.js Compat module type

src/workerd/io/BUILD.bazel, src/workerd/io/worker-entrypoint.h
They are commonly used without full io dependency
=> [nfc] extracting io:observer and io:worker-interface libraries

.github/workflows/npm.yml
The decompression path was incorrect, causing the `Publish to NPM` workflow to fail. It should start with
`$GITHUB_WORKSPACE/release-downloads/`.
=> Fix npm release workflow download paths

.bazelrc
While #578 pulled in the updated capnproto version which includes zlib compilation fixes, this is still needed in workerd – capnproto defines the zlib compile options in its WORKSPACE file, which is not accessed by workerd.
=> Partially revert #568, fixing mac compilation

src/workerd/io/worker-entrypoint.c++
Prior to this, if an application queued a storage write, then threw an exception, and the storage write failed later on, the exception might nevertheless be received by the caller. If, for some reason, an application were confirming writes by throwing exceptions, this could result in confirming a write that didn't actually make it to disk.
Of course, surely no app does that. The bigger problem is that this could screw with the `durableObjectReset` flag on exceptions thrown after storage breakages. Say a storage write fails, and we respond by simultaneously throwing an exception from the storage API to the application, as well as breaking the output gate with the same exception. The version of the exception thrown at the application could propagate out of the fetch handler before the …
=> Exceptions from fetch handlers should wait for output gate.

src/workerd/io/io-context.c++, src/workerd/io/limit-enforcer.h, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++, src/workerd/util/sqlite.c++
This is mostly implemented in the internal codebase. These are just a couple related tweaks.
=> Tweaks for SQLite CPU limiting

src/workerd/api/basics.c++, src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/trace.c++, src/workerd/api/trace.h
The existing `trace` handler is still available to maintain backwards compatibility.
=> Rename `trace` handler to `tail`

WORKSPACE, src/workerd/api/sockets.c++, src/workerd/api/sockets.h
Capnproto PR: https://github.com/capnproto/capnproto/pull/1653
Verified same as #440.
(Tests might fail as this PR doesn't point at capnproto PR yet)
=> Update to include changes to support startTls with http-over-capnp.

src/workerd/util/sqlite.c++
Clearly the regex I used to process lang_aggfunc.html didn't work. Each of these document pages is formatted a little differently. Grr.
=> Fix more mistakes in SQLite allowlist.

src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/tests/performance-test.js, src/workerd/tests/performance-test.wd-test
Provides a basic implementation for performance.now in a manner that follows the same rules as Date.now().
This is potentially one way of accomplishing this. @kentonv not sure if you have an alternative idea in mind.
=> Implement performance.now/timeOrigin

samples/nodejs-compat/worker.js, src/node/internal/constants.ts, src/node/internal/internal_path.ts, src/node/path.ts, src/node/path/posix.ts, src/node/path/win32.ts, src/workerd/api/node/path-test.js, src/workerd/api/node/path-test.wd-test
Implements only the path.posix variant. The path.win32 variant is present but all of the methods will throw an error if called.
=> Add Node.js compat path module

src/workerd/api/r2-admin.c++, src/workerd/api/r2-admin.h, src/workerd/api/r2-bucket.c++, src/workerd/api/r2-bucket.h, src/workerd/api/r2-multipart.c++, src/workerd/api/r2-rpc.c++, src/workerd/api/r2-rpc.h, src/workerd/io/io-context.c++, src/workerd/io/io-context.h
To allow greater flexibility in how R2 RPC operations can be performed, introducing the jwt as optional attribute. Also refactored the way R2 paths are built and passed to the doR2HTTP<verb>Request functions, since we expect to support greater variety of paths.
Introduced concept of R2CrossAccount, which will leverage the new underlying flexibility to perform cross account operations with proper auth.
=> Add mechanism to inject a JWT + account name

src/workerd/util/sentry.h
This commit does the following:
- Removes the `message` parameter from LOG_NOSENTRY, LOG_ERROR_ONCE, and LOG_ERROR_PERIODICALLY so that they can take a single string.
- Removes LOG_ERROR_ONCE_IF and LOG_ERROR_PERIODICALLY_IF since they were sugar for if statements.
- Removes the GCC CPP token paste operator from LOG_ERROR_ONCE and LOG_ERROR_PERIODICALLY. KJ_LOG already has it for us. (And if it didn't, we should be using `__VA_OPT__(...)`.)
=> Cleanup: Simplify sentry logging macros

src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/io/io-context.c++, src/workerd/io/io-context.h
Returning higher precision might impact our Spectre risk. We cannot do this without careful study.
=> performance.now() must return excatly what Date.now() returns.

src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/api/sql-test.js, src/workerd/api/sql.c++, src/workerd/api/sql.h, src/workerd/io/actor-sqlite.c++, src/workerd/io/actor-sqlite.h, src/workerd/io/io-context.h, src/workerd/server/server.c++, src/workerd/util/sqlite-test.c++, src/workerd/util/sqlite.c++, src/workerd/util/sqlite.h
Per the old blog post:
https://blog.cloudflare.com/durable-objects-easy-fast-correct-choose-three/
All writes that occur without an `await` in between are supposed to be automatically coalesced and submitted atomically.
With this change, the SQLite-based DO storage respects this requirement, by automatically creating a transaction.
As it turns out, this actually makes SQLite more efficient. Multiple changes to the same pages will be coalesced, and fsync()s will only be needed at commit time.
=> Automatically wrap SQLite usage in transactions and respect OutputGate.

src/node/crypto.ts, src/node/internal/crypto.d.ts, src/node/internal/crypto_random.ts, src/workerd/api/node/crypto.h, src/workerd/api/node/crypto_random-test.js, src/workerd/api/node/crypto_random-test.wd-test, src/workerd/api/node/crypto_random.c++, src/workerd/api/node/crypto_util.c++, src/workerd/api/node/crypto_util.h
I plan to amend this PR once the other prime functions are done, just wanted to float it now to see if there's any issues with the overall approach. Tests are not included yet as most checkPrime tests depend on generatePrime, but the few tests I looked at all passed.
=> Node compat: Implement crypto primes

build/BUILD.sqlite3, src/workerd/api/sql-test.js, src/workerd/api/sql.c++, src/workerd/api/sql.h, src/workerd/util/sqlite.c++
This is Glen's #606 and #607, plus some commits of my own.
My commits:
- Refactor the code a bit to enforce pragma signatures more precisely.
- Roll back some of the permissions that I'm not sure we want to grant.
- Introduce a new JavaScript API to query the database size and set a "voluntary size limit" based on the max_page_count pragma.
=> Modify SQLite allowlists and limits as needed for D1.

samples/tcp/config.capnp, src/workerd/api/http.h, src/workerd/api/sockets.c++, src/workerd/api/sockets.h, src/workerd/io/compatibility-date.capnp
```
$ bazel run @workerd//src/workerd/server:workerd -- serve $PWD/deps/workerd/samples/tcp/config.capnp --watch --verbose
$ curl localhost:8080
```
=> Deprecate tcp_sockets_support compat flag.

src/workerd/api/global-scope.h
Changes the origin property from unimplemented to undefined. If origin is unimplemented, then it causes an exception to be thrown when the inspector queries the origin property, and this subsequently trips checks in v8 that cause process termination.
=> Implement global origin property

src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/hibernatable-web-socket.c++, src/workerd/api/hibernatable-web-socket.h, src/workerd/api/hibernation-event-params.h, src/workerd/api/http.c++, src/workerd/api/web-socket.c++, src/workerd/api/web-socket.h, src/workerd/io/hibernation-manager.c++, src/workerd/io/hibernation-manager.h, src/workerd/io/worker-interface.capnp, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server.c++
Old PR: https://github.com/cloudflare/workerd/pull/339
@jqmmes, @xortive
=> WebSocket Hibernation Manager

src/node/crypto.ts, src/node/internal/crypto.d.ts, src/node/internal/crypto_pbkdf2.ts, src/node/internal/crypto_random.ts, src/node/internal/crypto_util.ts, src/workerd/api/node/crypto.h, src/workerd/api/node/crypto_pbkdf2-test.js, src/workerd/api/node/crypto_pbkdf2-test.wd-test, src/workerd/api/node/crypto_pbkdf2.c++
This patch implements the `crypto.pbkdf2Sync()` and `crypto.pbkdf2()` functions. Work is still needed in a few places, notably async has not been implemented. For some of these changes, it is probably better when some of the other crypto PRs get merged first, e.g. to establish `node-internal:crypto_util`.
=> Implement crypto.pbkdf2

src/workerd/util/sentry.h
Since it uses the monotonic clock, the "origin" time is system boot time. So the first time LOG_ERROR_PERIODICALLY() runs, it thinks it last logged at system boot time, and it only logs again if it's been more than an hour since then.
We'll just subtract an hour from the origin. Monotonic time is never negative so this should be sufficient.
=> LOG_ERROR_PERIODICALLY() would not log in the first hour after system boot.

src/workerd/io/hibernation-manager.c++, src/workerd/io/hibernation-manager.h
We weren't moving the promised worker interface into the event dispatch promise, so we would destroy it before the event ran, causing issues.
=> Fix hibernatable websocket disconnect bug

.github/secret_scanning.yml, src/workerd/api/crypto-impl-aes.c++, src/workerd/api/crypto-impl-asymmetric.c++, src/workerd/api/crypto-impl-hkdf.c++, src/workerd/api/crypto-impl-hmac.c++, src/workerd/api/crypto-impl-pbkdf2.c++, src/workerd/api/crypto-impl.c++, src/workerd/api/crypto-impl.h, src/workerd/api/crypto.c++, src/workerd/api/crypto.h, src/workerd/api/node/crypto-keys.c++, src/workerd/api/node/crypto_keys-test.js, src/workerd/api/node/crypto_keys-test.wd-test
Since we're using CryptoKey under the covers of KeyObject, we need to teach the various CryptoKey::Impl subclasses how to compare their contents.
=> Add basic impl for Node.js KeyObject equals

npm/lib/node-install.ts
We're planning to add `workerd` as a hard dependency of `wrangler`. If `workerd` fails to install, we'd still like the `wrangler` install to succeed, so users can use remote dev and the rest of the commands. This logs the error instead of throwing, allowing the `postinstall` to "succeed".
=> Soft fail if `workerd` `npm` `postinstall` script fails

src/workerd/server/server.c++, src/workerd/server/server.h, src/workerd/server/workerd.c++
Hey! 👋 This PR adds a `--control-fd` flag that allows an additional file descriptor to be passed (probably a pipe) for reporting control messages. I wasn't really sure what to name this flag, but this seemed like we could extend it with more messages later on if needed. Each message is a JSON-object terminated by a newline. Currently we only report the port each socket is listening on when it's ready. There's definitely a bug here if the socket name includes characters like `"`, `\n`, `\`, etc, but it also seems like this is a problem in inspector endpoints too, and it seems unlikely these characters would appear here: https://github.com/cloudflare/workerd/blob/89199545cf23160ff30efd5ba331a933fc8310f1/src/workerd/server/server.c%2B%2B#L1083
Tested on macOS and Windows with the following …
=> Report port each socket is listening on when ready

src/workerd/api/basics.c++, src/workerd/api/basics.h
AbortSignal.any is a new API that allows combining multiple AbortSignals into one...
```
const s1 = new AbortController();
const s2 = AbortSignal.timeout(1000);
const s3 = AbortSignal.any([s1.signal, s2]);
// s3 is aborted either when s1.abort() is called or
// s2 times out after 1 second, whichever comes first.
```
Refs: https://github.com/whatwg/dom/pull/1152
=> Implement AbortSignal.any

src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/api/sql-test.js, src/workerd/io/actor-sqlite.c++, src/workerd/io/actor-sqlite.h, src/workerd/util/sqlite.c++, src/workerd/util/sqlite.h
This is implementing the storage.transaction() API we've always had. SQLite queries will be included in the transaction.
Note that unlike the traditional implementation, this one does not require you to use the transaction object passed into the callback to access storage -- all storage access during the transaction is automatically included. There's no other choice since we'd need to have a second SQLite database connection to perform queries that bypass the transaction, and even then SQLite does not allow concurrent writers.
=> SQLite: Support explicit transaction API. 

src/workerd/api/queue.c++
Hey! 👋 One of our Miniflare tests for Queues was occasionally failing on Windows with `Error: Unable to deserialize cloned data`. From debugging, it looked like message bodies were correctly being passed to: https://github.com/cloudflare/workerd/blob/8f4274db3823772dc86fade66c631775405dca30/src/workerd/api/queue.c%2B%2B#L217
When constructing `QueueMessage`s though, `kj::mv` was used to avoid copying the message body. It looks like `jsg::Deserializer` doesn't take ownership of the data:
https://github.com/cloudflare/workerd/blob/8f4274db3823772dc86fade66c631775405dca30/src/workerd/jsg/ser.h#L74
...meaning it was dropped after the constructor, and the `readValue()` back in `QueueMessage` could end up reading garbage. Maybe this isn't usually a problem because of the `inline` on the …
=> Fix use-after-free when constructing `QueueMessage` on Windows

src/workerd/api/url-standard.c++, src/workerd/api/url-standard.h, src/workerd/util/sentry.h
In preparation for landing support for the new value arguments added recently to URLSearchParams.has() and delete(), we need to know if adding the new arguments will break any existing workers. This commit adds a warning.
Refs: https://github.com/whatwg/url/pull/735
=> Warn if URLSearchParams has() or delete() are called with multiple args

.bazelrc
This change disables warnings where needed in third party code and pulls in additional warnings used in the upstream repo. workerd now compiles without warnings on mac using XCode 14.3 and on Ubuntu using LLVM 15.
=> [nfc] clean up bazelrc warnings

src/workerd/api/sql-test.js, src/workerd/api/sql.c++, src/workerd/api/sql.h
Hitting the `voluntartySizeLimit` kills the current DB connection, rolling back the current implicit transaction (not just the statement that failed), and resulting in unwanted behaviour (like a `SQLITE_MISUSE` error trying to reuse a prepared statement from the now-dead connection). This PR removes it.
It also changes the semantics of `getDatabaseSize` to take `freelist_count` into consideration. From the docs: https://www.sqlite.org/pragma.html#pragma_freelist_count
> Return the number of unused pages in the database file.
When you delete a table, or enough rows that an entire page can be reclaimed, the result `PRAGMA page_count` doesn't change until you do a VACUUM (it represents the size of the file on-disk).
Currently, VACUUMs aren't supported (error message is `cannot VACUUM from …
=> Revisiting SQL limits

src/workerd/io/worker-entrypoint.c++
```
$ bazel run @workerd//src/workerd/server:workerd -- serve $PWD/deps/workerd/samples/tcp/config.capnp --watch --verbose --experimental
```
Verified that the gopher example still works with proxy.
=> Fail WorkerEntrypoint::connect with a JSG error

src/workerd/api/sockets.c++
Should eliminate this class of errors from Sentry.
=> Reject closeFulfiller with jsg exception instead of KJ_EXCEPTION.

src/workerd/api/global-scope.c++, src/workerd/api/hibernatable-web-socket.c++, src/workerd/api/hibernatable-web-socket.h, src/workerd/api/web-socket.c++, src/workerd/api/web-socket.h, src/workerd/io/hibernation-manager.c++, src/workerd/io/hibernation-manager.h
We saw a situation where queued websocket messages (`send()`/`close()`) that were inserted during the `webSocketClose` event failed to deliver. This was caused by the fact that the `HibernationManager` drops `HibernatableWebSocket`'s after their final close/error event is dispatched.
Unfortunately, the `HibernatableWebSocket` would get dropped too soon, so the underlying `kj::WebSocket` was no longer available to send messages.
We fix this by moving the owned `kj::Own<kj::WebSocket>` out from the `HibernatableWebSocket` and back into the `api::WebSocket`'s `NativeState` after dispatching the final close/error event. `NativeState`'s lifetime is managed by the `IoContext`'s `DeleteQueue`, so it lives long enough to flush the remaining messages.
=> Move owned WebSocket back to api::WebSocket on final hibernation event

src/workerd/jsg/jsg.h
#653 added more debugging checks to the jsg::Data constructor but missed the move operator=.
=> Add debugging for jsg::Data move operator=

src/workerd/io/worker.c++
Since these errors come from externally provided pipelines, we should not send them to sentry and we want to guard against bursts of log spam.
=> Restrict logging when an exported handler cannot be used

src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/hibernatable-web-socket.c++, src/workerd/api/hibernatable-web-socket.h, src/workerd/api/hibernation-event-params.h, src/workerd/io/hibernation-manager.c++, src/workerd/io/hibernation-manager.h, src/workerd/io/worker-interface.capnp
We noticed the `webSocketForEventHandler` reference was being overwritten by subsequent events before an event that set it could read the value.
To fix this, we use a map of `ID`s to `HibernatableWebSocket`s and pass the ID to the event itself so it can find its associated websocket.
=> Change delivery of websocket for hibernation event

src/workerd/api/global-scope.h
This PR adds the type of `EmailExportedHandler` to `ExportedHandler`, as was done with other triggers.
Resolves #504
=> Add `email` trigger type to `ExportedHandler`

src/workerd/jsg/string.c++
while it works, it triggers ubsan and is easy to fix.
=> fixing undefined behavior when src == null

src/workerd/api/sql-test.js, src/workerd/api/sql.c++, src/workerd/api/sql.h
These were being implicitly coerced into a string before reaching the `SqliteDatabase::Query::bind` function.
I've also added tests to confirm that you can inject BLOBs by binding a `Uint8Array`
=> Handling explicit null bindings in SQLite

src/workerd/api/streams/internal.c++
The warning text was confusing since it would specifically mention response.clone() even if the unused branch was created in other ways (such as cloning a request or calling tee().)
Refs: https://github.com/cloudflare/workerd/issues/399
=> Clarify unused stream clone warning message

src/workerd/api/sql-test.js, src/workerd/util/sqlite.c++
Also adding a test to demonstrate a `json_object` query that requires the higher limit
=> Increasing `SQLITE_LIMIT_FUNCTION_ARG` to 32

.bazelrc
The Windows build log on CI is currently very large, ~12MB on a recent run with few changes compared to 400kb on Mac and Linux, which makes it more difficult to look at the build logs when tracking down Windows build failures on CI and is bad for the Windows DX.
This is caused largely by V8 needing the `-Wno-invalid-offsetof` flag to not throw a ton of warnings. V8's bazel enables the flag when using a clang-based compiler, but it doesn't realize that the Windows build uses clang.
Adding the warning reduces the build log to 1.1MB, likely even more on a regular build where the build settings don't change. 
I'm not sure if this is the right place for the flag though – it might make more sense to integrate it into V8's build system through a patch.
=> Drastically reduce Windows build log size

docs/v8-updates.md, patches/v8/0001-Allow-manually-setting-ValueDeserializer-format-vers.patch, patches/v8/0002-Allow-manually-setting-ValueSerializer-format-versio.patch, patches/v8/0003-Make-icudata-target-public.patch, patches/v8/0004-Add-ArrayBuffer-MaybeNew.patch, patches/v8/0005-Allow-compiling-on-macOS-catalina-and-ventura.patch, patches/v8/0006-Fix-v8-code_generator-imports.patch, patches/v8/0007-Allow-Windows-builds-under-Bazel.patch, patches/v8/0008-Disable-bazel-whole-archive-build.patch, patches/v8/0009-Make-v8-Locker-automatically-call-isolate-Enter.patch, patches/v8/0010-Add-an-API-to-capture-and-restore-the-cage-base-poin.patch
Incorporates review comments in #678 
Review comments from https://github.com/cloudflare/workerd/pull/678
* Documents that patches should be generated with --full-index
* Adds a note about git_repository shallow-since
* Some re-wording of vs-updates.md.
Bug: EW-7428
Test: bazel build //...
=> Review comments from V8 11.4.183.12 update (#678)

WORKSPACE, patches/v8/0011-Cherry-pick-to-fix-mksnapshot-on-OS-X-ARM.patch
The move to V8 11.4 inadvertantly broke the build for folks with ARM based OS X machines. The breakage was present in V8 and has subsequently been fixed. This change adds a cherry-pick of the fix to workerd's set of V8 patches.
Bug: https://bugs.chromium.org/p/v8/issues/detail?id=14023
Bug: EW-7428
=> Fix the bazel build of V8 for OS X ARM devices

src/workerd/api/queue.c++, src/workerd/api/queue.h, src/workerd/io/worker-interface.capnp
Previously, queue messages were always serialized and stored in v8 format, and deserialized from v8 format before being passed to a `queue()` event handler via dynamic dispatch.
This PR adds support for alternative content types:
* A new `contentType` option can be specified when calling `send()` or `sendBatch()` on a Queue. The message will be stored in the desired format, enabling it to be retrieved in the same format later.
* The `contentType` is used to determine the serialization format for the message, before sending it off for storage
* The `contentType` is used to determine the deserialization format for incoming messages from the Queue.
=> Add support for alternative content types when sending and receiving Queue messages

src/workerd/api/streams/internal.c++
Hit in various connect() related cases.
=> Avoid assert when internal WritableStream aborted twice

src/workerd/jsg/setup.c++
Reverts cloudflare/workerd#714
Potential issue with internal tests, to be investigated.
=> Revert "Fix deprecation warning for v::BasicTracedReference::operator->()"

src/workerd/api/r2-admin.c++, src/workerd/api/r2-admin.h, src/workerd/api/r2-bucket.c++, src/workerd/api/r2-bucket.h, src/workerd/api/r2-multipart.c++
The admin account is not needed in the path, only the jwt. This was an oversight from #577.
=> Remove admin account tag from path in R2 operations

src/workerd/util/sqlite.c++
fixes #717 
The function was not allowlisted correctly.
=> SRS: fix typo - stftime -> strftime

src/workerd/api/url-standard.c++, src/workerd/api/url-standard.h, src/workerd/io/compatibility-date.capnp
The whatwg url spec was updated to add a second optional argument to delete() and has(). While it was determined that it likely didn't break browser users, the change could break at least a couple existing deployed workers so we have to gate support behind a compat flag.
Tests are added in the internal PR.
=> Implement new URLSearchParams has and delete second argument

src/workerd/api/sql-test.js, src/workerd/util/sqlite.c++
Fixes #718 
These are built-ins that aren't documented in https://www.sqlite.org/lang_datefunc.html but are required to use `current_timestamp`, `current_date` and `current_time` in queries per https://github.com/smparkes/sqlite/blob/8caf9219240123fbe6cff67b1e0da778c62d7621/src/date.c#L1072-L1079 (GitHub mirror)
```sh
sqlite> SELECT current_timestamp;
2023-05-31 20:59:38
sqlite> SELECT current_time;
21:00:51
sqlite> SELECT current_date;
2023-05-31
```
```sh
➜  wrangler d1 execute db-enam --command "SELECT current_date"
🌀 Mapping SQL input into an array of statements
🌀 Parsing 1 statements
🌀 Executing on db-enam (4006a897-c765-4999-9ff1-465a8cf1ec00):
✘ [ERROR] A request to the Cloudflare API (/accounts/d458dbe698b8eef41837f941d73bc5b3/d1/database/4006a897-c765-4999-9ff1-465a8cf1ec00/query) …
```
=> SRS: allowlist current_(timestamp,time,date) functions

.vscode/launch.json, docs/vscode.md
This change adds the majority of workerd's wdtests to vscode as launch targets for debugging. The two tests that require a temporary directory (actor-alarms-test.wd-test, sql-test.wd-test) are not included.
Test: manually run wdtests with breakpoints
=> Add support for debugging wdtests in vscode

src/workerd/api/streams/compression.c++, src/workerd/api/streams/compression.h, src/workerd/io/compatibility-date.capnp
Perform more error checking for DecompressionStream, which requires adding a new compat flag.
=> Additional error checking in Compression API

src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker-entrypoint.h, src/workerd/io/worker.c++, src/workerd/io/worker.h
This commit does a few notable things:
- The WorkerEntrypoint now invokes `context.run()` and `incomingRequest.drain()` on the promise chain for the `runAlarm()` request. This means that we are able to report to the actor when that request is cancelled, which implies that the worker entrypoint will be going away. (There is an explicit guard for request cancellation now.)
- The Worker::Actor now has two functions for alarms. `getAlarm()` checks if there is an existing alarm for a given time synchronously. `scheduleAlarm()` provides a promise that will resolve when it is time to run the alarm or the alarm has been cancelled. It also cancels the currently scheduled alarm if there is one.
- Durable object alarms in the sandbox can now be "scheduled" or "running" instead of "running" or …
=> Rewrite durable object alarm deduplication with cancellation considerations

.bazelrc, WORKSPACE, src/workerd/api/cache.c++, src/workerd/api/cache.h, src/workerd/api/global-scope.c++, src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/kv.c++, src/workerd/api/kv.h, src/workerd/api/r2-admin.c++, src/workerd/api/r2-admin.h, src/workerd/api/r2-bucket.c++, src/workerd/api/r2-bucket.h, src/workerd/api/r2-rpc.c++, src/workerd/api/r2-rpc.h, src/workerd/api/streams/common.h, src/workerd/api/system-streams.c++, src/workerd/api/system-streams.h, src/workerd/io/BUILD.bazel, src/workerd/io/compatibility-date.capnp, src/workerd/io/worker.c++
Creating a new PR since there are significant changes compared to the previous PR ([diff](https://github.com/cloudflare/workerd/compare/felix/brotlify...felix/brotlify-v2) after rebasing [old PR](https://github.com/cloudflare/workerd/pull/624)). 
This is the first time I'm adding a compat flag – suggestions on the name, description and how to best pass the flags object are welcome. There also needs to be a proper compatibility date defined.
=> Add support for brotli content encoding, if enabled through compat flag

.bazelrc, .github/workflows/release.yml, .github/workflows/test.yml, WORKSPACE, build/BUILD.brotli
kj-brotli was only included in the build for unix platforms, which caused the Windows runner to fail. Not sure how this slipped through CI previously, all tests passed on the PR for this.
Edit: Looks like the `Build & Release` job is what's failing, that's why it wasn't caught earlier
=> Fix Windows compilation by enabling kj-brotli

src/workerd/api/global-scope.c++, src/workerd/api/trace.c++, src/workerd/api/trace.h
The underlying io Trace objects are kj heap allocated. They cannot be referenced unprotected by the TraceItem jsg object and we do not want to restrict them to the IoContext lifetime. Instead we'll extract the detail we need on TraceItem creation.
=> Do not refcount Trace instances in TraceItem API

src/workerd/api/r2-rpc.c++
The default error message must be a json object.. I missed this previously
=> Fixup json error message in r2-rpc.c++.

src/workerd/jsg/setup.c++, src/workerd/jsg/wrappable.h
In V8 11.5, things changed so that the `ResetRoot()` callback might be called on a background thread. A new method, `TryResetRoot()`, can be implemented to return false in order to prevent this and force `ResetRoot()` back to the main thread. However, its default implementation just calls `ResetRoot()` (on the background thread), hence the default behavior changed.
https://chromium-review.googlesource.com/c/v8/v8/+/4474708
Our `ResetRoot()` must be called on the main thread, so we must implement `TryResetRoot()` to return false.
This allows us to remove the `single_threaded_gc` flag we added recently as a work-around. It turns out that flag isn't actually sufficient to avoid the problem anyway.
=> Implement `EmbedderRootsHandler::TryResetRoot()`.

src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/io/actor-cache.c++, src/workerd/io/actor-cache.h
Note: I think we may need an additional API to list the history of restorations, but I haven't defined that yet. This would be needed in particular for the case where a restoration is scheduled, but the "undo" bookmark is not successfully returned to the caller; the caller will need a way to fetch the undo bookmark after the fact. A history of restorations would provide that.
=> SQLite: Add point-in-time recovery API.

.bazelrc, src/workerd/server/BUILD.bazel, src/workerd/util/BUILD.bazel, src/workerd/util/symbolizer.c++
Including in wd_tests, which requires linking into workerd.
This should make debugging a lot easier for people working on this repo.
=> Enable LLVM_SYMBOLIZER by default in tests

src/workerd/api/url-standard.h, src/workerd/jsg/promise.c++, src/workerd/jsg/promise.h
In both these cases, hash collisions are expected to happen from time to time, so assuming equality on equal hash code is not safe.
=> Fix hash tables that assume hashes don't collide

src/workerd/api/global-scope.h
`QueueMessage` is renamed to `Message` in its override...
https://github.com/cloudflare/workerd/blob/d073c092e57c96895e8eccbfe21d27aefb4b0604/src/workerd/api/queue.h#L133
...but the rename transform is not type parameter aware. To ensure the type parameter is still used, rename it to something that shouldn't be renamed.
Fixes #758
=> Rename `QueueMessage` type parameter

.vscode/launch.json, .vscode/tasks.json, build-releases.sh, docs/vscode.md
* Use fastbuild for release temporarily.
* Add opt builds for vscode
* Trivial clean-up of macOS build options
=> macOS build and release updates for workerd

WORKSPACE, build/run_binary_target.bzl, patches/v8/0011-Use-target-cfg.patch, src/workerd/tools/BUILD.bazel
Compile substantially all of workerd in the bazel 'target' configuration
instead of 'exec', which allows us to avoid compiling major components
twice.
This should offer a large performance improvement, especially when
rebuilding after a V8 update or building all targets and drive down the
worst-case CI build time significantly.
Bazel supports an exec configuration for building code that needs to run
on the host machine during the build, e.g. tools used to generate source
files or type definitions. When not cross-compiling exec and target will
be the same, but bazel does not offer a flag to use just one configuration
when the configurations are identical (https://github.com/bazelbuild/bazel/issues/14848),
making manual changes necessary.
Bazel appears to offer no way to detect if exec and …
=> Speed up build by avoiding build config duplication

src/workerd/api/queue.c++, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h
Not massively important, just a fun little quick win to improve a couple copies introduced by #690 
cc @jasnell for the new `jsg::parseJson` variant
=> Remove a few copies in the queue event handler code

src/node/internal/inspect_polyfill.ts, src/node/internal/internal_assert.ts, src/node/internal/internal_assertionerror.ts, src/workerd/api/node/assert-test.js
Previously, using the following code in a workerd test:
```ts
import * as assert from "node:assert";
export const test_deep_equals = {
async test(ctr, env) {
assert.deepStrictEqual({
a: [1,2,3],
b: true
}, {
a: [1,2,4],
c: false
});
}
}
```
Would give the following error:
```
jsg.Error: AssertionError: Expected actual to be deeply strictly equal to expected
```
With this PR, you should get:
```
Error: AssertionError: Expected values to be strictly deep-equal:
+ actual - expected
+ { a: [ 1, 2, 3 ], b: true }
- { a: [ 1, 2, 4 ], c: false }
```
I did this by injecting the compiled output of https://www.npmjs.com/package/node-inspect-extracted as a new file.
I didn't wire this up as `import { inspect } from 'node:util';` because I only really wanted it for assertion errors, and because this …
=> Adding a `util.inspect` polyfill for `assert.deepEqual`

src/workerd/api/sockets.c++, src/workerd/api/sockets.h
This fixes a regression where `connect("google.com:443")` fails with a TypeError.
=> Don't fail on `port` from URL parser being empty.

src/workerd/api/sql-test.js, src/workerd/util/sqlite.c++
This PR:
* Allowlists `table_xinfo` (https://www.sqlite.org/pragma.html#pragma_table_xinfo) - which shows generated columns (https://github.com/cloudflare/cloudflare-docs/pull/9420) that `table_info` does not.
* Expands an existing test to ensure `table_xinfo` works.
=> srs: allowlist table_xinfo

WORKSPACE, src/workerd/api/actor.c++, src/workerd/api/cache.c++, src/workerd/api/cache.h, src/workerd/api/global-scope.c++, src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/kv.c++, src/workerd/api/kv.h, src/workerd/api/queue.c++, src/workerd/api/r2-admin.c++, src/workerd/api/r2-bucket.c++, src/workerd/api/r2-multipart.c++, src/workerd/api/sockets.c++, src/workerd/api/web-socket.c++, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/worker.c++
* [Don't set observer null when ending span](https://github.com/cloudflare/workerd/commit/6e971e5439ec67e4a3f8e2788d3bdb9ff71b80ed)
Encapsulating the entire span in a state containing the observer and span and setting it null on `end()` prevents the creation of subspans after the span has ended.
* [Add getObserver to SpanBuilder](https://github.com/cloudflare/workerd/commit/e3ec9a9541908a00ddcd793435ca63c0986c2785)
* [Switch span tracing APIs to use kj::ConstString](https://github.com/cloudflare/workerd/commit/66b2b51ca93693f4f6ee5edaec483f5456fe553a)
=> Minor span tracing improvements

src/workerd/api/basics.h, src/workerd/api/http.c++, src/workerd/api/streams/common.h, src/workerd/api/streams/readable.c++, src/workerd/api/streams/transform.c++, src/workerd/api/streams/transform.h, src/workerd/api/streams/writable.c++, src/workerd/api/url.h, src/workerd/api/web-socket.c++, src/workerd/api/web-socket.h, src/workerd/io/compatibility-date-test.c++, src/workerd/io/compatibility-date.c++
refs EW-7514
- Previously we used the language "feature flag" and "compatibility flag" interchangeably
- This was ambiguous, since on Cloudflare and other platforms, "feature flag" refers to a separate concept and system, that requires internal action to enable.
- This PR updates all references to "feature flag" to use the "compatibility flag" language, to ensure that when people encounter error messages, it is clear that these are in reference to compatibility flags, as described [here](https://developers.cloudflare.com/workers/platform/compatibility-dates/#compatibility-flags) in the Workers docs.
=> Use 'compatibility flag' language consistently

src/workerd/server/server.c++
When attempting to use the websocket hibernation api while running `wrangler dev`, we saw `a.getHibernationEventType() != nullptr` errors pop up because the hibernation event ID is defined in our internal codebase.
Note that this change only affects `server.c++`, which durable objects does not rely upon in production. This also does not enable the actual hibernation of websockets/DOs, it's only a step towards getting hibernatable websocket events to deliver locally.
=> Hardcode ws hibernation event type in workerd

src/workerd/io/worker-entrypoint.c++
To get accurate metrics when load testing an optimized build, the GC pass that is normally done per test is now disabled.
=> Noop for test GC pass when not in debug

src/workerd/api/sql-test.js, src/workerd/util/sqlite.c++
Fixes #795 
This PR increases the `SQLITE_MAX_COMPOUND_SELECT` limit (https://www.sqlite.org/limits.html#max_compound_select) from the [dark arts recommended](https://www.sqlite.org/security.html) `3` to a slightly more permissive `5` based on user feedback. The SQLite default is 500.
=> sql: increase SQLITE_LIMIT_COMPOUND_SELECT to 5

src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/api/global-scope.h, src/workerd/api/web-socket.c++, src/workerd/api/web-socket.h, src/workerd/io/hibernation-manager.c++, src/workerd/io/hibernation-manager.h, src/workerd/io/worker.c++, src/workerd/io/worker.h
When a specific `request` is set for hiberntabale web socket, they must respond with `response`, store the timestamp and if currently hibernating, should stay hibernated.
This PR adds a new `DurableObjectState::setWebSocketAutoresponse(request: string, response: string);` and `WebSocket::getAutoresponseTimestamp();`.
=> Application-level auto-response for hibernatable web sockets 

build-releases.sh, src/workerd/jsg/setup.c++
workerd: Use --single-threaded-gc
Consecutive requests could lead to calling into the isolate whilst code pages are being collected. This problem has only been observed on macOS arm64.
Bug: CUSTESC-29094
Bug: https://github.com/cloudflare/workers-sdk/issues/2386
=> workerd: Use --single-threaded-gc

samples/nodejs-compat-module/foo.js, src/node/internal/process.ts
Exposes text bindings from the worker via process.env
Requires internal changes and CI also.
=> Implement Node.js compat process.env

.bazelrc, README.md
macOS 11 is the oldest version still being maintained, V8 also depends on multithreading-related functions introduced with it. This is hopefully sufficient to fix https://github.com/cloudflare/workers-sdk/issues/3307 https://github.com/cloudflare/workers-sdk/issues/3315 https://github.com/cloudflare/workers-sdk/issues/3432 – macOS shouldn't require static linking of system libraries and at least two of the issues are on macOS 11.
Also updated the readme, the `ubuntu-latest` Github Actions runner image is now identical to ubuntu-22.04 so it works just fine. Based on #170 the commend-line tools should be sufficient for compiling.
=> Define macOS 11 as earliest supported version

src/workerd/api/crypto-impl-asymmetric.c++, src/workerd/io/compatibility-date.capnp
With the `strict_crypto_checks` flag enabled, imported ECDH keys were required to have empty usages, but for private keys the usage set should be allowed to include deriveBits and deriveKey.
Since the compatibility date for the flag has not yet passed, this is unlikely to have had a significant effect.
Also updates a compat flag description to clarify that the public exponent is limited to a certain set of values.
=> Fix ECDH key import when strict_crypto_checks is enabled

src/workerd/api/sockets.c++, src/workerd/api/sockets.h
So that they can return a properly configured Socket when appropriate.
This is used by an API I'm working on that will mostly be implemented internally, but wants to return a Socket.
=> Make setupSocket() callable by other API implementations

src/workerd/jsg/README.md
Signed-off-by: Jianyong Chen <baluschch@gmail.com>
=> jsg/readme: fix some syntax errors and some typos.

.github/workflows/npm-types.yml, .github/workflows/npm.yml, .github/workflows/release.yml
#800 changed the Linux runner image to Ubuntu 20.04, but only adjusted the clang version for the main test and release builds, causing other jobs that need to compile capnp_tool to fail.
=> Fix release build versioning

WORKSPACE, patches/v8/0001-Allow-manually-setting-ValueDeserializer-format-vers.patch, patches/v8/0002-Allow-manually-setting-ValueSerializer-format-versio.patch, patches/v8/0003-Make-icudata-target-public.patch, patches/v8/0004-Add-ArrayBuffer-MaybeNew.patch, patches/v8/0005-Allow-compiling-on-macOS-catalina-and-ventura.patch, patches/v8/0006-Fix-v8-code_generator-imports.patch, patches/v8/0007-Allow-Windows-builds-under-Bazel.patch, patches/v8/0008-Disable-bazel-whole-archive-build.patch, patches/v8/0009-Make-v8-Locker-automatically-call-isolate-Enter.patch, patches/v8/0010-Add-an-API-to-capture-and-restore-the-cage-base-poin.patch, patches/v8/0011-Speed-up-V8-bazel-build-by-always-using-target-cfg.patch, patches/v8/0012-Implement-Promise-Context-Tagging.patch, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/worker.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/setup.h
Implements a mechanism in v8 that allows tagging a Promise with a creation context, then using that to implement cross-request promise awaits.
The way the mechanism works is fairly straightforward:
1. Whenever we enter IoContext::Scope, we'll set a "promise context tag" on the Isolate, currently this is just an opaque empty object that we use only as a marker.
2. Whenever a JS Promise is created while we are in that IoContext::Scope, the Promise will be tagged with that same promise context tag object. When a JS Promise is created outside of the IoContext::Scope, its context tag is empty.
3. Whenever a JS Promise is followed (e.g. using await or by calling then, etc) the context tag on the promise is compared against the isolate's current context tag. If they are the same, or if the JS …
=> Update v8 to include Promise Context Tagging patch

samples/nodejs-compat-diagnosticschannel/README.md, samples/nodejs-compat-diagnosticschannel/config.capnp, samples/nodejs-compat-diagnosticschannel/library.js, samples/nodejs-compat-diagnosticschannel/worker.js, src/node/diagnostics_channel.ts, src/node/internal/diagnostics_channel.d.ts, src/workerd/api/node/async-hooks.c++, src/workerd/api/node/async-hooks.h, src/workerd/api/node/diagnostics-channel-test.js, src/workerd/api/node/diagnostics-channel-test.wd-test, src/workerd/api/node/diagnostics-channel.c++, src/workerd/api/node/diagnostics-channel.h, src/workerd/api/node/node.h, src/workerd/api/trace.c++, src/workerd/api/trace.h, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/worker-interface.capnp, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/rtti.capnp, src/workerd/jsg/rtti.h, types/src/generator/type.ts, types/test/generator/type.spec.ts
An implementation of Node.js diagnostics_channel.
* Supports TracingChannels
* Includes capturing diagnostic channel events to tail workers automatically.
Refs: https://nodejs.org/dist/latest-v20.x/docs/api/diagnostics_channel.html
=> Implement node.js compat diagnostics_channel

build/wd_js_bundle.bzl, build/wd_ts_bundle.bzl, src/cloudflare/tsconfig.json, src/node/tsconfig.json, src/workerd/api/modules.h, src/workerd/api/node/async-hooks.h, src/workerd/api/node/node.h, src/workerd/api/rtti-test.js, src/workerd/api/rtti-test.wd-test, src/workerd/api/rtti.c++, src/workerd/api/rtti.h, src/workerd/api/sockets.h, src/workerd/io/BUILD.bazel, src/workerd/io/compatibility-date.capnp, src/workerd/jsg/modules.capnp, src/workerd/jsg/rtti.capnp, src/workerd/jsg/rtti.h, src/workerd/server/BUILD.bazel, src/workerd/server/workerd-api.c++
Hey! 👋 This PR adds a `workerd:rtti` module (gated behind an experimental `rtti_api` compatibility flag), for accessing RTTI.
This allows us to move automatic type generation for `@cloudflare/workers-types` into a worker, and dynamically generate types based on compatibility dates and flags. This worker would be accessible by the quick editor, and `wrangler` for local dev (we could also run this worker locally for fully-offline development).
TypeScript declaration files for internal and builtin modules are also included in JavaScript bundles, allowing us to include these in generated types (i.e. we can now include types for the `nodejs_compat` flag in `@cloudflare/workers-types`).
Once we have this worker setup, we should be able to remove `src/workerd/tools/api-encoder.c++`.
=> Add runtime API for accessing RTTI & include internal/built-in modules

.vscode/launch.json, src/workerd/api/actor-alarms-delete-test.js, src/workerd/api/actor-alarms-delete-test.wd-test, src/workerd/server/alarm-scheduler.c++, src/workerd/server/alarm-scheduler.h
Calling deleteAlarm() while an alarm() handler is running was crashing running locally, specifically when using alarms with `wrangler dev`.
This PR affects only local development and  tries to fix this by disallowing alarms.erase for running alarms.
A test is included, mostly based on @xortive actor-alarms test, including the script causing crashes in workerd.
=> Fix actor alarms, deleteAlarm() crash when called inside alarm() 

src/workerd/io/compatibility-date.capnp
We're hoping to get a Wrangler release out today (assuming LDW exception granted), with a `workerd` bump. `workerd` releases can take a few hours to get ready, so creating this PR now. We'll still need to manually trigger the npm publish, so if the exception isn't granted, we can just abort the release. 👍
=> Bump compatibility date to `2023-06-28` for release

src/workerd/io/compatibility-date.c++, src/workerd/io/compatibility-date.h
This makes it possible to more easily set up compatibility flags based on the current date and avoids putting the entire CompatDate class in the header. Also see the upstream PR.
=> Add API for current date string based on CompatDate

compile_flags.txt
Fixes clangd errors on workerd sources for missing nullptr_t definition and not being able to find stdarg.h.
Test: tools/unix/clangd-check.sh
=> Improvements to compile_flags.txt for macOS

src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker-entrypoint.h
The code was adaping an HttpService (WorkerInterface) into an HttpClient and then adapting that back into an HttpService. This change removes the two layers of adapters.
In addition to being more efficient, I'm hoping this fixes some weird sentry errors we're seeing from `LOG_EXCEPTION("failOpenFallback", e)`.
=> Clean up fail-open fallback code.

src/node/internal/crypto_keys.ts
The Node.js compat crypto createPrivateKey and createPublicKey APIs are the rough equivalent to Web Crypto importKey for key pairs. Unfortunately they provide a range of options that are not currently supported by the Web Crypto implementation. The current Web Crypto implementation either needs to be refactored or duplicated in a number of ways in order to properly support createPrivateKey/createPublicKey. For now, we'll mark these apis as unimplemented and will revisit once the import key internals have been sufficiently refactored.
=> Mark Node.js createPrivateKey/createPublicKey unimplemented for now

src/node/crypto.ts, src/node/internal/crypto.d.ts, src/node/internal/crypto_hash.ts, src/node/internal/crypto_util.ts, src/node/internal/streams_transform.d.ts, src/workerd/api/node/crypto.h, src/workerd/api/node/crypto_hash-test.js, src/workerd/api/node/crypto_hash-test.wd-test, src/workerd/api/node/crypto_hash.c++
Builds upon the felix/node-crypto-prime branch.
Remaining issues:
- I couldn't quite figure out how to have TypeScript consider Hash to be an actual class and a type, fix this and get rid of the casts to `any`.
- Hash is supposed to extend `stream.transform`, but having it inherit from that class seems difficult to do without having Typescript bindings for a large proportion of stream-related code. This is needed for the stream-based test cases to work.
=> Implement crypto.createHash(), Hash class

src/workerd/api/BUILD.bazel, src/workerd/api/actor-alarms-delete-test.js, src/workerd/api/actor-alarms-test.js, src/workerd/server/alarm-scheduler.c++, src/workerd/server/alarm-scheduler.h
This PR should fix flakey alarm tests.
During CI, it can happen that `Date.now() < scheduledTime` by a few ms. We could be less strict about this, adding a few ms margin.
=> Fix flakey alarm tests

src/workerd/api/blob.h, src/workerd/api/form-data.h, src/workerd/jsg/jsg.h, src/workerd/jsg/wrappable.c++
`api::FormData::getData()` (an interface meant for C++ callers, not JS) returns a const array, but the array contains instances of `jsg::Ref<File>`. Before this commit, those refs couldn't actually be used due to the constness.
(To be used in some internal code.)
=> Add some const accessors.

.bazelrc, src/node/internal/util.d.ts, src/node/util.ts, src/workerd/api/blob.c++, src/workerd/api/form-data.c++, src/workerd/api/html-rewriter.c++, src/workerd/api/http.c++, src/workerd/api/kv.c++, src/workerd/api/node/mimetype-test.js, src/workerd/api/node/mimetype-test.wd-test, src/workerd/api/node/node.h, src/workerd/api/node/util.c++, src/workerd/api/node/util.h, src/workerd/api/queue.c++, src/workerd/api/r2-bucket.c++, src/workerd/api/util-test.c++, src/workerd/api/util.c++, src/workerd/api/util.h, src/workerd/io/worker.c++, src/workerd/server/server.c++, src/workerd/util/mimetype-test.c++, src/workerd/util/mimetype.c++, src/workerd/util/mimetype.h, src/workerd/util/strings.h
Implements Node.js MIMEType API. Implemented in C++ because this also addresses a number of internal TODOs by implementing a proper MIME type parser internally.
=> Implement MimeType parser and class

src/workerd/io/compatibility-date.capnp
This does not enable compression for all compatibility dates.
=> Enable websocket compression compat date

src/node/crypto.ts, src/workerd/api/crypto-impl-asymmetric.c++, src/workerd/api/node/crypto_dh.c++
See getHashes() for the rationale for hardcoding getCiphers() and getCurves(). The second commit fixes several error messages, see the commit description.
=> Implement node crypto algorithm listings, crypto error message fixes

src/workerd/api/streams/queue-test.c++, src/workerd/io/BUILD.bazel, src/workerd/io/observer.h, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/jsg/BUILD.bazel, src/workerd/jsg/jsg-test.c++, src/workerd/jsg/jsg-test.h, src/workerd/jsg/jsg.h, src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h, src/workerd/jsg/observer.h, src/workerd/jsg/promise.h, src/workerd/jsg/resource.h, src/workerd/jsg/setup-test.c++, src/workerd/jsg/setup.c++, src/workerd/jsg/setup.h, src/workerd/server/server.c++, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h, src/workerd/tests/test-fixture.c++
this change moves the ownership of `ModuleRegistry` to `JsgContext`. The goal is to always have it available for every context to be able to compile and use bootstrap js modules.
To properly support observability it brings `CompilationObserver` into `IsolateObserver` hierarchy.
Internal PR 5780
=> extending module registry lifetime

src/workerd/api/kv.c++, src/workerd/api/kv.h
When KV returns this in the response, propagate it.
=> Propagate the cf-cache-status from the KV worker

rust-deps/BUILD.bazel, rust-deps/packages.bzl
the intent is to reuse RTTI_PACKAGES in edgeworker to enable /tools/... compilation on CI.
=> [nfc] extracting rust pacakge definitions to packages.bzl

WORKSPACE, patches/v8/0012-Enable-V8-shared-linkage.patch
For linking tests, we currently use dynamic linkage, except for V8, which has dynamic linkage disabled. The provided V8 patch shifts a snapshot related file around to make dynamic linkage possible. This dramatically reduces test binary sizes – `//src/workerd/api:crypto-impl-test` shrinks from ~100MB to 5.8MB.
Note that the mac toolchain does not enable dynamic linkage, so the change is having no effect there.
There is no noticeable speedup in CI, Perhaps this will improve when the remote cache is primed and runners can fetch the (significantly smaller) test binaries from there. For the Linux runner at least, disk usage compared to a build on the main branch goes from `11G => 7.9G` for the disk cache and `7.4G => 4.5G` for the output directory. 
This should be more beneficial for the local …
=> Allow shared linkage for V8

src/workerd/api/r2-bucket.c++
Changes the the invocation of the toUTCString JavaScript method so that the receiver is a Date.
Bug: https://github.com/cloudflare/workerd/issues/851
Bug: EW-7623
=> Fix receiver argument in toUTCString in r2-bucket.c++

src/workerd/server/alarm-scheduler.c++, src/workerd/server/alarm-scheduler.h
The previous `checkTimeStamp()` implementation could cause async busy looping problems, since we could get stuck on `checkTimeStamp()` without waiting on a `timer.afterDelay()`. 
Also, as we were checking for `scheduledTime >= clock.now()` before waiting for `delay`, retries weren't backing-off, if needed. 
This PR fixes both issues, guaranteeing we wait on retries, and we can't get into a `checkTimeStamp()` loop without waiting on a timer.
=> Fix alarms checkTimestamp()

src/workerd/api/sql-test.js, src/workerd/util/sqlite.c++
Introduce VALUE_GATE macro to capture which "db names" (usually param3) are allowed for each actionCode
This replaces `isAuthorizedTemp`, by permitting "temp" as param3 to SQLITE_READ and SQLITE_UPDATE.
Also note that for SQLITE_ALTER_TABLE, "db name" is sent as param1 not param3 (afaik it's the only one that we support that does this). This might be a sqlite bug, as it conflicts with the following comment
> CAPI3REF: Authorizer Action Codes
> 
> The [sqlite3_set_authorizer()] interface registers a callback function
> that is invoked to authorize certain SQL statement actions.  The
> second parameter to the callback is an integer code that specifies
> what action is being authorized.  These are the integer action codes that
> the authorizer callback may be passed.
> 
> These action code …
=> [SQLite] Refactor Authorizer

src/workerd/api/blob.c++, src/workerd/api/util.h
As part of the effort to begin broader adoption of coroutines across the codebase, I plan to open a number of small examplar PRs as part of the preparation for the larger effort to devise and document a plan for the larger effort. This is largely intended to help tease out whether there are any particularly thorny issues that may be uncovered while we go through the process, but also to provide examples for the team on how the conversion can be done. 
This PR picks one small API largely at random (Blob::BlobInputStream) that is easy to convert.
And since I'm in the code, I'm also taking the opportunity to do a bit of Drive By cleanup, documentation, and minor refactoring to simplify impl along the way.
=> Coroutines Conversion: convert Blob::BlobInputStream

src/workerd/api/queue.h
Following on from #690, this PR changes the type definitions for the Queues message `.send()` and `.sendBatch()` functions to reflect the new `contentType` option. This was originally left out of the generated types so it could be tested before it was documented (see [here](https://github.com/cloudflare/workerd/pull/690#discussion_r1203024274))
(cc @jbwcloudflare)
=> Add Queues message contentType to types

.bazelrc, .github/workflows/npm-types.yml, .github/workflows/npm.yml, .github/workflows/release.yml, .github/workflows/test.yml
We currently do not utilize the actions/cache-based CI bazel disk cache well: On recent Linux CI build runs, there was a disk cache hit for only 10 out of 5575 build actions. This is because we always use the same cache key when building for the same platform, which means that the actual cache entries being used are still the ones that were first added for the platform (or a  have been evictions based on the cache size limit). This means very old cached data is provided, which largely can't be used if the compile options or V8 version has changed.
This PR introduces a new cache key scheme based on https://github.com/actions/cache/blob/main/examples.md#---bazel that changes the cache key/updates the cache whenever the OS version, bazel version or major build options or dependencies as …
=> Overhaul bazel disk cache management

src/workerd/api/queue.h
This PR adds the generic type default of `unknown` to the TS definition for Queues. It looks like there used to be a default type of `any`, but this regressed earlier (see [here](https://github.com/cloudflare/workerd/pull/541#discussion_r1165777988)). I used `unknown` instead of `any` for consistency with the rest of the Queues generic types.
Without this, the Workers templates generated by `create-cloudflare` will have incorrect initial typing, since they type the Queue bindings as `Queue` without any type parameter (see [here](https://github.com/cloudflare/workers-sdk/blob/main/packages/create-cloudflare/templates/hello-world/ts/src/worker.ts#L25)). 
(cc @jbwcloudflare // @jasnell @mrbbot)
=> Add generic type default to Queue TS definition

src/workerd/api/analytics-engine-test.js, src/workerd/api/analytics-engine-test.wd-test, src/workerd/server/server.c++, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h, src/workerd/server/workerd.capnp
Closes #536 
This implementation will forward analytics engine events in the body of http requests to a provided service. The binding is marked as experimental and requires the `--experimental` flag to use
=> Add AnalyticsEngine binding type to workerd

src/workerd/jsg/setup.c++
This reverts commit ad65da8e4d7a1bbf5b800de35d13cc5a7eef73f0.
For some reason I have not yet determined, this change appears to be persistently breaking a couple of internal tests. Let's back it out for now while we investigate further.
=> Revert "fix v8 deprecation warning (#909)"

rust-deps/crates/BUILD.phf-0.8.0.bazel, rust-deps/crates/BUILD.phf_macros-0.8.0.bazel, rust-deps/crates/BUILD.proc-macro-hack-0.5.19.bazel, rust-deps/crates/defs.bzl
This should serve as a temporary fix for the rules_rust-related Windows compile issues. It likely works solely based on the shorter name which causes MSVC input file paths to be within the limit. A better solution is needed, but this should be enough to unblock us.
=> Downgrade proc-macro-hack to 0.5.19

src/workerd/api/streams/readable.c++, src/workerd/api/streams/streams-test.js, src/workerd/api/streams/streams-test.wd-test
Fixes: https://github.com/cloudflare/workerd/issues/892
=> Allow pumpTo() from unlocked, disturbed readable streams

src/workerd/api/gpu/gpu-command-encoder.h, src/workerd/api/gpu/gpu-compute-pipeline.h, src/workerd/api/gpu/gpu-device.c++, src/workerd/api/gpu/gpu-device.h, src/workerd/api/gpu/gpu-pipeline-layout.h, src/workerd/api/gpu/gpu-shader-module.h, src/workerd/api/gpu/gpu.h, src/workerd/api/gpu/webgpu-test.js
Added support for compute pipelines, shaders and pipeline layouts.
=> implement more webgpu objects

src/workerd/api/sql-test.js, src/workerd/api/sql.c++, src/workerd/api/sql.h
(Replaces #696 as I renamed the remote branch name and the other PR got closed)
This PR adds a `.columnNames` property that can be called on a Cursor before iterating over the result:
```js
// Given the following data:
sql.exec(`CREATE TABLE abc (a INT, b INT, c INT);`)
sql.exec(`CREATE TABLE cde (c INT, d INT, e INT);`)
sql.exec(`INSERT INTO abc VALUES (1,2,3),(4,5,6);`)
sql.exec(`INSERT INTO cde VALUES (7,8,9),(1,2,3);`)
const iterator = sql.prepare(`SELECT * FROM abc, cde`)();
console.log(iterator.columnNames)
// ["a","b","c","c","d","e"]
console.log(Array.from(iterator.raw()))
// [
//   [1, 2, 3, 7, 8, 9],
//   [1, 2, 3, 1, 2, 3],
//   [4, 5, 6, 7, 8, 9],
//   [4, 5, 6, 1, 2, 3],
// ]
```
This helps us get around the issue where the default iterator swallows data when column names …
=> [SQLite] Add `.columnNames` property on Cursor

src/workerd/api/actor-state.c++, src/workerd/api/cache.c++, src/workerd/api/crypto-impl-aes-test.c++, src/workerd/api/crypto.c++, src/workerd/api/crypto.h, src/workerd/api/global-scope.c++, src/workerd/api/http.c++, src/workerd/api/kv.c++, src/workerd/api/r2-admin.c++, src/workerd/api/r2-bucket.c++, src/workerd/api/sockets.c++, src/workerd/api/streams/common.h, src/workerd/api/streams/internal.c++, src/workerd/api/streams/readable.c++, src/workerd/api/streams/standard.c++, src/workerd/api/streams/standard.h, src/workerd/api/streams/transform.c++, src/workerd/api/web-socket.c++, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/promise-wrapper.h, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker.c++, src/workerd/jsg/iterator.h, src/workerd/jsg/promise-test.c++, src/workerd/jsg/promise.h
Fairly large but largely non-functional change. Addresses a long standing todo for consistently passing js::Lock& references where needed and moves us away from deprecated methods.
=> Use jsg::Lock passing variant of jsg::Promise::then

src/workerd/api/gpu/gpu-bindgroup.h, src/workerd/api/gpu/gpu-command-encoder.c++, src/workerd/api/gpu/gpu-command-encoder.h, src/workerd/api/gpu/gpu-compute-pass-encoder.c++, src/workerd/api/gpu/gpu-compute-pass-encoder.h, src/workerd/api/gpu/gpu-compute-pipeline.h, src/workerd/api/gpu/gpu-query-set.h, src/workerd/api/gpu/gpu-utils.h, src/workerd/api/gpu/gpu.h, src/workerd/api/gpu/webgpu-test.js
New objects: command encoder, compute pass encoder, query set.
=> implement additional webgpu objects

src/workerd/api/sockets.c++
The way this was previously written, the errorHandler would correctly run if the readable contoller's cancel promise rejects, but not if the writable controller's abort promise rejects. This fixes that, since it does appear possible for the abort promise to reject, for example in WritableStreamDefaultWriter::abort.
Unless for some off chance we don't want `errorHandler` to be called if the readable contoller's cancel promise succeeds? If that's the case, I'm happy to close this.
---
I noticed this when looking into some `The script will never generate a response.` issues when running in edge preview on the new internal type I'm working on, although I doubt this is actually the cause -- I’m more suspicious about whether I need to add something similar to the `handleProxyStatus` method for …
=> Ensure proper socket error handling when write controller abort fails

src/workerd/api/queue-test.js, src/workerd/api/queue-test.wd-test, src/workerd/api/queue.c++
Hey! 👋 It looks like #690 may have re-introduced the bug fixed by #644. This PR applies the same fix, and adds a test to prevent this regressing again. The important part is the `await env.SERVICE.queue()` call, which will result in a `Error: Unable to deserialize cloned data` without this fix.
=> Fix use-after-free when deserializing `QueueMessage` on Windows

WORKSPACE
Capnproto now requires support for C++20, and drops support for the use_coroutines build flag. This seems to cause no turbulence in workerd code, and is just a regular dependency update.
=> Update capnproto dependency to C++20 version

src/workerd/api/http-test.js, src/workerd/api/http-test.wd-test, src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/queue-test.js, src/workerd/server/server-test.c++
Hey! 👋 This PR implements a `Fetcher#scheduled()` method for dispatching `scheduled` events to bound services. This will allow us to add support for triggering scheduled events in Miniflare without transforming user code. Like `Fetcher#queue()`, this is gated behind the experimental `service_binding_extra_handlers` compatibility flag.
=> Implement `Fetcher#scheduled()` for dispatching `scheduled` events

src/workerd/api/streams/internal.c++
Reverts cloudflare/workerd#883
Reproducer is in #974
=> Revert "Coroutines Conversion: rewriting AllReader into coroutines"

src/workerd/api/streams/compression.c++
if the stream has already completed and output is too small the resulting promise will never get resolved.
I wasn't able to test this separately because we do not expose this functionality directly.
This is the actual underlying issue of #970
=> fix reading from ended compression stream with high minBytes

.github/workflows/npm-types.yml, .github/workflows/release.yml, .github/workflows/test.yml
This includes some Github Actions CI cleanup and fixes an issue with the new disk cache approach implemented in #800.
- Simplify CI setup: The GitHub runner images have many packages installed already, which makes setup significantly easier.
- Use a split cache for CI test and release builds: In the previous cache overhaul a shared cache key was used, resulting in a release cache being used for test builds when a main branch release build finished before the test build. This made the cache less effective for test builds, which are more frequent and more expensive.
Another issue with the new cache setup is that when a stale cache is being used after there are build system changes and a new cache is subsequently generated, the new cache ends up being larger – bazel likely adds data based on …
=> Github Actions fixes/cleanup

src/workerd/api/basics.c++, src/workerd/jsg/README.md, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/promise.h
Proposes the introduction of a new js.withinHandleScope(...) utility that replaces direct use of v8::HandleScope. While the utility is not ideal it does help avoid direct use of an obscure but necessary v8 API and makes it easier when dealing with v8::HandleScope vs. v8::EscapableHandleScope, as well as working with v8::Context::Scope.
The naming is, admitedly, a bit clumsy, and I'm not entirely sold on the approach here yet, so definitely open to suggestions.
```cpp
js.withinHandleScope([&] {
// Everything here is within a v8::HandleScope!
return foo;  // returns whatever the inner lambda returns
});
js.withinHandleScope([&]() -> v8::Local<v8::Value> {
// Everything here is within a v8::EscapableHandleScope!
return v8::Object::New(js.v8Isolate);  // The returned v8::Local<...> is passed …
```
=> Introduce js.withinHandleScope(...) utility

WORKSPACE, src/workerd/server/server-test.c++, src/workerd/server/server.c++
_(depends on capnproto/capnproto#1738)_
Hey! 👋 As stated in #933, we're planning to port Miniflare's data store simulators to Durable Objects running in `workerd`. Being able to read specific ranges of file-system-backed blobs would be very useful when implementing Cache and R2 simulators. This PR adds support for the HTTP `Range` header to disk directory `GET` requests. Only single ranges are supported at the moment, specifying multiple ranges just responds with the full response.
=> Implement `Range`ed `GET`s for disk directories

src/workerd/api/global-scope.c++, src/workerd/api/http.c++, src/workerd/api/kv.c++, src/workerd/api/node/async-hooks.c++, src/workerd/api/r2-admin.c++, src/workerd/api/r2-bucket.c++, src/workerd/api/r2-rpc.c++, src/workerd/api/urlpattern.c++, src/workerd/io/worker.c++, src/workerd/jsg/dom-exception.c++, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/modules.c++, src/workerd/server/workerd-api.c++, src/workerd/tests/test-fixture-test.c++
Help to eliminate v8 specific boilerplate when getting/setting values on v8::Object instances. This should be considered transitional. It helps to eliminate a number of direct uses of v8::Isolate and other v8 specific APIs but does not completely hide the v8 semantics.
For example,
```cpp
jsg::check(bound->Set(js.v8Context(), jsg::v8StrIntern(js.v8Isolate, "foo"_kj), handler.wrap(js, JSG_THIS)));
// becomes
js.v8Set(bound, "asyncResource"_kj, handler.wrap(js, JSG_THIS));
```
=> JSG Completion: add interim jsg::Lock::v8Set and jsg::Lock::v8Get

src/workerd/api/actor-state-test.c++, src/workerd/api/actor-state.c++, src/workerd/jsg/jsg.c++
Start conversion of v8::HandleScope uses over to new jsg utility
=> JSG Completion: Use new js.withinHandleScope utility in actor-state

src/workerd/io/worker-interface.c++, src/workerd/io/worker-interface.h
This is to make it more explicit that this class only revokes web socket connections, not all HTTP requests.
Suggested by @kflansburg to make it more obvious what the code does.
=> Renames RevocableWorkerInterface to RevocableWebSocketWorkerInterface.

src/workerd/api/kv.c++, src/workerd/api/sql.c++, src/workerd/jsg/function.h, src/workerd/jsg/promise.h, src/workerd/jsg/util.c++, src/workerd/server/workerd-api.c++
Use js.withinHandleScope to replace a number of direct uses of v8::HandleScope. There are more to do but it touches a lot of files and I prefer to make the changes incrementally.
=> JSG Completion: Convert some direct uses of v8::HandleScope to new utility

src/workerd/api/sockets.c++, src/workerd/api/sockets.h
So that I can handle initial connection errors on connections that were established without using HTTP connect.
=> Add a new overload of Socket::handleProxyStatus for internal use

src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/queue-test.js, src/workerd/io/compatibility-date.capnp
Hey! 👋 This PR adds support for passing V8 serialised bodies (as received from `queue` producer bindings), to `Fetcher#queue()` for dispatch to user `queue` event handlers. This is a stop-gap solution until we implement an in-memory message dispatcher within `workerd` itself. Note this change exposes the V8 deserialiser to users. This function is gated behind the experimental `service_binding_extra_handlers` compatibility flag though.
=> Allow `Fetcher#queue()` to accept V8 serialised bodies

src/workerd/api/sockets.c++, src/workerd/api/sockets.h
This was broken by the recent switch to use JSG_KJ_EXCEPTION.
This PR re-applies the recently reverted #975 and applies a fix on top. The commits should preferably be squashed when merging.
=> Fix exception message in Socket::handleProxyStatus

WORKSPACE, patches/sqlite/0001-row-counts-amalgamation.patch, patches/sqlite/0001-row-counts-plain.patch, patches/sqlite/README, src/workerd/api/sql-test.js, src/workerd/api/sql.c++, src/workerd/api/sql.h, src/workerd/util/sqlite-test.c++, src/workerd/util/sqlite.c++, src/workerd/util/sqlite.h
In a durable object, state.storage.sql now has two new properties: rowsRead and rowsWritten. These count the number of rows read and written by the underlying SQLite database.
This is more than just the number of rows returned from queries or the number of records inserted/updated; it counts all rows read by the database engine in the processing of a query. For example, SELECT MAX(unindexed_column) FROM a_table returns a single result but reads every row from disk, and rowsRead reflects that.
=> SQL: counters for rows read and written

.clang-format, src/workerd/api/gpu/gpu-device.c++, src/workerd/api/gpu/gpu-shader-module.c++, src/workerd/api/gpu/gpu-shader-module.h, src/workerd/api/gpu/gpu-utils.h, src/workerd/api/gpu/gpu.h, src/workerd/api/gpu/webgpu-compute-test.js
Added getCompilationInfo() to shader object so that compilation errors can be analysed.
=> webgpu: implement compilation info

build-releases.sh
The build script failed for me but I didn't notice and inferred that it succeeded from the presence of the .gz files
This should make it more obvious in the future
=> fix release script: remove .gz files before building new ones

WORKSPACE, build/wd_cc_benchmark.bzl, compile_flags.txt, src/workerd/tests/BUILD.bazel, src/workerd/tests/bench-json.c++, src/workerd/tests/bench-tools.h
Implements a microbenchmark based on [google/microbenchmark](https://github.com/google/microbenchmark). This includes bazel integration for the library, defining the `wd_cc_benchmark()` target rule and adding an example benchmark.
There is also a header with convenience macros for benchmarking, including `WD_BENCH()` which is not yet used but can serve as a drop-in replacement for KJ_TEST() to make it easy to benchmark many of our existing tests. The felix/microbench-poc branch expands on this, but contains more experimental work; this PR is intended to land the microbenchmark and allow developers to define simple benchmarks, use `bazel run //src/workerd/tests:bench-json` to check it out!
=> Implement microbenchmark

src/workerd/api/http.c++, src/workerd/api/kv.c++, src/workerd/io/worker.c++, src/workerd/util/mimetype.c++, src/workerd/util/mimetype.h
mimetype serialization is surprisingly complex and involves heap allocations (kj::strTree). Fix it for simple case while waiting for a proper toString improvement.
=> micro optimization: do not serialize PLAINTEXT mimetype

src/workerd/api/global-scope.h, src/workerd/api/gpu/webgpu-errors-test.js
Some webgpu libraries use `instaceof`checks on objects returned from the API. Ensure that these work for some objects.
=> webgpu: ensure instaceof checks work

src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/gpu/gpu.c++, src/workerd/api/gpu/webgpu-buffer-test.gpu-wd-test, src/workerd/api/gpu/webgpu-buffer-test.js, src/workerd/api/gpu/webgpu-compute-test.gpu-wd-test, src/workerd/api/gpu/webgpu-compute-test.js, src/workerd/api/gpu/webgpu-errors-test.gpu-wd-test, src/workerd/api/gpu/webgpu-errors-test.js, src/workerd/api/gpu/webgpu-write-test.gpu-wd-test, src/workerd/api/gpu/webgpu-write-test.js, src/workerd/io/compatibility-date.capnp
The webgpu API can only be used in the context of a durable object and when the "webgpu" compatibility flag is set.
=> webgpu: ensure api restrictions

src/workerd/api/form-data.c++, src/workerd/api/form-data.h, src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/url-standard.c++, src/workerd/api/url-standard.h, src/workerd/api/url.c++, src/workerd/api/url.h, src/workerd/jsg/function.h
The jsg::Function will automatically set the receiver when mapping
from a JS function to jsg::Function. This is not always what we want.
In many cases we have to be able to override the receiver on a case
by case basis. This pr introduces the ability to change the receiver
on a jsg::Function, and updates the various forEach method impls to
use jsg::Function instead of directly using v8::Function calls.
=> Allow overriding the received (this) of a jsg::Function, update forEach impls

src/workerd/util/abortable.h, src/workerd/util/batch-queue.h, src/workerd/util/canceler.h, src/workerd/util/capnp-mock.h, src/workerd/util/http-util.h, src/workerd/util/mimetype.h, src/workerd/util/sqlite-kv.h, src/workerd/util/sqlite-test.c++, src/workerd/util/sqlite.c++, src/workerd/util/sqlite.h, src/workerd/util/symbolizer.c++, src/workerd/util/thread-scopes.c++, src/workerd/util/thread-scopes.h, src/workerd/util/uuid.h, src/workerd/util/wait-list.c++, src/workerd/util/wait-list.h
Wanted to get a sense of how difficult and time consuming it would be to manually convert the comment style to the more idiomatic comments-before-declarations style. Turns out it's rather quick and generally painless. This batch took about 30 minutes with several interruptions. Most of it is purely mechanical. In a few cases it's obvious that a tool would be difficult since some comments are obviously impl details that do, for instance, belong inside a function body, while others are clearly meant to describe the declaration. Some judgement is required to pick those out case by case but it seems to be rather painless overall.
=> Switch workerd/util to idiomatic comment style

src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/node/async-hooks.c++, src/workerd/api/node/async-hooks.h, src/workerd/api/node/diagnostics-channel.c++, src/workerd/api/node/diagnostics-channel.h, src/workerd/jsg/function.h, src/workerd/jsg/type-wrapper.h
Variation of jsg::Function that takes a jsg::Arguments<jsg::Value>
=> Variation of jsg::Function that takes jgs::Arguments<jsg::Value>

src/workerd/api/basics.c++, src/workerd/api/basics.h, src/workerd/api/r2-bucket.c++, src/workerd/api/streams/internal.c++, src/workerd/api/streams/standard.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/jsvalue-test.c++, src/workerd/jsg/jsvalue.c++, src/workerd/jsg/jsvalue.h, src/workerd/jsg/rtti-test.c++, src/workerd/jsg/rtti.h, src/workerd/jsg/type-wrapper.h, src/workerd/jsg/util.c++, src/workerd/jsg/util.h, types/src/generator/type.ts
These are a new abstraction meant to discourage use of v8::Local<T> directly in most cases.
See the included test for examples of use.
PR includes changes to `AbortSignal`/`AbortController` to illustrate how it is used and to verify it works.
~~Still todo:~~
=> Implement jsg::JsValue and related types

.gitignore
I have several scripts and files related to workerd development that would be convenient to store under the workerd/ source folder. Designate /local/ folder for that.
=> [nfc] add /local/ to gitignore

src/workerd/api/streams/queue-test.c++, src/workerd/io/io-context.c++, src/workerd/io/worker.c++, src/workerd/jsg/iterator-test.c++, src/workerd/jsg/jsg-test.h, src/workerd/jsg/jsg.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/modules.c++, src/workerd/jsg/promise-test.c++
Reduce direct usage of v8::Isolate APIs
=> JSG Completion: Replace v8 PerformMicrotaskCheckpoint with js.runMicrotasks()

src/workerd/api/actor-state-test.c++, src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/api/basics.c++, src/workerd/io/worker.c++, src/workerd/io/worker.h
The new `jsg::JsValue` and `jsg::JsRef<...>` are replacements for `v8::Local<...>` and `jsg::V8Ref<...>` ... this starts the transition over to using the new abstractions, starting with `ActorState`.
=> JSG Completion: update ActorState to use jsg::JsValue

src/workerd/api/gpu/gpu-command-encoder.h, src/workerd/api/gpu/gpu-device.c++, src/workerd/api/gpu/webgpu-compute-test.js
Most objects will need to expose a label, which has a default value of an empty string. This is an attempt to validate a pattern that will be applied to the rest of the webgpu objects.
=> webgpu: add labels to objects

src/workerd/api/cf-property.c++, src/workerd/api/cf-property.h, src/workerd/api/global-scope.c++, src/workerd/api/http.c++, src/workerd/api/http.h, src/workerd/api/util.h
Extracted all logic to handle the value to a separate class.
Most customers don't need this. Shaves off 6-10ns (10%) on hello world :)
lazy cf parsing:
`iteration_duration.............: avg=76.65µs min=52.06µs med=65.46µs max=25.35ms  p(90)=91.45µs p(95)=108.09µs`
main:
`iteration_duration.............: avg=87.73µs min=58.69µs med=74.47µs max=20.27ms  p(90)=107.58µs p(95)=120.31µs`
=> lazy cf property parsing

.bazelrc, WORKSPACE, src/workerd/api/url-standard.h, src/workerd/api/urlpattern.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/string.h, src/workerd/server/workerd.c++, src/workerd/util/mimetype.c++, src/workerd/util/mimetype.h
- As long as -std=c++20 is specified, clang supports coroutines without `-fcoroutines-ts` since version 10; the flag is also deprecated in clang 16 and no longer supported in clang 17, which will be released next month.
- Remove a number of != operators, these are not needed if operator== is present and can prevent the compiler from finding the right operator under C++20.
Also see the corresponding upstream and capnproto PRs.
=> Improve support for clang 16+

githooks/pre-commit
#1059 will actually execute this.
Example while trying to commit this change:
```
$ git commit -a
+DISALLOWED_PATTERN='KJ_DBG'
ERROR, disallowed text patterns detected.
To commit anyway, use --no-verify
```
=> pre-commit hook to check for KJ_DBG in source files

npm/workers-types/README.md, src/workerd/api/url-standard.h, src/workerd/tools/BUILD.bazel
Hey! 👋 This PR adds `@cloudflare/workers-types` entrypoints for compatibility dates `2023-03-01` and `2023-07-01`. These are the default on dates for `http_headers_getsetcookie` and `urlsearchparams_delete_has_value_arg`, both of which have user facing types changes. We're still planning to build a better system for this, that will allow users to generate types for any combination of compatibility dates and flags.
=> Add `2023-03-01` and `2023-07-01` types entrypoints

src/workerd/tests/BUILD.bazel, src/workerd/tests/bench-global-scope.c++
this benchmarks request handling innards without networking overhead.
on my laptop:
```
Run on (16 X 2531.17 MHz CPU s)
CPU Caches:
L1 Data 48 KiB (x8)
L1 Instruction 32 KiB (x8)
L2 Unified 1280 KiB (x8)
L3 Unified 24576 KiB (x1)
Load Average: 8.29, 9.28, 11.45
-----------------------------------------------------------------------
Benchmark                             Time             CPU   Iterations
-----------------------------------------------------------------------
GlobalScopeBenchmark/request      12805 ns        12787 ns        56261
```
=> [nfc] benchmark for GlobalScope::request serving function

.bazelrc, build/wd_cc_benchmark.bzl
```
$ bazel build --config=benchmark //... --build_tag_filters="benchmark_report"
$ find ./bazel-bin/ -name "*.benchmark.csv"
./bazel-bin/src/workerd/tests/bench-json.benchmark.csv
./bazel-bin/src/workerd/tests/bench-mimetype.benchmark.csv
$ cat ./bazel-bin/src/workerd/tests/bench-json.benchmark.csv
name,iterations,real_time,cpu_time,time_unit,bytes_per_second,items_per_second,label,error_occurred,error_message
"Test_JSON_ENC",96561,7.23878,7.23829,us,,,,,
"Test_JSON_DEC",81347,7.12574,7.12138,us,,,,,
```
cc @irvinebroque
=> [nfc] wd_cc_benchmark can generate csv report

.github/workflows/test.yml
Broken by actions/runner-images#812
Unforunately upgrading to LLVM16 per scikit-image/scikit-image#7109 appears to be hampered by https://github.com/bazelbuild/bazel/issues/17863. Working around this, there is a static assertion failure in Google benchmark.
=> Temporarily disable github runner for Windows 2022

compile_flags.txt, tools/unix/clangd-check.sh
* update include paths in compile_flags.txt.
* parallelize the execution of clangd in the clangd-check.sh script.
Manual check: server.cc has no clangd include errors in vscode.
=> A couple of improvements relating to clangd

src/workerd/io/worker.c++
Fixes a use-after-free for a stack allocated timer.
Bug: EW-7719
Test: See EW-7719
=> Bugfix: re-instate threadId guard in currentTimeMS

build/wd_cc_benchmark.bzl
bazel doesn't build/run it otherwise. It doesn't hurt if there's none, since run target are not run by `bazel test`.
=> [nfc] remove off-by-default bench tag

src/workerd/api/r2-bucket.c++
Needed to make use of JSG_REQUIRE instead of KJ_REQUIRE
Error messages were already strings so I don't think this will result in behavioral differences between this and what I intended to do with KJ_REQUIRE originally.
=> actually report http etag parsing errors to users for R2 conditional

package.json, pnpm-lock.yaml
Hey! 👋 This PR bumps `json5` to https://github.com/advisories/GHSA-9c47-m6qq-7p4h. Whist this is only used as a transitive dev dependency to read trusted `tsconfig.json`s, GitHub was warning us about it when pushing. To prevent people getting conditioned to avoid security warnings, let's bump it. This patch was generated by running `pnpm upgrade json5` with `pnpm@7`. This also changed some of our package specifiers, but not the locked versions. 👍
Ref: https://github.com/cloudflare/workerd/pull/1065
=> Bump `json5` to `1.0.2`

src/workerd/api/kv.c++, src/workerd/api/kv.h
Updates api/kv to make use of the new `jsg::JsValue` abstraction rather than using `v8::Local<...>` APIs directly.
=> JSG Completion: update api/kv.{h|c++} to use jsg::JsValue

.bazelrc, .github/workflows/release.yml, .github/workflows/test.yml
This is required due to https://github.com/actions/runner-images/issues/8125
An assortment of changes to enable building with the LLVM16 toolchain on Windows:
- add Windows-2022 back to the test strategy matrix in test.yml.
- add an LLVM upgrade step to test.yml to install LLVM 16
- add command to test.yml to fix the include path for LLVM includes
(Bazel issue https://github.com/bazelbuild/bazel/issues/17863).
- add a macro definition to .bazelrc to prefer __builtin_offsetof
(the offsetof macro without this is broken under LLVM16).
- add enforced include path override to files including emmintrin.h.
clang-cl.exe in LLVM15 picks up the LLVM version of this file, but
LLVM16 was picking up the MSFT version and preventing the compiler
from replacing intrinsics. It looks like there is a change …
=> Resurrect Windows-2022 with LLVM 16

.bazelrc, WORKSPACE
For now, I'm disabling the new deprecation warnings, since they are very noisy.
Depends on https://github.com/capnproto/capnproto/pull/1777
=> Update capnproto submodule to pick up KJ_IF_SOME

src/workerd/api/sockets.c++, src/workerd/api/sockets.h, src/workerd/io/worker.c++, src/workerd/io/worker.h
Such that internal machinery can generate special hostnames that will behave differently when connected to. This is useful, for example, to connect allow generic client libraries to connect to private local services using just a provided address (rather than requiring them them to support being passed a binding to call binding.connect() on).
=> Support overriding connect() behavior via callbacks for specified addrs

tools/windows/install-deps.bat
Sync with .bazelrc changes in d9338a6c425b57999be38661133282629ade1f69 (https://github.com/cloudflare/workerd/pull/1092)
The script now installs LLVM 16.0.6 and moves the clang include dir to match the expectations in .bazelrc. Hopefully, the .bazelrc changes can be dropped soon, but in the interim ensure local setup and build continues to work.
=> Update install-deps.bat to LLVM 16

WORKSPACE, src/workerd/api/encoding.c++, src/workerd/api/node/buffer.c++, src/workerd/jsg/function.h, src/workerd/jsg/iterator.h, src/workerd/jsg/setup.c++, src/workerd/jsg/util.h, src/workerd/jsg/value.h
In order to support KJ_STACK_ARRAY properly in coroutines, we're dropping support for VLAs.
Depends on https://github.com/capnproto/capnproto/pull/1762
=> Replace KJ_STACK_ARRAY with SboArray/Builder

build/wd_cc_benchmark.bzl, src/workerd/tests/BUILD.bazel, src/workerd/tests/benchmark-main.c++, src/workerd/tests/malloc-memory-manager.c++, src/workerd/tests/malloc-memory-manager.h
according to https://github.com/google/benchmark/issues/1217 it is output only in .json format.
Results for bench-api-headers:
```
"allocs_per_iter": 9.8750000000000000e+01,
"max_bytes_used": 0,
"total_allocated_bytes": 800105
```
=> [nfc] using malloc hooks to benchmark memory allocations too.

.bazelrc, build/kj_test.bzl, build/wd_cc_binary.bzl, src/workerd/tools/BUILD.bazel
This PR got significantly bigger than expected over time – please let me know if you find it difficult to review or have additional questions.
Changes:
- Set rust flags in the host configuration (used for e.g. rust build scripts, running param_extractor, but not for the actual workerd binary). This should save some time and make the bazel output directory smaller.
- Add a TODO message about flags that could disk space improvements. Expected savings are relatively small (~300K), so this is not worth prioritizing.
- Windows: Remove warning 4503, this is no longer being used since MSVC 2017. https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4503?view=msvc-170
- Enable the MSVC flags `/DWINDOWS_LEAN_AND_MEAN` and …
=> Bazel linker improvements and cleanup

src/workerd/api/actor.c++, src/workerd/io/io-context.h
Modify actor channel setup to let `getActor` tracing spans appear nested under `actor_subrequest` spans, instead of under the context's "current" span
This change does have the side effect of skipping the lazy actor stub initialization if an intervening step of the fetcher setup fails (e.g. when the worker is over request limits), but I think this is unlikely to have user-visible behavior, and may in fact be desirable, in that it avoids unnecessary `getActor()` calls.
=> Nest getActor tracing spans under "actor_subrequest" spans

BUILD.bazel, WORKSPACE, build/BUILD.dawn, build/kj_test.bzl, build/run_binary_target.bzl, build/wd_cc_binary.bzl, build/wd_test.bzl, build/wd_ts_type_test.bzl, rust-deps/BUILD.bazel, src/workerd/api/BUILD.bazel, src/workerd/io/BUILD.bazel, src/workerd/jsg/BUILD.bazel, src/workerd/server/BUILD.bazel, src/workerd/tests/BUILD.bazel, src/workerd/tools/BUILD.bazel, src/workerd/util/BUILD.bazel, types/BUILD.bazel
This largely reorders statements to fix lint messages in VSCode, behavior is not affected.
=> [nfc] Lint bazel files using buildifier

.github/workflows/npm-types.yml, .github/workflows/npm.yml, .github/workflows/release.yml, .github/workflows/test.yml
The potential cache issue mentioned in #980 does end up happening and on a larger scale than expected: Unfortunately, bazel ends up with a significantly larger cache after running, causing caches to grow unacceptably big over several cycles of creating a new cache entry based on an old cache entry. For example, the Linux release cache is ~300MB when generated from scratch, but the cache using the key `bazel-disk-cache-release-Linux-X64-e28f1163e74e6d1aedb49ec825177f2daa557137cdcce3a89271b392de3df1d4` is 2.5 GB large. This causes CI runners to take a long time downloading/uploading the cache data, which is the opposite of what cache reuse is intended to do.
=> [CI] Do not allow stale cache to be used

src/workerd/io/io-context.h
I'm not sure how just these got messed up without any of the other template declarations in the file being similarly affected, but these are the only ones I noticed. I haven't checked any other files for something similar.
Looks like these got affected by the comment cleanup in d3f25fc1e6f073155ee6bf5c7656c153f241be80
=> Clean up the line placement of some template declarations in io-context

.github/workflows/release.yml, .github/workflows/test.yml
The Github CI images now include LLVM 16.0.6 by default as of https://github.com/actions/runner-images/commit/4a0c3808de19abe49a8cbdbfe8254ae92ed026e5. We should also be able to remove the bazel workaround soon (https://github.com/bazelbuild/bazel/issues/19035)
=> [CI] Partially remove Windows workaround

src/workerd/io/io-context.c++, src/workerd/io/io-context.h
Reminder: the promise context tag is the mechanism I added to v8 to allow us to do cross-request i/o awaits
=> JSG Completion: use JsObject for promise context tag

src/workerd/io/compatibility-date.capnp
Hey! 👋 We'd like to do pre-releases of Miniflare & Wrangler including #1129. For this, we'll need a `workerd` release. Ideally, this would be a pre-release too. Our CI is setup to do pre-release npm publishes, but not GitHub pre-releases. With this in mind, I suggest we just do a regular `workerd` release, so our Git tags/GitHub releases/npm releases all stay in sync. Miniflare & Wrangler's `workerd` dependency is pinned, so they won't pick up this new release automatically. 👍
=> Bump compatibility date to `2023-09-08` for release

src/workerd/server/server.c++
An extra `"` snuck into #1127, leading to invalid JSON being logged. Ooops!
=> Remove extraneous `"` from `listen-inspector` control message

src/workerd/io/actor-cache-test.c++, src/workerd/io/actor-cache.c++, src/workerd/io/actor-cache.h
This reverts commit 3a49006467148ee4eba469f3d84e7dbf67491661, reversing changes made to 812f78b6073c2586672269016c8c2fb0a4bb4014.
=> Revert "Merge pull request #1033 from cloudflare/bcaimano/actor-cache-no-state

src/workerd/api/encoding.h
Hey! 👋  This PR fixes the auto-generated return type of `TextEncoder#encode()`. https://github.com/cloudflare/workerd/pull/1047 updated this function to return a `jsg::BufferSource`. This generates `ArrayBuffer | ArrayBufferView` as the TypeScript type, as `jsg::BufferSource` [retains the input type when passed back out to JavaScript](https://github.com/cloudflare/workerd/blob/main/src/workerd/jsg/README.md#typedarrays-kjarraykjbyte-and-jsgbuffersource). `TextEnoder::encode()` uses `BufferSource::tryAlloc()` though which always gives a `Uint8Array`: https://github.com/cloudflare/workerd/blob/2182afdd8ca9ac35fb18b76205308fabd5000d01/src/workerd/jsg/buffersource.c%2B%2B#L89
Therefore, an override has been added to force a `Uint8Array` return type as required by [the …
=> Fix generated `TextEncoder#encode()` return type

src/workerd/api/web-socket.c++, src/workerd/jsg/buffersource.h, src/workerd/jsg/jsg.h
MessageEvent.data should be an `ArrayBuffer` if the data is bytes. The recent JsValue conversion accidentally changed it to `Uint8Array`.
=> Fixup MessageEvent.data regression

src/workerd/api/streams/internal.c++
Also took the opportunity to optimize just a bit.
=> Coroutines Conversion: update api/streams/internal.c++

src/workerd/api/gpu/gpu-adapter.c++, src/workerd/api/gpu/gpu-bindgroup-layout.c++, src/workerd/api/gpu/gpu-bindgroup.c++, src/workerd/api/gpu/gpu-command-encoder.c++, src/workerd/api/gpu/gpu-compute-pass-encoder.c++, src/workerd/api/gpu/gpu-device.c++, src/workerd/api/gpu/gpu-queue.c++, src/workerd/api/gpu/gpu-supported-features.c++, src/workerd/api/gpu/gpu-utils.c++, src/workerd/api/gpu/gpu.c++
KJ_IF_MAYBE is being replaced with KJ_IF_SOME and kj::none
=> Update api/gpu to use KJ_IF_SOME

src/workerd/api/tests/abortsignal-test.js, src/workerd/api/tests/abortsignal-test.wd-test, src/workerd/api/tests/encoding-test.js, src/workerd/api/tests/encoding-test.wd-test, src/workerd/api/tests/events-test.js, src/workerd/api/tests/events-test.wd-test, src/workerd/api/tests/scheduler-test.js, src/workerd/api/tests/scheduler-test.wd-test
Kicking off a process of porting internal tests over into workerd with a lot of restructuring and converage improvements along the way. This starts with `Event` and `EventTarget`
=> Add wd-test unit tests for Event, EventTarget, AbortSignal, and others

WORKSPACE, patches/v8/0001-Allow-manually-setting-ValueDeserializer-format-vers.patch, patches/v8/0002-Allow-manually-setting-ValueSerializer-format-versio.patch, patches/v8/0003-Make-icudata-target-public.patch, patches/v8/0004-Add-ArrayBuffer-MaybeNew.patch, patches/v8/0005-Allow-Windows-builds-under-Bazel.patch, patches/v8/0006-Disable-bazel-whole-archive-build.patch, patches/v8/0007-Make-v8-Locker-automatically-call-isolate-Enter.patch, patches/v8/0008-Add-an-API-to-capture-and-restore-the-cage-base-poin.patch, patches/v8/0009-Speed-up-V8-bazel-build-by-always-using-target-cfg.patch, patches/v8/0010-Implement-Promise-Context-Tagging.patch, patches/v8/0011-Enable-V8-shared-linkage.patch, patches/v8/0012-Fix-ICU-build.patch, patches/v8/0013-Randomize-the-initial-ExecutionContextId-used-by-the.patch
This is to help the devtools sources inspector detect when workerd has been restarted by miniflare.
Discussed in https://chat.google.com/room/AAAAnS2bXT4/GX5-pa8O0ts
=> Randomize the initial value of V8 Inspectors's ExecutionContextId

src/workerd/io/actor-cache-test.c++, src/workerd/io/actor-cache.c++, src/workerd/io/actor-cache.h
We were accidentally invalidating the lru list by removing the UNKNOWN entry that marks the end of a list when the previous entry was evicted. This PR adds a test for that case and a fix. This PR also does the KJ_IF_SOME/kj::none conversion for the actor cache code.
=> Reapply track value category, staleness, and sync state separately for ActorCache::Entries with bugfix

.bazelrc, src/workerd/io/compatibility-date.capnp
Hey! 👋 This PR bumps the compatibility date for release as usual, but disables WebGPU temporarily. See internal discussions for why we're doing this.
=> Bump compatibility date to `2023-09-14` for release

src/workerd/api/sockets.c++, src/workerd/api/streams/internal.c++
For all I know it has to be this way for compatibility reasons, but I have to say it confused me when I saw `undefined` getting thrown during some tests I was running, so I'm sending this out in case it wasn't intentional.
The error message was chosen to be analogous to what's used by ReadableStreamInternalController::doCancel ("Stream was cancelled."), but I'm not at all attached to it.
For clarity, I ran into this case due to Socket::handleProxyStatus calling `writable->getController().abort(js, nullptr)`. If for some reason this isn't something we want to add to the WritableStream implementation, I'll go ahead and change that call point instead.
=> Improve the Error thrown by a Socket's WritableStream after closure

src/workerd/io/actor-cache.h
This set of three methods had been grouped together, with a single comment under them applying to all three. d3f25fc1e6f073155ee6bf5c7656c153f241be80 broke apart the group and placed the comment so it appears to apply only to the third method.
I'm not sure if there may have been more instances like this around the codebase. I just happened to see this.
=> Fix comment conversion in actor-cache.h.

src/workerd/api/streams/common.h, src/workerd/api/streams/compression.c++, src/workerd/api/streams/internal.c++, src/workerd/api/streams/readable.c++, src/workerd/api/streams/standard.c++, src/workerd/api/streams/standard.h, src/workerd/api/streams/transform.c++, src/workerd/api/streams/writable.c++
Finishes off workerd/api/streams
=> More KJ_IF_SOME changes to workerd/api/streams

patches/v8/0013-Randomize-the-initial-ExecutionContextId-used-by-the.patch
Avoid a Smi range exception when picking a random initial executionContextId.
Not a fix for #1201, but discovered looking into the problem.
Bug: 🐛 Bug Report — `workerd` sometimes doesn't send `Debugger.scriptParsed` events #1201
=> Fix initial executionContextId range

src/cloudflare/internal/vectorize.d.ts, types/defines/vectorize.d.ts
This list will grow fairly rapidly over time. As this list is only used in a GET-like readonly capacity, using a generic string is okay without sacrificing much in the way of user DX.
=> VS-18: make Vectorize index preset a generic string

src/workerd/io/worker.c++
This change adds a 300ms pause before workerd starts sending out messages when a CDP client attaches. Some clients seem to lose track of the first few messages if they are sent right away.
Bug: #1201
Test: manual
=> Pause before initial burst of inspector messages

src/cloudflare/internal/test/vectorize/vectorize-api-test.js, src/cloudflare/internal/test/vectorize/vectorize-mock.js, src/cloudflare/internal/vectorize-api.ts
Previously the detailed error was always caught by the outer try/catch.
=> VS-46 Throw detailed errors properly

src/workerd/io/worker.c++
This reverts commit bdb7eb7fb82542b1805287f0dc4e880bbe0bf4cf.
This turned out not to be a factor in the underlying problem in #1201.
Bug: https://github.com/cloudflare/workerd/issues/1201
=> Revert "Pause before initial burst of inspector messages"

src/workerd/api/system-streams.c++
=> Move workerd/api/system-streams.c++ to KJ_IF_SOME

src/node/internal/crypto_random.ts
In trying to test some random numbers using a DO, I found that I could only get 1024 values. Looking into the workerd [implementation](https://github.com/cloudflare/workerd/blob/01001ba62e7aed632ffc9c3356f361a6cd608f40/src/node/internal/crypto_random.ts#L157) of randomInt compared to the Node [version](https://github.com/tniessen/node/blob/2cdb569a72db2d4b86685a43612c3269194eca42/lib/internal/crypto/random.js), this is almost certainly because values are being drawn from a 6 * 1024 size buffer which can never be replenished (unlike the node version).
A subtle difference between the two implementations is that the while loop for generating the integer in the Node implementation is true when either isSync or (randomCacheOffset < randomCache.length) is true, which means it is possible to …
=> Fix randomInt 1024 number generation limit

src/workerd/api/crypto.c++, src/workerd/api/global-scope.c++, src/workerd/io/actor-cache-test.c++, src/workerd/io/hibernation-manager.c++, src/workerd/io/io-gate-test.c++, src/workerd/server/server.c++
I found these by grabbing the changes from https://github.com/capnproto/capnproto/pull/1810, which makes the compiler warn about dropped promises.
=> Fix various dropped promises

src/workerd/io/actor-cache-test.c++, src/workerd/io/io-context.c++, src/workerd/io/promise-wrapper.h, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker.c++
Bug: EW-7618
Test: bazel build //...
=> Additional nullptr -> kj::none in src/workerd/io

src/workerd/api/BUILD.bazel, src/workerd/api/html-rewriter.h, src/workerd/io/BUILD.bazel, src/workerd/jsg/BUILD.bazel, src/workerd/server/BUILD.bazel, src/workerd/tools/BUILD.bazel
This allows us to avoid superfluous linker includes, for example the rust-deps library no longer need to be parsed for most api tests.
Full description to follow.
=> [nfc] Refactor bazel dependencies

src/workerd/tests/test-fixture-test.c++, src/workerd/tests/test-fixture.c++, src/workerd/tests/test-fixture.h
The utility methods are unused in workerd other than to test themselves.
Removing this removes a number of direct uses of v8 apis in the code that just appear to be unnecessary.
In the internal equivalent the `compileAndRunScript` utility is also unused and can safely be removed.
An argument can be made to keep `compileAndInstantiateModule` since internally that is used in a handful of fuzzing tests but it's not clear if those will ever be ported out to workerd and the internal `test-fixture` impl has it's own copy of `compileAndInstantiateModule`. Removing this in a separate commit here so that, if necessary, we can revert removing `compileAndInstantiateModule` separately if necessary.
=> Remove test fixture compileAndRunScript and compileAndInstantiateModule

src/workerd/api/gpu/gpu-adapter.c++, src/workerd/api/gpu/gpu-device.c++, src/workerd/api/gpu/webgpu-errors-test.js
Don't attempt to deference the first element of an empty array.
=> webgpu: check for empty features list

.github/workflows/test.yml
During setup put the appropriate path for llvm-symbolizer into `.bazelrc` for Linux and macOS.
Bug: https://github.com/cloudflare/workerd/issues/1247
=> Enable for llvm-symbolizer for GitHub test workflow

src/workerd/api/streams/standard.c++
When pumping from a JavaScript-backed stream to a WritableStreamSink, we want to ensure that small reads are accumulated into larger chunks to prevent a large number of small writes on the sink.
Partially addresses: https://github.com/cloudflare/workerd/issues/1235
=> Accumulate reads in streams PumpToReader

src/workerd/api/basics.c++, src/workerd/api/basics.h
Fixes: https://github.com/cloudflare/workerd/issues/1020
Previously, `AbortSignal.timeout()` would cause the `AbortSignal` to trigger with an exception not marked as `DISCONNECTED`. This would mean that when the signal is used to cancel, for instance, a fetch POST, the exception passed on via the internal canceler would end up being logged as an uncaught exception as reported in the github issue. This commit updates things such that AbortSignal.timeout properly reports a `DISCONNECTED` kj::Exception when the timeout fires. It also makes that path slightly more efficient by avoiding an extraneous kj::Exception->JS exception->kj::Exception round trip.
=> AbortSignal.timeout inner exception should be DISCONNECTED

src/workerd/api/global-scope.c++
This span is specifically for the exported fetch handler.
=> Add span to fetch handler

src/workerd/api/basics.c++, src/workerd/api/basics.h, src/workerd/api/global-scope.h, src/workerd/api/tests/events-test.js
`CustomEvent`  is a Web platform standard API that is also supported by other WinterCG-compat runtimes (e.g., Node.js, Deno, etc). It is defined by DOM (https://dom.spec.whatwg.org/#interface-customevent) and is in fairly common use (https://github.com/search?type=code&q=new+CustomEvent+language%3AJavaScript&l=JavaScript). This PR just makes the API available for use within Workers.
=> Implement the Web Platform standard CustomEvent

src/workerd/api/crypto-impl-aes.c++, src/workerd/api/crypto-impl-asymmetric-test.js, src/workerd/api/crypto-impl-asymmetric-test.wd-test, src/workerd/api/crypto-impl-asymmetric.c++, src/workerd/api/crypto-impl-hkdf.c++, src/workerd/api/crypto-impl-hmac.c++, src/workerd/api/crypto-impl-pbkdf2.c++, src/workerd/api/crypto-impl.h, src/workerd/api/crypto.c++, src/workerd/api/crypto.h, src/workerd/api/node/crypto-keys.c++, src/workerd/io/compatibility-date.capnp
This addresses #48 and refactors the `EdDsaKey` class. 
- In terms of refactoring, we can combine the EdDsaKey and EdDsaCurveKey classes as they are largely identical, the subtle difference in the naming of the algorithm field can be handled in getAlgorithm() alone.
- For the issue I primarily changed the clone() method of RsaKeyAlgorithm to return the correct type for publicExponent instead of making more invasive changes, this should minimize the risk of introducing bugs. The change is behind the new `cryptoPreservePublicExponent` compat flag, the other changes are for adding a test and introducing additional scaffolding
- Some additional questions regarding potential refactoring came up while reviewing the code to look for any other situations where we might be returning the wrong …
=> Webcrypto refactor, fix type of publicExponent

src/workerd/api/trace.c++, src/workerd/api/trace.h, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/worker-interface.capnp
This adds a new TraceItem::EventType union member - TraceEventInfo. This allows event info for invocations of a trace or tail worker to show up when tailing it (i.e. attaching a tail to a tail worker).
TraceEventInfo only contains an array "traces" of objects with a single "scriptName", i.e. the script that the script _you're_ tracing was tracing. There's hypothetically more that could be included on these items, but any sort of recursive could ballon the size of these events or even get into circular references, so it's kept simple for now.
=> Add TraceEventInfo for TraceItem

.vscode/launch.json, .vscode/tasks.json
- refresh the list of wd-tests to match those currently available.
- provide tests with a path for TEST_TMPDIR which allows previously blocked tests to run.
=> Updates to launch.json

.bazelrc, tools/windows/create-external.bat
clang-cl has a different syntax for specifying the C++ standard version so was rejecting the fix added in #1184 for the DCHECK in V8's graph-visualizer.cc that needs C++20. V8 DCHECKs are enabled for dbg builds. This is fixed in .bazelrc.
To add to my own confusion when looking into this issue, the junction we create in the workspace folder, `external`, was stable. The junction is created to make it easy to find sources to downloaded dependencies and also to help VSCode find the right sources when bazel build emits compilation errors. Unfortunately, the junction was stale locally so following the error links reported in VSCode went to an old version of V8 on the disk with entirely different code that could not possibly have caused the error observed. As a result, the script that creates …
=> Fix the dbg config on Windows

.bazelrc, .github/workflows/test.yml
Enabling webgpu added a common option that is not supported by `bazel shutdown` resulting in:
ERROR: Unrecognized arguments: --//src/workerd/io:enable_experimental_webgpu=True
This change moves the webgpu config from `bazel common` to `bazel build` and adds a check to the github test workflow to avoid similar issues in future.
Test: manual invocation of webgpu tests continues to work, e.g.
bazel-bin/src/workerd/server/workerd test                       \
`realpath src/workerd/api/gpu/webgpu-buffer-test.gpu-wd-test` \
--verbose --experimental
=> Unbreak `bazel shutdown`

src/workerd/jsg/util.h
Necessary for compatibility with this capnp change: https://github.com/capnproto/capnproto/pull/1800/files
=> JSExceptionThrown noexcept default

src/workerd/util/sqlite.c++
This PR sets the maximum expression depth to 100 as an intermediate measure, accepting that it may not unblock every user.
Background: We're seeing developers (particularly those using ORMs) run into limitations when running queries against D1. It is not clear from an EQP (EXPLAIN QUERY PLAN) output what the expression depth of a query is, which makes it challenging to set this to a value that works for users without being unnecessarily high — the deeper the expression depth the more likely the query to just run into other limits.
For context:
* The SQLite default is 1000.
* Our current is 20
* The "Dark Arts" suggested value was 10 (https://www.sqlite.org/security.html)
Fixes [#4094](https://github.com/cloudflare/workers-sdk/issues/4094)
=> SQL: increase EXPR_DEPTH from 20 -> 100

src/workerd/server/server-test.c++, src/workerd/server/server.c++, src/workerd/server/server.h, src/workerd/server/workerd.capnp
This behavior has been present in production for a while. Durable Objects with Hibernatable WebSockets should now be able to hibernate when using Wrangler or Miniflare.
Credit to Sam for adding the websocket test functions!
=> Evict actors after 10 sec inactivity in Workerd

src/workerd/io/actor-cache.c++
With this change, we won't spam logs when we have issues with our storage api servers. (These errors are generally obvious in metrics and other error logs.)
=> Cleanup: Only log interesting exceptions when an actor cache flush fails

src/workerd/api/hyperdrive.c++, src/workerd/api/hyperdrive.h, src/workerd/server/server-test.c++, src/workerd/server/server.c++, src/workerd/server/server.h, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h, src/workerd/server/workerd.capnp, src/workerd/tools/api-encoder.c++
Adda a new binding type `Hyperdrive` as well as a corresponding Service definition `ExternalTcpService` that allows TCP connections to the designated host address & port
=> Add Hyperdrive bindings

src/workerd/api/sockets.c++
Accidentally rejecting with a `nullptr` lead to exception being logged.
=> Fixes logspam in sockets (handleProxyError).

.github/workflows/issues.yml
Add an issues workflow that assigns issues labeled with `types` label to the [workers-sdk GH project](https://github.com/orgs/cloudflare/projects/1)
=> Add issues workflow

src/workerd/api/web-socket.c++
In #953 the behaivor of this function was accidentally changed to return the result of the pumpTo promise.
=> No longer return promise result in websocket couple()

src/workerd/jsg/BUILD.bazel, src/workerd/jsg/observer.h
This will allow us to compile some upstream targets without depending on V8, resulting in better link performance. Upstream PR to follow.
=> [nfc] Break JSG observer dependency on V8

src/workerd/api/actor-state.c++, src/workerd/api/web-socket.c++, src/workerd/api/web-socket.h, src/workerd/io/hibernation-manager.c++, src/workerd/io/hibernation-manager.h, src/workerd/io/worker.h
This PR fixes racing issues between regular websocket messages and auto-responses.
The initial version of this PR held a jsg::Ref<> for a long time, which could cause occasional segfaults. This new version fixes that segfault.
=> Fix websocket auto-response message races

.bazelrc, .github/workflows/release.yml, .github/workflows/test.yml, tools/unix/workspace-status.sh
Three commits here:
1. Adds new tests to the github test workflow:
* `debug` builds on Linux, macOS, and Windows
* `linux-asan`
Initially, the new test configurations are advisory and do not block PR submission.
For ASAN and debug builds, benchmark builds are skipped to free up disk space. The runners have a nominal 14GB of storage consumed by build files, the build cache, and the tarball of build cache when it is saved.
With more build configurations there is more pressure on the bazel cache. This PR avoids caching files larger than 100MB as the nominal limit is 10GB across all the workerd build combinations.
2. Fixes a warning on macOS (`workspace-status.sh` using non-existent `realpath`). Variable was unused so just deleted.
3. Configures git hooks to quell warnings from …
=> Add linux-asan and {linux,macOS,windows}-debug to the github test workflow

.github/workflows/test.yml
Accidentally dropped in a pre-merge rebase of #1283.
=> Add back "Configure download mirrors" step to test.tml

src/workerd/server/server-test.c++
A`KJ_IF_MAYBE` snuck in from PR that had started before the clean-up.
=> Replace a straggling KJ_IF_MAYBE with KJ_IF_SOME

src/workerd/api/tests/unsafe-test.js, src/workerd/api/tests/unsafe-test.wd-test, src/workerd/api/unsafe.c++, src/workerd/api/unsafe.h, src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h, src/workerd/server/server.c++, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h, src/workerd/server/workerd.capnp
This adds a new `UnsafeEval` binding APi that is intended only for use with workerd and only when the `--experimental` flag is specified. See the included test for an example on how to use it.
```js
console.log(env.unsafe.eval('1+1'));  // 2
const fn = env.unsafe.newFunction('return m', 'foo', 'm');
console.log(fn(1));  // 1
console.log(fn.name);  // foo
console.log(fn.length); // 1 argument
```
/cc @mrbbot @IgorMinar
=> Implement an `UnsafeEval` binding

src/workerd/api/crypto-impl-aes.c++, src/workerd/api/crypto-impl-hkdf.c++, src/workerd/api/crypto-impl-hmac.c++, src/workerd/api/crypto-impl-pbkdf2.c++, src/workerd/api/crypto-impl.c++, src/workerd/api/crypto-impl.h, src/workerd/api/node/crypto-keys.c++
For various `CryptoKey::Impl`s we use a `kj::Array<kj::byte>` internally to store the raw key data in memory. When these structures are freed, we really ought to be zeroing out that memory before returning it.
This, of course, does not fully guarantee that the all copies of the key data in memory are zeroed. If the CryptoKey is exported, for example, the exported copy may still exist. Rather, this just ensures that the internal storage used by the various `CryptoKey::Impl`s are zeroed out
=> Zero out raw key data when freed

src/workerd/io/worker.c++, src/workerd/util/color-util.h
Hey! 👋 This PR addresses a couple of issues from #1294 that we encountered when integrating this with Wrangler.
When spawning `workerd` from Node, we configure [`stdout` and `stderr` as `pipe`s](https://nodejs.org/api/child_process.html#optionsstdio), rather than inheriting stdio from the parent. This allows us to intercept output and explicitly log it with `console.log()` _(Wrangler uses a library called Ink for rendering its interface. Ink monkeypatches `console` methods so UI elements remain in the correct place after logging)_. Unfortunately, using `pipe` requires explicit flushes on `stdout`/`stderr` before data is delivered. Additionally, `pipe` isn't a TTY, so logs would never use colour. This PR adds explicit flushes, and always logs in colour when the `FORCE_COLOR` environment …
=> Fix Node-like `console.log()`ing when spawning from Node

.bazelrc, build/BUILD.dawn
We have ~500 warnings on Windows CI runs, this should fix most of them.
- We need to redefine `_WIN32_WINNT` to have DirectX12 available when building dawn (unlike WIN32_LEAN_AND_MEAN, which is already defined in .bazelrc). Disable `-Wmacro-redefined` when building dawn on Windows.
- Adjust zlib warning settings since some workarounds are no longer needed with version 1.3, but there is also a new warning in newer clang/LLVM versions
=> Clean up warnings on Windows/with LLVM16

src/workerd/api/gpu/gpu-bindgroup-layout.c++, src/workerd/api/gpu/gpu-compute-pass-encoder.c++, src/workerd/api/gpu/gpu-device.c++, src/workerd/api/gpu/gpu-utils.c++, src/workerd/api/gpu/gpu-utils.h, src/workerd/api/gpu/webgpu-windowless-test.js
- Rely on Dawn defaults instead of having them in workerd code
- Finished work on parsing RenderPipelineDescriptor.
- Since the above descriptor is parsed on a separate function, we can't rely on stack variables being in scope, so we use an auxiliar object to maintain ownership of allocated objects until we can free them after the Dawn call.
=> webgpu: implement more api objects related to rendering

.github/workflows/test.yml, src/workerd/jsg/string-test.c++
The windows-debug config exposed a UAF for the `testUsvPtr()` test in
the `KJ_TEST("JavaScript USVStrings")` since the debug build on Windows
overwrites freed memory which shows up as corruption if used after
free. The issue is described in #1334.
Fix: https://github.com/cloudflare/workerd/issues/1334
Test: `bazel test -c dbg --cache_test_results=no //...`
=> Enable windows-debug github runner

src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/tests/navigator-beacon-test.js, src/workerd/api/tests/navigator-beacon-test.wd-test
A POC simplistic implementation of the standard `navigator.sendBeacon()` API -- https://www.w3.org/TR/beacon/#sendbeacon-method
`navigator.sendBeacon()` is essentially a simplified fire-and-forget POST request that eliminates a fair amount of boilerplate that is necessary when using fetch. For example, within a request:
```js
const promise = fetch('https://example.com', { method: 'POST', body: 'hello world' });
ctx.waitUntil(promise);
```
Can be replaced with simply:
```js
navigator.sendBeacon('https://example.com', 'hello world');
```
This implementation uses the global fetch (and therefore configured 'internet' service). Similar implementation could be added to any `Fetcher`, however, allowing this pattern to be used with bindings also. However, this PR just sticks with the standardized …
=> Implement navigator.sendBeacon

samples/extensions/README.md
I found the example code great, but as there are a few very similarly named files for the extension sample with two different ways of using the burrito-shop, it wasn't clear without a deep look into exactly what was happening or why specific things were defined as they were. 
As such, I put my thoughts into a README.md so the next person doesn't have to build the same mental model from scratch.
Ideally I'd have split this into two different samples, with one being the environment binding and another being the imported module, but I choose to use this as a stepping stone since it's my first PR.
=> Revised the extension sample README.md

.github/CODEOWNERS
Following the agreed ownership boundaries from https://wiki.cfdata.org/display/WX/Ownership, this ensures that the Wrangler team is able to release `workerd` and `workers-types` to `npm` without requiring approval from the runtime or durable objects teams
=> Add `wrangler` team to CODEOWNERS

.github/workflows/test.yml, build/wd_cc_benchmark.bzl
We already use shared linkage for tests – `cc_test` uses shared linkage by default. This allows us to compile benchmark binaries for CI debug/ASAN builds, which would otherwise be prohibitively large.
=> Use shared linkage for benchmarks

src/workerd/jsg/observer.h, src/workerd/jsg/util.c++
This is a quick POC for a request from @bcaimano for how to make it easier to collect metrics for certain kinds of internal exceptions. This PR may not be complete or may change significantly so keeping it as a draft for now.
=> Extends `IsolateObserver` to include reporting of internal exceptions

.bazelrc
This option is not supported by clang-cl.exe which we use on Windows.
=> Only use -gsimple-template-names with clang

src/workerd/api/BUILD.bazel, src/workerd/api/actor-state-iocontext-test.c++, src/workerd/api/actor-state.c++, src/workerd/server/server.c++, src/workerd/server/server.h, src/workerd/tests/bench-global-scope.c++, src/workerd/tests/bench-regex.c++, src/workerd/tests/test-fixture.c++, src/workerd/tests/test-fixture.h
When V8 deserialization fails, it’s likely due to corruption somewhere
between the Actor in JS and the storage layer.  In order to aid
debugging, log the actor id if we know of one.
=> Log Actor ID on V8 deserialization errors

.github/workflows/cla.yml, .github/workflows/npm.yml, .github/workflows/release.yml, WORKSPACE
See details in the commit descriptions. Note: This removes esbuild which appears to be unused but might be useful for future JS/TS work, feel free to add it back if needed or lmk if you want to keep it.
=> Assorted CI dependency cleanup

src/workerd/server/server.c++
Hey! 👋 https://github.com/cloudflare/workerd/pull/1294 broke `console.log()`ing in local development for service workers. It looks like this fix for this might be slightly more involved than initially expected. While we work on a permanent solution, this PR reverts the change if service workers are used. In Wrangler, we can re-enable inspector style logging if we detect the bundle is a service worker.
Ref: https://github.com/cloudflare/workerd/issues/1362
=> Temporarily disable Node-style logging for service workers

npm/scripts/build-shim-package.mjs
Include the `workerd.capnp` file in the `workerd` npm package for downstream consumption in Miniflare
=> Vendor workerd.capnp in NPM package

WORKSPACE, package.json, pnpm-lock.yaml, src/node/tsconfig.json
Updates aspect_rules_js, aspect_rules_ts and Node.js versions in several spots. As I understand these are primarily used for generating types, testing and linting, but please lmk if you have any concerns about breakage here.
=> Update Node version

.github/workflows/npm-types.yml, .github/workflows/npm.yml, .github/workflows/release.yml
#1378 broke some of our GitHub actions release workflows. This change updates them to refer to `supported-compatibility-date.txt` directly, rather than using the `capnp` tool to extract it.
=> Use `supported-compatibility-date.txt` in release workflows

src/workerd/server/server.c++
Recent Chrome builds are supplying a `for_tab` argument to `/json/list`. Simply recognizing this pattern appears to enable `chrome://inspect` to work again. Unable to find any docs or info relating to this seemingly new argument.
Fix: https://github.com/cloudflare/workerd/issues/1388
=> Unbreak chrome://inspect for workerd

.github/workflows/release.yml
Hey! 👋 This PR updates `workerd`'s release workflow to run Miniflare's tests on every PR. If these fail, a message will be sent to chat, but the job won't fail. This is meant to be an early warning to us that we need to make Miniflare changes when the next `workerd` release happens. We'll need to add a `MINIFLARE_TEST_WEBHOOK` secret to this repository before merging this PR.
Closes DEVX-1003
=> Run Miniflare tests on PR merge

src/workerd/api/streams/compression.c++
found by fuzzer and new asan from clang-16
=> streams: fix container overflow

RELEASE.md
We've recently made some changes to the `workerd` release process to make everything a little easier. This PR updates the release instructions, taking into account these new changes.
=> Update `RELEASE.md` with `supported-compatibility-date.txt` file and information on internal runners

README.md
Changes to how `workerd` builds SQLite require Tcl 8.6 on the system.
Notes made for Linux and macOS. macOS appears to have Tcl 8.5
installed by default, but this is not adequate to build `workerd`.
For Windows, Tcl is installed and used from `msys64` so no explicit
action is required at present.
=> Update README.md with Tcl dependency

types/defines/d1.d.ts
Hi :wave:
The published types for `D1Result` currently have meta defined as any, and error defined as never:
https://github.com/cloudflare/workerd/blob/713d9824a4cbc988d6a622813a3087b6a894650f/types/defines/d1.d.ts#L1-L6
This PR aims to clean them up, based on the binding types:
https://github.com/cloudflare/workerd/blob/713d9824a4cbc988d6a622813a3087b6a894650f/src/cloudflare/internal/d1-api.ts#L9-L14
the binding mapper function:
https://github.com/cloudflare/workerd/blob/713d9824a4cbc988d6a622813a3087b6a894650f/src/cloudflare/internal/d1-api.ts#L302-L316
the client API docs:
https://developers.cloudflare.com/d1/platform/client-api/#return-object
and Q5 in the pricing FAQ:
https://developers.cloudflare.com/d1/platform/pricing/#frequently-asked-questions
cc @geelen and @mrbbot per `git …
=> Add type for D1Result meta

src/workerd/api/trace.c++, src/workerd/api/util.c++, src/workerd/jsg/exception.c++, src/workerd/tests/test-fixture.c++
This series of commits replaces uses of strstr with StringPtr::contains.
There's still 1 place where workerd uses strstr, but that's doing index arithmetic and I'll fix it in a follow-up PR.
=> Replace strstr with StringPtr::contains

src/workerd/jsg/exception.c++
StringPtr::find provides the same functionality as strstr, but with a kj API.
This is the last use of strstr in workerd.
=> Replace strstr with StringPtr::find

src/workerd/api/tests/unsafe-test.js, src/workerd/api/unsafe.c++, src/workerd/api/unsafe.h
A variation on unsafe.newFunction that returns an async function allowing internal use of await
Only impacts workerd/local-dev.
=> Implement unsafe.newAsyncFunction for unsafe eval binding

src/workerd/io/BUILD.bazel, src/workerd/io/compatibility-date.capnp, src/workerd/io/compatibility-date.h, src/workerd/io/supported-compatibility-date.capnp, src/workerd/server/workerd.c++
Some external systems vendor compatibility-date.capnp without running workerd's build process. This fixes issues with that vendoring process that arose in https://github.com/cloudflare/workerd/commit/e1e67c38d449bc3f4b3c870a36c17776890e6474#diff-025905f76d1858e597340d2c52fcd507c5928fedf61392257cbb22197175d5e7 by factoring out the generated supportedCompatibilityDate text from the static CompatibilityFlags struct.
=> Refactor out supportedCompatibilityDate

.github/workflows/npm-types.yml
Hi :wave:
I was wondering why renovate wasn't screaming at me to update workers-types after the release yesterday, turns out that it was released under 1.x.
This PR should fix that and use 4.x which is the latest currently.
Also noticed by @phanect in #1430.
cc @mrbbot
=> Fix workers-types release version

src/workerd/api/streams/internal.c++, src/workerd/api/streams/internal.h
The maybeClosureWaitable can only have then(...) called on it once. Use whenResolved() to support multiple branches.
=> Fix multiple waits on maybeClosureWaitable

src/workerd/io/worker.c++
Hey! 👋 With https://github.com/cloudflare/workerd/pull/1294, `console.log()`s are now logged directly to stdio when running locally. This means Wrangler no longer uses the V8 inspector to receive log messages. Unfortunately, this means we're were missing out on some warnings from `workerd`. This change logs those warnings directly to `stderr` too if we're running locally.
Ref: cloudflare/workers-sdk#4512
=> Log warnings directly to `stderr` locally

src/workerd/io/request-tracker.h, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker-entrypoint.h, src/workerd/io/worker-interface.c++, src/workerd/io/worker-interface.h, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++
No functional changes here. Just cleaning up headers a bit by moving a couple of class definitions out of the header and into the c++ they are used. Plus removing a couple of unnecessary symbol definitions.
=> Cleanup a handful of workerd/io headers

src/workerd/api/crypto-impl-aes-test.c++, src/workerd/api/urlpattern.c++, src/workerd/io/compatibility-date.c++
I know that we plan to replace the existing URL parsing implementation soon, but fixing undefined behavior here felt like a quick win.
Credit for discovering the missing parser check goes to Martin Schwarzl.
=> Fix ubsan warnings, apply additional hardening for Date parsing

.bazelrc, WORKSPACE, patches/v8/0001-Allow-manually-setting-ValueDeserializer-format-vers.patch, patches/v8/0002-Allow-manually-setting-ValueSerializer-format-versio.patch, patches/v8/0003-Make-icudata-target-public.patch, patches/v8/0004-Add-ArrayBuffer-MaybeNew.patch, patches/v8/0005-Allow-Windows-builds-under-Bazel.patch, patches/v8/0006-Disable-bazel-whole-archive-build.patch, patches/v8/0007-Make-v8-Locker-automatically-call-isolate-Enter.patch, patches/v8/0008-Add-an-API-to-capture-and-restore-the-cage-base-poin.patch, patches/v8/0009-Speed-up-V8-bazel-build-by-always-using-target-cfg.patch, patches/v8/0010-Implement-Promise-Context-Tagging.patch, patches/v8/0011-Enable-V8-shared-linkage.patch, patches/v8/0012-Fix-V8-ICU-build.patch, patches/v8/0013-Randomize-the-initial-ExecutionContextId-used-by-the.patch
This requires defining `V8_EXTERNAL_CODE_SPACE` for V8's mksnapshot build tool to not crash based on https://bugs.chromium.org/p/v8/issues/detail?id=14486. While this changes how V8 is compiled, it should be a benign change as V8_EXTERNAL_CODE_SPACE is enabled in GN (V8's default build system) by default, bringing the bazel build closer to the reference builds that receive more extensive testing.
Few changes are needed otherwise, patches are unchanged except for `0010-Implement-Promise-Context-Tagging.patch` which needed to be updated based on increased usage of `Tagged<>` in the codebase.
=> Update to V8 12.0

src/workerd/api/streams/standard.c++, src/workerd/api/streams/standard.h, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/util/weak-refs.h
We had multiple WeakRef impls that were nearly identical. Consolidate those to reduce duplication.
=> Consolidate multiple defs/impls of WeakRef

src/workerd/api/rtti.c++, src/workerd/io/compatibility-date-test.c++, src/workerd/io/observer.h, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/tools/api-encoder.c++, src/workerd/util/thread-scopes.c++, src/workerd/util/thread-scopes.h
More work towards cleaning up the workerd public API surface
* Move WarnAbourtIsolateLockScope out of worker.h into thread-scopes.h 
* Move TeardownFinishedGuard out of worker.h into observer.h
* Move AsyncWaiter definition out of worker.h into worker.c++ (it's only used in there)
* Eliminate duplicate `ValidatorErrorReporter` impls
* Make ConsoleModule an enum class.
=> Multiple minor worker.h related cleanups

src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker-entrypoint.h, src/workerd/io/worker-interface.c++, src/workerd/io/worker-interface.h, src/workerd/io/worker.c++, src/workerd/io/worker.h
Further simplification of worker.h
* Move the class definition in WorkerInterface alongside AlarmResult (with which it is closely related)
* Move the implementation in worker-interface.c++
=> Move AlarmFulfiller impl out of worker.h

src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker-entrypoint.h, src/workerd/io/worker.c++
~~Once~~ Now that the PR on the internal repo ~~lands~~ has landed replacing `WorkerEntrypoint::construct(...)` with `newWorkerEntrypoint(...)`, we can land this moving the definition of `WorkerEntrypoint` into the c++ file.
=> Move WorkerEntrypoint definition out of header

build/wd_js_bundle.bzl, build/wd_ts_bundle.bzl, src/workerd/jsg/modules.capnp, src/workerd/jsg/modules.h
Followup of #1402. We need data modules for Pyodide too.
Currently targeting the wasm-builtin branch pending that PR being merged.
No automated tests for this, but I've tested it manually on my branch that builds pyodide into workerd with bazel.
=> Allow builtin data modules

src/workerd/api/global-scope.h, src/workerd/api/gpu/gpu-async-runner.h, src/workerd/api/gpu/gpu-shader-module.c++, src/workerd/io/actor-cache-test.c++, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/io-gate.c++, src/workerd/io/io-gate.h, src/workerd/io/io-own.c++, src/workerd/io/io-own.h, src/workerd/io/io-thread-context.c++, src/workerd/io/io-thread-context.h, src/workerd/io/io-timers.c++, src/workerd/io/io-timers.h
Start pulling things out of io-content.h into separate headers/c++ ... generally make io-content.h smaller and more focused.
=> Decompose io-context.h/c++ into multiple headers/c++ files

build/BUILD.dawn
Add compile time flags, include only the needed tint header.
=> webgpu: tidy build script

src/workerd/api/crypto.c++, src/workerd/api/queue.c++, src/workerd/io/features.c++, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server.c++, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h, src/workerd/tests/test-fixture.c++, src/workerd/tests/test-fixture.h
Rename `Worker::ApiIsolate` to just `Worker::Api`... aliasing the old name along with a `[[deprecated]]` attribute until the internal repo can be updated to use the new name.
Renaming `ApiIsolate` has been a long standing todo since the `Isolate` name is rather overloaded.
=> Address long-standing todo to rename ApiIsolate

src/workerd/server/server.c++
An actor setting an alarm would start to fail after hibernation due to the `ActorKey` pointing to a `kj::StringPtr` that would be freed.
Fixes: https://github.com/cloudflare/workerd/issues/1386
=> Persist the actorId for ActorSqliteHooks

build/wd_js_bundle.bzl, build/wd_ts_bundle.bzl
Before this build, `wd_ts_bundle` has a bunch of logic for generating module specifiers, renaming modules, naming the capnp bundle, etc. This makes it problematic to use `wd_js_bundle` directly because ideally we'd want to exactly match the conventions in `wd_ts_bundle`.
So this fixes it by moving this logic into `wd_js_bundle`.
Split off from #1467 per @mikea's request.
=> Move logic from `wd_ts_bundle` to `wd_js_bundle`

WORKSPACE, build/perfetto/perfetto_cfg.bzl, compile_flags.txt, patches/perfetto/0001-Rename-ui-build-to-ui-build.sh-to-allow-bazel-build-.patch, src/workerd/api/global-scope.c++, src/workerd/io/BUILD.bazel, src/workerd/io/io-context.h, src/workerd/io/worker-entrypoint.c++, src/workerd/server/BUILD.bazel, src/workerd/server/server.c++, src/workerd/server/workerd-api.c++, src/workerd/server/workerd.c++, src/workerd/util/BUILD.bazel, src/workerd/util/perfetto-tracing.c++, src/workerd/util/perfetto-tracing.h, src/workerd/util/use-perfetto-categories.h
Adds a new `-p {file}={categories}` option to `workerd serve` and `workerd test` that will generate a perfetto trace at `{file}` with `{categories}` enabled. Currently will only capture trace events from workerd as there is currently no way to enable perfetto in v8 using v8's current bazel build. Enabling that will be a follow up step.
Example:
```
workerd serve -p /tmp/PERFETTO_TRACE=workerd /path/to/config.capnp
```
The PR also starts to add `TRACE_EVENT` instrumentation to various locations.
The Windows build is explicitly excluded from the party for now. Kept running into issues building perfetto on windows here and couldn't easily determine if it was the way I was calling the bazel build or if it's a problem with perfetto's own bazel build... and at the moment it's not worth the …
=> Experimental perfetto support for workerd

src/workerd/io/worker-entrypoint.c++, src/workerd/server/workerd-api.c++, src/workerd/util/perfetto-tracing.c++, src/workerd/util/perfetto-tracing.h
Fixes a minor bug in the workerd perfetto fd tracking and adds more spans to worker-entrypoint for illustration.
This starts to make use of custom tracks and flows to track activity through kj promises ...
=> More perfetto instrumentation and fixes

samples/module_fallback/README.md, samples/module_fallback/cjs.js, samples/module_fallback/config.capnp, samples/module_fallback/fallback.js, samples/module_fallback/worker.js, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/jsg/modules.c++, src/workerd/jsg/modules.h, src/workerd/jsg/resource.h, src/workerd/jsg/setup.h, src/workerd/server/server.c++, src/workerd/server/workerd-api.c++, src/workerd/server/workerd-api.h, src/workerd/server/workerd.capnp
Adds the ability to load modules lazily from a local http fallback service. The fallback service is a simple http server that returns the Worker::Module configuration for a module dynamically rather than embedded within the worker configuration. This is only usable for local dev. See samples/module_fallback for an example.
Not all modules will use the fallback service. In the worker configuration, a module has to be explicitly configured to use the fallback. Also, because of the nature of the ESM modules and the way v8 handles them, there really is no hot-module-reloading. Once a module is loaded for a worker it cannot be replaced without restarting the worker. Currently that's only possible by either shutting workerd down or using the `--watch` feature which watches for changes in the …
=> Implement experimental module fallback service for testing

src/workerd/api/trace.c++, src/workerd/api/trace.h, src/workerd/io/BUILD.bazel, src/workerd/io/script-version.capnp, src/workerd/io/trace.c++, src/workerd/io/trace.h, src/workerd/io/worker-interface.capnp
Follow up to https://github.com/cloudflare/workerd/pull/1445.
We have since decided that we want to expose additional fields (provisionally `tag` and `message`) associated with the script version. As such, we replace the string `scriptVersionId` field with a `scriptVersion` object in the JS API.
The API is not used yet so we don't need to worry about backwards compatibility here.
=> Replace scriptVersionId with scriptVersion object in worker trace events

src/cloudflare/internal/test/vectorize/vectorize-api-test.js, src/cloudflare/internal/test/vectorize/vectorize-mock.js, src/cloudflare/internal/vectorize.d.ts, types/defines/vectorize.d.ts
We're adding filtering support for Vectorize metadata when querying. For now, this is limited to basic equality checks, though we plan to expand on this work in the near future to allow for more operations.
This primarily just updates the types to account for the new option - we were already sending the full option object to the Vectorize binding so no actual logic changes to the binding are necessary.
=> [Vectorize] Update types to allow filtering metadata for equality

src/workerd/api/trace.c++, src/workerd/api/trace.h, src/workerd/io/script-version.capnp, src/workerd/util/uuid-test.c++, src/workerd/util/uuid.c++, src/workerd/util/uuid.h
We want to constrain the ID to be a UUID so let's enforce that constraint in the capnp interface.
=> Convert script version ID capnp representation to UUID.

src/workerd/api/modules.h, src/workerd/api/unsafe.c++, src/workerd/api/unsafe.h, src/workerd/io/compatibility-date.capnp, src/workerd/io/io-channels.h, src/workerd/io/io-context.h, src/workerd/server/server.c++, src/workerd/server/server.h, src/workerd/server/tests/unsafe-module/BUILD.bazel, src/workerd/server/tests/unsafe-module/unsafe-module-test.js, src/workerd/server/tests/unsafe-module/unsafe-module-test.wd-test
Hey! 👋 This PR implements a function for aborting all Durable Objects in the current `workerd` process, except those marked with `preventEviction`. We're currently porting Miniflare 2's Vitest unit testing environment to Miniflare 3, and would like a function like this for a couple of reasons:
1. Vitest ideally needs to reuse the same `workerd` process between test reruns. This is so it can retain its module cache and only rerun tests that have had their dependencies changed (effectively HMR for tests). The `workerd` process takes just about a second to startup and initialise Vitest too, so we don't really want to be doing this on each rerun. Even though we're reusing processes, we'd like each test rerun to execute in a clean environment, **including Durable Object in-memory state**. This …
=> Implement `abortAllDurableObjects()` function

src/workerd/api/global-scope.c++, src/workerd/api/trace.c++, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/util/uncaught-exception-source.h
The headers are generally cleaned up. Will be turning attention to splitting more of the v8::Inspector stuff out of the worker.c++ file.
=> Additional minor cleanups for worker.h

src/workerd/api/tests/actor-stub-test.js, src/workerd/api/tests/js-rpc-disabled.js, src/workerd/api/tests/js-rpc-disabled.wd-test, src/workerd/api/worker-rpc.c++, src/workerd/api/worker-rpc.h, src/workerd/io/compatibility-date.capnp, src/workerd/io/worker-interface.capnp, src/workerd/jsg/jsg.h, src/workerd/jsg/setup.h
As of opening this draft PR, I've added one method to the `Fetcher` (since we don't have a Proxy type yet) that:
1. Initiates a JS RPC "session" (for now behaves more like `getHttpService` in that we get a single-use capability that we use to call rpc)
2. Calls the remote method over rpc
3. Returns the result of the remote call to JS.
I'm opening this for initial review from @kentonv and @bcaimano because I want to clarify a few things about the "session" lifetime.
The demo method on `Fetcher` is called `getRpcAndCallRemote`. It takes a method name and optional args (note that args aren't supported yet).
Each time I call `stub.getRpcAndCallRemote("methodName")`, we go through the process of
1. Dispatching a `jsRpcService` event via customEvent, which gives us a capability (JsRpcTarget) we …
=> JS RPC for Durable Objects

.bazelrc, .github/workflows/release.yml, .github/workflows/test.yml, Dockerfile.release, README.md
Upgrade the build to LLVM 15 on macOS and Linux – this allows us to benefit from many compiler improvements and aligns the build closer to the versions used for Windows and for the upstream repository. On macOS, this is achieved by upgrading to the macOS 13 runner and using Xcode 14.3.1. Note that while the clang version in the Xcode release is defined as `Apple clang version 14.0.3 (clang-1403.0.22.14.1)`, it is actually [based on](https://en.wikipedia.org/wiki/Xcode#Xcode_11.0_-_14.x_(since_SwiftUI_framework)_2) LLVM 15.
Please disregard the previous comments – they address potential issues and benefits related to upgrading to LLVM 16/Xcode 15, but this will be done in a later PR.
=> Upgrade to macOS 13 runner and switch to LLVM 15 on Linux

src/workerd/api/web-socket.h, src/workerd/jsg/jsg.h
See https://github.com/cloudflare/workerd/issues/1370. I also added in a little macro so that we could reuse the existing constants for both new and old js constants.
=> Provide WebSocket ready state constants to follow the Web IDL definition

patches/sqlite/README
Commit 2c81b17a stopped workerd from using the SQLite amalgamation, making this README stale. I've updated it to remove all the now-useless bits about patching the amalgamation.
=> Update README for SQLite patches.

src/workerd/api/tests/actor-stub-test.js, src/workerd/api/worker-rpc.c++
Previously the code was passing the function being called as the `this` argument. Ensure we're passing the DO as the `this`.
=> Ensure `this` is correct in js rpc calls

src/workerd/jsg/modules.h
Change landed internally that removes use of the deprecated function. Go ahead and remove it now.
=> Remove deprecated API from modules.h

src/workerd/api/crypto-impl-pbkdf2.c++, src/workerd/api/crypto-impl.c++, src/workerd/api/crypto-impl.h, src/workerd/api/node/crypto.h, src/workerd/api/node/crypto_pbkdf2.c++, src/workerd/io/BUILD.bazel, src/workerd/io/limit-enforcer.h, src/workerd/io/worker-entrypoint.c++, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++
Introduces the ability for workerd embedders to configure the max iteration limit for KDFs. Removes the limit for workerd by default. Keeps the current limit of 100,000 when not configured.
Refs: https://github.com/cloudflare/workerd/issues/1346
=> Introduce configurable pbkdf2 iteration limit

src/workerd/io/io-context.c++
Improves the error message that we show when someone attempts to call `fetch()` or do some other async work in global scope.
Consider the following code:
```js
await fetch('https://cloudflare.com')
async fetch(request, env, ctx) {
return new Response('Hello World!');
},
};
```
This error message could be improved:
```
⛅️ wrangler 3.22.1
-------------------
⎔ Starting local server...
✘ [ERROR] service core:user:top-level-await-fail: Uncaught Error: Some functionality, such as asynchronous I/O, timeouts, and generating random values, can only be performed while handling a request.
```
- Doesn't tell you what to do next
- Uses language that is specific to a "request", even though there are ways of invoking workers that don't involve an HTTP request (ex: Queue Consumer, Email …
=> Clarify error message when disallowed operations are called within global scope

src/workerd/io/io-context.c++
KJ_THREADLOCAL_PTR is going away: https://github.com/capnproto/capnproto/pull/1890
(This PR needs to be merged before the capnp PR lands.)
=> Change KJ_THREADLOCAL_PTR to thread_local.

.bazelrc, .github/workflows/release.yml, .github/workflows/test.yml, README.md
Xcode 15.1 is now available on the macos-13 runner image. Note that the unwind info flag introduces a hard requirement for Xcode 15 and by extension macOS 13 for compiling workerd, but Mac developers generally update to new versions quickly and the minimum supported version to run workerd will remain at 11.
=> Upgrade to Xcode 15, avoid duplicate unwind info on x86 macOS

src/workerd/io/worker.c++
Internal production logging shows zero instances of the log entry for the past three months. Fairly certain it is safe to remove this branch.
=> Remove old customer-specific hack from workerd.

WORKSPACE, src/pyodide/BUILD.bazel, src/pyodide/internal/builtin_wrappers.js, src/pyodide/internal/pyodide-bootstrap.js, src/pyodide/internal/pyodide-lock.js
This PR implements a few things:
* Ability to load Python extensions
* Pinning for langchain and openai packages
Some of the dependencies of langchain require Python extension support. This requires loading arbitrary WASM code. This is done via `UnsafeEval.newWasModule`. Right now we are loading packages by downloading them from the internet, so technically we are at risk of a supply chain attack, but our next step will be to embed these packages to avoid download so this issue will be resolved in follow up PRs.
Pinning the packages is required to ensure compatibility. Plus when we embed the packages will be naturally pinned too. We will follow up with a PR to upgrade the pinned versions.
=> Implements Python langchain support

src/workerd/server/server.h
Hey! 👋 This PR intentionally adds code that will fail arm builds. We automatically build for Linux and macOS arm on every merge to `main` using internal CI runners. We recently added configuration to report internal build failures to our internal chat, and want to test this system works. Once this PR has been merged, it should be immediately reverted.
=> Intentionally break arm builds to test internal CI notifications

src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/api/global-scope.c++, src/workerd/api/global-scope.h, src/workerd/api/hibernatable-web-socket.c++, src/workerd/api/hibernatable-web-socket.h, src/workerd/api/hibernation-event-params.h, src/workerd/io/hibernation-manager.c++, src/workerd/io/hibernation-manager.h, src/workerd/io/worker-interface.capnp, src/workerd/io/worker.h
This PR adds new methods for setting event timeouts for hibernatable websockets. 
When a timeout is, it defines the maximum amount of time that a single event of any type is allowed to run before the event will be canceled.
The added methods are `void DurableObjectState::setEventTimeout(int timeoutMs)` and `void DurableObjectState::gettEventTimeout()`.
The timeout acts in global-scope, preventing an event handler to run for more than the desired duration.
=> Enable event timeout for hibernatable web sockets

WORKSPACE, src/workerd/api/node/async-hooks.h, src/workerd/api/sql.h, src/workerd/api/web-socket.h
- V8 roll is pretty minor, primarily adding this to transition to the tagged version
- Binary size impact of cleaning up the compat flag arg is less than expected/rather low (~6K for macOS debug), still good to clean up the affected headers a bit
=> Roll V8, remove unused compat flags arg

src/workerd/api/sockets.c++, src/workerd/api/sockets.h
This was implemented as part of another PR, all this PR does is expose it as an attribute in a Socket instance.
Defined here in the sockets spec https://sockets-api.proposal.wintercg.org/#opened-attribute.
=> Implements `opened` attribute in Socket

src/workerd/api/worker-rpc.c++, src/workerd/api/worker-rpc.h
We're adding a limit to the size of JS RPC messages until we support streaming.
=> Enforce message size limit for JS RPC

src/workerd/api/actor-state.c++, src/workerd/api/actor-state.h, src/workerd/api/global-scope.c++, src/workerd/api/hibernatable-web-socket.c++, src/workerd/api/hibernatable-web-socket.h, src/workerd/api/web-socket.c++, src/workerd/api/web-socket.h, src/workerd/io/hibernation-manager.c++, src/workerd/io/hibernation-manager.h
This method was requested during the hibernation Beta. Previously, if you wanted to get back the tags associated with a hibernatable websocket you would have had to store them in the websocket's attachments (limited) or DO storage (slow + need to ID websocket somehow).
=> Add getTags() for websocket hibernation

src/workerd/api/web-socket.c++, src/workerd/api/web-socket.h
WebSocket events weren't being delivered when the WebSocket was created in a blockConcurrencyWhile callback if the callback depended on a websocket event completing.
=> Try to take lock when delivering websocket events

WORKSPACE
When WebSocket clients send frames we can't accept (too large, invalid UTF-8, etc.), we'll now reply with a Close frame explaining the error. Previously, we'd just disconnect the client without any hint as to what they did wrong.
This is analogous to an HTTP server responding with 400 when a client sends bad headers (or something) instead of just disconnecting.
=> Update capnproto to get new WebSocket closing behavior

src/workerd/api/tests/websocket-hibernation.js, src/workerd/api/tests/websocket-hibernation.wd-test, src/workerd/api/web-socket.c++
It looks like we're failing to send websocket `close()` events in the `webSocketClose()` handler for hibernatable websockets. Print debugging suggests we queue a close message to be sent but then never get past waiting for the `GatedMessage::outputLock` promise.
Strangely, the test seems to pass if a 1ms wait is added between a websocket send and a websocket close.
=> Verify close() works in ws close handler

WORKSPACE, build/BUILD.pyodide_packages, src/pyodide/BUILD.bazel, src/pyodide/internal/pyodide-bootstrap.js, src/workerd/api/pyodide.h
Embeds a tarball containing a Python `site-packages` which includes all the packages necessary to run a langchain + openai demo without the need to download anything at runtime.
Tested upstream via `python-langchain.ew-test`.
=> Implements embedding of Python packages in workerd.

types/defines/email.d.ts
A type `Uint8Array` is missing in a generic to retrieve the raw data.
An issue (#1500) was created and converted into discussion #1501 with the following answer.
> [jasnell](https://github.com/cloudflare/workerd/discussions/1501#discussioncomment-7918779)
> In this case, the value should always be a `Uint8Array`.
=> Improve `ReadableStream` type for email message

src/workerd/api/global-scope.h, src/workerd/io/compatibility-date.capnp
We have no plans to ever implement `importScripts()` and having it defined but marked explicitly non-implemented is causing issues with using certain third-party libraries in workers. So let's just remove it entirely.
Refs: https://github.com/cloudflare/workerd/issues/1521
=> Remove explicitly unimplemented importScripts

WORKSPACE
The zlib.net host eagerly deletes older zlib releases as they become obsolete, this can cause unexpected build failures whenever there is a new zlib version.
=> Update to zlib 1.3.1, switch to fetching from GitHub

src/workerd/api/actor-state-test.c++, src/workerd/api/crypto-impl-aes-test.c++, src/workerd/api/streams/internal.c++, src/workerd/api/streams/queue-test.c++, src/workerd/io/io-context.c++, src/workerd/io/io-context.h, src/workerd/io/observer.h, src/workerd/io/worker.c++, src/workerd/io/worker.h, src/workerd/jsg/jsg-test.c++, src/workerd/jsg/jsg-test.h, src/workerd/jsg/setup-test.c++, src/workerd/jsg/setup.h, src/workerd/server/server.c++, src/workerd/tests/test-fixture.c++
Continued work refactoring the Lock-taking APIs to a callback-style API .... There's still more to do but this PR is large enough already. Will keep working in increments
=> Refactor IoContext::Scope and ThreadScope into callback-based API

src/workerd/util/thread-scopes.c++, src/workerd/util/thread-scopes.h
This is not used in workerd anywhere. It is here only to support a single use on the internal repo. I've got a PR to add the impl to the internal repo. Once that lands, this can be removed.
=> Remove IsolateShutdownScope

src/workerd/api/streams/common.h, src/workerd/api/streams/standard.c++, src/workerd/api/streams/transform.c++, src/workerd/api/tests/streams-test.js, src/workerd/api/tests/streams-test.wd-test
Allows setting an `expectedLength` option for JS-backed readable and transform streams. When the readable stream is used as the body of a request or response, the expectedLength is used as the value of the content-length header. When set, chunked encoding will not be used.
=> Add expectedLength for JS streams

WORKSPACE, samples/pyodide-fastapi/worker.py, samples/pyodide-langchain/config.capnp, samples/pyodide-langchain/worker.py, samples/pyodide/worker.py, src/pyodide/python-entrypoint-helper.js
Just a simple way to disable embedding of Python packages only in workerd to reduce its binary size.
=> Don't embed Python packages in workerd.

build/wd_cc_library.bzl, src/workerd/tools/BUILD.bazel, src/workerd/util/BUILD.bazel
Mark library targets as off-by-default. We do not ship any libraries as part of workerd releases or use them outside of bazel, so there is generally no need to build them explicitly. This allows us to not build library targets by default. Note that on macOS (and likely Windows) library targets will still be built as dependencies of other targets such as tests and workerd itself as `start_stop_lib` is not supported – on Linux binaries are built directly from object files so there's no need to build the library files.
This reduces the size of the build output folder from 6.1GB to 5.9GB on Linux CI builds.
=> [bazel] Do not compile wd_cc_library by default

src/workerd/api/worker-rpc.c++, src/workerd/api/worker-rpc.h, src/workerd/io/worker-interface.capnp, src/workerd/jsg/jsg-test.c++, src/workerd/jsg/jsg.h, src/workerd/jsg/jsvalue.h, src/workerd/jsg/resource.c++, src/workerd/jsg/resource.h, src/workerd/jsg/rtti.h
This implements the change we discussed previously, to allow the named property getter to return an arbitrary wrappable value.
I also came up with what I think is more intuitive name for this feature: "Wildcard property"
=> Simplify "named intercept"
