src/workerd/api/analytics-engine.c++
src/workerd/api/basics.c++
src/workerd/api/trace.c++
src/workerd/api/trace.h
src/workerd/io/actor-cache-test.c++
src/workerd/io/io-context.c++
src/workerd/io/io-context.h
src/workerd/io/io-gate.c++
src/workerd/io/io-gate.h
src/workerd/io/limit-enforcer.h
src/workerd/io/worker-entrypoint.c++
src/workerd/io/worker-entrypoint.h
src/workerd/io/worker-interface.c++
src/workerd/io/worker-interface.h
src/workerd/io/worker.c++
src/workerd/io/worker.h
src/workerd/jsg/README.md
src/workerd/jsg/iterator-test.c++
src/workerd/jsg/jsg.h
src/workerd/jsg/promise-test.c++
src/workerd/jsg/util-test.c++
src/workerd/jsg/value-test.c++
src/workerd/server/server.c++
src/workerd/util/own-util.h

This is the last sync. From this point on the GitHub repo is the single source of truth for this code and we've deleted the internal copy.

Sync changes from internal repo for the last time.

---

src/workerd/server/server.c++

Signed-off-by: spacewander <spacewanderlzx@gmail.com>

chore: fix comments

---

src/workerd/api/streams/README.md
src/workerd/api/streams/internal.c++
src/workerd/api/streams/internal.h
src/workerd/api/streams/queue-test.c++
src/workerd/api/streams/queue.c++
src/workerd/api/streams/queue.h
src/workerd/api/streams/readable.c++
src/workerd/api/streams/readable.h
src/workerd/api/streams/standard.c++
src/workerd/api/streams/standard.h
src/workerd/jsg/buffersource.c++
src/workerd/jsg/buffersource.h

This reverts some commits which predate workerd's commit history.

Revert recent streams backpressure tee refactor

---

src/workerd/jsg/promise.h

It bugged me for some reason, so just making a pico change to fix it.

Fixing a typo

---

src/workerd/io/compatibility-date.capnp

Will be used with upcoming node compat work experiments.
@jasnell @byule

add nodeCompatExperimental feature flag

---

samples/durable-objects-chat/config.capnp

I guess if you run a security scanner on this repo these might be flagged as possible leaked secrets. They aren't, obviously, but let's make that clear.

Clarify the chat demo unique keys are examples

---

src/workerd/api/streams/writable.c++
src/workerd/api/streams/writable.h

Just aligning it with what's currently in ReadableStream
/cc @harrishancock

Wrap the WritableStream controller in a kj::Own

---

src/workerd/api/streams/internal.c++

The assert is just invalid.
/cc @harrishancock

Remove obsolete invalid assert

---

src/workerd/api/streams/transform.c++

Small typo fix in comment

---

src/workerd/io/io-context.c++
src/workerd/io/io-context.h
src/workerd/server/server.c++

Add a new param to IO context of type bytestream,
used for streaming content.

add bytestream to context

---

.github/workflows/test.yml

Change from `devprod.workers.dev` to `devprod.cloudflare.dev` (an actual zone) to increase upload limits and reduce 413 errors

Run the bazel cache worker on a zone to increase upload limits

---

src/workerd/jsg/dom-exception.c++
src/workerd/jsg/dom-exception.h
src/workerd/jsg/value.h

Cleanups + improved spec alignment

Improve implementation of DOMException

---

WORKSPACE
src/workerd/api/analytics-engine.capnp
src/workerd/api/r2-api.capnp
src/workerd/io/actor-storage.capnp
src/workerd/io/cdp.capnp
src/workerd/io/compatibility-date.capnp
src/workerd/io/jaeger.capnp
src/workerd/io/outcome.capnp
src/workerd/io/worker-interface.capnp
src/workerd/jsg/rtti.capnp
src/workerd/server/workerd.capnp
src/workerd/util/capnp-mock.h

See: https://github.com/capnproto/capnproto/pull/1569

Update for Cap'n Proto allowCancellation change.

---

src/workerd/api/r2-bucket.c++
src/workerd/api/r2-bucket.h

Tests are in an associated EW PR

return null upon R2 conditonal put  failure

---

src/workerd/api/actor.c++
src/workerd/api/actor.h
src/workerd/io/io-channels.h
src/workerd/io/io-context.h
src/workerd/server/server.c++

Already reviewed/approved here, but PR checks were goofing up: https://github.com/cloudflare/workerd/pull/206

Add optional locationHint parameter to Durable Objects `get()`

---

WORKSPACE

syncing with internal version before upstreaming changes.

[bazel] updating js dependencies

---

src/workerd/api/sockets.c++

We want to specifically disallow newline characters in the addresses, but I ended up creating an allowlist for the valid characters instead of the other way around.

Validate addresses passed to `connect`.

---

types/defines/email.d.ts

- EmailMessage
- EmailEvent
- EmailExportedHandler

Add Email types

---

types/defines/pubsub.d.ts

Pulling over the stale PR from https://github.com/cloudflare/workers-types/pull/246#issuecomment-1397398674
cc/ @mrbbot

types: add Pub/Sub types

---

src/workerd/jsg/modules.c++

It seems there are cases where the cache can fail. While I investigate the issue, let's disable it so that it doesn't block progress on other pieces.

Temporarily disable the built-in module compile cache

---

src/node/buffer.ts
src/node/internal/bufferImpl.ts
src/workerd/api/BUILD.bazel
src/workerd/api/node/node-test.c++
src/workerd/api/node/node.h
src/workerd/io/BUILD.bazel
src/workerd/tests/BUILD.bazel

use node bundle

---

samples/nodejs-compat/worker.js
src/node/assert.ts
src/node/internal/internal_assert.ts
src/node/internal/internal_assertionerror.ts
src/node/internal/internal_buffer.ts
src/node/internal/internal_comparisons.ts
src/node/internal/internal_diffs.ts
src/node/internal/internal_errors.ts
src/node/internal/internal_utils.ts

Initial, exerimental implementation of Node.js assert module
TODO

Add Node.js Compat assert implementation

---

src/workerd/io/compatibility-date.capnp

This release includes some fun things like `workerd test`, SQLite-backed Durable Object storage, and new `AsyncLocalStorage` methods.

Bump compatibility date to `2023-02-21` for release

---

src/workerd/api/url-standard.h
src/workerd/api/url.h

In preparation for https://github.com/whatwg/url/pull/734
~~(this shouldn't land until that spec change lands)~~ Landed

Implement URLSearchParams size getter

---

src/node/internal/internal_buffer.ts
src/workerd/api/BUILD.bazel
src/workerd/api/node/buffer-base64.h
src/workerd/api/node/buffer-nodejs-test.js
src/workerd/api/node/buffer-nodejs-test.wd-test
src/workerd/api/node/buffer-string-search.h
src/workerd/api/node/buffer.c++
src/workerd/api/node/buffer.h

Note that this pulls in parts of the implementation directly from Node.js. Namely, the StringSearch and base64 decoding impls. See comments in the C++ files for details.

Initial port of Node.js buffer tests and fixes

---

src/node/internal/streams_readable.js
src/workerd/api/node/streams-test.js

... and we're still not done yet.

More Node.js Streams Tests

---

types/defines/email.d.ts

Declared new module where EmailMessage lives, added new type for SendEmail binding. Extracted EmailMessage from ForwardableEmailMessage.

types related to mail sending

---

src/cloudflare/.eslintrc.json
src/cloudflare/BUILD.bazel
src/cloudflare/README.md
src/cloudflare/email.ts
src/cloudflare/internal/email.d.ts
src/cloudflare/tsconfig.json

Add a cloudflare TS module where we will be
simulating bindings. The first candidate will
be the binding to send email from workers.
This will allow local development using
miniflare 3.

add Cloudflare TS module

---

src/workerd/server/server.c++
src/workerd/server/server.h

part of #413 and a real pain to rebase

refactor: extract createBinding function

---

src/workerd/server/workerd-api.c++

This is part of #413 and is a pain to rebase/merge.

refactor: extract createBindingValue fn for a single binding

---

src/workerd/api/crypto-impl-asymmetric.c++

A number of Web API fixes:
- Fix validation of the `use` and  `key_ops` parameters when importing JWK keys, which currently assumes that only signing-related operations are supported, which is not the case for ECDH and RSA-OAEP. This should fix #138.
- The `JSG_WARN_ONCE_IF()` check for ECDH usages was using the wrong variable, which may have caused warnings even when the usages parameter is valid.
- Remove unused variables, fix formatting and comments
Upstream PR has been added.

Web crypto: Fix JWK key import for ECDH and RSA-OAEP, minor cleanup

---

src/workerd/api/queue.c++
src/workerd/api/queue.h
src/workerd/server/server-test.c++
src/workerd/server/server.c++
src/workerd/server/workerd-api.c++
src/workerd/server/workerd-api.h
src/workerd/server/workerd.capnp
src/workerd/tools/api-encoder.c++
types/defines/queues.d.ts

This is just code movement other than the new test.

Move implementation of queue bindings into workerd

---

src/workerd/util/sqlite.c++
src/workerd/util/sqlite.h

Also, set SQLITE_IOCAP_POWERSAFE_OVERWRITE by default. This flag is highly desirable for performance and probably satisfied by all modern disks. See:
https://www.sqlite.org/psow.html

SQLite: Allow setting VFS device characteristics.

---

build/BUILD.sqlite3
src/workerd/api/sql-test.js
src/workerd/util/sqlite.c++
src/workerd/util/sqlite.h

* Allow some pragmas and functions.
* Apply suggestions from: https://www.sqlite.org/security.html
(This is based on top of #513; that'll have to be merged first.)

Improve SQLite security

---

src/node/internal/streams_adapters.js
src/node/internal/streams_duplex.js
src/node/internal/streams_readable.js
src/node/internal/streams_writable.js
src/workerd/api/node/streams-test.js

More Node.js-compat streams impl...
For background, these are utility APIs in Node.js for adapting between standard Web streams and Node.js streams... See the additional tests for examples.

Add the Node.js streams toWeb/fromWeb adapters

---

src/workerd/api/streams/common.h

Remove an artifact of an old iteration that is no longer needed. Improves the robustness of the two classes.

Eliminate Impl indirection in WriterLocked/ReaderLocked

---

README.md
docs/vscode.md

Adds notes on using bazelisk, that build can be done with VSCode, etc.

Update README.md and docs/vscode.md

---

src/workerd/api/sql-test.js
src/workerd/util/sqlite.c++

There was a typo, `sumunc`, and `total` was missing. Added both and added test cases.

Allowing sum/total SQL functions

---

.vscode/extensions.json
docs/vscode.md

Adds a list of recommended extensions and a few tips.
Adds an `extensions.json` file that can be used to install the recommended extensions with one command.

Additional notes on using vscode for workerd development

---

src/node/crypto.ts
src/node/internal/crypto.d.ts
src/node/internal/crypto_keys.ts
src/workerd/api/node/crypto-keys.c++
src/workerd/api/node/crypto.h

Initial scaffolding for the Node.js crypto KeyObject implementation. Actual implementations of the underlying c++ will come in a follow on PR.

Add Node.js crypto KeyObject JS api

---

src/workerd/api/sockets.h

Use IoOwn instead of Own in Socket.

---

.github/workflows/fixup.yml

[nfc] Add github action to block merging fixup commits

---

src/workerd/api/node/crypto-keys.c++
src/workerd/api/node/crypto_keys-test.js

Basic initial `SecretKeyObject` impl.

Add basic impl for Node.js SecretKeyObject

---

src/workerd/jsg/jsg.c++
src/workerd/jsg/jsg.h

The move constructor is normally allowed to be used without a lock, but this isn't true in the specific case that the source is a handle that has been reachable via GC tracing. This case isn't used often but let's make sure it's right. We'll move the logic out-of-line and add some more debug checks.
(This didn't catch any issues in tests but I'm worried this interface is error-prone.)

Add some hardening on jsg::Data move constructor.

---

types/defines/sockets.d.ts

Need this to generate types for the `cloudflare:sockets` module.

Adds cloudflare:sockets module types.

---

.vscode/tasks.json
WORKSPACE
docs/v8-updates.md
docs/vscode.md
patches/v8/0001-Allow-manually-setting-ValueDeserializer-format-vers.patch
patches/v8/0002-Allow-manually-setting-ValueSerializer-format-versio.patch
patches/v8/0003-Make-icudata-target-public.patch
patches/v8/0004-Add-ArrayBuffer-MaybeNew.patch
patches/v8/0005-Allow-compiling-on-macOS-catalina-and-ventura.patch
patches/v8/0006-Fix-v8-code_generator-imports.patch
patches/v8/0007-Allow-Windows-builds-under-Bazel.patch
patches/v8/0008-Disable-bazel-whole-archive-build.patch
patches/v8/0009-Make-v8-Locker-automatically-call-isolate-Enter.patch
patches/v8/0010-Add-an-API-to-capture-and-restore-the-cage-base-poin.patch
src/workerd/io/worker.c++
src/workerd/jsg/jsg.c++
src/workerd/jsg/jsg.h
src/workerd/jsg/setup.c++
src/workerd/jsg/setup.h
src/workerd/jsg/v8-platform-wrapper.c++
src/workerd/jsg/v8-platform-wrapper.h

In our production build, we use multi-cage mode, which has some new issues in 11.4. I have introduced some patches to work around them here but I don't think they are the right patches to upstream. We'll need to revisit this soon.

Update V8 to 11.4

---

WORKSPACE

Test: bazel build //src/workerd/server:workerd

Update to V8 11.4.183.17

---

docs/api-updates.md

Document the workflow when adding compatibility flags and dates.

docs: Add doc on compatibility flags and dates

---

src/workerd/api/sockets.c++
src/workerd/api/sockets.h

This turns out to be due to the `whenWriteDisconnected()` not being canceled before the connection stream is destroyed. Under KJ rules this would be a UAF, but in practice it harmlessly logs a spurious error: 'PromiseFulfiller was destroyed without fulfilling the promise.'

Fix PromiseFulliller error when api::Socket is GC'd.

---

src/workerd/server/server-test.c++
src/workerd/server/server.c++
src/workerd/server/workerd.capnp

See discussion on #70
Fixes #70

Add binding type that takes value from system environment variable.

---

src/workerd/api/global-scope.c++

We were only removing the queued websocket when a handler was exported so the websocket could be delivered to the hibernatable websocket event.

Remove queued websocket if no handler exported

---

src/workerd/api/global-scope.c++
src/workerd/api/http.c++
src/workerd/api/kv.c++
src/workerd/api/r2-bucket.c++
src/workerd/api/r2-rpc.c++
src/workerd/api/urlpattern.c++
src/workerd/io/io-context.c++
src/workerd/io/worker.c++
src/workerd/jsg/modules.c++
src/workerd/jsg/resource.c++
src/workerd/jsg/resource.h
src/workerd/jsg/struct.h
src/workerd/jsg/util.c++
src/workerd/jsg/util.h
src/workerd/server/workerd-api.c++

Generally non-functional change.

Use v8StrIntern more to reduce number of string copies in v8 heap

---

src/workerd/api/queue.c++

**Remove some copies from the queue binding's send() method**
By not copying data out of perfectly good Strings into new heap arrays
when we don't need to.
**Remove a copy when calling queue.sendBatch with "bytes" content**
Because we synchronously consume the arraybuffer in order to base64-
encode it further down in sendBatch, there's no point in making a full
copy of it.
In theory we could just always call `BufferSource::detach()` to avoid
ever needing a copy, but I'm a little worried about the unintuitive
behavior of an arraybuffer being emptied out whenever you pass it into a
queue method. While it'd be really nice for performance, I'd hate to see
it cause a serious customer bug.

Remove some copies from the queue binding implementation

---

src/workerd/api/node/async-hooks.c++
src/workerd/io/compatibility-date.h
src/workerd/io/worker.c++
src/workerd/io/worker.h
src/workerd/server/server-test.c++
src/workerd/server/server.c++
src/workerd/server/workerd.capnp

Fixes a few some minor spelling issues.

Fix a few spello's

---

src/workerd/api/cache.c++

Allows open() to be called in the global scope fixing a minor TODO and eliminating a minor restriction on the API since the result is not actually dependent on any particular request.

Address minor TODO in CacheStorage::open()

---

src/workerd/jsg/function.h
src/workerd/jsg/jsg.h
src/workerd/jsg/meta.h
src/workerd/jsg/resource.h
src/workerd/jsg/util.h
src/workerd/jsg/wrappable.h

I had to do it in my PR to make things compile. Extracting to a separate change to reduce the noise level.

[nfc] moving jfc definitions around

---

src/workerd/api/actor-state.c++

Converts kj::Promise .then uses to coroutines. This one picks ones with trivial reference captures and uses of IoContext.

Coroutines Conversion: updates parts of actor-state.c++ to coroutines

---

src/workerd/api/sql-test.js

No functional changes, just ran prettier and refactored to use more node:assert things (thanks @jasnell for the suggestions!)

Refactored `sql-test.js`

---

src/workerd/api/sockets.c++
src/workerd/api/sockets.h
src/workerd/api/streams/common.c++
src/workerd/api/streams/common.h
src/workerd/api/streams/internal.c++
src/workerd/api/streams/internal.h
src/workerd/api/streams/queue.c++
src/workerd/api/streams/readable.c++
src/workerd/api/streams/readable.h
src/workerd/api/streams/standard.c++
src/workerd/api/streams/standard.h
src/workerd/io/io-context.h
src/workerd/jsg/promise.h

Fairly large but generally non-functional change.

Use jsg::Lock& taking variants of jsg::Promise::Resolver methods

---

src/workerd/jsg/setup.c++
src/workerd/jsg/setup.h

...and a few drive-by spelling tweaks.

Fix some unusual spacing around Isolate constructor

---

src/workerd/api/html-rewriter.c++

This reverts commit 52cb906aeaa28666ca9521c450fa04b1b5a562fa.

Revert "Coroutines Conversion: update api/html-rewriter.c++"

---

src/workerd/jsg/BUILD.bazel
src/workerd/jsg/rtti-test.c++
src/workerd/jsg/rtti-test.capnp
src/workerd/jsg/rtti.capnp
src/workerd/jsg/rtti.h

[jsg] rtti support for context builtin modules

---

src/workerd/server/server-test.c++
src/workerd/server/server.c++

Hey! 👋 We're planning to port Miniflare's data store simulators to Durable Objects running in `workerd` instead of Node. Miniflare's existing simulators use an SQLite database for metadata and a separate blob store. We were thinking of using Durable Object's new SQL support for metadata, and a disk directory service for the blob store. We'd ideally like to be able to delete unused blobs, so this PR adds support for the `DELETE` method to writable disk directory services.

Implement disk directory service `DELETE` method

---

src/workerd/server/server.c++

Accidentally introduced an infinite recursion bug in the method. Switching to `for (;;}` to avoid it.

Avoid infinite recursion bug in server.c++ coroutine

---

src/workerd/api/sockets.c++
src/workerd/api/sockets.h

This reverts commit 7955dc47ac04bbe869fdbae734d8c48a7f281cff.

Revert "Add a new overload of Socket::handleProxyStatus for internal use"

---

src/workerd/api/sql-test.js
src/workerd/util/sqlite.c++

Adding a column with a CHECK to an existing table triggers quick_check behind the scenes. So we should enable it:
From https://www.sqlite.org/pragma.html#pragma_quick_check
> The pragma is like [integrity_check](https://www.sqlite.org/pragma.html#pragma_integrity_check) except that it does not verify UNIQUE constraints and does not verify that index content matches table content. By skipping UNIQUE and index consistency checks, quick_check is able to run faster. PRAGMA quick_check runs in O(N) time whereas [PRAGMA integrity_check](https://www.sqlite.org/pragma.html#pragma_integrity_check) requires O(NlogN) time where N is the total number of rows in the database. Otherwise the two pragmas are the same.
I've just confirmed that even if you set `ignore_check_constraints=ON` before your …

SQLite: allowlisting `quick_check` PRAGMA, and tests to explain why

---

src/workerd/api/sql-test.js

Was just curious whether this worked, and it does!
Also ran prettier just to keep this file tidy

[SQLite] confirming row counts work with interleaved cursors

---

src/workerd/api/encoding.c++
src/workerd/api/encoding.h
src/workerd/jsg/buffersource.c++
src/workerd/jsg/buffersource.h

* Add the ability to set and use a detach key
* Add the ability to wrap an external data buffer with a
custom disposer (as used, for instance, in GPU)

JSG Completion: fill out more BufferSource features

---

src/workerd/server/server.c++

Fixes a race between initializing the InspectorService::isolates field on the inspector service thread and
Server::InspectorServiceIsolateRegistrar::registerIsolate inserting an isolate into the InspectorSerivce::isolates field on a worker thread.
This change ensures that the InspectorService instance is initialized before worker threads can start registering isolates.
Test: manual check repro steps in
https://github.com/cloudflare/miniflare/issues/651
no longer cause crashes.
Bug: https://github.com/cloudflare/workerd/issues/1075
Bug: https://github.com/cloudflare/miniflare/issues/651
Bug: EW-7716

EW-7716: fix crashing race with InspectorService initialization

---

src/workerd/jsg/jsg.h
src/workerd/jsg/setup.h

To be used by some internal apis.

JSG Completion: add JsValue-variant for js.toDict()

---

src/workerd/jsg/jsg.h
src/workerd/jsg/jsvalue.c++

To be used by some internal apis

Add variant of jsg::Lock::arr(...) that takes kj::ArrayPtr

---

WORKSPACE
src/workerd/io/worker-interface.c++
src/workerd/io/worker.c++
src/workerd/server/server.c++

co_await forks without creating new branch

---

src/workerd/api/node/async-hooks.h
src/workerd/api/node/buffer.h
src/workerd/api/node/crypto-keys.c++
src/workerd/api/node/node.h
src/workerd/api/node/util.c++
src/workerd/api/streams/common.h
src/workerd/api/streams/compression.c++
src/workerd/api/streams/internal.c++
src/workerd/api/streams/internal.h
src/workerd/api/streams/queue.h
src/workerd/api/streams/readable.h
src/workerd/api/streams/standard.c++
src/workerd/api/streams/standard.h
src/workerd/api/streams/transform.h
src/workerd/api/streams/writable.h
src/workerd/jsg/jsg-test.h
src/workerd/tests/bench-json.c++
src/workerd/tests/bench-tools.h
src/workerd/tests/test-fixture.h

This should be the final batch for workerd. There might still be lingering old-style comments around, folks should fix those as they find them :-)

Convert the remaining files to idiomatic comment style

---

src/workerd/api/gpu/gpu-command-encoder.c++
src/workerd/api/gpu/gpu-compute-pass-encoder.c++
src/workerd/api/gpu/gpu-compute-pass-encoder.h
src/workerd/api/gpu/gpu-queue.c++
src/workerd/api/gpu/webgpu-buffer-test.js

Off-by-one error when checking for the size of the data to copy.

webgpu: fix size check

---

src/workerd/server/server.c++

Hey! 👋 This PR extends https://github.com/cloudflare/workerd/pull/638 to report the port of the inspector socket too. This allows us to start the inspector on port "0", and then make requests to the allocated port. We'd like to use this in Wrangler's inspector proxy service, to start the inspector on a random port each time `workerd` is reloaded.
```
$ workerd --verbose --control-fd=1 --inspector-addr=127.0.0.1:0
workerd/server/server.c++:2613: info: Inspector is listening
{"event":"listen-inspector","port":"62274}
{"event":"listen","socket":"http","port":8080}
```

Report port inspector socket is listening on when ready

---

src/workerd/server/server.c++

This is an alternate fix for #1161.
The underlying problem is a race condition which used to be won by the error, but started being won by the success case after an unrelated Cap'n Proto change: https://github.com/capnproto/capnproto/pull/1630

Fix handling of fatal errors in server.c++.

---

src/workerd/api/streams/internal.c++

Don't try to read if the buffer would be zero-length.

Add additional guard for internal streams AllReader

---

src/workerd/api/tests/abortsignal-test.js
src/workerd/api/tests/abortsignal-test.wd-test
src/workerd/api/tests/encoding-test.js
src/workerd/api/tests/encoding-test.wd-test
src/workerd/api/tests/scheduler-test.js
src/workerd/api/tests/scheduler-test.wd-test

Add unit tests for `AbortSignal` and `AbortController`

Add wd-test unit tests for AbortSignal/AbortController

---

src/workerd/api/streams/standard.c++
src/workerd/jsg/promise.h

In certain fairly rare circumstances the .then call on a jsg::Promise can throw a JsExceptionThrown so make sure those are guarded with a js.tryCatch

Ensure that .then calls in maybeRunAlgorithm are guarded

---

src/workerd/api/blob.c++

Remove the blob mime type sentry warning

---

src/workerd/api/gpu/gpu-compute-pipeline.h
src/workerd/api/gpu/gpu-device.c++
src/workerd/api/gpu/gpu-device.h
src/workerd/api/gpu/webgpu-compute-test.js

Ensure strings on compute pipeline layout and implement more gpu device properties.

Webgpu improvements

---

src/workerd/io/hibernation-manager.c++
src/workerd/io/hibernation-manager.h

This undoes the changes to the hibernation-manager files in https://github.com/cloudflare/workerd/commit/91b6a93ae351169240ef34e49845b740564d2804

Undo coroutine change for hibernatable websockets

---

src/workerd/io/hibernation-manager.c++
src/workerd/io/hibernation-manager.h

Revert "Undo coroutine change" and add missing co_await

---

src/workerd/io/trace.c++
src/workerd/io/trace.h

EW-7618: convert trace.{h,c++} to use KJ_IF_SOME

---

src/workerd/api/streams/queue.c++
src/workerd/api/streams/queue.h

EW-7618: Replace KJ_IF_MAYBE with KJ_IF_SOME in queue.{h,c++}

EW-7618: Replace KJ_IF_MAYBE with KJ_IF_SOME in queue.{h,c++}

---

src/workerd/api/sockets.c++

Simple fix to ensure proxy disconnections errors propagate properly to the Socket API.

Handle socket proxy disconnections.

---

samples/extensions/burrito-shop-impl.js

Fixes: https://github.com/cloudflare/workerd/issues/1207

Fixup extensions sample

---

src/workerd/api/http.c++
src/workerd/api/web-socket.c++
src/workerd/api/web-socket.h

Migrate src/workerd/api/{http,websocket}.c++ to use KJ_IF_SOME

---

src/workerd/api/queue.c++

Move workerd/api/queue.c++ to KJ_IF_SOME

---

src/workerd/api/http.h

Move workerd/api/http.h to KJ_IF_SOME

---

src/workerd/api/util.c++

Move workerd/api/util.c++ to KJ_IF_SOME

---

src/workerd/api/actor-state.c++
src/workerd/api/actor.c++

Move workerd/api/actor-state.c++ and actor.c++ to KJ_IF_SOME

---

src/workerd/util/abortable.h
src/workerd/util/capnp-mock.h
src/workerd/util/mimetype.h
src/workerd/util/sqlite.h

KJ_IF_SOME nullptr to kj::none conversions in src/workerd/util

---

src/workerd/api/api-rtti-test.c++
src/workerd/api/cache.c++
src/workerd/api/form-data.h
src/workerd/api/http.c++
src/workerd/api/streams/internal.c++
src/workerd/api/streams/internal.h
src/workerd/api/streams/queue-test.c++
src/workerd/api/streams/queue.c++
src/workerd/api/streams/queue.h
src/workerd/api/streams/standard.c++
src/workerd/api/streams/writable.h
src/workerd/api/url-standard-test.c++
src/workerd/api/url-standard.h
src/workerd/api/url.h
src/workerd/api/util-test.c++
src/workerd/api/web-socket.c++

Updates based on recent changes to conversion script.
Bug: EW-7618

A few KJ_IF_SOME updates to src/workerd/api

---

src/workerd/jsg/jsg.h
src/workerd/jsg/setup.h
src/workerd/jsg/string.c++
src/workerd/jsg/string.h
src/workerd/jsg/struct.h
src/workerd/jsg/type-wrapper.h
src/workerd/jsg/util.h
src/workerd/jsg/value.h

A few KJ_IF_SOME related updates to src/workerd/jsg

---

src/workerd/server/alarm-scheduler.h
src/workerd/server/server.c++

A few KJ_IF_SOME related updates to worker/src/server

---

src/workerd/tests/test-fixture.c++

A few kj::none related updates to src/workerd/tests

---

.bazelrc

Adds flags for test coverage.

---

WORKSPACE

this matches downstream version

upgrade rust toolchain to 1.72.1

---

src/workerd/api/streams/standard.c++

This reverts commit 7c0569656c4f808d88c28ea304953516f6a7e94d.

Revert "Accumulate reads in streams PumpToReader (#1264)"

---

.github/workflows/release.yml
.github/workflows/test.yml
WORKSPACE

Only targets nodejs as it is prone to fail fetch on github runners.

Add support for fetching from a mirror

---

src/workerd/api/basics.c++
src/workerd/api/cache.c++
src/workerd/api/http.c++
src/workerd/api/streams/common.h
src/workerd/api/streams/internal.h
src/workerd/api/streams/readable.c++
src/workerd/api/streams/standard.c++
src/workerd/api/streams/transform.c++
src/workerd/api/streams/transform.h
src/workerd/api/trace.c++
src/workerd/api/url-standard-test.c++
src/workerd/api/url-standard.c++
src/workerd/api/url-standard.h
src/workerd/api/urlpattern.h
src/workerd/io/worker.c++
src/workerd/jsg/meta.h
src/workerd/jsg/setup.h
src/workerd/jsg/value.h
src/workerd/util/sqlite-kv-test.c++
src/workerd/util/sqlite.c++

A few of these stood out when looking at ew today.

A few more nullptr to kj::none conversions

---

src/workerd/api/sockets.c++
src/workerd/api/sockets.h

Similar to https://github.com/cloudflare/workerd/pull/1284 but for socket's `close` method.

Flush and await Socket connection before resolving Socket.close().

---

src/workerd/api/streams/internal.c++

found by new asan in upstream tests

streams: fix pipe use after free

---

src/workerd/api/sockets.c++
src/workerd/api/sockets.h

Reverts cloudflare/workerd#1369
Temporary revert.

Revert "Flush and await Socket connection before resolving Socket.close()."

---

src/workerd/io/worker.c++

To cleanup correctly the Delete method on the HeapSnapshot must be called.

Fixup HeapSnapshot cleanup

---

src/workerd/api/gpu/gpu-command-encoder.c++
src/workerd/api/gpu/gpu-command-encoder.h
src/workerd/api/gpu/gpu-compute-pass-encoder.c++
src/workerd/api/gpu/gpu-compute-pass-encoder.h
src/workerd/api/gpu/gpu-render-pass-encoder.c++
src/workerd/api/gpu/gpu-render-pass-encoder.h
src/workerd/api/gpu/gpu-utils.c++
src/workerd/api/gpu/gpu-utils.h
src/workerd/api/gpu/gpu.h
src/workerd/api/gpu/webgpu-windowless-test.js

Implemented more webgpu objects/methods: beginRenderPass() and the GPURenderPassEncoder.

webgpu: implement render pass encoder

---

src/workerd/api/gpu/gpu-command-encoder.c++
src/workerd/api/gpu/gpu-command-encoder.h
src/workerd/api/gpu/gpu-device.c++
src/workerd/api/gpu/gpu-render-pass-encoder.h
src/workerd/api/gpu/gpu.h
src/workerd/api/gpu/webgpu-windowless-test.js

Continued implementing more render-related methods, improved test and corrected one bug that the test found.

webgpu: implement copyTextureToBuffer()

---

src/workerd/api/gpu/gpu-command-encoder.c++
src/workerd/api/gpu/gpu-command-encoder.h
src/workerd/api/gpu/webgpu-buffer-test.js
src/workerd/api/gpu/webgpu-windowless-test.js

Added methods:
- copyBufferToTexture
- copyTextureToTexture
- clearBuffer

webgpu: Implemented more command encoder methods

---

src/workerd/server/BUILD.bazel
src/workerd/server/autogate.c++
src/workerd/server/autogate.h
src/workerd/server/workerd.c++
src/workerd/server/workerd.capnp

* Tests in our internal repo
* Verified that workerd runs via `bazel run @workerd//src/workerd/server:workerd -- --help`

Implements autogate framework.

---

src/workerd/io/worker.c++
src/workerd/util/xthreadnotifier.h

Move to taking the inspector lock asynchronously in the I/O thread when dispatching messages. The I/O thread runs multiple co-routines and blocking acquisition is problematic.
Also move XThreadNotifier to use kj::PromiseCrossThreadFulfillerPair instead of kj::PromiseFulfillerPair. There was a problem with a missing notification with the latter that does not repro with the former. However, I've not been able to repro this outside of `inspector-invocations.ew-test-bin.c++` so this part of the change could be masking an issue. The issue was occurring 1 in O(10,000) runs.
Bug: EW-7833

inspector: simplify locking to avoid deadlock

---

src/workerd/io/hibernation-manager.c++
src/workerd/io/hibernation-manager.h
src/workerd/io/worker.h
src/workerd/server/server.c++

Move some function implementations out of the header.

Some minor cleanup of hibernation-manager headers

---

.devcontainer/Dockerfile

To keep consistent with this update
https://github.com/cloudflare/workerd/commit/64274c249a8234784ce9f25c9f8a8a519477ce8d

Update dev container's node version

---

src/workerd/io/worker.c++
src/workerd/io/worker.h
src/workerd/util/weak-refs.h

Move WeakIsolateRef out to templated util

---

src/workerd/api/actor-state-iocontext-test.c++
src/workerd/api/actor-state.c++
src/workerd/api/actor.h
src/workerd/io/actor-id.h
src/workerd/io/io-channels.h
src/workerd/io/io-context.h
src/workerd/io/worker.h
src/workerd/server/server.c++
src/workerd/tests/test-fixture.c++

Addresses long-standing TODO about moving the def out of io-channels.h

Move ActorIdFactory/ActorId out to separate header

---

src/workerd/jsg/wrappable.c++

Work around overly-aggressive ASAN poisoning in cppgc.

---

WORKSPACE

https://github.com/capnproto/capnproto/pull/1873
Fixes #1408

Update capnproto to b652cf8

---

src/workerd/jsg/wrappable.c++

Hey! 👋 The internal Linux arm64 build was failing with...
```
src/workerd/jsg/wrappable.c++:13:10: fatal error: 'sanitizer/asan_interface.h' file not found
#include <sanitizer/asan_interface.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
...following https://github.com/cloudflare/workerd/pull/1480. This PR adds back the `#if` guards removed before that PR landed to only include this code in ASAN builds.

Add `#if` guards to `ASAN_UNPOISON_MEMORY_REGION` and `#include`

---

src/pyodide/BUILD.bazel
src/pyodide/internal/pyodide-bootstrap.js
src/pyodide/internal/pyodide-lock.js
src/workerd/api/pyodide.h

Adds Pyodide files used to bootstrap a worker as a `wd_js_bundle`.

Introduces Pyodide bootstrap files.

---

src/workerd/api/crypto-impl-asymmetric-test.js
src/workerd/api/crypto-impl-asymmetric.c++
src/workerd/api/crypto-impl.h

Completed alternative to https://github.com/cloudflare/workerd/pull/1404
Fixes: https://github.com/cloudflare/workerd/issues/1403
Thank you @panva!

fix ECDH JWK key imports do not check alg

---

WORKSPACE
src/workerd/jsg/BUILD.bazel

Also see the downstream branch.

[nfc] Assorted bazel cleanup

---

src/workerd/io/worker.h

It is not used anywhere in this file.

Remove the jsg::V8System decl from worker.h

---

src/workerd/api/tests/htmlrewriter-test.js
src/workerd/api/tests/htmlrewriter-test.wd-test

Port a handful of HTMLRewriter tests from the internal repo

---

src/workerd/server/server.h

Reverts cloudflare/workerd#1525

Revert "Intentionally break arm builds to test internal CI notifications"

---

src/pyodide/BUILD.bazel
src/pyodide/internal/patches/aiohttp_fetch_patch.py
src/pyodide/internal/pyodide-bootstrap.js
src/workerd/api/pyodide.h

Tested upstream. Implements a way to add Python patches and adds one for aiohttp.

Implements automated aiohttp patching for Python.

---

src/workerd/api/worker-rpc.c++

Reorder JS RPC message size exception

---

src/workerd/api/streams/standard.c++

Changes the `ReadPendingScope` from a struct to a function that includes (hopefully) appropriate error handling logic.

Improve streams ReadPendingScope cleanup

---

src/workerd/io/worker.c++

Since this is for debugging only, we don't really need to be so strict.
Fixes #1563.

Increase size limit for inspector protocol messages.

---

src/workerd/api/actor-state-test.c++
src/workerd/api/crypto-impl-aes-test.c++
src/workerd/io/hibernation-manager.c++
src/workerd/io/worker.c++
src/workerd/jsg/jsg.c++
src/workerd/jsg/jsg.h

Depends on https://github.com/cloudflare/workerd/pull/1565 which needs to land first

Refactor js.enterContextScope() to JSG_WITHIN_CONTEXT_SCOPE macro

---

src/workerd/io/io-context.c++
src/workerd/io/observer.h

Add support for counting invocations of now()

---

src/workerd/api/streams/transform.c++

Sets up backpressure on the readable-side of a JS-backed `TransformStream` by default.

Set backpressure by default on JS-backed TransformStream

---

src/workerd/api/web-socket.c++
src/workerd/api/web-socket.h

Reverts cloudflare/workerd#1537

Revert "Try to take lock when delivering websocket events"

---

WORKSPACE
src/workerd/io/worker-interface.c++
src/workerd/util/abortable.h

Capnp PR: https://github.com/capnproto/capnproto/pull/1885

Add implementations for getPreferredExtensions

---

src/workerd/api/http.c++
src/workerd/api/r2-bucket.c++
src/workerd/api/util.c++
src/workerd/api/util.h
src/workerd/util/mimetype-test.c++
src/workerd/util/mimetype.c++
src/workerd/util/mimetype.h

Fixes: https://github.com/cloudflare/workerd/issues/528

Avoid false-positives in content-type text warning

---

src/workerd/server/server.c++

kj::GlobFilter was added to capnproto. We can remove it here.

Switch to using kj::GlobFilter

---

src/workerd/api/sql.h
src/workerd/api/trace.c++
src/workerd/api/trace.h
src/workerd/io/BUILD.bazel
src/workerd/io/trace.h

... and one small related warning squash in sql.h

Add heap snapshot memory tracker to api/trace.h

---

src/workerd/server/server-test.c++

server-test has always featured a mock timer. The idea behind this is that the test can simulate the passage of time by advancing the timer explicitly, rather than waiting for real time to pass.
Apparently, there was some confusion about this, and we ended up with code in the test which tried to pass time by busy-looping while watching the real clock. This is completley unnecessary.

Reduce server-test runtime from >3min to <1.5s.

---

src/pyodide/internal/asgi.py

This makes the env parameter available in fastapi, though in a somewhat obscure way. Will have to investigate how to improve the user interface for this. Tested downstream.
cc @garrettgu10 @dom96

Python/fastapi: Update asgi.py to pass request environment

---

WORKSPACE
tools/windows/install-deps.bat

As suggested by @fhanau on #1645.

Update rules_python to use 3.12

---

src/node/internal/internal_inspect.ts
src/workerd/api/http-test.js
src/workerd/jsg/resource.h

Hey! 👋 #1294 introduced Node-like logging for `workerd`, including for JSG resource types. Formatting for resource types is implemented in JavaScript, and uses `Object.getOwnPropertyNames()` to get the list of properties to display. Unfortunately, this included properties where the getters returned `jsg::Unimplemented`. Accessing these properties throws an exception. This change records unimplemented properties and skips them when formatting. I'm using `!Gcb::enumerable` as a signal for "`Getter`-returning unimplemented", since as far as I can tell, that's the only time it's `false`. I tired to see if we could use a JavaScript function like `Object.prototype.propertyIsEnumerable()` or `Object.getOwnPropertyDescriptor(s)()` inside the formatter to avoid C++ changes, but …

Ignore unimplemented resource type properties in `util.inspect()`

---

src/workerd/jsg/jsg.h
src/workerd/jsg/resource.h
src/workerd/jsg/wrappable.h

Reverts cloudflare/workerd#1700
I will now create a matching PR in edgeworker to update the test case that was failing 🥵

Revert "Revert "Add toStringTag value on JSG resource types""

---

src/workerd/api/global-scope.c++

This is an attempt at making alarm handler timeouts less noisy. Comments are welcomed.

Make alarm handler timeout less noisy

---

src/workerd/util/sentry.h

Maybe a general LOG_PERIODICALLY would be useful too, so users could just pass in whatever warning level they'd like?

add LOG_PERIODICALLY and LOG_ONCE

---

src/workerd/api/streams/common.h
src/workerd/api/streams/queue.h
src/workerd/api/streams/standard.c++
src/workerd/api/streams/standard.h
src/workerd/api/tests/streams-test.js

Reverting a handful of streams commits that landed this week. There's at least one bug in here that was hit in production that wasn't caught by current test coverage. I need to find it and figure out where the test coverage gap is. I don't have time at the moment to go through these so safer to revert the set, investigate, then I will reapply the changes with additional tests.

Revert recent streams commits

---

src/workerd/jsg/promise.h

This logging will be temporary. We want to enable the promise wrapper to support custom thenables but we need to make sure it won't be a breaking change.
This will log in cases like:
```js
const rs = new ReadableStream({
start() {
return { then() {} };
}
});
```
or
```js
ctx.waitUntil({ then() {} });
```

Emit a warning if promise wrapper encounters a possible thenable

---

WORKSPACE
src/workerd/api/tests/url-test.js

Fixes: https://github.com/cloudflare/workerd/issues/1777
Refs: https://github.com/ada-url/ada/pull/606
/cc @anonrig

Bump ada-url to 2.7.7, add test for URLSearchParams pct-encoding

---

src/workerd/api/streams/standard.c++

Further necessary simplification of JS-backed readable stream.
Like the previous change with `AllReader`, this modifies `PumpToReader` so that we do not move the underlying `kj::Own<ValueReadable>` or `kj::Own<ByteReadable>` out of the stream into the `PumpToReader`. This allows us to remove `AllReaderBase` and eliminate the buggy logic around changing the ownership of the `ValueReadable` and `ByteReadable`.
This allows us to further simplify other bits in`ReaddableStreamJsController` while we're at it.

Simplify PumpToReader, eliminate AllReaderBase

---

src/pyodide/python-entrypoint-helper.js

After #1780, we now instantiate mainModule at top level (if not in workerd). In that case we can determine the handler exports directly from the functions that are defined on the Python module.

Determine handler exports from Python module

---

src/workerd/util/sqlite-test.c++

I was curious about how we might use read-only databases in conjuction with read/write databases, so I wrote up these test cases to prove to myself that they work they way I expect.  We might as well keep them in the code base since they’re good confidence tests!

Add tests for read-only SQLite databases

---

.github/DISCUSSION_TEMPLATE/python_package_request.yml

fixes errors from https://github.com/cloudflare/workerd/pull/1810. See https://github.com/cloudflare/workerd/blob/main/.github/DISCUSSION_TEMPLATE/python_package_request.yml

Fix issues with Python discussion template

---

.github/DISCUSSION_TEMPLATE/python_package_request.yml

Verified that this _actually_ fixes things here: https://github.com/irvinebroque/test-discussion-template/blob/main/.github/DISCUSSION_TEMPLATE/foo.yml
refs https://github.com/cloudflare/workerd/pull/1810 and https://github.com/cloudflare/workerd/pull/1813

Discussion template fix

---

WORKSPACE
patches/v8/0001-Allow-manually-setting-ValueDeserializer-format-vers.patch
patches/v8/0002-Allow-manually-setting-ValueSerializer-format-versio.patch
patches/v8/0003-Add-ArrayBuffer-MaybeNew.patch
patches/v8/0004-Allow-Windows-builds-under-Bazel.patch
patches/v8/0005-Disable-bazel-whole-archive-build.patch
patches/v8/0006-Make-v8-Locker-automatically-call-isolate-Enter.patch
patches/v8/0007-Add-an-API-to-capture-and-restore-the-cage-base-poin.patch
patches/v8/0008-Speed-up-V8-bazel-build-by-always-using-target-cfg.patch
patches/v8/0009-Implement-Promise-Context-Tagging.patch
patches/v8/0010-Enable-V8-shared-linkage.patch
patches/v8/0011-Randomize-the-initial-ExecutionContextId-used-by-the.patch
patches/v8/0012-Always-enable-continuation-preserved-data-in-the-bui.patch
patches/v8/0013-Attach-continuation-context-to-Promise-thenable-task.patch
patches/v8/0014-increase-visibility-of-virtual-method.patch
patches/v8/0015-Add-ValueSerializer-SetTreatFunctionsAsHostObjects.patch

This PR just updates v8 to version 12.3.

Update to v8 12.3

---

src/workerd/jsg/jsvalue.c++
src/workerd/jsg/jsvalue.h

Separated out from the module registry refactor. Very simple addition, just want to shrink the acutal module registry refactor a bit to make it easier to land/review.
Refs: https://github.com/cloudflare/workerd/pull/1553

Add JsValue::strictEquals method

---

src/workerd/api/streams/standard.c++
src/workerd/api/streams/standard.h

More simplification of the JS-backed streams... 
Previously, the code was needlessly jumping through a few weakref hoops to try to avoid a hard circular ref. These can be handled just fine via tracing since v8 now more optimistically gc'ing wrapper objects. Long overdue change.

More JS stream simplifications

---

src/pyodide/BUILD.bazel
src/pyodide/pyodide_extra.capnp
src/workerd/server/BUILD.bazel
src/workerd/server/workerd.c++

This command simply prints the pyodide-lock.json file onto stdout and exits. 
I have no idea whether or not I'm actually supposed to print stuff out like this, someone please check my work in workerd.c++.

Add pyodide-lock command to cli

---

src/workerd/api/http.c++
src/workerd/api/http.h
src/workerd/api/tests/js-rpc-test.js
src/workerd/api/worker-rpc.c++
src/workerd/io/worker-interface.capnp
src/workerd/jsg/resource.h
src/workerd/jsg/ser-test.c++
src/workerd/jsg/ser.c++
src/workerd/jsg/ser.h
src/workerd/jsg/setup.h
src/workerd/jsg/struct.h

(Based on top of #1806 which should be ready to merge very soon.)

JSRPC: Support sending Headers, Request, and Response over RPC

---

src/node/stream/web.js
src/workerd/api/node/streams-test.js

Fixes: https://github.com/cloudflare/workerd/issues/1711

Fixup the exports in `node:stream/web`

---

src/workerd/api/tests/url-test.js
src/workerd/jsg/url.c++

Fixes: https://github.com/cloudflare/workerd/issues/1880

Fix URLPattern port handling

---

src/workerd/api/global-scope.c++

We were logging when an alarm broke its output gate after running. 
This PR will also log when output gate is broken during the alarm execution. 
This is disabling `retryAgainstLimits`. We want to be aware when, and why this happens.

Additional logging when alarm throws during execution

---

src/pyodide/internal/setupPackages.js

Remake of #1830 since too much stuff changed since then

Give a friendly message when the user specifies an unsupported package in local dev

---

src/cloudflare/internal/test/d1/BUILD.bazel
src/cloudflare/internal/test/d1/d1-api-test.py
src/cloudflare/internal/test/d1/python-d1-api-test.wd-test

Just a simple test to verify that D1 can be used in Python Workers.

Adds Python D1 binding test.

---

WORKSPACE
src/workerd/api/tests/url-test.js

Fixes a minor regression in url search param serialization

Update ada-url to 2.7.8

---

src/workerd/api/crypto-impl-asymmetric.c++
src/workerd/api/crypto-impl.c++
src/workerd/api/hyperdrive.c++
src/workerd/api/streams/internal.c++
src/workerd/api/streams/standard-test.c++
src/workerd/jsg/setup.c++
src/workerd/server/server.c++
src/workerd/server/workerd-api.c++
src/workerd/server/workerd.c++
src/workerd/util/symbolizer.c++
src/workerd/util/uuid.c++

fixing downstream clang-tidy warnings

initializing all arrays

---

src/workerd/jsg/modules-new-test.c++
src/workerd/jsg/modules-new.c++
src/workerd/jsg/modules-new.h

Iterating on the implementatin to add the mechanism for deferring evaluation outside the request context.

Continue work on new module registry, deferred eval callback

---

.github/workflows/release.yml

This is needed following https://github.com/cloudflare/workers-sdk/pull/5809.

[CI] Fix Miniflare tests by updating pnpm version

---

src/workerd/jsg/dom-exception.h

Fixes: https://github.com/cloudflare/workerd/issues/2174

Add type override for DOMException stack property

---

src/workerd/api/streams/internal.c++

The implementation was allocating a new 4096 byte buffer for each read even if the stream was errored or closed. This change avoids the unnecessary allocation.
I'll likely take another cleanup pass in this area soon to simplify a few bits and pieces since this was all written before `jsg::BufferSource` existed, but for now just making this allocation lazy will make things more efficient.

Avoid unnecessary allocation in internal stream read

---

src/node/internal/events.ts
src/workerd/api/node/node-compat-v2-test.js

https://nodejs.org/api/events.html#emittergetmaxlisteners

fix(node:events): add missing getMaxListeners and usingDomains exports

---

.bazelrc
.github/workflows/test.yml

Reverts cloudflare/workerd#2207

Revert "Revert "Disable slow tests by default""

---

src/workerd/api/r2-bucket.h

Fixes: https://github.com/cloudflare/workerd/issues/2211

Fixup r2-bucket types after update

---

src/node/crypto.ts

Fixes: https://github.com/cloudflare/workerd/issues/2172

Fixup timingSafeEqual export for node crypto

---

src/workerd/api/r2-bucket.c++
src/workerd/api/r2-bucket.h

Unfortunately the change appears to cause some breakage. Will revisit.

Revert "Optimize r2-bucket Checksums (#2201)"

---

.github/workflows/cla.yml

This will allow CLA check to pass on #2252 etc.

[CI] Fix CLA check for dependabot

---

src/workerd/io/compatibility-date.capnp

See comment for explanation.
This flag doesn't actually affect workerd behavior but will affect Cloudflare's hosting. Hence, there's no implementation in this PR, but we still need to declare all flags here.

Define global_fetch_strictly_public compat flag.

---

build/wd_ts_bundle.bzl
src/pyodide/.eslintrc.json
src/pyodide/BUILD.bazel
src/pyodide/internal/builtin_wrappers.ts
src/pyodide/internal/disk_cache.d.ts
src/pyodide/internal/jaeger.ts
src/pyodide/internal/loadPackage.ts
src/pyodide/internal/metadata.ts
src/pyodide/internal/metadatafs.ts
src/pyodide/internal/python.ts
src/pyodide/internal/readOnlyFS.ts
src/pyodide/internal/setupPackages.ts
src/pyodide/internal/snapshot.ts
src/pyodide/internal/tar.ts
src/pyodide/internal/tarfs.ts
src/pyodide/internal/topLevelEntropy/lib.ts
src/pyodide/internal/util.ts
src/pyodide/python-entrypoint-helper.ts
src/pyodide/tsconfig.json

This is initial scaffolding with all files marked with ts-ignore. More follow-up PRs will come with actual TypeScript.

Initial Migration of Pyodide Glue Code to Typescript

---

src/node/BUILD.bazel
src/node/assert/strict.ts
src/node/internal/streams_legacy.js
src/node/internal/streams_util.js
src/node/stream.js
src/node/tsconfig.json
src/node/util/types.ts

Add missing node.js util/types and fixup BUILD.bazel and tsconfig.json

---

build/wd_ts_bundle.bzl
src/pyodide/.eslintrc.json
src/pyodide/BUILD.bazel
src/pyodide/internal/builtin_wrappers.ts
src/pyodide/internal/disk_cache.d.ts
src/pyodide/internal/jaeger.ts
src/pyodide/internal/loadPackage.ts
src/pyodide/internal/metadata.ts
src/pyodide/internal/metadatafs.ts
src/pyodide/internal/python.ts
src/pyodide/internal/readOnlyFS.ts
src/pyodide/internal/setupPackages.ts
src/pyodide/internal/snapshot.ts
src/pyodide/internal/tar.ts
src/pyodide/internal/tarfs.ts
src/pyodide/internal/topLevelEntropy/lib.ts
src/pyodide/internal/util.ts
src/pyodide/python-entrypoint-helper.ts
src/pyodide/tsconfig.json

Reverts cloudflare/workerd#2267
Now we hopefully have fixed the Windows build so we can merge it in

Revert "Revert "Initial Migration of Pyodide Glue Code to Typescript""

---

src/workerd/api/worker-rpc.c++
src/workerd/io/io-context.h
src/workerd/io/io-own.c++
src/workerd/io/io-own.h

All of these were spotted by @jclee.

JSRPC: Fix misc bugs

---

src/workerd/server/workerd.c++

It will use context.exit() for fast shutdown and normal control flow for clean shutdown.
This lets us restore noexcept on serve* functions. noreturn is still not applicable.

better KJ_CLEAN_SHUTDOWN support

---

src/workerd/api/streams/standard-test.c++
src/workerd/io/actor-cache-test.c++
src/workerd/io/actor-cache.c++
src/workerd/io/actor-sqlite.c++
src/workerd/io/worker.c++
src/workerd/jsg/BUILD.bazel
src/workerd/jsg/jsg-test.h
src/workerd/jsg/modules-new-test.c++
src/workerd/jsg/util.c++
src/workerd/jsg/value.h
src/workerd/util/autogate.c++
src/workerd/util/autogate.h

Cleans up the "updated-actor-exception-types" and "actor-exception-properties" autogates

Actor exception autogate cleanup

---

WORKSPACE
src/workerd/api/blob.c++
src/workerd/api/cache.c++
src/workerd/api/html-rewriter.c++
src/workerd/api/http.c++
src/workerd/api/kv.c++
src/workerd/api/queue.c++
src/workerd/api/r2-rpc.c++
src/workerd/api/streams/common.h
src/workerd/api/streams/compression.c++
src/workerd/api/streams/internal-test.c++
src/workerd/api/streams/internal.c++
src/workerd/api/streams/internal.h
src/workerd/api/streams/readable.c++
src/workerd/api/streams/standard.c++
src/workerd/api/streams/writable.c++
src/workerd/api/system-streams.c++
src/workerd/io/worker.c++
src/workerd/server/server-test.c++
src/workerd/server/server.c++
src/workerd/tests/test-fixture.c++
src/workerd/util/stream-utils.c++

This is downstream of https://github.com/capnproto/capnproto/pull/2041

ArrayPtr-based async write api

---

src/workerd/util/autogate.c++
src/workerd/util/autogate.h

Per discussion on PR #2297:
https://github.com/cloudflare/workerd/pull/2297#discussion_r1646760004

Add initAutogateNamesForTest() convenience method

---

src/workerd/io/worker.c++

Not sure how exactly to trigger this but the problem is obvious enough.

Fix obscure null pointer crash in alarms.

---

src/workerd/api/streams/internal.c++

See comment for explanation.
Tests in internal codebase.

Fix response body write() hanging on request cancellation.

---

src/workerd/api/modules.h
src/workerd/api/node/async-hooks.h
src/workerd/api/node/buffer.h
src/workerd/api/node/crypto.h
src/workerd/api/node/diagnostics-channel.h
src/workerd/api/node/node.h
src/workerd/api/node/util.h
src/workerd/api/pyodide/pyodide.h
src/workerd/api/rtti.h
src/workerd/api/sockets.h
src/workerd/api/unsafe.h
src/workerd/api/worker-rpc.h
src/workerd/io/compatibility-date.capnp
src/workerd/io/worker.c++
src/workerd/jsg/BUILD.bazel
src/workerd/jsg/jsg.h
src/workerd/jsg/modules-new-test.c++
src/workerd/jsg/modules-new.c++
src/workerd/jsg/modules-new.h
src/workerd/jsg/resource.h
src/workerd/jsg/url.c++
src/workerd/jsg/url.h
src/workerd/server/server.c++
src/workerd/server/workerd-api.c++
src/workerd/server/workerd-api.h
src/workerd/tests/test-fixture.c++

Work in progress .... additional work towards enabling the new module registry implementation. Still a lot more to do here...

More implementation for the new module registry

---

WORKSPACE
src/workerd/io/worker.c++
src/workerd/server/server.c++

See https://github.com/capnproto/capnproto/pull/2079.

Pull in capnproto promise continuation refactor

---

WORKSPACE
src/workerd/io/worker-interface.c++
src/workerd/util/abortable.h

KJ PR: https://github.com/capnproto/capnproto/pull/2095

Update code for WebSocket disconnect() signature change.

---

WORKSPACE
patches/v8/0018-Update-illegal-invocation-error-message-in-v8.patch
src/workerd/jsg/jsg-test.c++
src/workerd/jsg/resource-test.c++
src/workerd/jsg/resource.h

~~An internal PR adding the v8 patch to the internal repo will also be necessary here. I want to make sure we are good with this approach, however, before opening that.~~

Improve illegal invocation error in the runtime

---

.bazelrc
WORKSPACE
package.json
pnpm-lock.yaml
rust-deps/crates/BUILD.ahash-0.8.11.bazel
rust-deps/crates/BUILD.bazel
rust-deps/crates/BUILD.cc-1.1.3.bazel
rust-deps/crates/BUILD.clang-ast-0.1.25.bazel
rust-deps/crates/BUILD.cssparser-macros-0.6.1.bazel
rust-deps/crates/BUILD.derive_more-0.99.18.bazel
rust-deps/crates/BUILD.log-0.4.22.bazel
rust-deps/crates/BUILD.lol_html-1.2.1.bazel
rust-deps/crates/BUILD.lolhtml-1.1.1.bazel
rust-deps/crates/BUILD.selectors-0.22.0.bazel
rust-deps/crates/BUILD.serde-1.0.204.bazel
rust-deps/crates/BUILD.serde_derive-1.0.204.bazel
rust-deps/crates/BUILD.serde_json-1.0.120.bazel
rust-deps/crates/BUILD.syn-2.0.71.bazel
rust-deps/crates/BUILD.thiserror-1.0.62.bazel
rust-deps/crates/BUILD.thiserror-impl-1.0.62.bazel
rust-deps/crates/BUILD.zerocopy-0.7.35.bazel
rust-deps/crates/BUILD.zerocopy-derive-0.7.35.bazel
rust-deps/crates/defs.bzl
types/test/index.spec.ts

- Minor WORKSPACE and .bazelrc cleanup

[build] Roll Rust and TS versions, assorted dependencies

---

types/defines/ai.d.ts

add @cf/meta/llama-3.1-8b-instruct model to types

Types: add @cf/meta/llama-3.1-8b-instruct model to types

---

src/workerd/api/node/zlib-util.c++
src/workerd/api/node/zlib-util.h

Fixes internal build to fail due to clash in function naming

fix edgeworker clashing with zlib function

---

src/cloudflare/internal/images-api.ts
src/cloudflare/internal/images.d.ts
src/cloudflare/internal/test/images/BUILD.bazel
src/cloudflare/internal/test/images/images-api-test.js
src/cloudflare/internal/test/images/images-api-test.wd-test
src/cloudflare/internal/test/images/images-upstream-mock.js
src/cloudflare/internal/test/images/tsconfig.json
types/defines/images.d.ts

This creates a new TS binding that allows image transformations and makes it available as an internal Cloudflare binding.

IMAGES-1177: Implement wrapped Images binding

---

justfile

Update clang to 18 and add several alias

add more recipes to justfile

---

src/workerd/jsg/jsg-test.c++
src/workerd/jsg/jsg.c++
src/workerd/jsg/jsg.h
src/workerd/jsg/setup.c++
src/workerd/jsg/setup.h

Reflecting additional feedback from Kenton

Refine the ExternalMemoryAdjuster API more

---

src/workerd/io/compatibility-date.capnp

Also fix compatDisableFlag documentation according to Kenton's comment.

EW-8589: Add a compatDisableFlag for allow_custom_ports.

---

src/workerd/util/mimetype.c++

An alternative to speed up `isTokenChar()` detection.

improve mimetype performance

---

src/workerd/server/tests/python/py_wd_test.bzl

we'll start enforcing different timeouts soon

[nfc] marking python tests as enormous

---

build/kj_test.bzl
src/workerd/server/BUILD.bazel

I see instances of it failed with 15s timeout

mark server-test as large

---

src/workerd/api/data-url.c++
src/workerd/api/form-data.c++
src/workerd/util/mimetype.c++

Small performance improvements on workerd/api

small perf improvements on workerd/api

---

src/workerd/api/BUILD.bazel

Also marking sql-test as large since it is slow sometimes.

[nfc] explicit test targets

---

build/wd_ts_bundle.bzl

15s is not good enough sometimes

[nfc] make eslint a large test

---

WORKSPACE

This requires an internal pull-request before landing.

update ada to v2.9.1

---

src/node/internal/internal_zlib_base.ts
src/node/internal/zlib.d.ts
src/workerd/api/node/tests/zlib-nodejs-test.js
src/workerd/api/node/zlib-util.c++
src/workerd/api/node/zlib-util.h
src/workerd/jsg/buffersource.h

Improves nodejs compat and adds a test that fails without the changes in the pull-request.

improve zlib for nodejs_compat

---

src/workerd/api/streams/internal.c++

When using the new proactive non-lazy drain compat flag, we missed a few necessary checks during the write loop

Account for the queue already having been drained

---

.github/workflows/test.yml

I made a small mistake in #2614

Fix wrongly triggered GH workflows on merge

---

tools/unix/create-internal-pr.sh

For the benefit of those whose /bin/sh implementation isn't bash / npaun learns to POSIX more good

Fix internal PR tool

---

src/workerd/api/node/tests/zlib-nodejs-test.js

simplify zlib tests

---

src/workerd/api/node/tests/zlib-nodejs-test.js
src/workerd/api/node/util.h
src/workerd/api/node/zlib-util.c++

Fixes zlib input and output boundary check

fix zlib buffers bound check

---

src/workerd/api/global-scope.c++
src/workerd/api/global-scope.h

Similar optimization was done on Node.js several months ago.

improve the performance of btoa

---

src/workerd/api/node/tests/zlib-nodejs-test.js

enable zlib test

---

src/workerd/api/eventsource.h
src/workerd/api/tests/eventsource-test.js

Fixes: https://github.com/cloudflare/workerd/issues/2698

Make EventSource extend EventTarget

---

src/workerd/io/compatibility-date-test.c++
src/workerd/io/compatibility-date.capnp

Let's merge this once the existing bugs are fixed.

remove the need for `nodejs_zlib` flag

---

src/workerd/api/node/BUILD.bazel
src/workerd/api/node/zlib-util.c++
src/workerd/api/node/zlib-util.h
src/workerd/api/streams/compression.c++
src/workerd/api/streams/compression.h
src/workerd/io/BUILD.bazel

Let's also inform v8 about the allocations that we've made.

use `ExternalMemoryAdjuster` on zlib allocations

---

src/workerd/api/util.c++

Improved the performance of `toUpper` and `toLower` functionality by introducing SWAR routines.

introduce swar routines for capitalization

---

src/workerd/api/sql-test.js
src/workerd/api/sql.c++
src/workerd/api/sql.h
types/test/types/do.ts

(I don't actually know how to run the type test so I hope it just works.)

SQL: Add next(), toArray(), and one() methods to cursor.

---

src/workerd/api/http.h

Removes the incorrect declaration.

remove incorrect websocket ts override

---

src/workerd/api/tests/global-scope-test.js
src/workerd/jsg/jsg-test.c++
src/workerd/jsg/resource.h

Fixes: https://github.com/cloudflare/workerd/issues/2769
Fixes: https://github.com/cloudflare/workerd/issues/2750

Add Symbol.toStringTag to jsg::Objects

---

src/workerd/api/http.h

Reverts websocket changes
Fixes https://github.com/cloudflare/workerd/issues/2765

revert websocket changes to unblock wrangler

---

build/deps/update-deps.py

not sure why it passed yesterday. Sorry for breakage.

[nfc] fixed lint

---

justfile

Adds a simple just command to run benchmarks.

add just command for running benchmarks

---

src/workerd/api/node/i18n.c++

Avoid creating a disposer when you can directly call `disposeWith<disposeFunction>()`

avoid creating a disposer on i18n

---

WORKSPACE

Tests are passing. Let me know if I need to do any manual verification as well or if we're good to go.

Upgrade perfetto to v47

---

src/workerd/jsg/BUILD.bazel
src/workerd/jsg/value.h

Improves StringWrapper `kj::Maybe<ByteString> tryUnwrap` performance

improve stringwrapper bytestring unwrap

---

WORKSPACE
docs/v8-updates.md
patches/v8/0001-Allow-manually-setting-ValueDeserializer-format-vers.patch
patches/v8/0002-Allow-manually-setting-ValueSerializer-format-versio.patch
patches/v8/0003-Add-ArrayBuffer-MaybeNew.patch
patches/v8/0004-Allow-Windows-builds-under-Bazel.patch
patches/v8/0005-Disable-bazel-whole-archive-build.patch
patches/v8/0006-Speed-up-V8-bazel-build-by-always-using-target-cfg.patch
patches/v8/0007-Implement-Promise-Context-Tagging.patch
patches/v8/0008-Enable-V8-shared-linkage.patch
patches/v8/0009-Randomize-the-initial-ExecutionContextId-used-by-the.patch
patches/v8/0010-increase-visibility-of-virtual-method.patch
patches/v8/0011-Add-ValueSerializer-SetTreatFunctionsAsHostObjects.patch
patches/v8/0012-Set-torque-generator-path-to-external-v8.-This-allow.patch
patches/v8/0013-Modify-where-to-look-for-fp16-dependency.-This-depen.patch
patches/v8/0014-Expose-v8-Symbol-GetDispose.patch
patches/v8/0015-Rename-V8_COMPRESS_POINTERS_IN_ISOLATE_CAGE-V8_COMPR.patch
patches/v8/0016-Revert-TracedReference-deref-API-removal.patch
patches/v8/0017-Revert-heap-Add-masm-specific-unwinding-annotations-.patch
patches/v8/0018-Update-illegal-invocation-error-message-in-v8.patch
patches/v8/0019-Implement-cross-request-context-promise-resolve-hand.patch
patches/v8/0020-Modify-where-to-look-for-fast_float-dependency.patch
src/workerd/jsg/v8-platform-wrapper.h
src/workerd/server/v8-platform-impl.h

Thanks to @erikcorry for the help with this one!

Update v8 to 13.0

---

src/workerd/api/hibernatable-web-socket.c++
src/workerd/api/hibernatable-web-socket.h
src/workerd/api/queue.c++
src/workerd/api/queue.h
src/workerd/api/trace.c++
src/workerd/api/trace.h
src/workerd/api/worker-rpc.c++
src/workerd/api/worker-rpc.h
src/workerd/io/hibernation-manager.c++
src/workerd/io/worker-entrypoint.c++
src/workerd/io/worker-interface.c++
src/workerd/io/worker-interface.h
src/workerd/io/worker.c++
src/workerd/server/server.c++

Reverts cloudflare/workerd#2863

Revert "Change WorkerInterface so prewarm returns a promise."

---

.vscode/settings.json
justfile

path needs to be absolute for it to work

[nfc] clangd tweaks

---

src/workerd/api/hibernatable-web-socket.c++
src/workerd/api/hibernatable-web-socket.h
src/workerd/api/queue.c++
src/workerd/api/queue.h
src/workerd/api/trace.c++
src/workerd/api/trace.h
src/workerd/api/worker-rpc.c++
src/workerd/api/worker-rpc.h
src/workerd/io/hibernation-manager.c++
src/workerd/io/worker-entrypoint.c++
src/workerd/io/worker-interface.c++
src/workerd/io/worker-interface.h
src/workerd/io/worker.c++
src/workerd/server/server.c++

Change WorkerInterface so prewarm returns a promise.

Restore: Change WorkerInterface so prewarm returns a promise.

---

src/node/diagnostics_channel.ts

As described in the commit title.

enable eslint on diagnostics_channel impl

---

src/workerd/api/cache.c++
src/workerd/api/memory-cache.c++
src/workerd/io/io-context.c++
src/workerd/io/io-context.h
src/workerd/io/observer.h
src/workerd/io/trace.c++
src/workerd/io/trace.h

Rename lime tracing => user tracing

---

src/node/internal/internal_path.ts
src/node/internal/internal_url.ts
src/workerd/api/node/tests/path-test.js
src/workerd/api/node/tests/url-nodejs-test.js

Node.js recently reverted some changes due to a bug. Ref: https://github.com/nodejs/node/commit/ee46d2297c648dc6cc8cbc0327c453514b878294#diff-092f2be30e312ebf7517f3d5f08b4c8d38a4bea3449ab15eb87f408a8f301dffL194

apply latest changes to node.js to fix path

---

src/workerd/io/io-context.c++
src/workerd/io/observer.h

Use an RAII pattern to simplify task metrics accounting

Small simplification to metrics task accounting

---

src/pyodide/internal/snapshot.ts
src/pyodide/types/FS.d.ts
src/pyodide/types/artifacts.d.ts

NFC Python: Tidy up some typescript types

---

src/workerd/api/hibernatable-web-socket.h
src/workerd/api/queue.h
src/workerd/api/trace.h
src/workerd/api/worker-rpc.h
src/workerd/io/worker-interface.h
src/workerd/server/server.c++

CustomEvent::notSupported method to raise appropriate error (if any)

---

src/workerd/api/pyodide/pyodide.c++

If we reuse the bundle for too many different isolates we were getting an error. As suggested in the capnproto docs, this copies the data to a `MallocMessageBuilder` which then doesn't enforce the limit. Tested downstream.

Python external capnproto: fix "Exceeded message traversal limit" error

---

src/workerd/jsg/setup.c++
src/workerd/jsg/setup.h

Replaces several reinterpret_cast with static_cast on setup files.

use static_cast rather than reinterpret_cast

---

src/workerd/api/node/tests/path-test.js
src/workerd/api/node/tests/path-test.wd-test
src/workerd/api/node/tests/util-nodejs-test.js

Validates https://github.com/unjs/unenv/pull/344 and add missing tests.

add missing tests for node:path/* and node:util/types

---

src/node/path/posix.ts
src/node/path/win32.ts

Add named exports for node:path/win32 and node:path/posix

---

samples/tail-workers/config.capnp
samples/tail-workers/tail.js
samples/tail-workers/worker.js
src/workerd/api/trace.h
src/workerd/server/server.c++
src/workerd/server/workerd.capnp
src/workerd/util/http-util.h

Enables tail workers for local development in workerd

Implement original tail worker support for local dev

---

build/wd_js_bundle.bzl
build/wd_test.bzl
build/wd_ts_bundle.bzl
src/pyodide/BUILD.bazel

data should flow from top to bottom and not sideways

[nfc] fixing *bundle rules dataflow

---

src/workerd/server/server-test.c++
src/workerd/server/server.c++

This worked originally but #1222 accidentally broke it in an attempt to fix a compiler warning about dropped promises. And, unfortunately, the test didn't catch it.
This only affects workerd, not the edge runtime.
Fixes #3000

Fix draining: Connections should stop being accepted after SIGTERM.

---

.github/workflows/_bazel.yml
.github/workflows/test.yml

This will require tweaking our project configuration after landing (required checks)
The idea is to invoke this workflow in other scenarios too. I'm working on lint, would like to refactor release.yaml too.

github actions: extract common bazel workflow

---

src/workerd/io/compatibility-date.capnp

Docs: https://github.com/cloudflare/cloudflare-docs/pull/18075

Ungate global_fetch_strictly_public compatibility flag

---

src/node/internal/buffer.d.ts
src/node/internal/internal_buffer.ts
src/workerd/api/node/buffer.c++
src/workerd/api/node/buffer.h
src/workerd/api/node/i18n.c++
src/workerd/api/node/i18n.h
src/workerd/api/node/tests/buffer-nodejs-test.js
src/workerd/jsg/buffersource.h

Ensure more allocations are known to the Isolate and occur within the Isolate allocators

Update Node.js buffer.transcode to use BufferSource

---

src/workerd/jsg/setup.c++
src/workerd/jsg/wrappable.h

This will let me upgrade it without juggling too many PRs in the process.

v8 13.2 support

---

src/workerd/api/crypto/hkdf.c++
src/workerd/api/crypto/kdf.h
src/workerd/api/crypto/pbkdf2.c++
src/workerd/api/crypto/scrypt.c++
src/workerd/api/node/crypto.c++
src/workerd/api/node/crypto.h

Reverts cloudflare/workerd#3111
This PR doesn't pass asan build.

Revert "Update node crypto kdf apis to use BufferSource"

---

src/workerd/api/modules.h
src/workerd/api/pyodide/pyodide.c++
src/workerd/api/pyodide/pyodide.h
src/workerd/server/workerd-api.c++

NFC Pyodide Rename PackagesTarReader to ReadOnlyBuffer and remove 0-arg constructor

---

src/workerd/api/blob.h
src/workerd/api/http.h
src/workerd/api/r2-bucket.h

Fixes https://github.com/cloudflare/workerd/issues/3186

Add overrides for arrayBuffer() types

---

.github/workflows/type-snapshot.yml
types/generated-snapshot/2021-11-03/index.d.ts
types/generated-snapshot/2021-11-03/index.ts
types/generated-snapshot/2022-01-31/index.d.ts
types/generated-snapshot/2022-01-31/index.ts
types/generated-snapshot/2022-03-21/index.d.ts
types/generated-snapshot/2022-03-21/index.ts
types/generated-snapshot/2022-08-04/index.d.ts
types/generated-snapshot/2022-08-04/index.ts
types/generated-snapshot/2022-10-31/index.d.ts
types/generated-snapshot/2022-10-31/index.ts
types/generated-snapshot/2022-11-30/index.d.ts
types/generated-snapshot/2022-11-30/index.ts
types/generated-snapshot/2023-03-01/index.d.ts
types/generated-snapshot/2023-03-01/index.ts
types/generated-snapshot/2023-07-01/index.d.ts
types/generated-snapshot/2023-07-01/index.ts
types/generated-snapshot/experimental/index.d.ts
types/generated-snapshot/experimental/index.ts
types/generated-snapshot/oldest/index.d.ts
types/generated-snapshot/oldest/index.ts

Fixup #3188 to account for recent changes, since that PR was slightly out of date. Also include instructions for how to fix the snapshot errors

Fix snapshots to account for recent changes

---

src/pyodide/internal/asgi.py
src/workerd/server/tests/python/BUILD.bazel
src/workerd/server/tests/python/asgi/asgi.wd-test
src/workerd/server/tests/python/asgi/worker.py

Python: Fix header conversion to byte-pair on scope building

---

types/scripts/build-types.ts
types/scripts/build-worker.ts
types/src/utils.ts

I'm open to better suggestions of how to do this.
Internal PR # 9348

Enable type generation in internal repo

---

tools/unix/create-internal-pr.sh

Updates internal submodules before opening an internal pull-request.

before creating internal-pr update submodules

---

src/workerd/io/BUILD.bazel
src/workerd/io/trace.c++
src/workerd/io/trace.capnp
src/workerd/io/trace.h

This will be used to better export user tracing spans in a follow-up PR.

[nfc] Refactor and add trace span RPC code

---

src/workerd/api/r2-test.js

Add more tests within `workerd` to cover common usecases for the R2 Binding.

R2-2604: Improve R2 Binding Test Coverage

---

src/workerd/jsg/jsg.h
src/workerd/jsg/jsvalue.c++

Adds the ability to leverage a faster v8::Object creation

add ability to create v8 objects more efficiently

---

src/workerd/jsg/BUILD.bazel
src/workerd/jsg/multiple-typewrappers-test.c++

Sadly I pushed https://github.com/cloudflare/workerd/pull/3194 without a test, I am making amends for my mistakes by adding this PR with a test.

Add a test for multiple typewrappers

---

.github/workflows/npm.yml

This is blocking the release https://github.com/cloudflare/workerd/actions/runs/12351159981/job/34465880875 please approve asap

Downgrade publish-wrapper to ubuntu-20.04 same as _bazel.yml

---

build/deps/gen/dep_capnp_cpp.bzl
src/workerd/server/workerd.c++
src/workerd/util/perfetto-tracing.c++

Uses new stuff from KJ PR: https://github.com/capnproto/capnproto/pull/2205

Use KJ_SYSCALL_FD and kj::OwnFd

---

src/workerd/jsg/commonjs.c++
src/workerd/jsg/commonjs.h

Turns out there are some tests this broke on the wrangler side. Partially revert the problematic bits

Partial revert of commonjs changes

---

src/node/net.ts

Adds the remaining node:net api stubs to get rid of polyfills in wrangler.

add rest of node:net api

---

src/node/internal/internal_timers.ts

Align types with Node types
(@anonrig, with this you can drop `?? 1` in your pending PR)

fix node:timers types

---

src/workerd/api/cache.c++
src/workerd/api/http.c++
src/workerd/api/sockets.c++
src/workerd/api/streams/standard.c++
src/workerd/api/web-socket.c++
src/workerd/io/worker.c++
src/workerd/util/sqlite.c++

Using nullptr to mean an empty Maybe is deprecated.

Cleanup nullptr-as-empty-Maybe usages

---

package.json
pnpm-lock.yaml
src/cloudflare/internal/pipeline-transform.ts
src/node/diagnostics_channel.ts
src/node/internal/crypto.d.ts
src/node/internal/internal_querystring.ts
src/node/internal/internal_url.ts
src/node/internal/validators.ts
src/node/net.ts

It's never the correct time to update prettier and esbuild I guess. Let's do it.

update prettier and esbuild

---

src/node/util.ts

Last remaining methods so we can remove the polyfills on node:util and node:sys. 
Ref: https://github.com/cloudflare/workers-sdk/pull/7942

add missing node:util methods

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

This should enable us to support all platforms and architectures more
easily.

Simplify and update devcontainer

---

src/node/async_hooks.ts
src/workerd/api/node/BUILD.bazel
src/workerd/api/node/tests/async_hooks-nodejs-test.js
src/workerd/api/node/tests/async_hooks-nodejs-test.wd-test

Adds remaining async_hooks methods so we can remove the unenv polyfill.

add remaining async_hooks methods

---

src/workerd/api/queue.c++

To help debug the problem where queue consumer isolates can time out unexpectedly.

Log error when a queue consumer gets aborted

---

types/defines/ai.d.ts
types/generated-snapshot/2021-11-03/index.d.ts
types/generated-snapshot/2021-11-03/index.ts
types/generated-snapshot/2022-01-31/index.d.ts
types/generated-snapshot/2022-01-31/index.ts
types/generated-snapshot/2022-03-21/index.d.ts
types/generated-snapshot/2022-03-21/index.ts
types/generated-snapshot/2022-08-04/index.d.ts
types/generated-snapshot/2022-08-04/index.ts
types/generated-snapshot/2022-10-31/index.d.ts
types/generated-snapshot/2022-10-31/index.ts
types/generated-snapshot/2022-11-30/index.d.ts
types/generated-snapshot/2022-11-30/index.ts
types/generated-snapshot/2023-03-01/index.d.ts
types/generated-snapshot/2023-03-01/index.ts
types/generated-snapshot/2023-07-01/index.d.ts
types/generated-snapshot/2023-07-01/index.ts
types/generated-snapshot/experimental/index.d.ts
types/generated-snapshot/experimental/index.ts
types/generated-snapshot/oldest/index.d.ts
types/generated-snapshot/oldest/index.ts

Adds `@cf/deepseek-ai/deepseek-r1-distill-qwen-32b` and `@cf/unum/uform-gen2-qwen-500m` to types.

Update Workers AI Types

---

src/cloudflare/internal/d1-api.ts

As title says, simple renames of comments and the `getCommitToken()` to be `getBookmark()`.
The HTTP header sent and used by the D1 API (not public REST API), just between the D1 binding and our API remains `x-cf-d1-session-commit-token`. Its rename will be done in a separate PR when our internal API supports both headers.

D1 Sessions API - Rename commit token to bookmark for API and comments

---

src/cloudflare/internal/images-api.ts

For the Images binding we want to support streaming as images could be fairly large (perhaps up to 100Mb). As we use multipart forms at the moment this isn't trivial as FormData doesn't support streaming.
Luckily the multipart format is so simple that we can easily implement FormData with streaming, which is what this PR does.

IMAGES-1405: Add streaming support to Images binding

---

src/workerd/jsg/jsg.c++
src/workerd/jsg/jsg.h
src/workerd/jsg/setup.c++
src/workerd/jsg/setup.h

Splitting @danlapid's PR to multiple ones.
Ref: https://github.com/cloudflare/workerd/pull/3464

use v8::ExternalMemoryAccounter more

---

src/workerd/jsg/jsvalue.c++
src/workerd/jsg/jsvalue.h

Opening individual PRs for @danlapid's PR to improve debugging.
Ref: https://github.com/cloudflare/workerd/pull/3464

use new v8 api Utf8LengthV2()

---

src/workerd/api/streams/encoding.c++
src/workerd/jsg/value.h

Removes unnecessary version checks.

remove outdated v8 major version checks

---

build/wd_test.bzl

Having these unindented lines inside of a conditional block makes the flow control hard to read.

wd_test: Move template string constants to top level

---

src/workerd/jsg/value.h

Splitting @danlapid's PR into multiple ones..
Ref: https://github.com/cloudflare/workerd/pull/3464

use new v8 api WriteUtf8V2()

---

src/workerd/io/observer.h
src/workerd/io/trace-stream.c++
src/workerd/server/server.c++

Adds a function to report the outcome event, this is not being called yet.

[o11y] Fix code comments, add outcome reporting function

---

src/workerd/api/node/buffer.c++
src/workerd/api/streams/encoding.c++
src/workerd/jsg/jsvalue.h

Taken from @danlapid's PR
Ref: https://github.com/cloudflare/workerd/pull/3464

use new v8 apis

---

build/wd_test.bzl

Helps with debugging to have these in the log

Add some echos to the modified wd_test

---

src/workerd/api/crypto/aes.c++
src/workerd/api/tests/crypto-extras-test.js

Addresses internal issue EW-6631. Fixes the counter overwrite so that the initial input counter is preserved. Updates comments that were highly misleading and made it seem like this code was sound. Adds a regression test.

[crypto] Fix overwriting AES-CTR counter in case of overflow

---

build/deps/gen/dep_ada_url.bzl
src/workerd/api/tests/url-test.js
src/workerd/api/wpt/url-test.ts

update ada to v3.1.0

---

src/workerd/api/BUILD.bazel
src/workerd/io/BUILD.bazel

Splitting https://github.com/cloudflare/workerd/pull/3529 into multiple PRs

create an independent target for urlpattern

---

src/pyodide/internal/snapshot.ts

There are several bugs in `memorySnapshotDoImports` that need to be fixed and tricky behaviors that need to be worked out. This doesn't fix any of the problems but at least it will surface them to users in local development and not when they deploy their worker.

Python: also call `memorySnapshotDoImports` in local development

---

.github/workflows/internal-build.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.github/workflows/type-snapshot.yml

let's limit our scope for triggering ci

do not trigger ci if you don't need it

---

src/workerd/api/BUILD.bazel
src/workerd/api/memory-cache.c++
src/workerd/api/memory-cache.h
src/workerd/io/compatibility-date.capnp

Add functionality to remove entries from memory cache.

Implement delete operation for memory cache.

---

src/node/internal/internal_inspect.ts
src/workerd/api/cache.c++
src/workerd/api/http.h

@jasnell a few minor comment edits.

Update comments related to Response#error

---

src/node/internal/crypto_hash.ts
src/node/internal/crypto_util.ts

enable eslint and typescript warnings for crypto_hash

---

src/node/internal/crypto.d.ts
src/node/internal/crypto_keys.ts

enable eslint and typescript warnings for crypto_keys

---

src/node/internal/crypto_spkac.ts

enable eslint and typescript warnings for crypto_spkac

---

src/node/internal/crypto_dh.ts

enable eslint and typescript warnings for crypto_dh

---

src/node/internal/crypto_hkdf.ts

enable eslint and typescript warnings for crypto_hkdf

---

src/node/internal/crypto_pbkdf2.ts

enable eslint and typescript warnings for crypto_pbkdf2

---

types/defines/ai.d.ts
types/generated-snapshot/2021-11-03/index.d.ts
types/generated-snapshot/2021-11-03/index.ts
types/generated-snapshot/2022-01-31/index.d.ts
types/generated-snapshot/2022-01-31/index.ts
types/generated-snapshot/2022-03-21/index.d.ts
types/generated-snapshot/2022-03-21/index.ts
types/generated-snapshot/2022-08-04/index.d.ts
types/generated-snapshot/2022-08-04/index.ts
types/generated-snapshot/2022-10-31/index.d.ts
types/generated-snapshot/2022-10-31/index.ts
types/generated-snapshot/2022-11-30/index.d.ts
types/generated-snapshot/2022-11-30/index.ts
types/generated-snapshot/2023-03-01/index.d.ts
types/generated-snapshot/2023-03-01/index.ts
types/generated-snapshot/2023-07-01/index.d.ts
types/generated-snapshot/2023-07-01/index.ts
types/generated-snapshot/experimental/index.d.ts
types/generated-snapshot/experimental/index.ts
types/generated-snapshot/oldest/index.d.ts
types/generated-snapshot/oldest/index.ts

+ Adding types for new "@cf/meta/llama-guard-3-8b" model
+ updating text-gen types to support "response_format"
+ lint changes

Update AI types

---

src/node/internal/crypto_scrypt.ts

enable eslint and typescript warnings for crypto_scrypt

---

src/cloudflare/eslint.config.mjs
src/cloudflare/internal/d1-api.ts
src/cloudflare/internal/pipeline-transform.ts
src/node/eslint.config.mjs
src/node/internal/crypto_scrypt.ts
src/node/internal/internal_dns.ts
src/node/internal/internal_dns_client.ts
src/wpt/eslint.config.mjs
tools/base.eslint.config.mjs

I realized that if we keep using "warning" log level for some eslint rules, noone will fix them. So, let's make them error, and also remove an unnecessary eslint rule.

replace eslint warnings with errors

---

src/workerd/api/queue.c++

As requested on #3647. It's possible that this would benefit from being split up into multiple functions, but I don't really want to mess with the actual code any more until I'm back from my time off unless absolutely needed.
@jbwcloudflare @jasnell

Add comments explaining the intended flow of QueueCustomEventImpl::run

---

src/cloudflare/internal/ai-api.ts

Merge two if conditions because of redundant behavior in both

Simplify throw condition AI binding

---

src/workerd/api/node/buffer.c++

This allows us to expand downstream UBSan coverage. Also see the downstream PR.

Fix minor UBSan violation in buffer-nodejs-test

---

src/workerd/api/node/buffer.c++

We should really have a UBSan CI job here too (even if it's just to catch things like this)

[build] Fix UBSan compilation following #3674

---

src/node/internal/crypto_dh.ts
src/workerd/api/node/crypto-keys.c++
src/workerd/api/node/tests/crypto_dh-test.js

Other named curves using ec keys still not supported and will remain unsupported for the time being.

Support x25519 for stateless diffieHellman

---

src/workerd/io/io-context.c++
src/workerd/io/io-context.h
src/workerd/io/io-own.c++
src/workerd/io/io-own.h

All const method changes were (correctly) forced upon me by compiler
This demonstrates (and depends on) https://github.com/capnproto/capnproto/pull/2251

Arc-ify IoOwn

---

src/workerd/api/global-scope.c++
src/workerd/api/tests/new-module-registry-test.js
src/workerd/io/io-context.c++
src/workerd/io/io-context.h
src/workerd/io/worker.c++
src/workerd/jsg/BUILD.bazel
src/workerd/jsg/jsg.c++
src/workerd/jsg/jsg.h
src/workerd/jsg/modules-new-test.c++
src/workerd/jsg/modules-new.c++
src/workerd/jsg/modules-new.h
src/workerd/jsg/setup.h
src/workerd/server/server.c++
src/workerd/server/server.h
src/workerd/server/workerd-api.c++
src/workerd/server/workerd-api.h

More work on the new module registry. This is just an interim PR to keep the change set relatively small. There are more PRs to come. As such, unless they are breaking issues I likely will make any follow on changes from code review in the next PR.

More work on new module registry

---

src/workerd/server/tests/python/BUILD.bazel

[build] disable failing test under ASan

---

.github/workflows/lint.yml
build/deps/gen/dep_ruff_darwin_arm64.bzl
build/deps/gen/dep_ruff_linux_amd64.bzl
build/deps/gen/dep_ruff_linux_arm64.bzl
build/deps/update-deps.py
src/pyodide/internal/patches/aiohttp.py

update ruff to 0.11

---

src/workerd/api/tests/js-rpc-socket-test.wd-test
src/workerd/api/tests/js-rpc-test.js
src/workerd/api/tests/js-rpc-test.wd-test
src/workerd/api/worker-rpc.c++
src/workerd/api/worker-rpc.h

See commits.
I tried using Claude Code to help debug this, fully expecting it would be too hard for it. Indeed, it flailed around a fair amount, proposing several non-fixes that weren't anywhere near the right location. But much to my surprise it then suddenly identified the problem fixed in the first commit -- which I hadn't actually found myself yet. I was pretty shocked because it requires a pretty deep understanding of the RPC system to get what's going on there... Mostly though this change is my own work rather than Claude's.

JSRPC: Fix multiple bugs with proxy pipelining

---

src/workerd/io/compatibility-date.capnp

This is going to be used by Workers Assets inside our asset-worker: https://github.com/cloudflare/workers-sdk/pull/8443

Add a compatibility flag for assets_navigation_prefers_asset_serving

---

src/node/internal/streams_duplex.d.ts
src/node/internal/streams_duplex.js
src/node/stream.js
src/workerd/api/node/tests/streams-test.js

Adds missing duplexPair method.

add duplexPair method to node:streams

---

src/workerd/api/cache.c++
src/workerd/api/cache.h
src/workerd/io/compatibility-date.capnp
src/workerd/io/io-channels.h
src/workerd/server/server.c++
src/workerd/tests/test-fixture.c++

We probably should've been doing this before, but it wasn't really necessary.

Pass featureFlagsForFl to Cache API

---

src/node/dns.ts
src/node/internal/internal_dns.ts
src/node/internal/internal_dns_promises.ts
src/workerd/api/node/tests/dns-nodejs-test.js

implement node:dns lookup and resolve functions

---

src/workerd/api/node/util.c++
src/workerd/api/tests/new-module-registry-test.js
src/workerd/jsg/jsg.c++

One of several smaller PRs along these liines that I will be opening over the next week.

Ensure process.getBuiltinModule works with new registry

---

types/defines/secrets-store.d.ts
types/generated-snapshot/2021-11-03/index.d.ts
types/generated-snapshot/2021-11-03/index.ts
types/generated-snapshot/2022-01-31/index.d.ts
types/generated-snapshot/2022-01-31/index.ts
types/generated-snapshot/2022-03-21/index.d.ts
types/generated-snapshot/2022-03-21/index.ts
types/generated-snapshot/2022-08-04/index.d.ts
types/generated-snapshot/2022-08-04/index.ts
types/generated-snapshot/2022-10-31/index.d.ts
types/generated-snapshot/2022-10-31/index.ts
types/generated-snapshot/2022-11-30/index.d.ts
types/generated-snapshot/2022-11-30/index.ts
types/generated-snapshot/2023-03-01/index.d.ts
types/generated-snapshot/2023-03-01/index.ts
types/generated-snapshot/2023-07-01/index.d.ts
types/generated-snapshot/2023-07-01/index.ts
types/generated-snapshot/experimental/index.d.ts
types/generated-snapshot/experimental/index.ts
types/generated-snapshot/oldest/index.d.ts
types/generated-snapshot/oldest/index.ts

Description: 
This PR setups up an interface Secrets Store secret binding. The objective is to have an interface in a worker that can retrieve a secret from from the Secrets Store with a call like `await env.SECRET_KEY.get()`.

Create Secrets Store Proxy Worker types

---

src/wpt/url-test.ts

I happened to notice this test and realized we're already passing it due to #3686.

Re-enable IdnaTestV2.window.js

---

build/python_metadata.bzl

Should make updating the bundles easier.

Python: Move BUNDLE_VERSION_INFO into workerd

---

src/workerd/api/cache.c++
src/workerd/api/queue.c++
src/workerd/io/io-context.c++
src/workerd/io/io-context.h
src/workerd/io/worker-entrypoint.c++
src/workerd/io/worker-entrypoint.h
src/workerd/io/worker.c++
src/workerd/io/worker.h
src/workerd/server/server.c++
src/workerd/tests/test-fixture.c++
src/workerd/tests/test-fixture.h

This reverts commit 1ebab7e13f30862361f7c13ec635754121c77221.

Revert "kj::Arc<Worker>"

---

src/workerd/io/worker.c++

The destructor for `ResponseStreamWrapper` would unconditionally take the isolate lock even if it was already held, leading to "recusive isolate lock" warnings spamming sentry. This changes to check to see if the lock is already held (indirectly via checking to see if there is a current IoContext). If there is a current IoContext, do not take the lock.

Avoid taking isolate lock recursively in ResponseStreamWrapper

---

src/workerd/server/server.c++

Dont log DISCONNECTED application errors

---

src/workerd/api/form-data.c++
src/workerd/api/form-data.h

One place of the internal project requires FormData parsing but parses outside of the isolate lock and does not actually need the FormData API itself. This separates that parsing path out so that the FormData object itself is not needed. This is in preparation for changing jsg::alloc<T> to js.alloc<T>.
The new static `parseWithoutLock(...)` method is used by the internal project.

Refactor FormData parse

---

src/node/internal/internal_tls.ts
src/node/tls.ts
src/workerd/api/node/tests/tls-nodejs-test.js

More progress on nodejs_compat and node:tls

add convertALPNProtocols() to node:tls

---

justfile
src/node/internal/internal_net.ts
src/node/internal/sockets.d.ts
src/workerd/api/node/tests/net-nodejs-tcp-server.js
src/workerd/api/node/tests/net-nodejs-test.js
src/workerd/api/sockets.c++

We had a bug with "end" event not being emitted on certain edge cases.

fix Socket class end events

---

src/workerd/api/node/tests/net-nodejs-test.js

resolve a todo in node:net tests

---

src/cloudflare/internal/pipeline-transform.ts
src/cloudflare/internal/test/pipeline-transform/transform-test.js

This commit adds a safety check that the line we are going to JSON.parse
is not an empty line, which will cause JSON.parse to throw an error.
I also updated the test cases to use more data to test the chunking of
readLines function, which was rewritten to use the TextDecoderStream and
skip iterating over each character.

Skip empty lines when calling JSON.parse in Pipeline Transformations

---

src/pyodide/internal/loadPackage.ts

This will retry package fetching 3 times if it fails for any reason.

Retry Python package loading from R2 to fix flaky tests.

---

src/workerd/api/hibernatable-web-socket.c++
src/workerd/api/queue.c++
src/workerd/api/trace.c++
src/workerd/io/observer.h
src/workerd/io/tracer.c++
src/workerd/io/tracer.h
src/workerd/io/worker-entrypoint.c++
src/workerd/server/server.c++

This was easier than expected – hope I'm not missing anything here.

[o11y] Merge Streaming Tail Worker outcome event reporting into WorkerTracer

---

justfile
src/node/internal/events.ts
src/node/internal/internal_net.ts
src/node/internal/streams_duplex.js
src/node/internal/streams_readable.js
src/node/internal/streams_util.js
src/node/internal/streams_writable.js
src/workerd/api/node/BUILD.bazel
src/workerd/api/node/tests/net-nodejs-tcp-server.js
src/workerd/api/node/tests/net-nodejs-test.js
src/workerd/api/node/tests/net-nodejs-test.wd-test

Fixes abort signal edge cases and updates duplex streams to latest Node.js version

fix edge cases with node:net including abortsignal and reconnect

---

src/workerd/api/node/zlib-util.h
src/workerd/api/streams/compression.c++
src/workerd/api/streams/compression.h
src/workerd/jsg/jsg-test.c++
src/workerd/jsg/jsg.c++
src/workerd/jsg/jsg.h
src/workerd/jsg/setup.c++
src/workerd/jsg/setup.h

Fix and clean up issues with external memory tracking

---

src/node/internal/internal_net.ts
src/node/internal/internal_tls_wrap.ts
src/node/internal/sockets.d.ts
src/workerd/api/node/tests/tls-nodejs-test.js

Enables node:net streams to be passed into node:tls. The following code now works:
```typescript
import { createConnection } from "mysql2/promise";
async fetch(request, env, ctx): Promise<Response> {
// Create a connection to the MySQL database
const connection = await createConnection({
host: env.MYSQL_HOST,
user: env.MYSQL_USER,
password: env.MYSQL_PASSWORD,
database: "mysql",
port: 3306,
disableEval: true,
debug: true,
ssl: {}
});
// Query the products table
const [rows] = await connection.query("SHOW tables;");
// Close the connection
await connection.end();
// Return the result as JSON
const resp = new Response(JSON.stringify(rows), {
headers: { "Content-Type": "application/json" },
});
return resp;
},
} satisfies ExportedHandler<Env>;
```

support upgrading insecure tcp connection in nodejs_compat

---

src/node/internal/internal_net.ts
src/node/internal/internal_tls_wrap.ts
src/workerd/api/node/tests/tls-nodejs-test.js

Supports passing empty socket to TLSSocket class. For example, the following code works from now on:
```typescript
export const testTlsOnEmptySocket = {
async test(ctrl, env) {
const { promise, resolve, reject } = Promise.withResolvers();
const socket = new net.Socket();
let out = '';
const s = tls.connect({ socket }, function () {
s.on('error', reject);
s.on('data', function (chunk) {
out += chunk;
});
s.on('end', resolve);
});
const onConnectFn = mock.fn();
socket.connect(env.HELLO_SERVER_PORT, onConnectFn);
await promise;
strictEqual(out, 'Hello');
strictEqual(onConnectFn.mock.callCount(), 1);
},
};
```

support passing empty socket to TLSSocket

---

src/node/internal/internal_tls_wrap.ts

Resolves a TODO since @dom96's PR has landed to main.

resolve todo in node:tls

---

src/workerd/api/node/tests/tls-nodejs-test.js

Improves the test coverage of node:tls

improve test coverage of node:tls

---

src/workerd/api/basics.c++
src/workerd/api/basics.h
src/wpt/dom/events-test.ts

Support null handlers for add/remove event listeners

---

src/workerd/io/compatibility-date.capnp
src/workerd/io/worker.c++
src/workerd/server/tests/python/durable-object/durable-object.wd-test
src/workerd/server/tests/python/worker-entrypoint/worker-entrypoint.wd-test

Seems to be working well in prod so let's roll it out to everyone.

Removes Python DO compat flag.

---

src/workerd/api/commonjs.c++
src/workerd/api/commonjs.h
src/workerd/api/node/BUILD.bazel
src/workerd/api/node/module.c++
src/workerd/api/tests/new-module-registry-test.js
src/workerd/api/tests/new-module-registry-test.wd-test
src/workerd/jsg/modules-new-test.c++
src/workerd/jsg/modules-new.h
src/workerd/server/workerd-api.c++

More work on the new module registry. gets commonjs modules working with a few other related bits.

Enable CommonJS in new module registry

---

.zed/settings.json

This adds a .zed configuration just like we have for vscode.

add zed settings

---

src/pyodide/BUILD.bazel
src/pyodide/eslint.config.mjs
src/pyodide/helpers.bzl
src/pyodide/internal/loadPackage.ts
src/pyodide/internal/metadata.ts
src/pyodide/internal/metadatafs.ts
src/pyodide/internal/pool/builtin_wrappers.ts
src/pyodide/internal/pool/emscriptenSetup.ts
src/pyodide/internal/python.ts
src/pyodide/internal/readOnlyFS.ts
src/pyodide/internal/setupPackages.ts
src/pyodide/internal/snapshot.ts
src/pyodide/internal/tarfs.ts
src/pyodide/python-entrypoint-helper.ts
src/pyodide/types/Pyodide.d.ts
src/pyodide/types/disk_cache.d.ts
src/pyodide/types/filesystem.d.ts
src/pyodide/types/internalJaeger.d.ts
src/pyodide/types/modules.d.ts

Enable eslint on Pyodide

---

build/BUILD.wpt
build/wpt_get_directories.bzl
src/workerd/api/crypto/ec.c++
src/workerd/api/crypto/keys.c++
src/wpt/BUILD.bazel
src/wpt/WebCryptoAPI-test.ts
src/wpt/harness/harness.ts

Imports all the tests so we can increase our test coverage.

WPT: Add WebCryptoAPI tests

---

src/workerd/api/memory-cache.c++

It looks like Use::getWithFallback() can return a promise that captures an InProgress reference, and may exercise that reference on destruction.  However, it looks like the actual ownership of the InProgress object is inside the SharedCache object, which is kept alive by the Use reference inside MemoryCache.
Since there doesn't seem to be an explicit reference between the promise and the SharedCache object, they can presumably be garbage collected in any order. If the MemoryCache is destroyed while there are still unresolved fallbacks, it's possible that fallback promises could be destroyed later, and attempt to run their destruction logic against the memory of freed InProgress objects.
This commit adds a reference to the MemoryCache object to a promise lambda, which may help ensure that …

SharedMemoryCache: Capture reference to cache in fallback lambda

---

.bazelignore

bazel has no business to look into them

[nfc] add node_modules to .bazelignore

---

src/workerd/api/BUILD.bazel
src/workerd/api/basics.h
src/workerd/api/global-scope.c++
src/workerd/api/global-scope.h
src/workerd/api/http.c++
src/workerd/api/http.h
src/workerd/api/tests/request-client-disconnect.js
src/workerd/api/tests/request-client-disconnect.wd-test
src/workerd/io/compatibility-date.capnp
src/workerd/io/worker-entrypoint.c++
src/workerd/server/server.c++
src/workerd/tests/test-fixture.c++

Reverts cloudflare/workerd#4044.
@jp4a50, with your approval, I think it's now safe to enable Request.signal again tomorrow morning

Revert "Revert "Re-merge Request.signal PR""

---

src/wpt/BUILD.bazel

The compat flag becomes available by default starting 2025-05-01

Fix urlpattern standard test

---

.github/workflows/internal-build.yml
tools/cross/internal_build.py

Send both HEAD and merge commit SHA as payload.

Fix internal-build in case of corresponding internal PR

---

src/workerd/api/global-scope.h
src/workerd/api/tests/navigator-test.js
types/generated-snapshot/2022-03-21/index.d.ts
types/generated-snapshot/2022-03-21/index.ts
types/generated-snapshot/2022-08-04/index.d.ts
types/generated-snapshot/2022-08-04/index.ts
types/generated-snapshot/2022-10-31/index.d.ts
types/generated-snapshot/2022-10-31/index.ts
types/generated-snapshot/2022-11-30/index.d.ts
types/generated-snapshot/2022-11-30/index.ts
types/generated-snapshot/2023-03-01/index.d.ts
types/generated-snapshot/2023-03-01/index.ts
types/generated-snapshot/2023-07-01/index.d.ts
types/generated-snapshot/2023-07-01/index.ts
types/generated-snapshot/experimental/index.d.ts
types/generated-snapshot/experimental/index.ts

Fixes https://github.com/cloudflare/workerd/issues/4067

add navigator.language attribute

---

npm/lib/node-install.ts
src/cloudflare/internal/ai-api.ts
src/pyodide/internal/setupPackages.ts
src/workerd/api/http-test-ts.ts
src/workerd/api/kv-test.js
src/workerd/api/node/tests/buffer-nodejs-test.js
src/workerd/api/node/tests/crypto_keys-test.js
types/test/types/rpc.ts

Some of the warnings are not caught by eslint.

fix warnings recommended by oxlint

---

src/workerd/io/compatibility-date.capnp

Cancel enable date for request_signal_passthrough due to ongoing work on feature

---

src/workerd/io/trace-stream.c++
src/workerd/io/trace-test.c++
src/workerd/io/trace.c++
src/workerd/io/trace.h
src/workerd/io/tracer.c++
src/workerd/io/tracer.h
types/defines/trace.d.ts
types/generated-snapshot/2021-11-03/index.d.ts
types/generated-snapshot/2021-11-03/index.ts
types/generated-snapshot/2022-01-31/index.d.ts
types/generated-snapshot/2022-01-31/index.ts
types/generated-snapshot/2022-03-21/index.d.ts
types/generated-snapshot/2022-03-21/index.ts
types/generated-snapshot/2022-08-04/index.d.ts
types/generated-snapshot/2022-08-04/index.ts
types/generated-snapshot/2022-10-31/index.d.ts
types/generated-snapshot/2022-10-31/index.ts
types/generated-snapshot/2022-11-30/index.d.ts
types/generated-snapshot/2022-11-30/index.ts
types/generated-snapshot/2023-03-01/index.d.ts
types/generated-snapshot/2023-03-01/index.ts
types/generated-snapshot/2023-07-01/index.d.ts
types/generated-snapshot/2023-07-01/index.ts
types/generated-snapshot/experimental/index.d.ts
types/generated-snapshot/experimental/index.ts
types/generated-snapshot/oldest/index.d.ts
types/generated-snapshot/oldest/index.ts

[o11y] STW API improvements

---

src/wpt/BUILD.bazel

They've been flakey lately. This should help.

Mark WPT WebCryptoAPI tests enormous

---

samples/webfs/README.md
samples/webfs/config.capnp
samples/webfs/worker.js
src/workerd/api/BUILD.bazel
src/workerd/api/filesystem.c++
src/workerd/api/filesystem.h
src/workerd/api/global-scope.c++
src/workerd/api/global-scope.h
src/workerd/api/rtti.c++
src/workerd/api/streams/readable.c++
src/workerd/api/streams/readable.h
src/workerd/api/tests/webfs-test.js
src/workerd/api/tests/webfs-test.wd-test
src/workerd/io/compatibility-date.capnp
src/workerd/io/worker-fs.c++
src/workerd/io/worker-fs.h
src/workerd/jsg/iterator.h
src/workerd/server/workerd-api.c++
types/generated-snapshot/experimental/index.d.ts
types/generated-snapshot/experimental/index.ts

Separated out from the larger #4029 PR. This Pr focuses specifically on the Web FileSystem API impl
This will remain behind an experimental compat flag until the impl is complete and there are web platform tests available for it.
As this is behind an experimental compat flag, this can be safely landed before having the appropriate web platform tests landed.

Experimental implementation of the Web FileSystem api

---

src/workerd/api/actor-state.c++
src/workerd/api/sql.c++
src/workerd/io/frankenvalue.c++
src/workerd/jsg/jsg.h

Update withinHandleScope to support JsValue and friends

---

src/workerd/jsg/value.h

This reverts commit f750e16aaac2f0156bc4a38558ae2cf2af6f8837.

Revert "avoid string coercion as much as possible (#4170)"

---

src/workerd/jsg/exception.h
src/workerd/jsg/fast-api-test.c++
src/workerd/jsg/fast-api.h
src/workerd/jsg/resource.h

simplify v8 fast api validations

---

src/node/internal/internal_errors.ts
src/node/internal/internal_net.ts
src/node/internal/internal_tls_common.ts
src/node/internal/internal_tls_jsstream.ts
src/node/internal/internal_tls_wrap.ts
src/node/internal/sockets.d.ts
src/node/internal/streams_adapters.js
src/node/internal/streams_duplex.d.ts
src/node/internal/streams_duplex.js
src/workerd/api/node/BUILD.bazel
src/workerd/api/node/tests/streams-nodejs-test.js
src/workerd/api/node/tests/tls-nodejs-tcp-server.js
src/workerd/api/node/tests/tls-nodejs-test.js
src/workerd/api/node/tests/tls-nodejs-test.wd-test
src/workerd/server/tests/weakref/BUILD.bazel

It seems this is required for mssql to work.

add support for duplex socket to node:net

---

src/workerd/api/tests/global-scope-test.js
src/workerd/api/tests/global-scope-test.wd-test
src/workerd/io/compatibility-date.capnp
src/workerd/io/worker.c++

Apply unique_ctx_per_invocation to historical workers too.

---

src/workerd/api/r2-bucket.c++

Back when we were trying to optimize the checksum handling to avoid unnecessary heap allocations we discovered that some checksums were being stored truncated (e.g. 8 bytes instead of 16 bytes). We reverted that change and added NOSENTRY logging so we could get a sense of how many checksums were being truncated. Turns out it's still fairly common and unlikely to go away. Let's remove the additional logging since it is no longer actually useful.

Remove the checksum length logging

---

src/node/internal/filesystem.d.ts
src/node/internal/internal_fs_callback.ts
src/node/internal/internal_fs_promises.ts
src/node/internal/internal_fs_sync.ts
src/node/internal/internal_fs_utils.ts
src/workerd/api/filesystem.c++
src/workerd/api/filesystem.h
src/workerd/api/node/tests/fs-access-test.js

Just more implementation detail.... one of several incremental PRs that will be coming, split up to hopefully make review not entirely overwhelming.

More node:fs impl

---

.bazelrc

it doesn't seem to be needed anymore

[build] cleanup tcmalloc define

---

src/workerd/io/promise-wrapper.h
src/workerd/io/worker.c++
src/workerd/jsg/buffersource.h
src/workerd/jsg/fast-api-test.c++
src/workerd/jsg/function.h
src/workerd/jsg/iterator.h
src/workerd/jsg/jsg.h
src/workerd/jsg/jsvalue.c++
src/workerd/jsg/jsvalue.h
src/workerd/jsg/modules-new-test.c++
src/workerd/jsg/modules-new.c++
src/workerd/jsg/modules-new.h
src/workerd/jsg/modules.c++
src/workerd/jsg/modules.h
src/workerd/jsg/promise.h
src/workerd/jsg/resource.h
src/workerd/jsg/setup.c++
src/workerd/jsg/setup.h
src/workerd/jsg/struct.h
src/workerd/jsg/type-wrapper-test.c++
src/workerd/jsg/type-wrapper.h
src/workerd/jsg/util.c++
src/workerd/jsg/value.h
src/workerd/jsg/wrappable.c++

Reverts cloudflare/workerd#4244

Revert "Pass a jsg::Lock to wrap and unwrap so we can get the isolate from it"

---

src/pyodide/internal/snapshot.ts
src/pyodide/types/disk_cache.d.ts

Python: Typescript: Tidy up the type of `DiskCache.put()`

---

src/workerd/io/BUILD.bazel
src/workerd/io/compatibility-date-test.c++
src/workerd/io/compatibility-date.c++
src/workerd/io/compatibility-date.h
src/workerd/io/worker-source.h
src/workerd/io/worker.c++
src/workerd/io/worker.h
src/workerd/server/server.c++
src/workerd/server/server.h

This is just some simple refactoring needed for my upcoming dynamic worker loading feature. Figured I'd put these up and get them merged before conflicts arise (especially the first commit, which moves a bunch of code).

Various refactoring for dynamic worker loading

---

WORKSPACE
patches/sqlite/0004-invalid-wal-on-rollback-fix.patch

Fix from: https://www.sqlite.org/src/info/5973f9b9aa828ec9

sqlite: Add patch to fix invalid wal frames on rollback

---

.github/workflows/_bazel.yml

Fixes https://github.com/cloudflare/workerd/issues/4379

add missing llvm-symbolizer

---

.github/actions/setup-runner/action.yml
.github/workflows/_bazel.yml
.github/workflows/release-python-runtime.yml
.github/workflows/release.yml
.github/workflows/test.yml

It seems we're duplicating the same exact code multiple times. Let's use a composite workflow action

add a composite action for preparing runners

---

src/node/internal/crypto.d.ts
src/node/internal/crypto_sign.ts
src/workerd/api/node/crypto.c++
src/workerd/api/node/tests/crypto_sign-test.js

Refs: https://github.com/axefinaxe/cfbug

Fixup node:crypto signature lengths

---

src/workerd/server/container-client.c++
src/workerd/server/container-client.h

Adds default environment variables

add default envs to container-client

---

src/workerd/api/filesystem.c++
src/workerd/io/worker-fs.c++
src/workerd/io/worker-fs.h

This reverts commit 69aedfe0a84be06aca2bed2cd0e5ca456779f16d.
Commit was accidentally pushed directly to main rather than a feature branch

Revert "Convert VirtualFileSystem tryGetCurrent() to current()"

---

build/wd_cc_benchmark.bzl
src/workerd/tests/BUILD.bazel
src/workerd/tests/bench-util.c++

Ref: https://github.com/cloudflare/workerd/pull/4452

add recursivelyFreeze benchmark

---

.github/workflows/codspeed.yml

Without this change we get an error 
Ref: https://github.com/cloudflare/workerd/actions/runs/16059498845/job/45321954837

use bazel run directly for benchmarking

---

src/workerd/api/global-scope.h
types/defines/trace.d.ts
types/generated-snapshot/experimental/index.d.ts
types/generated-snapshot/experimental/index.ts
types/generated-snapshot/latest/index.d.ts
types/generated-snapshot/latest/index.ts

An attempt at fixing the overbroad types I detailed here: https://wiki.cfdata.org/display/~jmorrell/May+2025+Streaming+Tail+Worker+Feedback?focusedCommentId=1166311884#comment-1166311884

Refine streaming tail worker interface types

---

src/node/fs.ts
src/node/internal/internal_fs_callback.ts
src/node/internal/internal_fs_promises.ts
src/node/internal/internal_fs_streams.ts
src/node/internal/internal_fs_sync.ts
src/node/internal/internal_fs_utils.ts
src/node/internal/streams_readable.d.ts
src/node/internal/streams_util.d.ts
src/node/internal/validators.ts
src/workerd/api/node/BUILD.bazel
src/workerd/api/node/tests/fs-dir-test.js
src/workerd/api/node/tests/fs-readstream-test.js
src/workerd/api/node/tests/fs-readstream-test.wd-test

Implements `fs.createReadStream(...)` and `fs.ReadStream`

Implement node:fs ReadStream

---

.bazelrc
.gitignore
WORKSPACE
build/wd_rust_binary.bzl
justfile
src/rust/gen-compile-cache/BUILD.bazel
src/workerd/api/BUILD.bazel
src/workerd/api/node/BUILD.bazel

Not yet fully complete, since it doesn't detect all tests.

add coverage and profile commands to justfile

---

src/pyodide/internal/python.ts
src/workerd/api/pyodide/pyodide-test.c++
src/workerd/api/pyodide/pyodide.c++
src/workerd/server/tests/python/vendor_dir/vendor_dir.wd-test
src/workerd/server/tests/python/vendor_dir/worker.py

Related to https://github.com/cloudflare/workers-sdk/pull/9905.

Rename Python vendor dir to `python_modules`

---

src/workerd/tests/bench-fast-api.c++
src/workerd/tests/bench-json.c++

With the goal of making benchmarks more stable.

update benchmark iteration counts

---

src/workerd/util/strong-bool-test.c++

There are a few of options here are the two that I like:
```
NO_COMPILE(T, t, t = false, Strongbad);
NO_COMPILE(t = false, Strongbad); // Implicit Types
```

add static-asserts to strong-bool-test

---

src/node/https.ts
src/node/internal/events.ts
src/node/internal/internal_fs_promises.ts
src/node/internal/internal_fs_streams.ts
src/node/internal/internal_http_agent.ts
src/node/internal/internal_process.ts
src/node/internal/internal_utils.ts

This fixes almost all typescript errors related to our EventEmitter implementation.

fix EventEmitter types

---

src/workerd/api/filesystem.c++
src/workerd/api/filesystem.h
src/wpt/fs-test.ts

More incremental work on the webfs impl...

Implement webfs file/directory locator property

---

src/workerd/api/cache.c++

Downstream PR adding tests to follow.

[o11y] Expand set of supported span tags in Cache API

---

src/node/_http_common.ts
src/node/internal/internal_http.ts
src/node/internal/internal_http_client.ts
src/node/internal/internal_http_outgoing.ts
src/node/tsconfig.json
src/workerd/api/node/tests/http-outgoing-nodejs-server.js
src/workerd/api/node/tests/http-outgoing-nodejs-test.js

This improves the nodejs compatibility of OutgoingMessage. It is one of the requirements for landing server-side support.
Kudos to @mhart for his `fetch-to-node` project.

improve nodejs compat of OutgoingMessage

---

src/workerd/api/filesystem.c++
src/workerd/api/filesystem.h
src/workerd/jsg/url.c++
src/workerd/jsg/url.h
src/wpt/fs-test.ts

More webfs fun and excitement

---

src/workerd/api/filesystem.c++
src/wpt/fs-test.ts

Just updating a handful of test statuses. There will be at least one additional PR updating the last known remaining set of tests I haven't fully triaged yet.

Update multiple webfs wpt test statuses

---

package.json
pnpm-lock.yaml
types/BUILD.bazel
types/tsconfig.json

Not really sure what I'm doing but it doesn't seem needed.

Remove @types/debug

---

src/workerd/api/node/node.h
src/workerd/api/node/tests/fs-access-test.wd-test
src/workerd/api/node/tests/fs-chown-chmod-test.wd-test
src/workerd/api/node/tests/fs-cp-test.wd-test
src/workerd/api/node/tests/fs-dir-test.wd-test
src/workerd/api/node/tests/fs-filehandle-test.wd-test
src/workerd/api/node/tests/fs-glob-test.wd-test
src/workerd/api/node/tests/fs-link-test.wd-test
src/workerd/api/node/tests/fs-misc-test.wd-test
src/workerd/api/node/tests/fs-readstream-test.wd-test
src/workerd/api/node/tests/fs-stat-test.wd-test
src/workerd/api/node/tests/fs-test.wd-test
src/workerd/api/node/tests/fs-utimes-test.wd-test
src/workerd/api/node/tests/fs-writestream-test.wd-test
src/workerd/api/node/tests/process-nodejs-test.wd-test
src/workerd/api/node/tests/process-stdio-nodejs-test.wd-test
src/workerd/io/compatibility-date.capnp

It's still experimental for the time being...

Add compatibility flag to enable node:fs

---

src/node/internal/internal_http_incoming.ts
src/node/internal/internal_http_outgoing.ts
src/node/internal/internal_http_server.ts
src/node/internal/internal_http_util.ts
src/node/internal/streams_readable.d.ts
src/node/internal/streams_writable.d.ts
src/workerd/api/node/tests/http-outgoing-nodejs-test.js
src/workerd/api/node/tests/http-outgoing-nodejs-test.wd-test
src/workerd/api/node/tests/http-server-nodejs-test.js

Adds a new test and removes several todos since they dont apply to our implementation.

improve test coverage of node.js http server

---

src/workerd/api/filesystem.c++
src/workerd/api/filesystem.h
src/workerd/api/node/BUILD.bazel
src/workerd/api/node/exceptions.c++
src/workerd/api/node/exceptions.h
src/workerd/api/node/process.c++
src/workerd/api/node/tests/fs-cp-test.js
src/workerd/api/node/tests/fs-test.js
src/workerd/io/BUILD.bazel
src/wpt/fs-test.ts

Resolve outstanding node-fs todos about errors, improve node.js-style error handling, use correct error codes

Cleanup node:fs node-style exceptions

---

src/node/internal/internal_http_incoming.ts
src/node/internal/internal_http_outgoing.ts
src/workerd/api/node/tests/BUILD.bazel
src/workerd/api/node/tests/http-incoming-nodejs-test.js
src/workerd/api/node/tests/http-incoming-nodejs-test.wd-test
src/workerd/api/node/tests/http-outgoing-nodejs-test.js
src/workerd/api/node/tests/http-server-nodejs-test.js

I've checked every http.OutgoingMessage tests. The remaining ones does not apply to us.

add more http.OutgoingMessage tests

---

src/rust/cxx-integration-test/cxx-rust-integration-test.c++

This should work since that is just a syntax sugar around one more throw/catch.

[rust] testing getCaughtExceptionAsKj

---

src/node/internal/internal_fs_utils.ts

Remove or consolidate unused functions

---

MODULE.bazel

Testing to see if we still needed rules_java

cleanup MODULE.bazel and update deps

---

src/node/internal/internal_fs_promises.ts

This one limited to some outstanding typescript fixes

Resolve more outstanding node:fs todos

---

src/pyodide/create_vendor_zip.py
src/pyodide/make_snapshots.py
src/pyodide/tool_utils.py

Just a little script to make creating .zip files for python vendored tests easier.
```
$ python3 src/pyodide/create_vendor_zip.py fastapi
Creating pyproject.toml in /tmp/vendor-fastapi
Running uv run pywrangler sync...
Creating zip archive...
Successfully created: /tmp/fastapi-vendored-for-ew-testing.zip
Upload this zip file to the ew-snapshot-tests R2 bucket: https://dash.cloudflare.com/e415f1017791ced9d5f3eb0df2b31c9e/r2/default/buckets/ew-snapshot-tests
Vendoring complete! Archive created at: /tmp/fastapi-vendored-for-ew-testing.zip
```

Implements script for creating vendored package zip for tests

---

src/workerd/api/actor.c++
src/workerd/api/actor.h

`git diff --color-moved` makes this really easy to review.

Move class definitions of *ActorOutgoingFactory into header file

---

src/pyodide/helpers.bzl
src/pyodide/types/emscripten.d.ts

Python: Add snapshotDebug setting

---

src/pyodide/internal/loadPackage.ts
src/pyodide/internal/metadatafs.ts
src/pyodide/internal/pool/builtin_wrappers.ts
src/pyodide/internal/python.ts
src/pyodide/internal/setupPackages.ts
src/pyodide/internal/snapshot.ts
src/pyodide/internal/tar.ts
src/pyodide/internal/tarfs.ts
src/pyodide/internal/topLevelEntropy/lib.ts
src/pyodide/internal/util.ts
src/pyodide/python-entrypoint-helper.ts

* Adds PythonUserError and PythonRuntimeError
* Adds type of pyodide_entrypoint_helper

Implements error types for Python runtime and PyodideEntrypointHelper.

---

src/cloudflare/internal/http.ts
src/cloudflare/node.ts
src/node/internal/internal_http_incoming.ts
src/node/internal/internal_http_server.ts
src/workerd/api/node/tests/http-server-nodejs-test.js

* remove the second argument to httpServerHandler(...)
* add the handleAsNodeRequest(...) method

Refine the cloudflare:node APIs further

---

src/workerd/io/trace-stream.c++
src/workerd/io/tracer.c++
src/workerd/io/tracer.h

We currently provide the same timestamp for span start and end events as both are reported at the end time and timestamps are based on when the tail worker receives events. Switch back to the behavior used prior to #4419 (using time stamps as defined in the completed span struct).
Split off from #4767, which provides sane timestamps, this approach is still inconsistent as indicated by the TODOs.

EW-9366 [o11y] Fix STW span event timestamps

---

src/workerd/api/sockets.c++
src/workerd/server/server.c++

Instead of having large function args inline in the invocation it's more readable to give them names.

Cosmetic: Name some function args.

---

build/deps/gen/dep_workerd_cxx.bzl
src/workerd/api/node/dns.c++
src/workerd/server/workerd-api.c++

It brings more explicit utf8 conversions

just update-deps workerd-cxx

---

justfile
src/workerd/api/BUILD.bazel
src/workerd/api/http.c++
src/workerd/api/tests/fetch-redirect-test.js
src/workerd/api/tests/fetch-redirect-test.wd-test
src/workerd/io/compatibility-date.capnp

Strip Authorization header on cross-origin redirects

---

src/workerd/api/node/tests/fs-misc-test.js
src/workerd/io/worker-fs.c++

Starting to work through fuzz tests corpus 🥳

Fixup nodejs node:fs oob write and and test

---

src/workerd/api/memory-cache.c++

Added comprehensive tracing throughout the memory cache to help debug performance issues and understand cache behavior in production.
The main changes:
- Track cache hits/misses with size metrics
- Show when requests get coalesced (multiple requests waiting on same key)
- Measure how long fallback functions take
- Log evictions with reasons (expired vs LRU)
- Monitor write rejections and why they happen
This should make it much easier to debug cache issues and understand why certain requests are slow (hint: it's most likely either request coalescing or fallback taking a long time).

Add tracing spans to memory cache

---

src/workerd/api/node/tests/zlib-nodejs-test.js
src/workerd/api/node/zlib-util.c++
src/workerd/api/node/zlib-util.h
src/workerd/jsg/modules.h
src/workerd/tests/BUILD.bazel
src/workerd/tests/module-imports-test.js
src/workerd/tests/module-imports-test.wd-test

Signed-off-by: James M Snell <jsnell@cloudflare.com>

Land a couple of patches from the downstream project

---

src/pyodide/upload_bundles.py

Factored out the steps better and added a step to update python_metadata.bzl.

Python: Improvements to upload_bundles.py script

---

src/pyodide/internal/topLevelEntropy/allow_entropy.py
src/pyodide/internal/topLevelEntropy/allow_entropy.py.d.ts
src/pyodide/internal/topLevelEntropy/entropy_import_context.py
src/pyodide/internal/topLevelEntropy/entropy_patches.py
src/pyodide/internal/topLevelEntropy/import_patch_manager.py
src/pyodide/internal/topLevelEntropy/lib.ts

In preparation to expose entropy hooks to downstream.

Python: refactor topLevelEntropy management

---

build/deps/dep_pyodide.bzl

First step of moving snapshot change tests into workerd.

Python: Move snapshot test bazel config into workerd

---

src/pyodide/internal/workers.py

Python: Add __all__ to workers.py

---

src/node/module.ts
src/workerd/api/node/tests/BUILD.bazel
src/workerd/api/node/tests/module-nodejs-test.js
src/workerd/api/node/tests/module-nodejs-test.wd-test

Adds remaining node:module methods/classes. Required to remove the necessary polyfills from Wrangler.

add remaining node:module methods

---

src/pyodide/internal/_workers.py

More cleanup here. I would like to eventually get rid of `FetchResponse` behind a compat flag.

Python: Move the static methods defined on Response to FetchResponse

---

samples/nodejs-compat-fs-graceful/config.capnp
samples/nodejs-compat-fs/config.capnp
src/workerd/api/node/node.h
src/workerd/io/compatibility-date.capnp

Remove experimental flag from node:fs and node:os modules

---

src/node/internal/internal_http_client.ts
src/node/internal/internal_http_server.ts

Fixes https://github.com/cloudflare/workerd/issues/4877

do not throw an error on insecureHTTPParser option

---

src/workerd/api/worker-rpc.c++
src/workerd/io/trace.h
src/workerd/io/tracer.c++
src/workerd/io/tracer.h
src/workerd/io/worker.c++

[o11y] 09-03-25 STW cleanup and QA 
- Allow overriding setTimestamp downstream
- Drop obsolete TODO
- Add an assert for additional hardening
[o11y] Add more debug logging for missing/delayed Onset event

[o11y] 09-03-25 STW cleanup, QA, debug logging

---

src/workerd/jsg/wrappable.c++

v8 14.1 update introduces a new Wrappable API which required changes to our `Wrappable::CppgcShim` type. This PR updates our Wrappable code so that we can upgrade EW to 14.1 while making it easy to revert to the earlier version and keeping workerd on 14.0.

Implements Wrappable changes for v8 14.1 support

---

src/workerd/jsg/modules-new-test.c++
src/workerd/jsg/modules-new.c++
src/workerd/jsg/modules-new.h
src/workerd/server/workerd-api.c++

Update some documentation comments for new module registry

---

src/node/internal/internal_dns_promises.ts
src/node/internal/internal_errors.ts
src/node/internal/util.d.ts
src/node/perf_hooks.ts
src/node/timers.ts
src/node/zlib.ts
src/workerd/api/global-scope.c++
src/workerd/api/global-scope.h
src/workerd/api/node/node.h
src/workerd/api/node/tests/BUILD.bazel
src/workerd/api/node/tests/perf-hooks-nodejs-test.js
src/workerd/api/node/tests/perf-hooks-nodejs-test.wd-test
src/workerd/api/node/util.h
src/workerd/api/performance.c++
src/workerd/api/performance.h
src/workerd/api/rtti.c++
src/workerd/io/compatibility-date.capnp
src/workerd/jsg/jsg.h
src/workerd/jsg/resource-test.c++
src/workerd/jsg/resource.h
src/workerd/jsg/rtti.h
src/workerd/server/workerd-api.c++
src/workerd/tests/BUILD.bazel
src/workerd/tests/performance-test.js
src/wpt/BUILD.bazel
src/wpt/performance-timeline-test.ts
types/generated-snapshot/experimental/index.d.ts
types/generated-snapshot/experimental/index.ts
types/generated-snapshot/latest/index.d.ts
types/generated-snapshot/latest/index.ts

Adds performance classes globally and adds a regression test in the last commit.

Add performance classes

---

build/wd_rust_crate.bzl
src/rust/cxx-integration-test/BUILD.bazel
src/rust/cxx-integration/BUILD.bazel

Better handling of multiple ffi bridges and cxx deps

[nfc] wd_rust_crate improvements

---

src/workerd/api/BUILD.bazel
src/workerd/api/actor-kv-test-tail.js
src/workerd/api/actor-kv-test.js
src/workerd/api/actor-kv-test.wd-test
src/workerd/api/actor-state.c++
src/workerd/api/tail-worker-test.js

Adds actor test for KV calls too in order to produce some spans.

WO-707 Adds tracing spans to Durable Objects KV calls

---

src/workerd/api/r2-instrumentation-test.js
src/workerd/io/trace.c++
src/workerd/io/trace.h
src/workerd/io/tracer.c++
src/workerd/io/tracer.h
src/workerd/io/worker-entrypoint.c++
src/workerd/server/server.c++

EW-9366 [o11y] Facilitate reporting I/O time for STW spans

---

src/workerd/api/container.c++
src/workerd/api/container.h
src/workerd/io/container.capnp
src/workerd/server/container-client.c++
src/workerd/server/container-client.h
types/generated-snapshot/experimental/index.d.ts
types/generated-snapshot/experimental/index.ts

Originally https://github.com/cloudflare/workerd/pull/5125

container: Add setInactivityTimeout 

---

src/workerd/api/trace.c++
src/workerd/api/trace.h
src/workerd/api/worker-rpc.c++
src/workerd/io/compatibility-date.capnp
src/workerd/io/trace.c++
src/workerd/io/trace.h
src/workerd/io/tracer.c++
src/workerd/io/tracer.h
src/workerd/io/worker-interface.capnp
types/generated-snapshot/experimental/index.d.ts
types/generated-snapshot/experimental/index.ts

[o11y] Remove support for Automated Tracing within LTW

---

build/wd_rust_crate.bzl

- proper include prefix
- `@expand` manual target to debug proc macros (if there are any)

wd_rust_crate improvements

---

src/workerd/io/trace-stream.c++

- JS exceptions will now be logged properly in all cases
- Limits exceeded exceptions no longer cause unsightly stack traces to be logged
- Exceptions are re-thrown at the level of the customEvent, instead of the report() call itself, ensuring that no more tail events are delivered to the tail worker after the exception.
A regression test will be added in a downstream PR to be filed later today.

EW-9453 Implement proper STW exception propagation

---

tools/base.eslint.config.mjs

Ref: https://github.com/typescript-eslint/typescript-eslint/issues/10935

remove deprecated tseslint.config() call

---

.gitignore
src/node/internal/internal_errors.ts
src/node/internal/internal_fs_callback.ts
src/node/internal/internal_fs_sync.ts
src/workerd/api/filesystem.c++
src/workerd/api/node/exceptions.c++
src/workerd/api/node/process.c++
src/workerd/api/node/tests/fs-nodejs-test.js

Fixes https://github.com/cloudflare/workerd/issues/5228

improve node.js filesystem errors
